### ISSUE TITLE
Error on command close-popup

### ISSUE THREAD

**Issue by VDRainer** [thomasloven/hass-browser_mod#10]
HA 0.96.3, browser_mod 5, latest FF on Ubuntu

Command popup-close works, but raises error:
```
2019-07-22 11:31:37 ERROR (MainThread) [frontend.js.latest.201907210] http://192.168.123.67:8123/browser_mod.js:56:2919 Uncaught TypeError: Cannot read property 'close' of undefined
```
Tested and confirmed with script:
```yaml
script:
  test_popup:
    sequence:
      - service: browser_mod.command
        data:
          command: popup
          title: Popup example
          card:
            type: entities
            entities:
              - light.bed_light
              - light.kitchen_lights
              - light.ceiling_lights
          deviceID:
            - d516918a-f3009bc7

      - delay: '00:00:05'

      - service: browser_mod.command
        data:
          command: close-popup
```

**Comment by VDRainer** [comment]
Strange!
After trying the same script in my Play hass.io, no error is raised.
After more and more testing the error from above in my prod system is also gone.
Ignore it!

**Comment by genem2** [comment]
So, I'm just adding this component today, and am seeing Only this error.

Example 1:  browser_mod.debug

Example 2:  browser_mod.popup
```
title: Popup example
card:
  type: entities
  entities:
    - light.coffee_table
    - light.credenza
deviceID:
  - 6fcdebdf-3d379f2e
(or)
  - this
```

2019-10-21 10:58:08 ERROR (MainThread) [frontend.js.latest.201910022] webpack:////card-tools/popup.js?:28:14 Uncaught TypeError: Cannot read property 'close' of undefined

My devices:

Entity | State | Attributes
-- | -- | -------
light.browser_mod_recroomtower | on | type: browser_mod deviceID: 6fcdebdf-3d379f2e    last_seen: 2019-10-21T11:11:21.380669 supported_features: 0
media_player.browser_mod_recroomtower | idle | volume_level: 1 is_volume_muted: false media_content_id:  type: browser_mod deviceID: 6fcdebdf-3d379f2e supported_features: 21005
sensor.browser_mod_recroomtower | 1 | type: browser_mod last_seen: 2019-10-21T11:11:21.380099 deviceID: 6fcdebdf-3d379f2e path: /developer-tools/state visibility: visible userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 currentUser: gene width: 1465 height: 1075
