### ISSUE TITLE
Error during setup of component browser_mod

### ISSUE THREAD

**Issue by SentryMax** [thomasloven/hass-browser_mod#108]
After the last Home Assistant 0.111.4 update I get this error every time I restart HA

Logger: homeassistant.setup
Source: custom_components/browser_mod/__init__.py:18
First occurred: 2:21:16 AM (1 occurrences)
Last logged: 2:21:16 AM 

Error during setup of component browser_mod

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 190, in _async_setup_component
    result = await asyncio.wait_for(task, SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/browser_mod/__init__.py", line 18, in async_setup
    name = config[DOMAIN][CONFIG_DEVICES][d].get("name", None)
AttributeError: 'str' object has no attribute 'get'

then in the Notifications bell i get
Invalid config

The following integrations and platforms could not be set up:

    browser_mod

Please check your config.

My configuration.yaml is 
```yaml
### Enables Browser Mod
browser_mod:
  prefix: "browser_"
  devices:
    XXXXXXXX-XXXXXXXX: 
      name: XXXXXX
```

**Comment by martinhoess** [comment]
I have this to, I think since the .114 update.
But my error message is slightly different

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 36, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 72, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 30, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
```

**Comment by thomasloven** [comment]
What's on the next line of your config, and how is that indented?

**Comment by SentryMax** [comment]
![browsermod](https://user-images.githubusercontent.com/57269475/96772838-fee73000-13e3-11eb-9c0d-02485b3e8e2b.PNG)

**Comment by thomasloven** [comment]
I mean after the browser_mod configuration.

The error makes me expect something like
```yaml
browser_mod:
  devices:
    xxx-xxx:
      name: xxx



    something_unrelated: whatever
```

or possibly
```yaml
browser_mod:
  devices:
    xxx-xxx:
      name: xxx
    yyy-yyy:
      name:I_forgot_the_space!
```
