### ISSUE TITLE
Popup header is broken for HA installs <0.113.0

### ISSUE THREAD

**Issue by Villhellm** [thomasloven/hass-browser_mod#124]
Using release 1.1.4 in versions of HA before 0.113.0 causes popups to display `true` in the header of the popup with no close button or title.

```yaml
tap_action:
  action: call-service
  service: browser_mod.popup
  service_data:
    title: test
    card:
      type: markdown
      content: test
```

![Annotation 2020-07-29 124347](https://user-images.githubusercontent.com/15912739/88845615-453c4280-d199-11ea-80e5-630a77486bcd.png)

I don't really expect this to be fixed, but I couldn't find any notes saying that 0.113.0+ was required for this release. So it's more of a heads up.
