### ISSUE TITLE
devices not renaming

### ISSUE THREAD

**Issue by MYLE-01** [thomasloven/hass-browser_mod#13]
```
browser_mod:
  devices:
    c7eed513_2b6db8a3:
      name: beast
```
on the state page i have

![image](https://user-images.githubusercontent.com/4362345/63695048-e923bc80-c86b-11e9-8828-57df1216e98d.png)

it did the naming but not working
where the other one is ie text to spech

and
them i tryed
```
type: media-control
entity: media_player.c7eed513_2b6db8a3
name: Beast PC
```
![image](https://user-images.githubusercontent.com/4362345/63695230-59324280-c86c-11e9-9349-dc3a611f9c71.png)

LOVE IT CAN SEE THE POWER OF IT
