### ISSUE TITLE
Cross "X" not showing in popup more info

### ISSUE THREAD

**Issue by soloam** [thomasloven/hass-browser_mod#130]
Hello, I can't tell when this started to happen, but when I open a custom more info popup window the closing "X" is not showing, even with "hide_header: false". This is not a problem in the PC, I can just click outside the window, but in mobile is very annoying because I don't have any option to close the window.

```yaml
                - entity: switch.livingroom_tv
                  type: "custom:secondaryinfo-entity-row"
                  secondary_info: "Fonte: [[ input_select.livingroom_tv_source ]]"
                  tap_action:
                    action: call-service
                    service: browser_mod.popup
                    service_data:
                      title: Televisão Sala
                      card:
                        type: custom:vertical-stack-in-card
                        cards:
                          - type: entities
                            entities:
                              - entity: switch.livingroom_tv
                              - entity: input_select.livingroom_tv_source
                          - type: entities
                            title: Devices
                            entities:
                              - entity: switch.livingroom_soundsys
                              - entity: switch.livingroom_meobox
                          - type: conditional
                            conditions:
                              - entity: input_select.livingroom_tv_source
                                state: "Chromcast"
                            card:
                              type: custom:mini-media-player
                              entity: media_player.living_room_tv
                          - type: conditional
                            conditions:
                              - entity: input_select.livingroom_tv_source
                                state: "Kodi"
                            card:
                              type: custom:mini-media-player
                              entity: media_player.livingroom_kodi
                              hide:
                                volume: true
                                power: true
                      deviceID:
                        - this
                - entity: switch.livingroom_soundsys
                - entity: switch.livingroom_meobox

```

![image](https://user-images.githubusercontent.com/11949987/89439819-a4262c80-d742-11ea-8c94-abe52306cffa.png)

Thank You
