### ISSUE TITLE
Title of popups is always "undefined" in 1.2.0

### ISSUE THREAD

**Issue by jncanches** [thomasloven/hass-browser_mod#154]
My Home Assistant version: 0.116.4

What I am doing:
Call service browser_mod.popup with a title set

What I expected to happen:
Popup title displayed as expected

What happened instead:
Popup displayed "undefined" as title, no matter what is set in yaml config

```yaml
    action: call-service
    service: browser_mod.popup
    service_data:
      deviceID: this
      title: My title
      card:
        whatever you want
```

Error messages from the browser console:
No error message in chrome Dev-Tools console

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
