### ISSUE TITLE
more_info is not shown when deviceID is set 'this' in automation or script

### ISSUE THREAD

**Issue by sunde41** [thomasloven/hass-browser_mod#155]
My Home Assistant version: 0.16.4
browser_mod test by 1.2 and 1.2.1

in automation or script, more_info popup is not shown when deviceID is set this

```yaml
# The least ammount of code possible to reproduce my error
- service: browser_mod.more_info
      data:
        entity_id: climate.xxx
        deviceID:
          - this

# End of code
```

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
