### ISSUE TITLE
Popup cards don't work on Safari

### ISSUE THREAD

**Issue by fi-sch** [thomasloven/hass-browser_mod#156]
My Home Assistant version: 0.116.4

**What I am doing:**
I am using 'popup cards' functionality. Pop-ups open properly in Firefox but in Safari (both MacOS and iOS app) they just don't work – don't open. I'm getting some errors in the browser console. 

**What I expected to happen:**
Pop-ups should open normally.

**What happened instead:**
No visible action, errors in the browser console.

**Minimal** steps to reproduce:
1. Edit dashboard config
2. Put my popup_cards config

```yaml
# The least ammount of code possible to reproduce my error
popup_cards:
  binary_sensor.okna_mieszkanie:
    title: Otwarte okna
    card:
      type: glance
      columns: 3
      show_state: false
      entities:
        - binary_sensor.okno_salon_1
        - binary_sensor.okno_salon_2
        - binary_sensor.okno_sypialnia
        - binary_sensor.okno_biuro
        - binary_sensor.okno_lazienka
        - binary_sensor.okno_kuchnia
# End of code
```

**Error messages from the browser console:**

> Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'e.localName')

> Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'this.shadowRoot.querySelector("ha-dialog").updateComplete')

---
![image](https://user-images.githubusercontent.com/59969726/97292823-09725100-184c-11eb-9f7b-ee29bf793469.png)

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
