### ISSUE TITLE
Kiosk-Mode - Race Condition when using browser_mod

### ISSUE THREAD

**Issue by benji1703** [thomasloven/hass-browser_mod#163]
Related to the combination, in my setup, of browser_mod and kiosk-mode

My Home Assistant version:  0.117.6

What I am doing: While loading kiosk-mode, and browser_mod, there is a race condition and kiosk-mode can't find lovelace.
Using browser_mod only for the wonderful popup service

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

*configuration.yaml*
browser_mod:
  disable:
    - all

# End of code
```

Error messages from the browser console:
Uncaught TypeError: Cannot read property 'config' of undefined

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
