### ISSUE TITLE
Popup in panel mode has rounded corners

### ISSUE THREAD

**Issue by tnagels** [thomasloven/hass-browser_mod#170]
I use a picture-elements card as screen saver in combination with kiosk-mode integration, it is fully black with grey text.
When the popup appears it is clearly noticeable that there are still white pixels in the screen corners. This is due to the rounded corners of the popup.
The popup should not have rounded corners when used in a panel-mode view.

**Comment by KTibow** [comment]
How do you open the popup?

**Comment by tnagels** [comment]
Below the start of the code of the card from which I call the popup. this card is shown from a view in "panel mode". 
On top of that I use the [kiosk-mode integration](https://github.com/maykar/kiosk-mode) to hide the header. 

First time activation is with a "hold" on the state label, afterwards it is timed as a screensaver.

```
type: picture-elements
elements:
  - type: state-label
    entity: sensor.time
    style:
      top: 50%
      left: 50%
      font-size: 200px
    tap_action:
      action: none
    hold_action:
      action: call-service
      service: browser_mod.popup
      service_data:
        title: Screensaver
        card:
          type: picture-elements
          elements:
            - type: state-label
          ( ... rest of code ... ) 
```
