### ISSUE TITLE
popup/ more_info not working in all devices

### ISSUE THREAD

**Issue by vdiogo** [thomasloven/hass-browser_mod#172]
My Home Assistant version: 2020.12.0

What I am doing:
I've setup browser_mod for multiple devices (Fire Tablet App, iMac Safari browser, Lenovo S8 Tablet Chrome browser, iPhone XR App) and have random behaviours.

What I expected to happen:
popup and more_info to work in all devices

What happened instead:
popup and more info: only works on the Fire tablets and iMac
off/ on using the browser_mod entity light.*** + TTS using the the browser_mod entity media_player.***: works in all devices

**Minimal** steps to reproduce:

```yaml
# 
service: browser_mod.popup

title: Clique para Abrir Portão da Frente
deviceID:
  - lenovo_s8
  - Fire_8
  - Fire_7
  - iphone_xr
card:
  type: button
  tap_action:
    action: toggle
  entity: switch.frontdoor_chime
  show_name: false
style:
  width: 40%
  height: 80%

# End of code
```

Error messages from the browser console:
None

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [ x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x ] Have made sure I am using the latest version of the plugin.

- [ x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
