### ISSUE TITLE
Service to toggle fullscreen

### ISSUE THREAD

**Issue by tbarbette** [thomasloven/hass-browser_mod#173]
I wish there was a service to toggle fullscreen mode. I found the fullscreen card but I don't want the big blue card, I'd like a service that I can trigger using icons in my "picture elements".  I think this mod is the right choice because it's very much browser related.

**Comment by KTibow** [comment]
Hey, creator of fullscreen-card here! One of the limitations of the fullscreen API is that it has to be triggered upon human interaction (like clicking a button). You might think this would work, but it ends up losing the focus of the button press when you call the service.

**Comment by tbarbette** [comment]
Ah, interesting :) Maybe there's a way to set the "onclick" event on any kind of interaction, like a "state-icon" of the picture elements card?

**Comment by jysaloma** [comment]
I would also have a use case to toggle a video image card to full screen when there is motion detected?

**Comment by dcapslock** [comment]
As for the fullscreen API, it does indeed need user interaction os not a good candidate for a Browser Mod service.

However, you can use browser_mod.javascript via fire-dom-event. 

### Enter Full Screen

```yaml
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.javascript
    browser_id: THIS
    data:
      code: document.documentElement.requestFullscreen()
```

### Exit Full Screen

```yaml
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.javascript
    browser_id: THIS
    data:
      code: document.exitFullscreen()
```

**Comment by runejuhl** [comment]
You can use something like this to have a toggle button:

```yaml
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.javascript
    browser_id: THIS
    data:
      code: >
        document.fullscreen && document.exitFullscreen() ||
        document.documentElement.requestFullscreen()
```

If you have just a single device that shows the dashboard you can also change the icon depending on the screen size, e.g. like this:

```yaml
type: custom:mushroom-template-badge
content: ""
icon: >-
  mdi:fullscreen{{ "-exit" if
  states('sensor.browser_mod_lenovotab_fennec_browser_height') | int > 500 else
  "" }}
color: black
entity: sensor.browser_mod_lenovotab_fennec_browser_height
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.javascript
    browser_id: THIS
    data:
      code: >
        document.fullscreen && document.exitFullscreen() ||
        document.documentElement.requestFullscreen()
```
