### ISSUE TITLE
browser_mod/update not found 

### ISSUE THREAD

**Issue by aladin2000** [thomasloven/hass-browser_mod#175]
My Home Assistant version: 2020.12.7 
it was running before that release but probably same behaviour in 118.5 ( quite sure )
What I am doing:

when Using lovelace  with pluggin  'custom:lg-remote-control' 

What I expected to happen:

tv channels icon should be part of a popup 

What happened instead:

an error : 
2020-12-29 19:29:36 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1749499520] Received invalid command: browser_mod/update

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

channels:
  - image: /local/community/LG-Keypad/tv_logo/TF1_268x171.png
    number: '1'
 ...
 ...
    number: '41'
  - image: /local/community/LG-Keypad/tv_logo/PlanetePlus_268x171.png
    number: '45'
dimensions:
  border_width: 5px
  scale: 0.72
entity: media_player.oled_tv
sources:
  - icon: 'mdi:netflix'
    name: Netflix
  - icon: 'mdi:youtube-tv'
    name: YouTube
  - icon: 'mdi:video-input-hdmi'
    name: HDMI 1
  - icon: 'mdi:video-input-hdmi'
    name: HDMI 2
title: Oled TV
type: 'custom:lg-remote-control'
theme: solarized


# End of code
```

Error messages from the browser console is :

Échec d'appel du service "**browser_mod/popup**". Service not found.

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x ] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
