### ISSUE TITLE
Error setup at boot time

### ISSUE THREAD

**Issue by aladin2000** [thomasloven/hass-browser_mod#181]
My Home Assistant version: 2021.1.4

What I am doing:
Boot ha

What I expected to happen:

Non error
What happened instead:
Error in setup

**Minimal** steps to reproduce:
Boot 

```yaml
# The least ammount of code possible to reproduce my error

- platform: browser_mod
  devices:
    eb1***68_48***5d0:
      name: phone_dadou
      disable:
        - light
        - media_player
      camera: true
    75****ad-e****d33f:
      name: ubuntu2_firefox
    87a***30_c718***9e:
      name: TabS2
    db5***dd_bd***58a:
      name: PC
  disable:
    - all
  prefix: "brmod_"

# End of code
```

Error messages from the browser console:

Today i got thé following

Logger: homeassistant.setup
Source: custom_components/browser_mod/__init__.py:22
First occurred: 23 janvier 2021, 23:08:59 (1 occurrences)
Last logged: 23 janvier 2021, 23:08:59

Error during setup of component browser_mod

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component

    result = await task

  File "/config/custom_components/browser_mod/__init__.py", line 22, in async_setup

    for d in config[DOMAIN].get(CONFIG_DEVICES, {}):

AttributeError: 'NodeListClass' object has no attribute 'get'

Any Idea  ?
---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [ x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x ] Have made sure I am using the latest version of the plugin.

- [x ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
