### ISSUE TITLE
Persistent floating tooltip

### ISSUE THREAD

**Issue by WRoss7** [thomasloven/hass-browser_mod#183]
My Home Assistant version: 2021.2.3
Browser-mod version: 1.3.0

What I am doing:
when a popup card is displayed, a floating label (with the appearance of a tooltip), with the name of the popup card, appears occasionally under the mouse pointer.
It is not limited to state-labels, but applies to icons, buttons, etc.

What I expected to happen:
the label should not appear

**Minimal** steps to reproduce:
I click on the 3 dots icon and the card popup appears, and also the label (the text written after "title:" in the Yaml syntax) which continues to follow the mouse movements.

![Immagine](https://user-images.githubusercontent.com/74879713/108123739-9add2b80-70a6-11eb-81ad-d76af1a6ab11.png)

```yaml
# The least ammount of code possible to reproduce my error
  - type: icon
    icon: 'mdi:dots-vertical'
    title: Manutenzione
    tap_action:
      action: call-service
      service: browser_mod.popup
      service_data:
        title: Manutenzione
        card:
          type: vertical-stack
          cards:
            - type: history-graph
              entities:
                - entity: timer.xiaomi_mi_robot
              hours_to_show: 168
            - type: entities
              entities:
                - entity: input_boolean.xiaomi_mi_robot_timer_on_off
                  name: Notifiche pulizia contenitore polvere
                - entity: input_datetime.xiaomi_mi_robot_timer_orario_attivazione
                  name: Si attiva alle...
                - entity: input_number.xiaomi_mi_robot_timer_ripetizione
                  name: Si ripete ogni...
              state_color: true
            - type: entities
              entities:
                - entity: script.azzera_il_contatore_dei_sensori
                - entity: script.azzera_il_contatore_del_filtro
                - entity: script.azzera_il_contatore_della_spazzola_principale
                - entity: script.azzera_il_contatore_della_spazzola_laterale
              state_color: true
          deviceID:
            - this
            - dashboard
    style:
      transform: 'translate(0%,0%)'
      right: 4px
      bottom: 10px
      color: 'rgb(0, 0, 0)'
# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
