### ISSUE TITLE
Popup does not re-render changes of state when using templates

### ISSUE THREAD

**Issue by dougmaitelli** [thomasloven/hass-browser_mod#186]
My Home Assistant version: 2021.2

What I am doing:
I am trying to add custom buttons on a popup that control specific attributes of a fan entity.
For that to work I have to use templates to render that button with different styles when the attribute is true or false.

What I expected to happen:
When I press my button the service is called to change the attribute, this change of state should render the new style in the button.

What happened instead:
If I use my button inside the normal dashboard the whole thing works perfectly. If I use it inside of a popup created with browser_mod the state never re-renders, unless I close the popup and open it again at every state change.

**Minimal** steps to reproduce:
Open a browser

```yaml
# The least ammount of code possible to reproduce my error
type: 'custom:button-card'
entity: fan.{{ fan_name }}
state:
  - value: 'on'
    spin: true
hold_action:
  action: call-service
  service: browser_mod.popup
  service_data:
    title: "Fan Details"
    card:
      type: 'custom:button-card'
      name: Auto
      color_type: card
      state:
        - operator: template
          value: >
            [[[
              return states['fan.{{ fan_name }}'].attributes && states['fan.{{ fan_name }}'].attributes.auto_mode == true;
            ]]]
          color: '{{ _global.colors.green }}'
        - operator: default
          color: '{{ _global.colors.blue_grey }}'
      tap_action:
        action: call-service
        service: dyson.set_auto_mode
        service_data:
          entity_id: fan.{{ fan_name }}
          auto_mode: >
            [[[
              return !(states['fan.{{ fan_name }}'].attributes && states['fan.{{ fan_name }}'].attributes.auto_mode == true);
            ]]]
    deviceID:
      - this
      - dashboard
# End of code
```

Error messages from the browser console:
N/A

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
