### ISSUE TITLE
New Popup event doesn't work from custom card

### ISSUE THREAD

**Issue by wbilger** [thomasloven/hass-browser_mod#189]
Newest homeassistant and browser_mod

I haven't tried all custom cards, but have mini-media-player and button-card,
and new "action: fire-dom-event" popup event does not work for tap_action, hold_action, or double_tap_action
Works when called from a regular lovelace card tap_action, hold_action, or double_tap_action

**Comment by jncanches** [comment]
Hope [custom:button-card](https://github.com/custom-cards/button-card) will implement support for fire-dom-event

**Comment by arielteacup** [comment]
This isn't working for me from a Grid card within a Vertical stack card either.

**Comment by Resurrection2981** [comment]
same for me.

**Comment by anschein** [comment]
same problem with any card I had.popup card does not work.

**Comment by TheRealBadRobot** [comment]
I have same problem with this message:
`Logger: homeassistant.config_entries
Source: config_entries.py:224
First occurred: 6:15:33 (1 occurrences)
Last logged: 6:15:33

Error importing platform config_flow from integration browser_mod to set up browser_mod configuration entry: No module named 'custom_components.browser_mod.config_flow'

It is working now, I don't know why just started again, but if Ichange the "service _data:" to simply "data:" the popup doesn't work.

**Comment by KTibow** [comment]
> Error importing platform config_flow from integration browser_mod to set up browser_mod configuration entry: No module named 'custom_components.browser_mod.config_flow'

Browser_mod is meant to only be configured via YAML at the moment. HA is trying to get the UI configuration flow from it, but it doesn't have one.

**Comment by littlerain14** [comment]
Pop up card stop working in 1.30. I rolled back to 1.23, and they working again. :(

**Comment by port3306** [comment]
+1

**Comment by conrad66** [comment]
+1

**Comment by KTibow** [comment]
Please use reactions, not comments. I'm pretty sure it's a problem with the custom card, not browser_mod.

**Comment by conrad66** [comment]
I use a custom card of the same author custom:layout-card
And I have a problem with popup

**Comment by TheRealBadRobot** [comment]
Please read the releases: [[()](https://github.com/thomasloven/hass-browser_mod/releases/tag/1.3.0)](url)

> For developers of lovelace plugins
This change makes use of the fire-dom-event tap action.
It's actually been in the code for almost a year, but has never been used (yet).
If your lovelace plugin does not support this, they will not work for direct triggering of browser_mod functions.
Calling a service as before still works, though, it's just the deviceID: this that's gone.

**Comment by darkkatarsis** [comment]
I read the documentation. I confirm it "new method" doesn't work for custom cards

**Comment by conrad66** [comment]
I read this too...
It only works on my Ipad )).
Firefox and Chrome don't work on PC

**Comment by jncanches** [comment]
> I read the documentation. I confirm it "new method" doesn't work for custom cards

The "old method" does not work too with custom cards... Need to revert browser_mod

**Comment by iprak** [comment]
For `button-card`, I had to switch to use `call-service` with `browser_mod.popup`. It works but presents the popup on all clients.

**Comment by KTibow** [comment]
> It works but presents the popup on all clients.

If you'll only ever be using it on one client, you can hardcode the device-id and it'll work.

**Comment by willheineman** [comment]
> For `button-card`, I had to switch to use `call-service` with `browser_mod.popup`. It works but presents the popup on all clients.

Can you post a sample of your YAML? All of my button-cards have a hold-action defined that uses callservice / browser_mod.popup. But none of my popups work anymore.

`    hold_action:
      action: call-service
      service: browser_mod.popup
      service_data:
        title: Game Room Lights
        deviceID: this
        large: true
        hide_header: true
        card:
          type: entities
          entities:
            - light.game_lights
            - light.game_light_bulb_1
            - light.game_light_bulb_2
            - light.game_light_bulb_3
            - light.game_light_bulb_4
            - switch.game_light_switch`

**Comment by KTibow** [comment]
@willheineman remove the `deviceID: this`.

**Comment by darkkatarsis** [comment]
Maybe I don't understand something. So far I have had this:

`tap_action:
      action: call-service
      service: script.popup_projector
      service_data:
        deviceID:
          - this`

but after the update, I try to like this:

`tap_action:
    action: fire-dom-event
    browser_mod:
      command: call-service
      service: script.popup_projector`

But not working anymore on a custom card.

**Comment by thomasloven** [comment]
This thread has quickly became unmaintainable.
Please use the issue template. That way people with different problems will know to open their own issue - also using the issue template.

A few points:
- READ THE RELEASE NOTES
- DO THAT FOR EVERY RELEASE
- fire-dom-event has two uses, and only two
  - causing something to happen **only** on the current device.
  - calling a backend service (e.g. a script) which needs to know which device it was called from.
- If you did not have `deviceID: this` or anything like that in your tap_action before, you do not need to change anything. - see release notes.
- If you did have `deviceID: this`, you should remove it - see release notes.
- fire-dom-event with command: call-service still needs deviceID: this - see readme.
- Please use the issue template when opening an issue.

**Comment by lasse9000** [comment]
hey

As i understand from all the reading the issues and readme file it is not posible to use the pop card that includes custom component and it only popup on a single device? 
If not corect, can any one please provide a working example, fell like i have tryed every combination, only one that works, pop up everywere.

Thanks in advance

**Comment by regystro** [comment]
@lasse9000, here you are:

```yaml
type: button
icon: 'mdi:account'
tap_action:
  action: fire-dom-event
  browser_mod:
    command: call-service
    service: browser_mod.popup
    service_data:
      deviceID: this
      title: Displayed only on THIS device
      card:
        type: entities
        entities:
          - sun.sun

type: button
icon: 'mdi:account-group'
tap_action:
  action: call-service
  service: browser_mod.popup
  service_data:
    title: Displayed on ALL devices
    card:
      type: entities
      entities:
        - sun.sun
```

**Comment by lasse9000** [comment]
thanks alot,
but it dosent work with custom butten card, even aften update so it sould suport frie-dom-event.

**Comment by anubisg1** [comment]
Even after upgrading custom button card it does not work...!

**Comment by lasse9000** [comment]
> Even after upgrading custom button card it does not work...!

nope if the popup card is cuntainen any custom card ex. a custom butten it 

```
type: 'custom:button-card'
icon: 'mdi:account'
tap_action:
  action: fire-dom-event
  browser_mod:
    command: call-service
    service: browser_mod.popup
    service_data:
      deviceID: this
      title: Displayed only on THIS device
      card:
        type: entities
        entities:
          - sun.sun
```
this dosent work

```
type: button
icon: 'mdi:account'
tap_action:
  action: fire-dom-event
  browser_mod:
    command: call-service
    service: browser_mod.popup
    service_data:
      deviceID: this
      title: Displayed only on THIS device
      card:
        type: entities
        entities:
          - sun.sun
```
This do work

**Comment by RomRider** [comment]
For `custom:button-card`:
* Please clear your cache
* Make sure you are running the version 3.4.2 and validate it by checking your browser console (**AND CLEAR YOUR CACHE ON EVERY DEVICE!**)
* See [here](https://community.home-assistant.io/t/lovelace-button-card/65981/5151?u=romrider) for a working config

**Comment by anubisg1** [comment]
the problem is with your working config ... 

browser mod explicitly says that this 

```
              tap_action:
                action: fire-dom-event
                #service: browser_mod.popup
                browser_mod: 
                  command: call-service
                  service: browser_mod.popup
                  service_data:
                    title: Heater
                    deviceID:
                      - this
```

must be changed to 

```
              tap_action:
                action: fire-dom-event
                #service: browser_mod.popup
                browser_mod:
                  command: popup
                  service_data:
                    title: Heater
 ```

and indeed it's not working
