### ISSUE TITLE
FR: Use of global defined popup_cards from deprecated popup-card

### ISSUE THREAD

**Issue by VDRainer** [thomasloven/hass-browser_mod#19]
Now that the popup-card is marked deprecated, i have multiple defined popup-cards that replaced the more-info dialog from some sensors.
That is very usefull if you have the sensors on multiple views.
In browser_mod it seems that i have to define the more-info popup on every entity/button that should show the more-info dialog.

Thanks in advance!

**Comment by thomasloven** [comment]
Here's a method: https://github.com/thomasloven/hass-browser_mod/wiki/Cookbook#reusing-popup-cards

**Comment by VDRainer** [comment]
Thanks, i already use anchors.
What i meant, is the function from popup-card to replace the more-info dialog from defined sensors.
Sorry for the confusion.

**Comment by spali** [comment]
same problem.
I generate files by a script with all the popup-cards for all sensors by type, which I include in the `ui-lovelace.yaml` with
```
popup_cards: !include_dir_merge_named ui-lovelace/popup-card-overrides/
```
there I have files for each type of sensor like the following `temperature.yaml` example
```
sensor.dg_schlafzimmer_temperatur:
  title: DG Schlafzimmer Temperatur
  large: false
  card:
    type: custom:mini-graph-card
    entities:
    - sensor.dg_schlafzimmer_temperatur
    points_per_hour: 1
    hour24: true
    decimals: 1
    show:
      name: false
      icon: false
      extrema: true
      labels: true
....
```
For instance, this replaces all popup-cards for temperature sensors with the generated config from `temperature.yaml`.
But now, it seems I can't do this anymore with `browser_mod` I would need to put this in each file I use the sensor and reference the anchor?
Would love to see the "global" feature in `browser_mod` somehow.
