### ISSUE TITLE
No entities created for iPhone (app or safari browser)

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/hass-browser_mod#190]
My Home Assistant version: 2021.2.2

**What I am doing:**

trying to use the media_player which was always created for my iPhone
**What I expected to happen:**

the creation of entities for my iPhone, including the prefix 'browser_'.
**What happened instead:**
No more entities are created for the iPhone, for 2 other devices (Chrome and Safari on the MacbookPro) entities are created according to the yaml config. 
However, these 2 don't get the prefix. Thats why I commented it right now for testing purposes finding the iPhone device, but it should really be uncommented

Odd thing is, when I reload the frontend cache in the App, I can see the Device_id change in the media_player card,   `- type: custom:browser-player`
I can not see this player in the developer-tools/state though, only the 2 devices in the config, with their respective entities

this is happening both on 1.2.3, and the new 1.3.0

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error
browser_mod:
#  prefix: 'browser_'
  devices:
    5a9redated675:
      name: theboss
      camera: true
      disable:
        - light
    3redacted67:
      name: hvbmbpro16-chrome
      disable:
        - light
    b7redacted59:
      name: hvbmbpro16-safari
      disable:
        - light
  disable:
    - all

# Put your code/steps here
```
not relevant for now, no code is used other than the setup config above and 
```
- url: /browser_mod.js
  type: module
```
in the resources

**Error messages from the browser console:**

Currently no log stack trace at all, usually the known data_adders is displayed for 3 items
```
// Select everything from the browser console and copy it

// Paste it here
2021-02-14 16:31:50 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2894763632] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 83, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 47, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
```

---

2 devices, where there should have been 3:

<img width="256" alt="Schermafbeelding 2021-02-14 om 16 57 43" src="https://user-images.githubusercontent.com/33354141/107881718-e72d3d80-6ee5-11eb-97d4-d00ec8bb58df.png">

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
