### ISSUE TITLE
hold_action no longer works after upgrade to 1.3.0 (custom:button-card

### ISSUE THREAD

**Issue by anubisg1** [thomasloven/hass-browser_mod#191]
My Home Assistant version: 2021.2.3
and custom:button-card 3.4.1

**What I am doing:**

upgraded browser_mod to version 1.3.0

**What I expected to happen:**
after migrating configuration, to work same as before

**What happened instead:**
nothing, hold_action no longer functioning

**Minimal** steps to reproduce:
```yaml
# The least amount of code or steps possible to reproduce my error
old configuration

    hold_action:
      action: call-service
      service: browser_mod.popup
      service_data:
        title: '[[[ return entity.attributes.friendly_name ]]]'
        deviceID: this


new configuration:

  hold_action:
    action: fire-dom-event
    browser_mod:
      command: popup
      title: "[[[ return entity.attributes.friendly_name ]]]"

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
