### ISSUE TITLE
browser_mod.popup not working on android mobile app

### ISSUE THREAD

**Issue by TTLucian** [thomasloven/hass-browser_mod#193]
My Home Assistant version: 0.XX.X

**What I am doing:**
Updated browser_mod to version 1.3.0

**What I expected to happen:**
Work as before

**What happened instead:**
Service browser_mod.popup is not popping up anything on mobile browser (tried Chrome and Edge + clear cache) or android mobile app (Home Assistant). It works fine in browser on PC. Don't know if I missed something but it used to work fine in previous versions.

**Minimal** steps to reproduce:

```yaml
type: button
name: Button 1
tap_action:
  action: call-service
  service: browser_mod.popup
  service_data:
    title: LPC
    deviceID:
      - this
      - dashboard
    card:
      type: button
      name: Button 2
```
I also tried this:
```yaml
type: button
name: Button 1
tap_action:
  action: fire-dom-event
  browser_mod:
    command: toast
    message: 'TEST'
```
and it's not popping up anything, anywhere.

**Error messages from the browser console:**

```
No errors, anywhere.
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
