### ISSUE TITLE
Unable to display a popup via a script

### ISSUE THREAD

**Issue by prbtt** [thomasloven/hass-browser_mod#195]
My Home Assistant version: supervisor-2021.02.9

**What I am doing:**
I'm trying to run a script to display a popup with a custom card inside

**What I expected to happen:**
To the popup to be displayed

**What happened instead:**
Nothing happened

**Minimal** steps to reproduce:
Grabbed the exampled showed in the cookbook

```yaml
# The least amount of code or steps possible to reproduce my error
test_popup:
  sequence:
    - service: browser_mod.popup
      data_template:
        deviceID: "{{ deviceID }}"
        title: Testing script
        card:
          type: entities
          entities:
            - light.bed_light

type: entity-button
entity: sun.sun
tap_action:
  action: call-service
  service: script.test_popup
  service_data:
    deviceID:
      - this

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by prbtt** [comment]
Solved by changing this
```
type: entity-button
entity: sun.sun
tap_action:
  action: call-service
  service: script.test_popup
  service_data:
    deviceID:
      - this
```
 to this:
```
type: entity-button
entity: sun.sun
tap_action:
  action: fire-dom-event
  browser_mod:
    command: call-service
    service: script.test_popup
    service_data:
      deviceID: this
```
