### ISSUE TITLE
1.3.0 Breaking Changes

### ISSUE THREAD

**Issue by tunerooster** [thomasloven/hass-browser_mod#200]
My Home Assistant version: 2021.2.1
Browser_mod version: 1.3.0

I can't figure out what I need to do to convert to the new system which does not use "this".  Below is the lovelace card configuration I have now:
````
type: picture-entity
entity: camera.frontdoor_preview
show_state: false
show_name: false
tap_action:
  action: call-service
  service: browser_mod.more_info
  service_data:
    deviceID: this
    entity_id: camera.frontdoor
    large: true
````
Please show me what I should replace this with.  Thanks for indulging me!  :)

P.S. On another note...
I could not find anything in the README about:  *browser_mod.clean_devices*

**Comment by KTibow** [comment]
Check https://github.com/thomasloven/hass-browser_mod/issues/189#issuecomment-780881434

**Comment by tunerooster** [comment]
Thank you for the prompt reply!  I now have:
```
type: picture-entity
entity: camera.frontdoor_preview
show_state: false
show_name: false
tap_action:
  action: fire-dom-event
  browser_mod:
    command: call-service
    service: browser_mod.more_info
    service_data:
      deviceID: this
      entity_id: camera.frontdoor
      large: true
```
It seems to work!  Is it the only way?  I.e., is there a simpler way?
          _(No reply is necessary unless there **IS** a better way)_       :)

Your browser_mod is *AWESOME*!  I would not be able to automate my many mounted dashboards without it!

Thanks!!!
