### ISSUE TITLE
time: parameter of browser_mod.popup does not work as intended

### ISSUE THREAD

**Issue by sickidolderivative** [thomasloven/hass-browser_mod#202]
My Home Assistant version: 2021.3.1

**What I am doing:**
Opening a popup with the time: parameter in developer tools with the following parameters:

service: browser_mod.popup
data:
  title: Popup example
  hide_header: true
  auto_close: true
  time: 10
  deviceID:
    - dashboard
  card:

**What I expected to happen:**
According to documentation, the popup should auto close after 10 seconds.

**What happened instead:**
The popup opening is delayed by time specified in the time: parameter. In the above case the popup opens 10 seconds after calling the service and stays open until touched/moved. 

**Minimal** steps to reproduce:
Clean HACS install of browser_mod. Calling the browser_mod.popup service from developer tools. 

```yaml
service: browser_mod.popup
data:
  title: Popup example
  hide_header: true
  auto_close: true
  time: 20
  deviceID:
    - dashboard
  card:
    type: entities
    entities:
      - sun.sun
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
