### ISSUE TITLE
Tons of entities unidentified and restored

### ISSUE THREAD

**Issue by Pirol62** [thomasloven/hass-browser_mod#213]
My Home Assistant version: 2021.4.6

**What I am doing:**
Deleted all restored entities manually step by step. Don'T know, where they come from
I have 9 devices, which could appear. Every device can be identified and are not restored

**What I expected to happen:**
Only the configured entities should be there.
Some entities did not get there name configured in yaml

**What happened instead:**
20 to 30 entities restored I've never seen before
![image](https://user-images.githubusercontent.com/48820003/115391514-d946b200-a1df-11eb-93ea-78da5455afd5.png)
![image](https://user-images.githubusercontent.com/48820003/115392549-fb8cff80-a1e0-11eb-81b4-e76eb93dd820.png)
![image](https://user-images.githubusercontent.com/48820003/115392102-7b669a00-a1e0-11eb-8527-73221cc65867.png)

**Minimal** steps to reproduce:
Perform a HA restart

```yaml
browser_mod:
  prefix: "browser_mod_"
  devices:
    efef8224-502fafc9:
      name: browser_s10_joerg
    eb8c217a_5a7f872c:
      name: browser_s6_joerg
    db50af9e_a80ef79d:
      name: browser_s6_joerg_nabu
    432f31ab-3d2db564:
      name: browser_tablet_joerg
    58d0f04b-cb1af20f:
      name: browser_firehd_wz
    a97ebb7b_d110bd6e:
      name: browser_bedroom
    71f999ec_d60be712:
      name: galaxy_gaestezimmer
    c947daf3_e25ed954:
      name: pc_chrome_duckdns
    5993efaf_8154f578:
      name: pc_chrome_nabu
    971ff32b_9b068323:
      name: pc_tata_duckdns
    edd7aa48_537d29da:
      name: pc_edge_duckdns

```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
