### ISSUE TITLE
Can't get `deviceID: this` to work

### ISSUE THREAD

**Issue by tunerooster** [thomasloven/hass-browser_mod#218]
I posted this on the community Home Assistant site but got no reply.  I took this from an example posted in the browser_mod section, but I can't get it to work...  I am running the latest version installed from `HACS`.  It is failing to recognize `deviceID: this`.

My picture-entity card configuration:
```
type: picture-entity
entity: camera.garage_preview
show_state: false
show_name: false
tap_action:
  action: call-service
  service: script.live_camera
  service_data:
    camera: garage
    deviceID: this
hold_action:
  action: more-info
```
The script:
```
live_camera:
  alias: Live Camera
  sequence:
    - service: script.camera_message
      data:
        payload: "tap action {{ camera | upper }}ON"
    - service: browser_mod.navigate
      data:
        navigation_path: "/lovelace/{{camera}}"
        deviceID: "{{ deviceID }}"
        # deviceID: screen_basement_gentoo
    - service: system_log.write
      data:
        level: info
        message: 'Live Camera Navigate: Path: (/lovelace/{{ camera }}) Device: ({{ deviceID }})'
```
The script executes successfully when I tap, the mqtt message is sent, but the browser_mod navigation fails.  It does not seem to understand `this`.  It works if I hard code a deviceID, but I need it to work on `this`.

Can someone offer a correction to my code?

THANKS!

**Comment by KTibow** [comment]
Check https://github.com/thomasloven/hass-browser_mod/releases/tag/1.3.0

**Comment by mutzl** [comment]
So does it mean, `- this` is deprecated and doesn't work anymore?
Because it is still mentioned in the readme and in the cookbook.

If `- this` can't be used anymore, how can I execute multiple service calls in a tap_action just for the current device?
I want to call a custom `netdaemon.xxx` followed by a `browser_mod.popup` for this device.

The cookbook recommends to call a script and getting `deviceID: "{{ deviceID }}"` 
But I cannot get this to work.

**Comment by KTibow** [comment]
> But I cannot get this to work.

What do you mean?

**Comment by tunerooster** [comment]
Ditto...  I need to execute multiple service calls on  `this` as illustrated in the script above.  How is this done?

**Comment by mutzl** [comment]
> What do you mean?
The sample doesn't work for me. 

Hence my question, if `- this` is deprecated. 

If so, ...
1. the documentation needs an update
2. and how can we execute a sequence of service calls for the calling device only?

**Comment by tankdeer** [comment]
The documentation is confusing. It really needs to be revised since this changed. I had trouble with too. I believe you need to change your card config to this:

```
type: picture-entity
entity: camera.garage_preview
show_state: false
show_name: false
tap_action:
  action: fire-dom-event
  browser_mod:
    command: call-service
    service: script.live_camera
    service_data:
      camera: garage
      deviceID: this
hold_action:
  action: more-info
```
