### ISSUE TITLE
can't make pop up work since the breaking change

### ISSUE THREAD

**Issue by thib5** [thomasloven/hass-browser_mod#219]
Hi, I didn't want to ask for help for that but it's been over a month that I'm searching on the web and can't make it work ...

I'm able to make it work but it open on all my devices... I want it to open only on the device I call it but if I add deviceID : this it stop working ... this is my code : 

```
type: button
tap_action:
  action: toggle
entity: group.salon
icon: 'mdi:sofa'
name: Salon
hold_action:
  action: call-service
  service: browser_mod.popup
  service_data:
    title: Lights
    card:
      type: entities
      entities:
        - entity: group.salon
    deviceID: this
```

Bonus : can I create .yaml file with all my popup and call them in my Lovelace ?  if so how ? thanks !!!
