### ISSUE TITLE
Using light-entity-card as a popup-card not working

### ISSUE THREAD

**Issue by jcbasso** [thomasloven/hass-browser_mod#221]
My Home Assistant version: 2021.5.1

**What I am doing:**
Changing light default Pop-Up to a custom one with `custom:light-entity-card` using `popup-cards`.

Having the following code at the beginning of the `ui-lovelace.yaml`:
```yaml
popup_cards:
  light.escritorio:
    type: 'custom:light-entity-card'
    entity: light.escritorio
    // The following are some default values
    shorten_cards: true
    consolidate_entities: false
    color_wheel: true
    persist_features: true
    brightness: true
    color_temp: true
    white_value: true
    color_picker: true
    smooth_color_wheel: false
    hide_header: false
    child_card: false
    show_slider_percent: false
    full_width_sliders: false
    brightness_icon: weather-sunny
    white_icon: file-word-box
    temperature_icon: thermometer
    header: Escritorio
    effects_list: false
```

**What I expected to happen:**
When I click on the light it should pop-up the `custom:light-entity-card`. 
This card is working standalone when used in a view:
<img width="472" alt="Screen Shot 2021-05-08 at 13 53 25" src="https://user-images.githubusercontent.com/9439373/117547226-eac3f280-b004-11eb-82b9-60aa98da7148.png">

**What happened instead:**
A blank popup is showing
<img width="411" alt="Screen Shot 2021-05-08 at 13 56 08" src="https://user-images.githubusercontent.com/9439373/117547280-39718c80-b005-11eb-8218-66d61fe83c32.png">

**Minimal** steps to reproduce:
- Have a light
- Define a custom pop-up in `popup-cards` for the card
- Add a `custom:light-entity-card` as the new card for the pop-up

**Error messages from the browser console:**
Looking at the console it looks like the problem appears when `card-mod` access `localName` from `ModdedElement` ([here](https://github.com/thomasloven/lovelace-card-mod/blob/c7e9342c4094141278a9182c6f27aecc28a6fd6d/src/helpers.ts#L27))
```yaml
chunk.e176e418edcf4883a584.js:2544 Uncaught (in promise) TypeError: Cannot read property 'type' of undefined
	    at c (chunk.e176e418edcf4883a584.js:2544)
	    at Module.a (chunk.e176e418edcf4883a584.js:2544)
	    at HTMLElement._makeCard (browser_mod.js:1)
	c 					@ chunk.e176e418edcf4883a584.js:2544
	a 					@ chunk.e176e418edcf4883a584.js:2544
	_makeCard 				@ browser_mod.js:1
	async function (async)
	_makeCard 				@ browser_mod.js:1
	showDialog 				@ browser_mod.js:1
	v 					@ browser_mod.js:90
	async function (async)
	v 					@ browser_mod.js:90
	_popup_card 				@ browser_mod.js:149
	(anonymous) 				@ browser_mod.js:149
	i 					@ app.780f338b.js:12797
	u 					@ chunk.5654564bf53dd6d74de2.js:318
	value 					@ chunk.5654564bf53dd6d74de2.js:1492
	handleEvent 				@ app.780f338b.js:12797
	__boundHandleEvent 			@ app.780f338b.js:12797
	i 					@ app.780f338b.js:12797
	(anonymous) 				@ chunk.5654564bf53dd6d74de2.js:318

card-mod.js:1 Uncaught (in promise) TypeError: Cannot read property 'localName' of null
	    at pe (card-mod.js:1)
	    at card-mod.js:5
	pe 					@ card-mod.js:1
	(anonymous) 				@ card-mod.js:5
	Promise.then (async)
	e.showDialog 				@ card-mod.js:5
	n 					@ app.780f338b.js:41423
	async function (async
	n 					@ app.780f338b.js:41423
	_handleMoreInfo 			@ app.780f338b.js:44047
	(anonymous) 				@ app.780f338b.js:44047
	w 					@ browser_mod.js:1
	(anonymous) 				@ browser_mod.js:149
	setTimeout (async)
	_popup_card 				@ browser_mod.js:149
	(anonymous) 				@ browser_mod.js:149
	i 					@ app.780f338b.js:12797
	u 					@ chunk.5654564bf53dd6d74de2.js:318
	value 					@ chunk.5654564bf53dd6d74de2.js:1492
	handleEvent 				@ app.780f338b.js:12797
	__boundHandleEvent 			@ app.780f338b.js:12797
	i 					@ app.780f338b.js:12797
	(anonymous) 				@ chunk.5654564bf53dd6d74de2.js:318
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [ X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [ X ] Have made sure I am using the latest version of the plugin.

- [ X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
