### ISSUE TITLE
Can't manage to have a deviceID generated for android app

### ISSUE THREAD

**Issue by thomasgermain** [thomasloven/hass-browser_mod#222]
My Home Assistant version: 2021-05

**What I am doing:**
I'm trying to display a popup on my android app. This is working correctly on my chrome (on my laptop) browser. But I can't manage to make it works on my android app. Here is what I'm doing:
```
    tap_action:
      action: fire-dom-event
      browser_mod:
        command: popup
        deviceID:
          - this
        title: Alerte météo
        large: true
        card:
          type: markdown
          content: |
            {{'test'}}
```

Real problem is _I think_, that I'm not able to generate any deviceID for my android app. As far as I can understand, I just have to connect to HA using my device. I tried to clean the cache, logout/login again, HA restart, but no way to get an id created (on browser_mod integration page, I only have one device for my chrome on my laptop).

`browser_mod.debug` (launched from my android app) has no effect on my android app, while it creates a popup on my laptop browser (as expected).

**What I expected to happen:**
A popup comes

**What happened instead:**
Nothing

**Minimal** steps to reproduce:

```yaml
- type: entities
  entities:
    - entity: binary_sensor.meteoalarm
      tap_action:
        action: fire-dom-event
        browser_mod:
          command: popup
          deviceID:
            - this
          title: Alerte météo
          large: true
          card:
            type: markdown
            content: |
              {{'test'}}
```

**Error messages from the browser console:**
No error
```
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
