### ISSUE TITLE
`deviceID: this` is not working for popups

### ISSUE THREAD

**Issue by estevez-dev** [thomasloven/hass-browser_mod#224]
My Home Assistant version: 2021.5.3

**What I am doing:**
I'm trying to show a popup with a card in current browser.

**What I expected to happen:**
The popup should be opened with a card configured.

**What happened instead:**
Nothing.

**Minimal** steps to reproduce:
- Add `tap_action` to a card with a card as a popup according to [documentation](https://github.com/thomasloven/hass-browser_mod#--popup) with `deviceID: this`.

```yaml
type: 'custom:button-card'
entity: input_select.mode
template: unit_card
name: Home
tap_action:
  action: call-service
  service: browser_mod.popup
  service_data:
    title: Popup example
    card:
      type: entities
      entities:
        - light.living_room
    deviceID:
      - this
```

It works when I replace `this` with actual deviceID:

```yaml
type: 'custom:button-card'
...
tap_action:
  action: call-service
  service: browser_mod.popup
  service_data:
  ...
    deviceID:
      - c8907873-cfa64be4
```

**Error messages from the browser console:** None

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by KTibow** [comment]
https://github.com/thomasloven/hass-browser_mod/releases/tag/1.3.0 should probably be added to the
> By replacing the space in the checkboxes ([ ]) with an X below

sectipn.

**Comment by estevez-dev** [comment]
> https://github.com/thomasloven/hass-browser_mod/releases/tag/1.3.0 should probably be added to the
> 
> > By replacing the space in the checkboxes ([ ]) with an X below
> 
> section.

Probably.

Thanks, it works.

**Comment by combative-american** [comment]
Can you post an example of how the popups work? I got the toast message to work fine.

**Comment by estevez-dev** [comment]
> Can you post an example of how the popups work? I got the toast message to work fine.

Sure.
```yaml
tap_action:
  action: fire-dom-event
  browser_mod:
    command: popup
    title: My popup
    card:
      # card config for popup
```
