### ISSUE TITLE
can not open thermostat card

### ISSUE THREAD

**Issue by trytogetme85** [thomasloven/hass-browser_mod#227]
My Home Assistant version: 2021.5.5

**What I am doing:**
Trying to open a Thermostat Card in Floorplan lovelace

**What I expected to happen:**
click on temperature state_lable - > open thermostat card

**What happened instead:**
nothing opens

**Minimal** steps to reproduce:

```yaml
- type: state-label
    entity: sensor.yumis_heizung_temperature
    style:
      top: 93%
      left: 53%
      color: '#000'
      border-radius: 50%
      text-align: center
      background-color: 'rgba(255, 255, 255, 0.3)'
      font-size: 11px
      font-weight: bold
    tap_action: call-service
    service: browser_mod.popup
    data:
      title: Heizung
      card:
        type: entities
        entities: climate.yumis_zimmer
      deviceID:
        - this
        - dashboard
```

---

**Comment by pedolsky** [comment]
Nor did work for me (Supervisor latest version + fresh installed browser_mod). The following example did the trick:

```
tap_action:
  action: call-service
  service: browser_mod.popup
  service_data:
    title: Heizung
    card:
      type: entities
      entities:
        - climate.yumis_zimmer
```

**Comment by trytogetme85** [comment]
> Nor did work for me (Supervisor latest version + fresh installed browser_mod). The following example did the trick:
> ```
Thanks for the tip, but the card is not a "thermostat" card, it only shows the temperature. But i want to regulate it. (with thermostat card it seems possible)

https://imgur.com/a/qCPIxJk

**Comment by pedolsky** [comment]
I‘ afraid I don’t get it yet. Your chosen card type is an entities card. But you want to use a the (built-in?) thermostat card?

**Comment by trytogetme85** [comment]
Yep, for example this one:
https://imgur.com/a/dO1sCz7

Its configured that way:
type: thermostat
entity: climate.yumis_zimmer

**Comment by pedolsky** [comment]
I followed your above posted config. If you want to popup a thermostate card you have to use one in the browser_mod config.

**Comment by trytogetme85** [comment]
Hm... I dont understand what you mean

**Comment by combative-american** [comment]
> 
> 
> Nor did work for me (Supervisor latest version + fresh installed browser_mod). The following example did the trick:
> 
> ```
> tap_action:
>   action: call-service
>   service: browser_mod.popup
>   service_data:
>     title: Heizung
>     card:
>       type: entities
>       entities:
>         - climate.yumis_zimmer
> ```

This works, but it pops up on every browser. I saw that '- this' has been removed and replaced with 'action: fire-dom-event'. I have no idea how to implement it for a pop up card that shows up only on the device that pressed the button.

**Comment by pedolsky** [comment]
> Hm... I dont understand what you mean

I mean the steps to reproduce you posted. There is no thermostat card inserted.

**Comment by pedolsky** [comment]
> saw that '- this' has been removed

Really?! The whole time I followed the doc instructions - without luck, of course 'cause I didn’t know. 😟 Thank you so much for pointing this out.
Without `- this` it the popup works as expected, you do not need fire-dom, use the given alias for your device.

**Comment by trytogetme85** [comment]
Yep "-this" can be removed.
Is there no other popup I can use to regulate the temperature? actulay it looks like this:
https://imgur.com/a/PsaFAYg

**Comment by pedolsky** [comment]
At the risk of seeming stupid: So why don‘t you use the thermostat card? 
(I don‘t use smart thermostats so I have to use other options)
```
type: button   ## or any other actionable card type
name: Heizung
tap_action:
  action: call-service
  service: browser_mod.popup
  service_data:
    title: Heizung
    card:
      type: light
      entity: light.anrichte
    deviceID:
      - your-browser_mod-alias


```
You click on the button (or label or something) and the controller pops up.

**Comment by trytogetme85** [comment]
`    deviceID:
      - your-browser_mod-alias`
The only one here, who is maybe stupid, is me :(

I have no idea what you mean with "your-browser_mod-alias" 
I see a couple of those ids in my standard-lovelace and have no idea how to use them, and what they're for:
https://imgur.com/a/zZUgpy0

Maybe browsermod is the wrong addon for me... I am so frustrated

**Comment by pedolsky** [comment]
Cheer up! 
Look at the [Alias-section in the docs](https://github.com/thomasloven/hass-browser_mod#aliases)

> Since the deviceID can be a bit hard to remember for devices you use often, you can specify an alias in configuration.yaml
> 
```browser_mod:
  devices:
    99980b13-dabc9563:
      name: arrakis
    d2fc860c-16379d23:
      name: dashboard
```
> This binds the aliases arrakis to 99980b13-dabc9563 and dashboard to d2fc860c-16379d23. Note: Aliases must be unique.

The ID ensures that the popup is only shown on certain devices, so it's not a must and you can drop it.

Please try an example and copy the following code into a blank card (i. e. card type „manual“):

```

type: button  
name: Heizung
tap_action:
  action: call-service
  service: browser_mod.popup
  service_data:
    title: Heizung
    card:
      type: thermostat
      entity: climate.yumis_zimmer

```

**Comment by trytogetme85** [comment]
That sir, is exactly what I want. It works perfectly :)

**Comment by pedolsky** [comment]
What do you mean by "only once"? In any case, I have not inserted an expiration date 🤓

**Comment by trytogetme85** [comment]
`  - type: state-label
    entity: sensor.yumis_heizung_temperature
    style:
      top: 93%
      left: 53%
      color: '#000'
      border-radius: 50%
      text-align: center
      background-color: 'rgba(255, 255, 255, 0.3)'
      font-size: 11px
      font-weight: bold
      tap_action:
        action: call-service
        service: browser_mod.popup
        service_data:
          title: Heizung
          card:
            type: thermostat
            entity: climate.yumis_zimmer`

**Comment by combative-american** [comment]
Someone else posted this and it's been working

```
tap_action:
  action: fire-dom-event
  browser_mod:
    command: popup
    title: My popup
    card:
      # card config for popup
```

It'll pop up on only the device you are using. The one above will show up on any HA device.

**Comment by combative-american** [comment]
Here is one with a vertical stack card that contains a thermostat card and buttons below in a horizontal stack
```
type: 'custom:button-card'
entity: climate.thermostat
icon: 'mdi:fan'
name: HVAC
aspect_ratio: 1/1.2
show_state: true
layout: vertical
tap_action:
  action: fire-dom-event
  browser_mod:
    command: popup
    title: HVAC
    card:
      type: vertical-stack
      cards:
        - type: thermostat
          entity: climate.thermostat
        - type: horizontal-stack
          cards:
            - type: conditional
              conditions:
                - entity: climate.thermostat
                  state: 'off'
              card:
                type: 'custom:button-card'
                icon: 'mdi:fan'
                name: Turn On
                confirmation:
                  text: Do you want to turn the HVAC system on?
                tap_action:
                  action: call-service
                  service: climate.turn_on
                  service_data:
                    entity_id: climate.thermostat
            - type: 'custom:button-card'
              entity: input_boolean.lock_temperature
              icon: 'mdi:thermometer'
              color_type: card
              name: Lock
              confirmation:
                text: Do you want to lock the thermostat at the current temperature?
              state:
                - value: 'on'
                  color: '#fac206'
            - type: 'custom:button-card'
              entity: input_boolean.disable_ac
              icon: 'mdi:fan'
              color_type: card
              name: Disable
              confirmation:
                text: Do you want to disable the air conditioning?
              state:
                - value: 'on'
                  color: '#fac206'
            - type: 'custom:button-card'
              entity: input_boolean.disable_heat
              icon: 'mdi:fire'
              name: Disable
              confirmation:
                text: Do you want to disable the heat?
              state:
                - value: 'on'
                  color: '#fac206'
            - type: conditional
              conditions:
                - entity: climate.thermostat
                  state_not: 'off'
              card:
                type: 'custom:button-card'
                icon: 'mdi:fan'
                name: Turn Off
                confirmation:
                  text: Do you want to turn the HVAC system back off?
                tap_action:
                  action: call-service
                  service: climate.turn_off
                  service_data:
                    entity_id: climate.thermostat
```

**Comment by pedolsky** [comment]
>       font-weight: bold
>       tap_action:
>         action: c

The indentation is not correct. In your code the tap action is part of the style section what is wrong. 

It has to be like that:

```
style: 
  font-weight: bold
  etc.
tap_action:

```

I just tried it with a picture-elements card and it works flawlessly:

```
type: picture-elements
elements:
  - type: state-badge
    entity: light.wohnzimmerlicht
    style:
      top: 32%
      left: 40%
    tap_action:
      action: call-service
      service: browser_mod.popup
      service_data:
        title: Test
        card:
          type: light
          entity: light.wohnzimmerlicht
image: /local/box.png

```
