### ISSUE TITLE
Feature Request - Name media players based on config.yaml

### ISSUE THREAD

**Issue by kloggy** [thomasloven/hass-browser_mod#23]
Would it be possible to have the `media-player` entities named as per the alias's created in the `config.yaml`?

i.e. for
```
browser_mod:
  devices:
    99980b13-dabc9563:
      name: arrakis
    d2fc860c-16379d23:
      name: dashboard
```
have two media_player's created,
`media_player.arrakis` and
`media_player.dashboard`
