### ISSUE TITLE
Navigation Snapshot

### ISSUE THREAD

**Issue by DivanX10** [thomasloven/hass-browser_mod#231]
The Home Assistant has a trick, it is to take snapshots of the state and then you can return to the state as it was before. We are talking about [scene.create service](https://community.home-assistant.io/t/the-scene-create-service-is-it-documented/178864). Can this be applied to browser_mod.navigate navigation? For example, I had page 1 open, then after starting the trigger, I opened page 2, when the trigger is re-triggered, it should return to page 1. Thus, no matter which page was opened, the return will always be to the page that was opened before switching.

**Comment by thomasloven** [comment]
The current path is available as an attribute to the `sensor` entity. You can save that somewhere.

**Comment by DivanX10** [comment]
I do not understand. How can browser_mod. navigate be used as a sensor and how can it be saved to the history? Can you make an example of how this can be done?

**Comment by thomasloven** [comment]
` {{ state_attr('sensor.xxxxxxxx-xxxxxxxx', 'path') }}` is the current path of device `xxxxxxxx-xxxxxxxx`.
You can store that in a variable or a input-text or something.

**Comment by DivanX10** [comment]
I don't have a device that can be recorded. I don't really understand how you can, for example, fix the last page. Let's say first I had the /lovelace-tablet / 1 tab open, then the /lovelace-tablet/5 tab opened, and as the trigger went off, the /lovelace-tablet/7 tab opened. How can I use it {{ state_attr('sensor.xxxxxxxx-xxxxxxxx', 'path') }} ? 

```
alias: 'Intercom: Incoming call. The sensor. Browser mod. Notification in a telegram'
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.domofon_incoming_call
    from: 'off'
    to: 'on'
condition: []
action:
  - service: notify.notify
    data:
      title: '*Intercom*'
      message: Someone rings the intercom
  - service: browser_mod.navigate
    data:
      navigation_path: /lovelace-tablet/7
mode: single
```

For example, how can I write navigation_path: / lovelace-tablet/7 to the history?
service: scene.create
data:
  snapshot_entities: navigation_path: /lovelace-tablet/5
  scene_id: navigation_path_history

**Comment by thomasloven** [comment]
```yaml

- variables:
    saved_path: "{{ state_attr('sensor.xxxxxxxx-xxxxxxxx', 'path') }}"
- service: browser_mod.navigate
  data:
    navigation_path: /lovelace-tablet/7
- ...do something else, a delay or wait for trigger or whatever
- service: browser_mod.navigate
  data:
    navigation_path: "{{ saved_path }}"
```

**Comment by DivanX10** [comment]
Thanks. I understand correctly that saved_path is a variable and when there is an entry in " {{saved_path }}", we get in the saved_path sensor: "{{state_attr ('sensor.lovelace_tablet_navigation_path', 'path')}} " entry, which page was opened? If we wrote to the sensor /lovelace-tablet/7, then in the sensor sensor. lovelace_tablet_navigation_path there will be an entry /lovelace-tablet/7, if we wrote to the sensor /lovelace-tablet/5, then in the sensor sensor. lovelace_tablet_navigation_path there will be an entry /lovelace-tablet/5


Here are two options, which one is correct?
```
service: scene.create
data:
  snapshot_entities: "{{ saved_path }}"
  scene_id: navigation_path_history
```
or

```
service: scene.create
data:
  snapshot_entities: sensor.lovelace_tablet_navigation_path
  scene_id: navigation_path_history
```

Tell me, for using-variables: do I need to put https://github.com/rogro82/hass-variables or is it a built-in function in HA?
