### ISSUE TITLE
browser_mod ignored when lovelace is accessed externally (Chrome based?)

### ISSUE THREAD

**Issue by gsotiriou** [thomasloven/hass-browser_mod#234]
I 've had a pretty rough time narrowing it  down - which by extension means that my testing may have not been thorough enough to answer all possible questions - but I am willing to test further. Here is what I have so far.

### Steps to reproduce:

1. Install browser_mod via HACS and paste the relevant configuration inside configuration.yaml
2. Use lovelace in .yaml  mode and use browser_mod to alter the more-info of a card to be another card
3. Open Chrome in a desktop/laptop PC running Windows and visit HA using the internal URL.
  - Expected: The mod should work and clicking the card affected by it should display the second card as more-info popup.
  - Actual: It does.
4. Close Chrome -> Clean cache.
5. Open Chrome in a desktop/laptop PC running Windows and visit HA using the external URL.
  - Expected: The mod should work and clicking the card affected by it should display the second card as more-info popup.
  - Actual: browser_mod gets ignored and the default more-info popup is displayed (also no deviceID is created for this session)
6. Open Android Companion App and use HA internal URL in app settings.
  - Expected: The mod should work and clicking the card affected by it should display the second card as more-info popup.
  - Actual: It does.
7. Close Android Companion App - remove from phone recently used (RAM) - visit app settings and clear cache
8. Open Android Companion App and use HA external URL in app settings.
  - Expected: The mod should work and clicking the card affected by it should display the second card as more-info popup.
  - Actual: browser_mod gets ignored and the default more-info popup is displayed (also no deviceID is created for this session)
9. Open iOS Companion App and repeat steps 6,7,8
  - Expected: The mod should work and clicking the card affected by it should display the second card as more-info popup.
  - Actual: browser_mod works as expected internally and externally as well!!!
10. Open Microsoft Edge in desktop/laptop PC running Windows and repeat steps 3,4,5
  - Expected: The mod should work and clicking the card affected by it should display the second card as more-info popup.
  - Actual: browser_mod works as expected internally and externally as well!!!

### configuration.yaml
```yaml
browser_mod:
  devices:
    d516f866-658301ba:
      name: g_desktop_chrome
    757d6caf-2cb3d566:
      name: v_mobile_companion
    07f9ff77-a48d0d75:
      name: g_mobile_companion
```
### ui-lovelace.yaml
```yaml
title: My House
views: !include_dir_list ui-lovelace/
```
### ui-lovelace\06-bedroom.yaml
```yaml
title: Bedroom
popup_cards:
  vacuum.roborock_vacuum_s5:
    title: Map control
    card:
      type: custom:xiaomi-vacuum-map-card
      entity: vacuum.roborock_vacuum_s5
      map_camera: camera.xiaomi_cloud_map_extractor
      camera_calibration: true
cards:
  - type: custom:vacuum-card
    entity: vacuum.roborock_vacuum_s5
    stats:
      default:
        - attribute: main_brush_left
          unit: hour(s) left
          subtitle: Main brush
        - attribute: side_brush_left
          unit: hour(s) left
          subtitle: Side brush
        - attribute: filter_left
          unit: hour(s) left
          subtitle: Filter
        - attribute: sensor_dirty_left
          unit: hour(s) left
          subtitle: Sensors
```
### Notes
I am by no means a web developer or enthusiast whatsoever , but in my mind it may be related to either the rendering engine used by iOS app vs Android App (which is basically Chrome - also the same culprit for desktop PC external discrepancy) ~~**OOOOOOORRRRR** it may be my proxy server (for external access) not forwarding something DOM-related to my internal-based instance correctly(?)~~.
