### ISSUE TITLE
Workaround for fire-dom-event

### ISSUE THREAD

**Issue by kimme1024** [thomasloven/hass-browser_mod#238]
My Home Assistant version: 2021.6.6

**What I am doing:**
I tried using browser_mod to create a popup (xiaomi-vacuum-map-card) from within a custom card (vacuum-card). I guess the custom card does not support fire-dom-event, so I made a workaround so that the action triggers a script that triggers the popup. However this makes the popup appear on all my devices.

**What I expected to happen:**
Show to popup on the device where the button is pressed.

**What happened instead:**
Shows the popup on every device.

**Minimal** steps to reproduce:

**Nothing happens:**
```yaml
actions:
  - name: Map
    icon: mdi:floor-plan
    tap_action:
      action: fire-dom-event
      browser_mod:
        command: popup
        title: Roborock Floor Plan
        large: true
        card:
          type: custom:xiaomi-vacuum-map-card
          entity: vacuum.xiaomi_vacuum_cleaner
          map_camera: camera.xiaomi_cloud_map_extractor
          camera_calibration: true
```

**Popup on all devices**
```yaml
actions:
  - name: Map
    icon: mdi:floor-plan
    service: script.vacuumpopup
```
```yaml
service: browser_mod.popup
data:
  title: Roborock Floor Plan
  large: true
  card:
    type: custom:xiaomi-vacuum-map-card
    entity: vacuum.xiaomi_vacuum_cleaner
    map_camera: camera.xiaomi_cloud_map_extractor
    camera_calibration: true
```

I hope there's a workaround for this issue...

Thanks in advance!
