### ISSUE TITLE
Popup to accept Conditional Cards: No row configured error

### ISSUE THREAD

**Issue by RazoredRaven** [thomasloven/hass-browser_mod#239]
My Home Assistant version: 2021.6.6

Browser_Mod version: 1.5.0

**What I am doing:**
Trying to get the Browser_Mod popup event to accept conditional cards.

**What I expected to happen:**
That an entity will only show in the popup if a condition is met.

**What happened instead:**
A Home Assistant frontend error shows the red box saying that it is incompatible. 

**Minimal** steps to reproduce:
It MIGHT be the way I've formatted my code, but here is a simple example of what I am trying to achieve:
```
type: button
entity: light.all_lights
tap_action:
  action: fire-dom-event
  browser_mod:
    command: popup
    deviceID: this
    title: Lights
    card:
      type: entities
      entities:
        - type: conditional
          conditions:
            - entity: light.all_lights
              state: 'off'
          card:
            type: button
            tap_action:
              action: toggle
            entity: light.all_lights
        - light.b2_lights
        - light.b3_lights
        - light.l1_lights
```

**Error messages from the browser console:**
```
No row configured
type: conditional
conditions:
  - entity: light.all_lights
    state: 'off'
card:
  type: button
  tap_action:
    action: toggle
  entity: light.all_lights
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
