### ISSUE TITLE
Add QR code sensor for FullyKiosk devices

### ISSUE THREAD

**Issue by vitalykorolev** [thomasloven/hass-browser_mod#24]
FullyKiosk has Javascript integration (https://www.ozerov.de/fully-kiosk-browser/#websiteintegration) that supports QR code/Barcode Scanning. With this integration devices with front camera could trigger actions for specific codes. For example, to activate and deactivate an alarm with a QR code keychain!

**Comment by thomasloven** [comment]
I've been experimenting a bit with this.
As it turns out, the QR scanning of FKB needs to be triggered manually, and will display a popup of sorts prompting for a QR code to be displayed for the camera.
QR code scanning also cannot be used while Motion Detection is enabled.

... so that makes it kind of useless...

However! Home Assistant has a QR processing integration https://www.home-assistant.io/integrations/qrcode/ which works very well with the new improved FKB camera in browser_mod (release 1.5.0).
I have made a `qrcode` entity connected to the new camera entity, set its scan interval to a very large number, and then have an automation to trigger more frequent scanning only on motion:

```yaml
image_processing:
  - platform: qrcode
    source:
      - entity_id: camera.browsermod_hallen
    scan_interval: 10000


automation:
- trigger:
    - type: motion
      platform: device
      entity_id: binary_sensor.browsermod_hallen
      domain: binary_sensor
  action:
    - repeat:
        while:
          - type: is_motion
            condition: device
            entity_id: binary_sensor.browsermod_hallen
            domain: binary_sensor
        sequence:
          - service: image_processing.scan
            target:
              entity_id: image_processing.qr_browsermod_hallen
          - delay:
              hours: 0
              minutes: 0
              seconds: 1
              milliseconds: 0
```

This seems to be very fast and reliable.
