### ISSUE TITLE
browser_mod.more_info - the problem is on Home Assistant 2021.8.5

### ISSUE THREAD

**Issue by DivanX10** [thomasloven/hass-browser_mod#244]
Home Assistant 2021.8.5

I installed the latest version of Home Assistant and ran into a problem. The window stopped showing when calling additional information. Tell me, is this a problem with the Home Assistant itself, or does your integration have an incompatibility with the latest version?

If I run it through the developer panel, then everything works
![image](https://user-images.githubusercontent.com/64090632/128907898-435946d0-1397-4efb-95a9-62e56346ee75.png)

If I click on the button and hold it for a long time, the service does not start, although it worked on version 2021.8.4 before the update
![image](https://user-images.githubusercontent.com/64090632/128908186-d1fc5cac-2eb1-46c0-a4d0-2ca46e3a972f.png)

```
type: button
tap_action:
  action: toggle
entity: switch.podsvetka_monitora_kompiutera_dima
show_state: true
icon: mdi:television-ambient-light
name: Подсветка монитора
hold_action:
  action: call-service
  service: browser_mod.more_info
  service_data:
    entity_id: input_select.gostinaia_podsvetka_monitora_vybor_tsveta
  target: {}
  
  service: browser_mod.more_info
  data:
    entity_id: input_select.gostinaia_podsvetka_monitora_vybor_tsveta
```
