### ISSUE TITLE
Service calls not working on Chromium?

### ISSUE THREAD

**Issue by acateon** [thomasloven/hass-browser_mod#250]
My Home Assistant version: core-2021.8.8

**What I am doing:**

All service calls to device running chromium fails silently. No info in the logs. The same calls to different deviceIDs works fine.

The device is identified correctly and the device sensor is in working order.

**What I expected to happen:**

Something

**What happened instead:**

Nothing

**Minimal** steps to reproduce:

Any service call

```yaml
# The least amount of code or steps possible to reproduce my error
type: browser_mod
last_seen: 2021-08-31T16:36:47.498547
deviceID: dashboard_display
path: /lovelace-dashboard-sidebar/home
visibility: visible
userAgent: Mozilla/5.0 (X11; CrOS armv7l 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.187 Safari/537.36
currentUser: Kiosk
fullyKiosk: false
width: 1280
height: 800
battery_level: 100
charging: true
darkMode: false
userData: 
id: 832b42c7d526459bacc43d4f708678d6
name: Kiosk
is_owner: false
is_admin: true
credentials:
  - auth_provider_type: homeassistant
    auth_provider_id: null
  - auth_provider_type: trusted_networks
    auth_provider_id: null
mfa_modules:
  - id: totp
    name: Authenticator app
    enabled: false

config: 
command: update
name: dashboard_display
# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [ x ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [ x ] Have made sure I am using the latest version of the plugin.

- [ x ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
