### ISSUE TITLE
Can't rename my devices that have entity ids with underscore instead of dash 

### ISSUE THREAD

**Issue by obriankevin11** [thomasloven/hass-browser_mod#254]
Hi,

I have devices with ids like `light.browser_2525f1b7_2e49af01`
```
browser_mod:
  prefix: "browser_"
  devices:
    2525f1b7_2e49af09:
      name: my_phone
```

But they are not renamed :(

how can I assign a correct id (with dash) to my device?
or
how can I rename device with underscore?

Thank you
