### ISSUE TITLE
FR: add View title to the browser_mod attributes

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/hass-browser_mod#259]
as title, it would be awesome if we could simply use `{{viewTitle}}` instead of having to use a rather extended template, especially when used with several dashboards, we now can (have to) do that using:

`{{state_attr('sensor.browsermod_id','path').split('/')[1].replace('_',' ').capitalize()}}`

to go from '/lovelace/media_players' to 'Media players' or
'/lovelace/home' to 'Home'

secondly, please let me ask if we can use these browser_mod attributes in card_mod themes? Suppose we can, given the fact they are regular Jinja, but just asking to be sure.

Use case: create a card_mod_theme mod and display the View title in the menubar.

thanks for considering!

**Comment by dcapslock** [comment]
@Mariusthvdb is this still needed? Does the `PathSegments` attribute of Browser Path give most of what you need?

**Comment by Mariusthvdb** [comment]
this is a very bold FR, and I have not used Browser mode in a long time because of the heavy burden issues we experienced. SO I need to revisit this.
exactly where can I find more info on that attribute `PathSegments`, and important, can we use  that in Jinja templating directly?

**Comment by Mariusthvdb** [comment]
well, yes, that would indeed answer your question ;-)
keep open for a real solution please.

**Comment by dcapslock** [comment]
I have a working prototype of new 'Panel' sensor which will report the panel title as well as some extra attributes. I have done it this way as as well as Lovelace panels, there are History, Energy, Custom Panels etc.

This gives viewTitle plus some extras. Let me know your feedback. Thanks.

#### Lovelace Panel on a second view

![Image](https://github.com/user-attachments/assets/ea00f6af-e5e8-4c19-a11a-e45234b78b46)

#### History Panel

![Image](https://github.com/user-attachments/assets/e46a986c-2bee-4657-bbda-5f580bcc8125)

**Comment by Mariusthvdb** [comment]
o that looks amazing, thanks!

before I mess up, how would we use those in a jinja template (either in frontend or backend)?

my hope was to be able to do in card-mod and use `{{FullTitle}}` ? is that correct now and are these available to the HA Jinja engine as-is, or do we still need a more complex syntax for that

btw which version is this? 2.4.0 release?

**Comment by dcapslock** [comment]
This is development at this stage. Targetting 2.4.1 

As fullTitle is an attribute, it would be state_attr(entity, "fullTitle"). 

If you would wish to have on all Browsers, but showing the fullTitle for current Browser, then i will have to work out the magic for that as well. Such would be handy for lots of things with Browser Mod.

**Comment by Mariusthvdb** [comment]
> If you would wish to have on all Browsers, but showing the fullTitle for current Browser, 

that would be the ultimate goal yes.... like we can use `{{user}}` now in the [Markdown](https://www.home-assistant.io/dashboards/markdown/#template-variables) . 

> then i will have to work out the magic for that as well. 

O dear, please only do if at all useful for other scenarios too in your opinion.

> Such would be handy for lots of things with Browser Mod.

Oeff, glad you mention that, makes me feel less embarrassed

**Comment by dcapslock** [comment]
> that would be the ultimate goal yes.... like we can use `{{user}}` now in the [Markdown](https://www.home-assistant.io/dashboards/markdown/#template-variables) .

If you are talking about `{{user}}` and card-mod, then yes, `{{browser}}` is available to card-mod just like `{{user}}`. But you have to do some magic like described in [Super charge Browser defaults..](https://github.com/thomasloven/hass-browser_mod/wiki/Super-charge-Browser-defaults-with-Default-action). So to get the Browser width for example, your card-mod jinja template would be `{{ states(device_entities(device_id(browser)) | select("contains", "_browser_width") | list | first) }}`.

> O dear, please only do if at all useful for other scenarios too in your opinion.

I have been looking into using `custom:config-template-card` which can use variables from javascript. As its stands currently with Browser Mod, the Browser's own entities are available in `window.browser_mod.browserEntities`. Each property is string for thet sensor. e.g. for my Browser `window.browser_mod.browserEntities.width = "sensor.dcd_browser_browser_width"`

So my working example, which works pretty well, is below. I think the new Panel sensor should be the fullTitle as that then makes sure the entity is seen to update when you change view. It seems that an attribute update does not always have `custom:config-template-card` force an update. More testing required.

If you like you can test all but the new Panel attribute (note comments in yaml) already with current Browser Mod and `custom:config-template-card`.

Overall, I am thinking that a custom Browser Mod wrapper card that supports UI editing and directly picking the local Browser entities would be much better that stuffing around with YAML in `custom:config-template-card`. While it works, you will see it is quite lengthy config with the variables etc.

```yaml
type: custom:config-template-card
variables:
  browserID: window.browser_mod.BrowserID
  browserActivityEntity: states[window.browser_mod.browserEntities.activity]
  browserBatterLevelEntity: states[window.browser_mod.browserEntities.battery_level]
  browserPanelEntity: states[window.browser_mod.browserEntities.panel] # Only in my development
  browserScreenEntity: states[window.browser_mod.browserEntities.screen]
  browserWidthEntity: states[window.browser_mod.browserEntities.width]
  browserHeightEntity: states[window.browser_mod.browserEntities.height]
entities:
  - ${browserActivityEntity.entity_id}
  - ${browserBatterLevelEntity.entity_id}
  - ${browserPanelEntity.entity_id}
  - ${browserScreenEntity.entity_id}
  - ${browserWidthEntity.entity_id}
  - ${browserHeightEntity.entity_id}
card:
  type: entities
  entities:
    - entity: ${browserActivityEntity.entity_id}
      show_state: false
      name: ${browserID}
      icon: "false"
      type: custom:multiple-entity-row
    - entity: ${browserActivityEntity.entity_id}
      name: Activity
    - entity: ${browserPanelEntity.entity_id} # Only in my development
      type: custom:multiple-entity-row
      attribute: fullTitle
      name: Current
      entities:
        - entity: ${browserWidthEntity.entity_id}
          name: Width
        - entity: ${browserHeightEntity.entity_id}
          name: Height
    - entity: ${browserScreenEntity.entity_id}
      type: custom:slider-entity-row
```

<img width="653" alt="Image" src="https://github.com/user-attachments/assets/e64d9129-24e5-46f7-839f-ff764f29728a" />

Thanks for your feedback on my development. If we are to include new features I want to make sure to get it right.
