### ISSUE TITLE
deviceID not working in automation with browser_mod.popup service

### ISSUE THREAD

**Issue by ShlomiPorush** [thomasloven/hass-browser_mod#262]
My Home Assistant version: 2021.11.0

**What I am doing:**
I created an automation that if someone rings the bell the camera feed will popup in Home Assistant on the tablet installed next to the door.
I created the automation and everything works properly except for the part where the popup should only popup on the tablet and not on all devices.

**What I expected to happen:**
the popup should popup on the tablet. 

**What happened instead:**
nothing. The popup does not popup on any device.
if I remove the deviceID part it works find (pops up on all devices)

**Minimal** steps to reproduce:
Use the code below as an action in a automation or call browser_mod.popup service

```yaml
# The least amount of code or steps possible to reproduce my error
`service: browser_mod.popup
data:
  title: Door
  card:
    type: picture-entity
    entity: camera.door
  large: true
  auto_close: true
  deviceID:
    - tablet_home`
# Put your code/steps here
```

**Error messages from the browser console:**
nothing. blank. no errors.
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- X Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- X Have made sure I am using the latest version of the plugin.

- X Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- X Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
