### ISSUE TITLE
Popup cards not working on HA Core 2021.12

### ISSUE THREAD

**Issue by jimbovp** [thomasloven/hass-browser_mod#274]
Hi

I just upgraded my HA Core to v2021.12 and the "popup_cards" config in lovelace seems to be broken.
A sample config (in the lovelace yaml):
```
  - title: Living 
    path: Living
    icon: mdi:sofa
    popup_cards:
      light.automatische_lichten:
        title: Sfeerlicht
        card:
          type: entities
          entities:
            - light.sonoff_plug_aquarium
            - light.sonoff_plug_barkast
```
This should replace the `more-info` box of `light.automatische_lichten` by an entities card on long press, but it doesn't.
Was working perfectly fine before the upgrade (up to 2021.11.8).
I didn't find any relevant logs, except for the log mentioned in  #273, but I don't believe it's related.

thx for your time!

**Comment by reidprichard** [comment]
I only just installed browser_mod after upgrading to 2021.21, but popups don't work for me either. This simple service call does nothing in dev tools:
```
service: browser_mod.popup
data:
  type: entity
  entity: light.office_lamp
```
