### ISSUE TITLE
Not loading Lovelace resources?

### ISSUE THREAD

**Issue by drinfernoo** [thomasloven/hass-browser_mod#283]
I noticed this weekend that I'm unable to get `custom:auto-entities` working in a `browser_mod` popup card...

@thomasloven mentioned on Discord:

> Could be that browser_mod doesn't propperly preload lovelace resources then. I'll have to look into that.

For a little further context, I'm attempting to load the popup via a service call from Developer Tools, but the card displays `Custom element doesn't exist: auto-entities.` on all my devices.

**Comment by thomasloven** [comment]
This is not a problem with browser_mod.
First get your card to work in lovelace, and then copy it over to the popup.

I think you should also review the auto-entities documentation.

**Comment by drinfernoo** [comment]
My apologies, I realized that was bad code, but this still doesn't work:
```yaml
service: browser_mod.popup
data:
  title: All Lights
  card:
    type: custom:auto-entities
    card:
      type: entities
    filter:
      include:
        domain: light
```
![image](https://user-images.githubusercontent.com/2319508/156017002-80a09fa2-8c3f-4dba-a3ff-caf328be8e61.png)
