### ISSUE TITLE
Battery values not updating in Brave browser

### ISSUE THREAD

**Issue by KixMan28** [thomasloven/hass-browser_mod#289]
My Home Assistant version: 2021.12.9
browser_mod version: 1.5.1

**What I am doing:**
I am using Brave browser and I have opened Home Assistant in to tabs: one is via Nabu Casa link and the other one the local instance (local_ip:8123). The browser mod has created 2 devices, one for each tab. From the device sensor I extracted with template the battery value, but for some reason the battery values won't update. The same battery entity works correctly if I open HA in Chrome browser.

**What I expected to happen:**
The battery entities to update their values according to the laptop's battery real value.  

**What happened instead:**
The battery values stay at 100% all the time and the charging attribute is always true, even the charger is not connected.

**Minimal** steps to reproduce:
NA
```yaml
# The least amount of code or steps possible to reproduce my error
# the Nabu Casa instance battery template
    brave_battery:
      friendly_name: "Brave Battery"
      unit_of_measurement: '%'
      device_class: battery
      value_template: "{{ state_attr('sensor.brave', 'battery_level') }}"
      unique_id: brave_batt
# the local instance battery template
    brave_local_battery:
      friendly_name: Brave Local Battery
      unit_of_measurement: '%'
      device_class: battery
      value_template: "{{ state_attr('sensor.brave_local', 'battery_level') }}"
      unique_id: brave_local_batt

# Configuration.yaml config:
devices:
  92eb4031-4cb22a80:
    name: sm_a51
    disable:
      - light
#        - sensor
#        - media
  d8e6dc4d-2b330088:
    name: dell_nc
    disable:
      - light
  74a8987c-2255ff53:
    name: brave
    disable: 
      - light
  9caec258-bca2f31d:
    name: brave_local
    disable:
      - light
   

# sensor.brave attributes:
type: browser_mod
last_seen: '2022-01-11T23:43:35.461054'
deviceID: 74a8987c-2255ff53
path: /developer-tools/state
visibility: visible
userAgent: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/97.0.4692.71 Safari/537.36
currentUser: Csaba
fullyKiosk: false
width: 1536
height: 726
battery_level: 100
charging: true
darkMode: false
userData:
  id: 4fe74b738bd94d4f8355531e7caXXXXX
  name: Csaba
  is_owner: true
  is_admin: true
  credentials:
    - auth_provider_type: homeassistant
      auth_provider_id: null
  mfa_modules:
    - id: totp
      name: Authenticator app
      enabled: false
config:
  command: update
  name: brave
  disable:
    - light
friendly_name: Sensor Brave

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

No error messages

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
