### ISSUE TITLE
Feature Request: Close popup on all devices

### ISSUE THREAD

**Issue by noxhirsch** [thomasloven/hass-browser_mod#29]
It would be great to have the option to close the popup on all devices when closed on one device:

```
service: browser_mod.popup
service_data:
  title: Popup example
  close_on_all: true
  card:
    type: entities
    entities:
      - light.bed_light
      - light.kitchen_lights
      - light.ceiling_lights
  deviceID:
    - dashboard_1
    - dashboard_2
    - dashboard_3
```
As soon as the popup is closed on e.g. `dashboard_2` it gets closed on `dashboad_1` & `dashboard_3`, too. So you don't have to close it on every dashboard if you already have seen it on one.

Thank you in advance :)
