### ISSUE TITLE
Some entities are not listed under in the browser mod integration page or assigned to device

### ISSUE THREAD

**Issue by markfrancisonly** [thomasloven/hass-browser_mod#300]
Running Home Assisstant 2022.2.9 but this issue has been occurring since I first used browser mod, and at least prior to the introduction of fully kiosk cameras support

### What I expected to happen:
All entities created by browser mod should appear under the Browser mod integration page entity listing, and all entities should be associated with a parent device. 

### What happened instead:

In my setup, only the sensor and light entities are shown under the browser mod integration entity list page.  

camera, media_player, and binary_sensor (motion) entities have no related parent browser device. 

### Steps to recreate:

Install browser mod, wait for entities to be generated, toggle light screens to positively confirm device id, add device ids as named device in yaml configuration: 

```yaml
prefix: "browser_mod_"

devices:
  da6a061-60b25539:
    name: Family Tablet
  1695b6ec-ff180641:
    name: Bedroom Wallpanel
  8cefd3c1-8e6fa89f:
    name: Nightstand Tablet
  b4d3deb5-4c17b89c:
    name: Desk Tablet
  23de826-8e589d2f:
    name: Kitchen Wallpanel
disable:
  - all

```

Other information:
All five devices are running the latest paid version of Fully Kiosk Browser APK ver. 1.46 (for Fire OS)

**Other thoughts**

Only a subset of Browser mod entities have a related device, and I suspect that entities without a related device are lost in the home assistant ui due to come type of configuration corruption. 

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
