### ISSUE TITLE
device_state_attributes

### ISSUE THREAD

**Issue by swa72** [thomasloven/hass-browser_mod#304]
My Home Assistant version:  2022.3.0

**What I am doing:**
Reboot HA.

**What I expected to happen:**
No warnings in log.

**What happened instead:**
Warnings in log.

**Minimal** steps to reproduce:
Reboot HA

```yaml
# The least amount of code or steps possible to reproduce my error
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:583
First occurred: 17:57:46 (6 occurrences)
Last logged: 18:05:44

Entity light.browser_9185a9b3_f83b9809 (<class 'custom_components.browser_mod.light.BrowserModLight'>) implements device_state_attributes. Please report it to the custom component author.
Entity media_player.browser_4829eb14_9690bdf4 (<class 'custom_components.browser_mod.media_player.BrowserModPlayer'>) implements device_state_attributes. Please report it to the custom component author.
Entity light.browser_4829eb14_9690bdf4 (<class 'custom_components.browser_mod.light.BrowserModLight'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.browser_4829eb14_9690bdf4 (<class 'custom_components.browser_mod.sensor.BrowserModSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.browser_9185a9b3_f83b9809 (<class 'custom_components.browser_mod.sensor.BrowserModSensor'>) implements device_state_attributes. Please report it to the custom component author.
# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [ X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [ X] Have made sure I am using the latest version of the plugin.

- [ X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
