### ISSUE TITLE
Input_select doesnt refresh in the Popup

### ISSUE THREAD

**Issue by pimp1310** [thomasloven/hass-browser_mod#310]
My Home Assistant version: newest

**What I am doing:**

i have a popup, where i want to change a input_select, for choosing a room to play media.
But after i change the input_select i must close and reopen the popup for the actually state of the input_select

**What I expected to happen:**
 when i change the input_select, he should refresh the state of the input_select

**What happened instead:**

nothing, i must close and reopen the popup, he still saves the old state of the input_select

**Minimal** steps to reproduce:
make a entity-card with the input_select, then make a button-card with the tab_action : input_select.set_options
then press the button-card, and you see the entity not refreshed. in the normal Home page it works well.

```yaml
# The least amount of code or steps possible to reproduce my error

- type: custom:button-card
            triggers_update:
              - light.dummy_light_plexmedia
            tap_action:
              action: fire-dom-event
              browser_mod:
                deviceID:
                  - this
                command: popup
                hide_header: false
                title: Plex Medien
                large: false
                style:
                  ..........
                card:
                  type: vertical-stack
                  cards:
                      - type: horizontal-stack
                        cards:
                           - type: button
                              tap_action:
                                action: call-service
                                service: input_select.set_options
                                service_data:
                                  entity_id: input_select.test
                                  options:
                                    - IT WORKS HERE
                              entity: light.dummy_light_plexmedia
                              name: HERE I SET THE INPUT_SELECT`
                          - type: entity
                             entity: input_select.test
# Put your code/steps here
```
`type: button
tap_action:
  action: call-service
  service: input_select.set_options
  service_data:
    entity_id: input_select.test
    options:
      - IT WORKS HERE
entity: light.dummy_light_plexmedia
name: HERE I SET THE INPUT_SELECT`

`type: entity
entity: input_select.test`

**Error messages from the browser console:**
NO ERROR MESSAGE
```


**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [ X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X ] Have made sure I am using the latest version of the plugin.

- [ X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
