### ISSUE TITLE
Browser_mod ignoring directives

### ISSUE THREAD

**Issue by sts098** [thomasloven/hass-browser_mod#321]
My Home Assistant version: 0.XX.X
Version | core-2022.4.7
Installation Type | Home Assistant OS
Browser_mod 1.5.3 installed via HACS

**What I am doing:**
Added:

# Browser Mod
browser_mod:
  prefix: 'browser_mod_'
  devices:
    0bd8dd7b-3c2b0cd4:
      name: wallpanel
      disable:
        - light
    0f8b0ca6-68cf16b4:
      name: laptop_pc
      disable:
        - light

to configuration.yaml

**What I expected to happen:**
I expected entities to be renamed, and light entities to be removed

**What happened instead:**
still have:
sensor.browser_mod_0f8b0ca6_68cf16b4
light.browser_mod_0f8b0ca6_68cf16b4

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error
# Browser Mod
browser_mod:
  prefix: 'browser_mod_'
  devices:
    0bd8dd7b-3c2b0cd4:
      name: wallpanel
      disable:
        - light
    0f8b0ca6-68cf16b4:
      name: laptop_pc
      disable:
        - light

# Put your code/steps here
n/a

**Error messages from the browser console:**
none
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
