### ISSUE TITLE
Certain dropdown menu's close pop-up

### ISSUE THREAD

**Issue by Xitro01** [thomasloven/hass-browser_mod#331]
My Home Assistant version: 2022.5

**What I am doing:**
I open a browser mod pop-up with a light entity and click the dropdown to select a scene.

**What I expected to happen:**
That I would be able to select a scene without the pop-up closing.

**What happened instead:**
When clicking anywhere, even outside of the dropdown or on an item in the dropdown, the pop-up closes without selecting anything.

**Minimal** steps to reproduce:
Create a pop-up with a light entity with a scene. Make the pop-up trigger and try selecting something in the dropdown.

This issue also happens with the Xiaomi Vacuum Map Card plug-in, but does not happen on dropdowns/selection boxes which are created directly by an entity.

```yaml
# The least amount of code or steps possible to reproduce my error
hold_action:
    action: fire-dom-event
    browser_mod:
      command: popup
      title: >
        [[[ return entity === undefined || entity.attributes.friendly_name; ]]]
      card:
        type: custom:light-popup-card
        entity: >
          [[[ return variables.entity_id; ]]]
        icon: none
        fullscreen: false
        brightnessWidth: 130px
        brightnessHeight: 360px
        borderRadius: 1.7em
        sliderColor: "#c7c7c7"
        sliderTrackColor: rgba(25, 25, 25, 0.9)
        displayType: slider
        actionSize: 4.5em
        actionsInARow: 2
        actions:
          - action: call-service
            service: light.turn_on
            color: "#d8d9e1"
            service_data:
              entity_id: >
                [[[ return variables.entity_id; ]]]
              color_temp: 153
          - action: call-service
            service: light.turn_on
            color: "#d5b08d"
            service_data:
              entity_id: >
                [[[ return variables.entity_id; ]]]
              color_temp: 326
          - action: call-service
            service: light.turn_on
            color: "#ce944b"
            service_data:
              entity_id: >
                [[[ return variables.entity_id; ]]]
              color_temp: 500
          - action: fire-dom-event
            image: >-
              data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 
              50 50"%3E%3Cstyle%3Esvg%7Bbackground:radial-gradient(circle,rgba(255,255,
              255,1) 0%25,rgba(255,255,255,0) 80%25),conic-gradient(%237827e6,%23e622e7,
              %23e40588,%23e41919,%23e5691e,%23e8e22e,%237de629,%2334e828,%2333e75c,
              %2334e8e0,%23207de5,%231227e5,%237827e6)%7D%3C/style%3E%3C/svg%3E
            browser_mod:
              command: popup
              title: >
                [[[ return entity === undefined || entity.attributes.friendly_name; ]]]
              card:
                type: custom:light-entity-card
                entity: >
                  [[[ return variables.entity_id; ]]]
                brightness: true
                color_temp: true
                white_value: true
                full_width_sliders: false
                hide_header: true
                show_slider_percent: true
                #smooth_color_wheel: true
                persist_features: true
                consolidate_entities: true
# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it
CARD-MOD 3.1.4 IS INSTALLED
card-mod.js:5 Card-mod is loaded as a module
entities.js:28   SPOTIFY-CARD   Version 2.4.0    
mini-graph-card-bundle.js?hacstag=1512800620110:1  MINI-GRAPH-CARD  0.11.0 
card-mod.js?hacstag=190927524314:5 Card-mod is loaded as a module
card-tools.js?hacstag=16140332811:90 CARD-TOOLS 2.1.2 IS INSTALLED  DeviceID: bcde0905-2bbdbee0
xiaomi-vacuum-map-card.js?hacstag=1933720442011:829    XIAOMI-VACUUM-MAP-CARD      Version v2.0.11          
kiosk-mode.js?hacstag=303101606172:64 ≡ kiosk-mode            ⋮ 
version 1.7.2            
layout-card.js?hacstag=156434866242:228 LAYOUT-CARD 2.4.2 IS INSTALLED
button-card.js?hacstag=146194325342:425   BUTTON-CARD   Version 3.4.2 
apexcharts-card.js?hacstag=331701152201:835  APEXCHARTS-CARD  v2.0.1 
light-entity-card.js?hacstag=168744428500:6868   LIGHT-ENTITY-CARD     Version 5.0.0       
slider-entity-row.js?hacstag=1448997001721:1 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
(anonymous) @ slider-entity-row.js?hacstag=1448997001721:1
slider-entity-row.js?hacstag=1448997001721:59 SLIDER-ENTITY-ROW 17.2.1 IS INSTALLED 
stack-in-card.js?hacstag=248954055020:200  STACK-IN-CARD    Version 0.2.0   
swipe-card.js?hacstag=192732887400:21    SWIPE-CARD   Version 4.0.0 
bar-card.js?hacstag=163363577320:4855   BAR-CARD   Version 3.1.7    
calendar-card.js:1065   CALENDAR-CARD     Version 3.109.0 
browser_mod.js:145 BROWSER_MOD 1.5.3 IS INSTALLED    DeviceID: x
23browser_mod.js:145 Uncaught (in promise) 3
DevTools failed to load source map: Could not load content for https://x/hacsfiles/cover-popup-card/index.m.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
