### ISSUE TITLE
browser_mod popup overlaps native popup.

### ISSUE THREAD

**Issue by kulmegil** [thomasloven/hass-browser_mod#336]
My Home Assistant version: 2022.6.6

**What I am doing:**
Opening entity's settings popup from more-info popup from browser_mod popup.

**What I expected to happen:**
Settings popup is visible and on top.

**What happened instead:**
browser_mod popup overlaps entity settings poup.

**Minimal** steps to reproduce:
1) Open custom browser_mod popup
2) Open any native more-info popup
3) Open entity settings popup using gear icon (admin user)

```yaml
# The least amount of code or steps possible to reproduce my error
type: button
entity: light.kitchen
tap_action:
  action: fire-dom-event
  browser_mod:
    command: popup
    title: Popup example
    card:
      type: entities
      entities:
        - light.kitchen
# Put your code/steps here
```

**Error messages from the browser console:**

```
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```
(not error just a warnings from /frontend_latest/9d0be70d.js when opening settings popup, looks unrelated)

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

https://user-images.githubusercontent.com/570575/174150888-abcc5530-d36a-4fa2-8dd5-0e8d1211f875.mp4
