### ISSUE TITLE
Playing Arlo camera plays last recording and not current stream

### ISSUE THREAD

**Issue by EvanRowls** [thomasloven/hass-browser_mod#337]
Home Assistant Core: 2022.6.6
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2
Frontend version: 20220601.0

**What I am doing:**
Using the camera popup from the Cookbook

**What I expected to happen:**
Popup should play current stream from camera

**What happened instead:**
Popup plays last recording from Camera

**Minimal** steps to reproduce:
Add the camera popup automation from the Cookbook

```yaml
alias: Play Doorbell
description: ''
trigger:
  - platform: state
    entity_id:
      - binary_sensor.aarlo_motion_doorbell
    from: 'off'
    to: 'on'
condition: []
action:
  - service: browser_mod.more_info
    data:
      hide_header: true
      auto_close: true
      entity_id: camera.aarlo_doorbell
      deviceID:
        - {{deviceID}} (replaced with my device's id)
mode: single
hide_entity: true
initial_state: true

```

No error messages

I am not able to test it with any other cameras.

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
