### ISSUE TITLE
How to restrict popup to current device?

### ISSUE THREAD

**Issue by totalitarian** [thomasloven/hass-browser_mod#341]
I assumed I could use this

```
    tap_action:
      action: call-service
      service: browser_mod.more_info
      service_data:
        entity_id: camera.side
        deviceid:
          - this
```

but the popup still happens on all device.
