### ISSUE TITLE
Map in popup doesn't work on first load

### ISSUE THREAD

**Issue by IDmedia** [thomasloven/hass-browser_mod#344]
My Home Assistant version: 2022.6.7

**What I am doing:**
Trying to use a map-card in a popup in order to show a users location

**What I expected to happen:**
The popup to open and the map to be displayed inside the popup

**What happened instead:**
The popup is blank when initially opened (the map-card isn't loaded). Closing the popup and triggering the event once more (without reloading the page) shows the map as intended. Reloading the page breaks it and requires the user to close the popup at least once in order for the map to be displayed.

**Minimal** steps to reproduce:
Add a tap_action to anything and use the following snippet:
```yaml
        tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            title: 'User Location'
            card:
              type: map
              entities:
                - person.doctor_who
```

**Error messages from the browser console:**
No errors are logged. The popup's div is just blank

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
