### ISSUE TITLE
Templates not rendering on popup via server call

### ISSUE THREAD

**Issue by TheFes** [thomasloven/hass-browser_mod#349]
My Home Assistant version: 2022.8.1

**What I am doing:**
Creating a popup with cards which are using templates. Small example would be this card:
```yaml
type: vertical-stack
cards:
  - type: markdown
    content: The input boolean is {{ states('input_boolean.test') }}
  - type: entities
    entities:
      - entity: input_boolean.test
 ```

**What I expected to happen:**
I would expect the state in the markdown card to change if I toggle the input_boolean in the entity card. This works perfectly fine if I use the popup in a browser call, using the toggle will change the state shown in the markdown card.
However, if I use a server call the initial state is shown correctly on the popup, but when I toggle the input_boolean, the state shown in the markdown card will not change.
![image](https://user-images.githubusercontent.com/28803438/183071342-8d3e7d78-cd76-4047-8bc5-1bacd3b6349a.png)

Closing the popup and opening it again will show the correct state.

**What happened instead:**
See above

**Minimal** steps to reproduce:
Create an `input_boolean.test`  and run the script below :)

```yaml
test_script:
  alias: "ZZ - Script for quick tests"
  icon: mdi:test-tube
  sequence:
    - alias: "popip"
      service: browser_mod.popup
      data:
        content:
          type: vertical-stack
          cards:
            - type: markdown
              content: The input boolean is {{ states('input_boolean.test') }}
            - type: entities
              entities:
                - entity: input_boolean.test
```

**Error messages from the browser console:**

```
none
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by TheFes** [comment]
@thomasloven provided the solution
The script already renders the templates before sensing them to the frontend.
By wrapping the template in `{% raw %}` and `{% endraw %]` it acually sends the template instead of the result.
Using that it works in the card

```yaml
test_script:
  alias: "ZZ - Script for quick tests"
  icon: mdi:test-tube
  sequence:
    - alias: "popip"
      service: browser_mod.popup
      data:
        content:
          type: vertical-stack
          cards:
            - type: markdown
              content: >
                {% raw %}
                  {{ 'The input boolean is ' ~ states('input_boolean.test') }}
                {% endraw %}
            - type: entities
              entities:
                - entity: input_boolean.test
```
