### ISSUE TITLE
browser_mod.lovelace_reload doesn't trigger lovelace reload/refresh

### ISSUE THREAD

**Issue by greberg** [thomasloven/hass-browser_mod#35]
Hi

Can't get browser_mod.lovelace_reload service to work. I have tried it from HA service menu as well as from an automation and can't get it to work. Just for my understanding, I assume that you don't give any service data to browser_mod.lovelace_reload like DeviceId or so.

Best regards Peter

**Comment by thomasloven** [comment]
Correct. Perhaps you misunderstand what it is supposed to do.

browser_mod.lovelace_reload does the same thing as clicking the three dots in the top right corner and select Refresh. It reloads the lovelace configuration from the server, but does not cause the browser to refresh the view (as with e.g. F5).

**Comment by igloo15** [comment]
is it possible to add a browser reload as F5? Some of the cameras feeds on my lovelace interface do not show up after HA is restarted unless I reload the webpage entirely. Would be nice to do that through this mod.

**Comment by Dino-Tech** [comment]
@igloo15  I have been using this `script` effectively for quite some time now:
```yaml
browser_navigate:
  sequence:
    - service: browser_mod.lovelace_reload
    - delay: '00:00:03'
    - service: browser_mod.navigate
      data:
        navigation_path: /lovelace/0 #<-- or whatever view
```
works well with my mounted tablets.

**Comment by igloo15** [comment]
@Dino-Tech that works but I think I would have to do per device as each one has a different view

**Comment by Dino-Tech** [comment]
@igloo15  then use `deviceID` like this:
```yaml
    - service: browser_mod.navigate
      data:
        navigation_path: /lovelace/0
        deviceID:
          - OfficePC
          - OfficeTab LAN
          - Kiosk
```

**Comment by igloo15** [comment]
@Dino-Tech I implemented your script today but unfortunately it didn't work. Navigating didn't do whatever refreshing the page does to make the camera picture-entities reconnect. 

I am going to try and mod this and see if I can add the reload function

**Comment by Dino-Tech** [comment]
@igloo15  Seems I remember I had one device that gave me issues. I had to navigate off the view> reload> then navigate back to the home view> reload again to get the proper refresh needed. Seems like a lot of unnecessary steps, but since the action was automated to fire the `script`, I only had to set it up once. My issue was originally screen loading/displaying and not camera related though. May not be what you are needing.

**Comment by igloo15** [comment]
@Dino-Tech I already tried the navigate somewhere else and then back again and it did not work. Regardless I modded the plugin in like 2 minutes and got the desired reload I was looking for.

If @thomasloven wants I can submit a pull request with the changes to add a page reload function. The steps to recreate are simple:

1. Locate browser_mod.js in the browser_mod plugin
2. Find the following piece of code in that file `case "lovelace-reload":{somestuff} break;`
3. After the `break;` insert this code `case "window-reload":window.location.reload(false);break;`
4. Find const.py file it should be in same folder as browser_mod.js
5. Insert in the USER_COMMANDS array the following string: `"window-reload",` doesn't matter where just insert it
6. Restart Home Assistant

If all worked correctly you should now have a service called browser_mod.window_reload. Calling this service will reload all the pages connected. You may have to hard refresh and clear cache of all clients connected to web browser so you can get the new browser_mod.js.

**Comment by gamer06** [comment]
@igloo15 This solution "window-reload" still working for you?
Thanks

**Comment by Dino-Tech** [comment]
@gamer06  yes it does, but I added the new service like this. Working well ATM, but loading frontend still buggy post `0.107.3` 
```yaml
browser_window_reload:
  sequence:
    - service: lovelace.reload_resources
    - delay: '00:00:10'
    - service: browser_mod.window_reload
      data:
        navigation_path: /lovelace/home
        deviceID:
          - OfficeTab LAN
          - Kiosk
          - mainKiosk
          - OfficePC
```
Anyone have a better solution, please post and thanks!

**Comment by gamer06** [comment]
> @gamer06 yes it does, but I added the new service like this. Working well ATM, but loading frontend still buggy post `0.107.3`
> 
> ```yaml
> browser_window_reload:
>   sequence:
>     - service: lovelace.reload_resources
>     - delay: '00:00:10'
>     - service: browser_mod.window_reload
>       data:
>         navigation_path: /lovelace/home
>         deviceID:
>           - OfficeTab LAN
>           - Kiosk
>           - mainKiosk
>           - OfficePC
> ```
> 
> Anyone have a better solution, please post and thanks!

@Dino-Tech i dont have "lovelace.reload_resources" in services...

**Comment by Dino-Tech** [comment]
you should, (I think) after `0.107.+` unless that's for `mode: yaml` only...IDK, but it popped up as soon as I updated to `0.107.1` However, the `window-reload` mod was working after latest update from dev service for me

**Comment by gamer06** [comment]
i'm in 0.107.4 and di havent the "lovelace.reload_resources. I will wait more updates to see if change. But the window-reload doesnt work for me too

**Comment by igloo15** [comment]
@gamer06 It is still working for me on 0.106.6. I have not upgraded to 0.107 yet. I do not reload lovelace as part of my automation. Instead on homeassistant start I reload the webpages. I have to do this because when I restart homeassistant the various video feeds I have on my monitors do not reload correctly. The below automation waits 15 seconds after homeassistant start and then reloads all the connected browsers. I also manually run the automation when I make lovelace changes but I manually hit the lovelace refresh usually.

```
id: 'Reload on startup'
  alias: Restart Browsers
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: '15'
  - data: {}
    service: browser_mod.window_reload
```

**Comment by igloo15** [comment]
@gamer06 I just updated to 0.107.4 and windows-reload is still working for me. I made a new script that accomplishes what I think you want to do and it works. I don't know what `lovelace.reload_resources` is but this works.

```
browser_reload:
  alias: Browser Reload
  sequence:
  - service: browser_mod.lovelace_reload
  - delay: 00:00:03
  - service: browser_mod.window_reload
```
