### ISSUE TITLE
Strange left-side sticky to screen edge when using size: wide on 2.0

### ISSUE THREAD

**Issue by chertvl** [thomasloven/hass-browser_mod#360]
My Home Assistant version: 2022.8.7

**What I am doing:**  Tried to create pop-up with some cards inside. But when I use ```size: wide``` option in mobile view cards not symmetry and somehow sticky to left corner of screen. It happens when screen width <450px. Some screenshots below.

**What I expected to happen:** Well-centered card on mobile screen

**What happened instead:** Cards sticky to the left edge of the screen.

**Minimal steps to reproduce:**  Create card in popup (yaml below) with parameter ```size: wide```, then go to f12 and change size of screen (preview) to width <450.

```
type: button
entity: light.mirror
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      size: wide
      content:
        type: button
        entity: light.mirror

```

BrowserMod 1.X:
![image](https://user-images.githubusercontent.com/38353584/188280814-4b2bdca4-fa5a-4405-87d1-3f1b3b786d94.png)

BrowserMod 2.0:
![image](https://user-images.githubusercontent.com/38353584/188281012-eb6c20b0-8948-4139-9048-841709c4a83e.png)
![image](https://user-images.githubusercontent.com/38353584/188280903-4d205068-6bf9-45b3-8817-59b6e9d2cf07.png)

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
