### ISSUE TITLE
popup no longer works

### ISSUE THREAD

**Issue by herveaurel** [thomasloven/hass-browser_mod#362]
Hello, I updated, uninstalled the integration, then installed it again. But, my popup windows don't open anymore.

Exemple : 
```yaml
tap_action:
  action: fire-dom-event
  browser_mod:
    command: popup
    title: Personnes
    card:
      type: vertical-stack
      cards:
        - type: grid
          cards:
            - type: custom:button-card
              template:
                - bouton_person_herve
            - type: custom:button-card
              template:
                - bouton_person_alex
            - type: custom:button-card
              template:
                - bouton_person_tom
          square: false
          columns: 3
```
What should I do  ?

**Comment by Zeunas** [comment]
Try replacing "card:" with "condition:". Also recommend to build the service from scratch as it's UI friendly now.

**Comment by thomasloven** [comment]
Replace
```yaml
action: fire-dom-event
browser_mod:
  service: popup
  title: Your title
  card:
    type: ... etc...
```
with
```yaml
action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: Your title
    content:
      type: ...etc...
```
