### ISSUE TITLE
can't get new popup to work

### ISSUE THREAD

**Issue by bkbartk** [thomasloven/hass-browser_mod#365]
I think I'm missing something, but I don't know what it is.
I migrated from v 1.5.3 to 2.0.0
And I am trying to recreate my popup cards.

Using the UI popup-card is not available.
But I tried the following 2 methodes.

```
show_name: true
show_icon: true
show_state: true
type: glance
entities:
  - entity: sensor.011090518272000349_bsh_common_option_remainingprogramtime
    icon: mdi:dishwasher
    name: Afwasmachine
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.more_info
        data:
          entity: light.dimmer_slaapkamer
  - entity: sensor.bosch_wav28kh7nl_68a40e90e01e_bsh_common_option_remainingprogramtime
    type: custom:popup-card
    card:
      type: light
      icon: mdi:lightbulb-variant-outline
      entity: light.dimmer_slaapkamer
    icon: mdi:washing-machine
    name: Wasmachine
state_color: true
```
fire-dom-event actualy does nothing where "type: custom:popup-card" just handles the default popup.
