### ISSUE TITLE
Bring back service 'lovelace_reload'

### ISSUE THREAD

**Issue by mleiber** [thomasloven/hass-browser_mod#377]
seems 2.x has lost the service `lovelace_reload`. can this be brought back ? Very handy when testing UI changes.

**Comment by robsonke** [comment]
I hit the same problem, just sharing my workaround:
```
service: browser_mod.javascript
data:
  code: cardTools.fireEvent("config-refresh", {}, cardTools.lovelace_view());
```

Though you'll have to install the [card-tools](https://github.com/thomasloven/lovelace-card-tools) yourself.

**Comment by thomasloven** [comment]
This is now much easier:

```yaml
service: browser_mod.javascript
data:
	code: "lovelace_reload();"
```

**Comment by pickonedev** [comment]
And... what about the toast? Before I was using 

```
service: browser_mod.toast
data:
  message: Lovelace Reloaded
  duration: 1
```

**Comment by pickonedev** [comment]
> ```yaml
> service: browser_mod.javascript
> data:
>   code: "lovelace_reload();"
> ```

For me, it is not working. I still get the toast notification for refreshing my dashboard...
I tested with "reload();", but it is refreshing the complete screen, more than that, this is happening on all the devices, not only those for which I modified the dashboard... :-(

**Comment by thomasloven** [comment]
It's not called `browser_mod.notification`

**Comment by pickonedev** [comment]
> It's not called `browser_mod.notification`

Little help, please? I don't understand :-(

**Comment by robsonke** [comment]
not = now ;)

**Comment by pickonedev** [comment]
Oh, ok, yes, true.
But even with this, I get no notification

```
service: browser_mod.notification
data:
  message: test
  duration: 10000
target:
  device_id: 121147ddbfrertfdgc5d0e20a45fca9c
```
