### ISSUE TITLE
cookbook: Displaying a popup via a script  not working after update to BM2.x

### ISSUE THREAD

**Issue by victorputroagung** [thomasloven/hass-browser_mod#379]
My Home Assistant version: 2022.8.7

**What I am doing:** i used the "Displaying a popup via a script" at the wiki cookbook. BM1.x is fine, now it doesn't show up after i updated to BM2.0

**What I expected to happen:** script called, popup showed up

**What happened instead:** script called, popup didn't show up

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error
installed new BM 2.0 through HACS
remove browser_mod: line from configuration.yaml
already remove lovelace resources (and the new .js resources added automaticaly)
remove browser_mod integration
restart HA
readd browser_mod integration
restart HA

# Put your code/steps here

this one is at the lovelace card

  - type: state-icon
    entity: vacuum.tachikoma
    style:
      top: 49%
      left: 48%
      width: 10%
      opacity: 1
      color: null
      '--paper-item-icon-active-color': yellow
      '--paper-item-icon-color': grey
    tap_action:
      action: fire-dom-event
      browser_mod:
        command: call-service
        service: script.vactachikoma
        service_data:
          deviceID:
            - this

this one is the script

  vactachikoma:
    sequence:
      - service: browser_mod.popup
        data_template:
          deviceID: "{{ deviceID }}"
          title: Vacuum Tachikoma
          card:
            type: vertical-stack
            cards:
              - type: picture-entity
                entity: camera.tachikoma_map
                show_state: false
                show_name: false
                camera_image: camera.tachikoma_map
                tap_action:
                  action: none
                hold_action:
                  action: none
              - type: custom:vacuum-card
                image: default
                entity: vacuum.tachikoma
                compact_view: true
                stats:
                  cleaning:
                    - attribute: currentCleanArea
                      unit: m2
                      subtitle: Cleaning area
                    - attribute: currentCleanTime
                      unit: minutes
                      subtitle: Cleaning time
                shortcuts:
                  - name: Clean living room
                    service: script.cleanlivingroom
                    icon: mdi:sofa
                  - name: Clean Foyer Entry
                    service: script.cleanfoyerentry
                    icon: mdi:seat
                show_status: true
                show_toolbar: true
                show_name: true


**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
theres no error at the browser console... just timeout from the valetudo map.

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
