### ISSUE TITLE
Disabling Light

### ISSUE THREAD

**Issue by biiiink** [thomasloven/hass-browser_mod#38]
I am trying to disable the Light entity for all of my devices, but it doesn't seem to be working.  

This is what i have in my config:
```
browser_mod:
  prefix: "browser_"
  devices:
    c18c68f5_a8169add:
      name: browser_brodie_macbook_pro
      disable:
        - light
    8551be6a_aab7701b:
      name: browser_brodie_iphone
      disable:
        - light
```
Both entities still show up in HA
