### ISSUE TITLE
dismiss_action executes immediately?

### ISSUE THREAD

**Issue by Protoncek** [thomasloven/hass-browser_mod#380]
My Home Assistant version: 2022.9.0b3

I'm testing this lovely new version of browser mod. Congrats ! It's amazing.
However, i wonder, is it normal that "dismiss_action" executes immediately when windows pops (i have timeout set) and not only after i cancel window?  Example below: say i have switch turned OFF. I execute code below, click "OFF", it asks "really?" , immediately turns on relay and starts countdown... i'd expect "dismiss_action" will turn on only if i click "X" (thus dismissing it), or am i wrong?

```yaml
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      content: TEST RELAY
      right_button: 'ON'
      left_button: 'OFF'
      right_button_action:
        service: switch.turn_on
        data:
          entity_id: switch.delavnica_rele
      left_button_action:
        service: browser_mod.popup
        data:
          title: Really?
          content: turning off...
          timeout: 3000
          dismissable: true
          dismiss_action:
            service: switch.turn_on
            data:
              entity_id: switch.delavnica_rele
          timeout_action:
            service: switch.turn_off
            data:
              entity_id: switch.delavnica_rele
```

**Error messages from the browser console:**

```
none...
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
