### ISSUE TITLE
Popup at minimum height with light entity and "light-popup-card" type

### ISSUE THREAD

**Issue by mcv93us** [thomasloven/hass-browser_mod#381]
My Home Assistant version: 2022.8.7

**What I am doing:**
I updated browser_mod from version 1.0 to 2.0.1 and now the popup for managing the RGB light appears to me as a narrow window that makes me see almost nothing (I have attached a screenshot).
![popup1](https://user-images.githubusercontent.com/9490541/188321319-e75454b8-eec6-4139-a213-3b1ac7cab6c0.png)

**What I expected to happen:**
It had to show the light entity with a custom "light-popup-card" slide and underneath the selection of three preset colors and the button for the custom color selector.

**What happened instead:**
I only partially see the selector of the light entity and by scrolling in the window I see the rest but overlaid with respect to how it should be (here the link to the reference repository with the relative images: https://github.com/DBuit/light -popup-card)

**Minimal** steps to reproduce:
I upgraded from the previous version to the latest available by following the guide and restarting HA as directed, I updated the code with the new syntax and restarted HA.

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here

# PART OF MY TEMPLATE FILE "button_card_templates.yaml"
popup_light_rgb:
  hold_action:
    action: fire-dom-event
    browser_mod:
      service: browser_mod.popup
      data:
        title: '[[[ return entity.attributes.friendly_name ]]]'
        autoclose: false
        style:
          $: |
            .mdc-dialog .mdc-dialog__container {
              width: 100%;
            }
            .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
              width:100%;
              box-shadow:none;
            }
          .: |
            :host {
              --mdc-theme-surface: rgba(0,0,0,0);
              --secondary-background-color: rgba(0,0,0,0);
              --ha-card-background: rgba(0,0,0,0);
              --mdc-dialog-scrim-color: rgba(0,0,0,0.8);
              --mdc-dialog-min-height: 100%;
              --mdc-dialog-min-width: 100%;
              --mdc-dialog-max-width: 100%;
            }
            mwc-icon-button {
              color: #FFF;
            }
        content:
          type: 'custom:light-popup-card'
          entity: '[[[ return entity.entity_id ]]]'
          icon: 'mdi:led-strip'
          actionSize: 60px
          settings:
            openButton: RGB
            closeButton: CHIUDI
          settingsCard:
            type: 'custom:light-entity-card'
            cardOptions:
              entity: '[[[ return entity.entity_id ]]]'
              brightness: true
              full_width_sliders: true
              hide_header: true
              show_slider_percent: true
              smooth_color_wheel: true
              consolidate_entities: true
          actions:
            - service: light.turn_on
              service_data:
                entity_id: '[[[ return entity.entity_id ]]]'
                color_temp: 153
              color: '#d8d9e1'
            - service: light.turn_on
              service_data:
                entity_id: '[[[ return entity.entity_id ]]]'
                color_temp: 326
              color: '#d5b08d'
            - service: light.turn_on
              service_data:
                entity_id: '[[[ return entity.entity_id ]]]'
                color_temp: 500
              color: '#ce944b'
```

```
#Part of  Frontend code:
      - type: 'custom:button-card'
        entity:  light.strip_led_tv
        icon: 'mdi:led-strip-variant'
        name: Strip Led TV
        template:
          - button_light
          - button_light_brightness
          - popup_light_rgb
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
BROWSER_MOD 2.0.1 IS INSTALLED    BrowserID: f5f8f0db-dd38d26c
card-mod.js:5 CARD-MOD 3.1.5 IS INSTALLED
floorplan.js?hacstag=1883234941032:89 Floorplan for Home Assistant (ha-floorplan)Version 1.0.32
fold-entity-row.js?hacstag=15078199420012:86 FOLD-ENTITY-ROW 20.0.12 IS INSTALLED 
simple-thermostat.js?hacstag=158654878250:292 simple-thermostat: 2.5.0
button-card.js?hacstag=1461943253501:425   BUTTON-CARD   Version 3.5.0-dev.1 
kiosk-mode.js?hacstag=303101606172:64 ≡ kiosk-mode            ⋮ 
version 1.7.2            
slider-entity-row.js?hacstag=1448997001721:1 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
(anonimo) @ slider-entity-row.js?hacstag=1448997001721:1
slider-entity-row.js?hacstag=1448997001721:59 SLIDER-ENTITY-ROW 17.2.1 IS INSTALLED 
light-entity-card.js?hacstag=168744428500:6868   LIGHT-ENTITY-CARD     Version 5.0.0       
hui-element.js?hacstag=249942054180547:1 HUI-ELEMENT 1.1.2 IS INSTALLED 
multiple-entity-row.js?hacstag=178921037441:1  MULTIPLE-ENTITY-ROW  4.4.1 
auto-entities.js?hacstag=1677445841110:172 AUTO-ENTITIES 1.11.0 IS INSTALLED
bar-card.js?hacstag=163363577320:4855   BAR-CARD   Version 3.1.7    
paper-buttons-row.js?hacstag=244872232101:1  PAPER-BUTTONS-ROW  1.0.1 
floor3d-card.js?hacstag=361776538144:2256   FLOOR3D-CARD   Version 1.4.4    
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
