### ISSUE TITLE
browser_mod.popup doesn't seem to work with custom:button-card

### ISSUE THREAD

**Issue by iprak** [thomasloven/hass-browser_mod#383]
My Home Assistant version: 2022.8.7

**What I am doing:**
Displaying a custom:button-card with tap-action to invoke browser_mod.popup

**What I expected to happen:**
Some popup to appear

**What happened instead:**
Nothing

**Minimal** steps to reproduce:
This is my setup

```
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: hubs
```

```
hubs:
  template: count_button_card
  name: Hubs
  icon: mdi:hubspot
  entity: sensor.hubs_disconnected_count
  label: >
    [[[
      var count=states["sensor.hubs_disconnected_count"].state;
      return count == 0 ? "Connected": count + " disconnected";
    ]]]
  tap_action:
    action: call-service
    service: browser_mod.popup
    service_data:
      title: The title
      content: The content
      right_button: Right button
      left_button: Left button
```

**Error messages from the browser console:**
No error message in Console but this is the content upon initial navigation.

```
BROWSER_MOD 2.0.1 IS INSTALLED    BrowserID: 9e1f084a-eb5fad6f
card-mod.js?3.1.5:5 CARD-MOD 3.1.5 IS INSTALLED
card-mod.js?3.1.5:5 You may not be getting optimal performance out of card-mod.
See https://github.com/thomasloven/lovelace-card-mod#performance-improvements
card-tools.js:1 CARD-TOOLS 2.1.2 IS INSTALLED  DeviceID: 32cf037e-9822c5a5
button-card.js?v3.5.0-dev.1:425   BUTTON-CARD   Version 3.5.0-dev.1 
auto-entities.js?1.11.0:172 AUTO-ENTITIES 1.11.0 IS INSTALLED
mini-graph-card-bundle.js?v0.11.0-dev.4:1  MINI-GRAPH-CARD  0.11.0-dev.4 
apexcharts-card.js?v=2.0.1:835  APEXCHARTS-CARD  v2.0.1 
card-tools.js:1 Uncaught (in promise) TypeError: Object(...)(...)._addCard is not a function
    at card-tools.js:1:14094
    at new Promise (<anonymous>)
    at Module.<anonymous> (card-tools.js:1:13792)
    at r (card-tools.js:1:110)
    at card-tools.js:1:902
    at card-tools.js:1:911
(anonymous) @ card-tools.js:1
(anonymous) @ card-tools.js:1
r @ card-tools.js:1
(anonymous) @ card-tools.js:1
(anonymous) @ card-tools.js:1
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [ x] Have made sure I am using the latest version of the plugin.

- [ x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by robsonke** [comment]
Works with me but with different yaml:
`tap_action:
    action: fire-dom-event
    browser_mod:
      service: browser_mod.popup
      data:
        title: Bla
        content: Bla
`

**Comment by ASNNetworks** [comment]
Because you're not using the correct code. You need to use the code like Robsonke above here posted, which is also explained in the readme: https://github.com/thomasloven/hass-browser_mod#how-do-i-update-a-popup-from-the-browser-mod-15

**Comment by iprak** [comment]
It was user error. My previous code was okay and it works; I just forgot to register the browser. Here is my complete working template.

```
hubs:
  template: count_button_card
  name: Hubs
  icon: mdi:hubspot
  entity: sensor.hubs_disconnected_count
  label: >
    [[[
      var count=states["sensor.hubs_disconnected_count"].state;
      return count == 0 ? "Connected": count + " disconnected";
    ]]]
  tap_action:
    action: call-service
    service: browser_mod.popup
    service_data:
      title: Hubs
      content:
        type: custom:auto-entities
        card:
          type: entities
        sort:
          method: name
        filter:
          include:
            - group: group.hubs
              options:
                entity: this.entity_id
                secondary_info: last-changed
```
