### ISSUE TITLE
Can't get new browser popups to work.

### ISSUE THREAD

**Issue by justinbyoung** [thomasloven/hass-browser_mod#390]
My Home Assistant version:  2022.8.7

**What I am doing:**
Updating my browser popups to use service: browser_mod.popup

**What I expected to happen:**
Clicking on a object and a popup appearing.

**What happened instead:**
Nothing.

**Minimal** steps to reproduce:
I have created a basic button with a tap action to open a popup as a test. I apologise if I have missed something basic. 

```yaml
# The least amount of code or steps possible to reproduce my error

`
show_name: true
show_icon: true
type: button
name: test
tap_action:
  action: call-service
  service: browser_mod.popup
  data:
    title: test
    content:
      name: test2
      show_name: true
      show_icon: true
      type: button
    size: normal
`


# Put your code/steps here
```

**Error messages from the browser console:**

```
Not seeing any new log items when clicking the button.
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by xZetsubou** [comment]
I don't if my answer is 100% corrent but to use call-service you need to set targets
```
service: browser_mod.popup
data:
  title: Test
  content:
    type: markdown
    content: "test-markdown"
  size: normal
target:
  device_id: a90fcf69-8bb4ffe4
```
otherwise you can use fire-dom-event

```
type: button
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      content:
        name: test2
        show_name: true
        show_icon: true
        type: button
      size: normal
```
