### ISSUE TITLE
New update 2.1.0 - Things which are not working

### ISSUE THREAD

**Issue by pickonedev** [thomasloven/hass-browser_mod#393]
Hi!

I tested some new changes from this version and the following are not working.

1. This is not doing anything. When it will work, should have "THIS" option as well, in order to refresh only the device is needed

```
service: browser_mod.javascript
data:
  code: "lovelace_reload();"
```

2. This should have the "THIS" option to device_id, in order to refresh only the device which needs. Adding "THIS" will refresh all the devices

```
service: browser_mod.refresh
data: {}
target:
  device_id: THIS
```

3. Notification feature it is not working. When I call service, nothing happening. If it will work in the future, should have the "THIS" option as well...

```
service: browser_mod.notification
data:
  message: test
  duration: 10000
target:
  device_id: 121147ddbfrertfdgc5d0e20a45fca9c
```

Thank you in advance!

**Comment by TheFes** [comment]
`device_id` is now `browser_id`

**Comment by pickonedev** [comment]
> `device_id` is now `browser_id`

When I try to call service, I configure all in the UI, after that I switch to YAML and the integration add me this "device_id" by default. I think that if "browser_id" it is the new config detail, the UI should add it, right?

I tried changing manually, but I get error with "browser_id"

`Failed to call service browser_mod.notification. extra keys not allowed @ data['sequence'][0]['target']['browser_id'].`

**Comment by thomasloven** [comment]
`device_id` is Home Assistants identifier for the Home Assistant Device, and exactly the reason it's now called browser_id in Browser Mod. They are not the same thing.

**Comment by pickonedev** [comment]
> `device_id` is Home Assistants identifier for the Home Assistant Device, and exactly the reason it's now called browser_id in Browser Mod. They are not the same thing.

In the frontend, "browser_id" it is working, but in the services, "browser_id" it is not working... only "device_id"... Even the UI of the browser_mod, it is adding me "device_id", not "browser_id", by default...

Take a look:

Here I call popup service with "device_id"
![image](https://user-images.githubusercontent.com/34201387/188500567-b299df44-185b-4409-8bb0-ebc407a8b524.png)

And here, I call it with "browser_id"

![image](https://user-images.githubusercontent.com/34201387/188500673-0c4e7e67-16ee-43cc-8d01-999898e61c26.png)

What I am doing wrong?

**Comment by pickonedev** [comment]
Only in frontend/lovelace, it is working with "browser_id"

![image](https://user-images.githubusercontent.com/34201387/188500877-5465e366-7959-4c74-973f-e32106631d9b.png)

**Comment by pickonedev** [comment]
I have tried all the combinations, with quotas, with parenthesis, with squate parenthesis, without, with, without again :-D Nothing is working, as you can see, I can't call the service with "browser_id", only if I use target and "device_id"....

![image](https://user-images.githubusercontent.com/34201387/188502080-dfdb28fe-9d65-4507-911b-b59b8a3943de.png)

**Comment by thomasloven** [comment]
Click it anyway.

That's a Home Assistant bug.

**Comment by pickonedev** [comment]
> Click it anyway.
> 
> That's a Home Assistant bug.

You are right, you can click it even if is greyed out
But still... It doesn't do nothing. I just press, but no reaction. I tried to refresh, then with a notification, with popup, still not working...

Please, can you write me a yaml services code, exactly how it should be written? Properly? Maybe I am doing something worng...

Thank you!

**Comment by thomasloven** [comment]
A very simple one:

```yaml
service: browser_mod.popup
data:
  title: Popup
  content: Some text
```

This should open a popup on all registered and currently connected browsers.

**Comment by pickonedev** [comment]
I think I found out how to make some things work (like popup, more info, even refresh). but some are still not working...
The yaml code which I must use, in order to get a popup with the new "browser_id", by calling a service, is this

```
service: browser_mod.more_info
data:
  entity: switch.sonoff_computer_light_1
  browser_id: Desktop Browser Mod
```

Using the name what I put on the specific device, as the browser_id, not the code which Home Assistant it is adding, It is working...

But now, the notification is still not working... I tried in every way...

```
service: browser_mod.notification
data:
  message: Test
  browser_id: Desktop Browser Mod
```

Any advice how to make "Notification" work?
Thank you!

**Comment by pickonedev** [comment]
```
service: browser_mod.javascript
data:
  code: lovelace_reload();

```

It is not doing anything, but glad that browser_mod.refresh it is working. Still, you should add the possibility to add "THIS" to browser_id, for this `browser_mod.refresh `feature

**Comment by pickonedev** [comment]
I have done the testing... All the features are working, less the **notification** feature.
Can you please show me a code which is working for you, as calling the browser_mod.notification service?

And as I said before, I think that "THIS" should be added for all the services as well, not only when using frontend/lovelace... It is **very** useful.

**Comment by thomasloven** [comment]
> Using the name what I put on the specific device, as the browser_id, not the code which Home Assistant it is adding, It is working...

So you're saying using the Browser Id instead of the device ID as the `browser_id` parameter works? Who'd have guessed?


>Any advice how to make "Notification" work?

This is copied exactly verbatim from the documentation:
```yaml
service: browser_mod.notification
data:
  message: <string>
```
![image](https://user-images.githubusercontent.com/1299821/188521830-cf8b2eb8-c0bb-4444-b295-3923bd222230.png)


And finally, also copied exactly verbatim from the documentation:

"Finally, in *browser calls*, a parameter browser_id with the value THIS will be replaced with the current Browsers browser ID."

I.E for ANY service call made FROM THE BROWSER `browser_ID: THIS` will work as advertised. Even services that are not `browser_mod.whatever`. What more do you want?

**Comment by matt8707** [comment]
It's worth mentioning that I had to register the browser for `browser_mod.notification` to work, this wasn't the case with `toast`

**Comment by thomasloven** [comment]
...because registering browsers wasn't a THING with browser mod 1.6

In how many more ways do I need to explain that EVERYTHING CHANGES with Browser Mod 2.
NOTHING of your old stuff will work.
READ THE README

**Comment by matt8707** [comment]
I did read it, it was meant for https://github.com/thomasloven/hass-browser_mod/issues/393#issuecomment-1237509456

**Comment by thomasloven** [comment]
Oh. Sorry

**Comment by pickonedev** [comment]
I don't think that this topic should be closed... The only thing solved from this, is that I managed to run a popup with "browser_id" feature, avoiding "device_id"

But still, notifications are not working in calling services with automation/developer tools;

![image](https://user-images.githubusercontent.com/34201387/188623101-345d2a8d-6d9f-4212-84dc-78c78a05141c.png)

And "THIS" feature it is not working as well, calling as service from developer tools or automation. It is only working into lovelace/frontend

![image](https://user-images.githubusercontent.com/34201387/188623329-ad0f6863-86c9-4ac8-a617-b1ec588e2312.png)
No popup with THIS in browser_id

I added qutoas as well, still nothing
![image](https://user-images.githubusercontent.com/34201387/188623454-f3dade08-7a17-4232-8044-2ead4bfa6514.png)

It is only working if you add the specific browser_id, but "THIS" it is not doing anything...
![image](https://user-images.githubusercontent.com/34201387/188623584-53668a91-04bb-4c72-8c61-7d0f1444e349.png)

**Comment by pickonedev** [comment]
> > Using the name what I put on the specific device, as the browser_id, not the code which Home Assistant it is adding, It is working...
> 
> So you're saying using the Browser Id instead of the device ID as the `browser_id` parameter works? Who'd have guessed?
> 
> > Any advice how to make "Notification" work?
> 
> This is copied exactly verbatim from the documentation:
> 
> ```yaml
> service: browser_mod.notification
> data:
>   message: <string>
> ```
> 
> ![image](https://user-images.githubusercontent.com/1299821/188521830-cf8b2eb8-c0bb-4444-b295-3923bd222230.png)
> 
> > And as I said before, I think that "THIS" should be added for all the services as well,
> 
> And finally, also copied exactly verbatim from the documentation:
> 
> "Finally, in _browser calls_, a parameter browser_id with the value THIS will be replaced with the current Browsers browser ID."
> 
> I.E for ANY service call made FROM THE BROWSER `browser_id: THIS` will work as advertised. Even services that are not `browser_mod.whatever`. What more do you want?

None of what you wrote here it is working for me :-| You can see the results in my above comment

**Comment by pickonedev** [comment]
> It's worth mentioning that I had to register the browser for `browser_mod.notification` to work, this wasn't the case with `toast`

I have registered all the devices to Browser_Mod.

**Comment by thomasloven** [comment]
That red circle means the backend didn't connect correctly.
Are you SURE there was nothing in your logs?

**Comment by TheFes** [comment]
@pickonedev the backend doesn't know the `browser_id`, this is only known in the frontend. You can't use `THIS` directly in a service_call like you are doing.
That variable is meant to be sent to the backend, so you can use it in a script for example

```yaml
# configuration of tap_action in lovelace
tap_action:
  action: fire-dom-event
  browser_mod:
    service: script.show_popup
    data:
      browser_id: THIS
```

```yaml
# the script
show_popup:
  sequence:
    - alias: "popup"
      service: browser_mod.popup
      data:
        browser_id: "{{ browser_id }}"
        content:
          type: markdown
          content: "This is a popup"
```

**Comment by pickonedev** [comment]
> That red circle means the backend didn't connect correctly. Are you SURE there was nothing in your logs?

Nothing in the logs, but after few minutes after HA restart, the red dot it is no more, and still those things are not working

![image](https://user-images.githubusercontent.com/34201387/188697843-2c4729d7-06e7-4acf-b8a9-5bb66b6315d7.png)

**Comment by pickonedev** [comment]
> @pickonedev the backend doesn't know the `browser_id`, this is only known in the frontend. You can't use `THIS` directly in a service_call like you are doing. That variable is meant to be sent to the backend, so you can use it in a script for example
> 
> ```yaml
> # configuration of tap_action in lovelace
> tap_action:
>   action: fire-dom-event
>   browser_mod:
>     service: script.show_popup
>     data:
>       browser_id: THIS
> ```
> 
> ```yaml
> # the script
> show_popup:
>   sequence:
>     - alias: "popup"
>       service: browser_mod.popup
>       data:
>         browser_id: "{{ browser_id }}"
>         content:
>           type: markdown
>           content: "This is a popup"
> ```

Before v2.0 version, I was using an automation in order to refresh lovelace if I was getting the toast notification "Your dashboard was updated. Refresh to see changes? REFRESH" on specific device. Lets say that I have 4 devices and I modify only the dashboard to device 1, In this case, only device 1 was having part of refreshing the lovelace, the other 3 devices no refresh...

Now, with v2.x, I can't use "THIS" in automation, as you said and what I said till now as well, regarding the fact that "THIS" it is working only in lovelace, not in the backend... It will refresh all my 4 devices, even if I modify dashboard for device 1...

Look, this is the code which I was using as automation before Browser Mod v2.x.
This automation was canceling that toast notification about refreshing the dasboard and automatically was refreshing it. Now, with 2.0, I don't know how to achieve this...

```
- id: '1638559422149'
  alias: Tablets - AutoRefresh Lovelace
  description: ''
  trigger:
  - platform: event
    event_type: lovelace_updated
  condition: []
  action:
  - service: browser_mod.lovelace_reload
  - service: browser_mod.toast
    data:
      message: Lovelace Reloaded
      duration: 1
  mode: parallel
  max: 6
```

**Comment by thomasloven** [comment]
I think you forgot to show the part of your old automation where you used the `this` functionality...

Also, that's not canceling that toast notification, it's reloading lovelace and then overwriting the toast with another one.
Both things you know how to do.

**Comment by pickonedev** [comment]
I didn't used "this" into an old automation, I am trying to use it now, but it is working only in lovelace.

As I said, in the past, I was using that automation, for refreshing the specific lovelace and cancel the notificaiton

This automation

```
- id: '1638559422149'
  alias: Tablets - AutoRefresh Lovelace
  description: ''
  trigger:
  - platform: event
    event_type: lovelace_updated
  condition: []
  action:
  - service: browser_mod.lovelace_reload
  - service: browser_mod.toast
    data:
      message: Lovelace Reloaded
      duration: 1
  mode: parallel
  max: 6
```
