### ISSUE TITLE
Some problems with popups and actions

### ISSUE THREAD

**Issue by emufan** [thomasloven/hass-browser_mod#395]
My Home Assistant version: 2022.8.7

**What I am doing:**

Having a setup like code below.

Because of the problem with https://github.com/thomasloven/hass-browser_mod/issues/392, I played around with further actions and popups and came to this:

- ignore_popup_card is not taken into account. Behavior is same with true or false in `browser_mod.more_info`

- confirmation is not working in popups. Even with the defined separate tap_action or without. 

- more_info is opening *behind* the popup.

**What I expected to happen:**

- confirmation should work in popups as well

- more_info is opening in front of popup (with ignore_popup_card=true) and leave popup open or close popup with ignore_popup_card=false.

```
type: button
icon_height: 39px
card_mod:
  style: |
    ha-card {padding: 12px 0px !important}
show_name: false
show_icon: true
show_state: false
entity: binary_sensor.wecker_irgendwo_an
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Wecker
      content:
        type: entities
        show_header_toggle: false
        state_color: true
        entities:
          - entity: input_boolean.wecker_schlafzimmer
            name: Sonnenaufgang Schlafzimmer
            tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.more_info
                data:
                  entity: input_boolean.wecker_schlafzimmer
                  large: true
                  ignore_popup_card: false
            double_tap_action:
              confirmation:
                text: |-
                  Soll der Schlafzimmerwecker für heute wirklich abgebrochen
                  werden?
              action: call-service
              service: automation.trigger
              service_data:
                entity_id: >-
                  automation.automatisch_wecker_und_lampe_im_schlafzimmer_aus_wenn_kinderzimmer_rollladen_geoffnet_wird
```

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
