### ISSUE TITLE
Popup style grid card - cards box shadow

### ISSUE THREAD

**Issue by pico1881** [thomasloven/hass-browser_mod#396]
Grid Card (or combination of vertical and horizontal stack) doesn't show box shadow around cards

This is my configuration example:

```yaml
type: button
entity: switch.myswitch
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Popup Title
      content:
        type: grid
        cards:
          - type: entity
            entity: sensor.mysensor1
          - type: entity
            entity: sensor.mysensor2
```
