### ISSUE TITLE
Custom layout card not working inside a popup card. Same for 'custom:state-switch' and 'custom:button-card'

### ISSUE THREAD

**Issue by mansellrace** [thomasloven/hass-browser_mod#399]
After updating from 1.5 to 2.1.0, after rewrite all of 145 popup card syntax of my lovelace,

With this code:

```
action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: Francesco
    content:
      type: 'custom:layout-card'
      layout_type: grid
      ...
```
 
I get the error "Custom element doesn't exist: layout-card."

![image](https://user-images.githubusercontent.com/23330590/188479751-27561e97-c0ac-4370-a6e5-4b9064edae5b.png)

Same error with 'custom:state-switch' and 'custom:button-card'
