### ISSUE TITLE
Option to hide 'Browser Mod' text and icon in the bottom right

### ISSUE THREAD

**Issue by shogun168** [thomasloven/hass-browser_mod#400]
Since updating to v2, I've noticed that every time I use home assistant on my phone, I get the browser mod text and a tap icon in the bottom right hand corner. I know it goes away with a tap, but it's really annoying having it show up every time I open the app. Can we get the option to disable or hide this?

**Comment by matt8707** [comment]
In the meantime the icon is easy to hide

```yaml
lovelace:
  mode: yaml
  resources:
    - url: /local/browser_mod_icon.js
      type: module
```

```js
// browser_mod_icon.js
// hide browser_mod "require interaction" icon

const style = document.createElement('style');

style.textContent = `
  .browser-mod-require-interaction {
    display: none;
  }
`;

document.head.appendChild(style);
```
