### ISSUE TITLE
browser_id: THIS not working

### ISSUE THREAD

**Issue by glienart** [thomasloven/hass-browser_mod#409]
My Home Assistant version: 2022.8.7

**What I am doing:**

I try to execute the following code :
![image](https://user-images.githubusercontent.com/8383279/188829781-34af0ef2-d128-421d-b3e0-500dfab78790.png)

**What I expected to happen:**
Pop-up on the browser where I am calling the service. The code works perfectly without the ```browser_id: THIS```

**What happened instead:**
Nothing

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error
# Put your code/steps here

service: browser_mod.popup
data:
  title: hello
  content: test
  browser_id: THIS

```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
none
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
https://github.com/thomasloven/hass-browser_mod/blob/master/documentation/services.md#a-note-about-targets

>The first way is as a server call. This is when the service is called from a script or automation, from the dev-services panel or from a dashboard call-service action.
>
>The second way is as a browser call. This is when the service is called from a dashboard fire-dom-event action, as a part of a browser_mod.sequence call or as a browser_mod.popup _action.
>[...]
>Finally, in browser calls, a parameter browser_id with the value THIS will be replaced with the current Browsers browser ID.

**Comment by glienart** [comment]
I was confused with the following: 

> < service call >
> [...]
> If data contains browser_id: THIS then THIS will be replaced with the current browser ID.

The sentence might not be necessary there

**Comment by thomasloven** [comment]
Oh. That shouldn't be there.
Thanks for the heads up!

**Comment by pickonedev** [comment]
> 

Hi! Have you managed to call the popup service from dev tools, using "THIS" ? If yes, please, illuminate me, i'm in full darkness.

**Comment by glienart** [comment]
Hi, 

here's how I am doing it, button to call the script: 

```
type: button
tap_action:
  action: fire-dom-event
  browser_mod:
    service: script.your_script
    data:
      browser_id: THIS
```
script:

```
data:
  browser_id: "{{browser_id}}"
  content:
    type: ...
  title: Open door
service: browser_mod.popup
```

Hope this helps

If it's for an automation I don't see how it will know where it was initiated.
