### ISSUE TITLE
close popup service error

### ISSUE THREAD

**Issue by madmicio** [thomasloven/hass-browser_mod#412]
My Home Assistant version: 2022.8.7

**What I am doing:**
i am trying to call service

**What I expected to happen:**
close popup

**What happened instead:**
nothing

**Minimal** steps to reproduce:

```
tap_action:
action: fire-dom-event
service: 
browser_mod:
  service: browser_mod.close_popup
  data:
    browser_id: THIS
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Fix your indentation and it should work.

**Comment by madmicio** [comment]
```
type: 'custom:button-card'
entity: light.luce_del_pc
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      style: |-
        --popup-min-width: 1100px;
        --popup-margin: 100px;
      right_button: exit
      right_button_action:
        service: browser_mod.close_popup
        data:
          browser_id: THIS
      content:
        type: 'custom:button-card'
        entity: light.luce_del_pc
        tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.close_popup
            data:
              browser_id: THIS
```

I'm sorry but I still can't get the service to work.
in the code written above, the close_popup service works correctly in right_button_action: but it does not work in the tap_action of the custtom button card. i think indentation is correct
