### ISSUE TITLE
The dropdown menu is hidden in the popup

### ISSUE THREAD

**Issue by WRoss7** [thomasloven/hass-browser_mod#422]
My Home Assistant version: 2022.9.1

**What I am doing:**
I have created a simple PopUp with a dropdown menu, but as you can see in the image the choice menu is not usable.
This bug has been present for many months, even in the old version of Browser Mod.
I reported it months ago as a Home Assistant bug, but they closed it by writing that it concerns an external component

**What I expected to happen:**
The dropdown list should be on top

**What happened instead:**
The dropdown list is only partially visible

```yaml
# The least amount of code or steps possible to reproduce my error
  - type: state-label
    entity: sensor.roborock_s5_traduzione_modalita_aspirante
    title: Modifica la potenza aspirante
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.popup
        data:
          title: Modalità aspirante
          content:
            type: entities
            entities:
              - entity: input_select.roborock_s5_modalita_aspirante

```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```
![Image](https://user-images.githubusercontent.com/74879713/189390408-b188c113-5cdc-4ef7-a5de-f4a3b91bcbbd.png)

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Comprendo che lasciare una o più caselle deselezionate o non seguire il modello di cui sopra può aumentare il tempo necessario per gestire la mia segnalazione di bug, o causarne la chiusura senza ulteriori azioni.
