### ISSUE TITLE
lovelace_reload

### ISSUE THREAD

**Issue by kaelsaes** [thomasloven/hass-browser_mod#424]
Die Automatisierung "Lovelace Refresh" (automation.lovelace_refresh) hat eine Aktion, die einen unbekannten Dienst aufruft: browser_mod.lovelace_reload.

Dieser Fehler verhindert, dass die Automatisierung ordnungsgemäß ausgeführt wird. Vielleicht ist dieser Dienst nicht mehr verfügbar oder vielleicht hat ein Tippfehler ihn verursacht.

**Comment by marrobHD** [comment]
Please use the issue template and the project language (English) next time.

As you should have noticed, browser_mod has been completely rewritten.
That's why some browser_mod service names changed. Basically everything changed a bit.  
Please read the [documentation](https://github.com/thomasloven/hass-browser_mod/blob/master/documentation/services.md#browser_modrefresh).
Spoiler: the service you're trying to execute is now called `browser_mod.refresh`.

**Comment by clau-bucur** [comment]
I have tried browser_mod.refresh but it's not the same, at least from what I saw, because it simply does a page refresh (F5) whereas lovelace_reload reloads the views.

**Comment by Vedeneb** [comment]
I'm also not happy that the service has been removed, however there is a workaround. You can use the `browser_mod.javascript` service to reload the lovelace configuration only.
Here's what I use:
```yaml
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.javascript
        data:
          code: lovelace_reload();
```
