### ISSUE TITLE
popup run from script via fire-dom-event opens on all browsers

### ISSUE THREAD

**Issue by dziadeck47** [thomasloven/hass-browser_mod#434]
My Home Assistant version: 2022.9.2

**What I am doing:**

I wrote a popup script to the side and want to launch it from dashboard via:

```yaml
action: fire-dom-event
      browser_mod:
        service: script.test_popup
        data:
          browser_id: THIS
```

script looks as follows:
```yaml
sequence:
  - service: browser_mod.popup
    data:
      title: The title
      right_button: Right button
      content: The content
```

**What I expected to happen:**

As per documentation I expect a popup to show up only on browser I click from

**What happened instead:**

Opens up on 2 browsers.  Same when I input an existing browserID in the card. 
Inputting the explicit browserid directly in the script works though so it looks like it is not passed thru from the dashboard

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by FrnchFrgg** [comment]
AFAICT, the `fire-dom-event` action you wrote passes a `browser_id` variable to your script, which does not use it at all. Shouldn't it read like so instead ? (note the added last line)
```
sequence:
  - service: browser_mod.popup
    data:
      title: The title
      right_button: Right button
      content: The content
      browser_id: "{{ browser_id }}"
```
