### ISSUE TITLE
fire-dom-event not work for custom cards

### ISSUE THREAD

**Issue by rfromano** [thomasloven/hass-browser_mod#436]
When using this action:

```
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      browser_id: THIS
```

Does not work for custom cards, does not open popup.
With (type:button) it works.

**Comment by dziadeck47** [comment]
tap_action:
      action: fire-dom-event
      browser_mod:
        service: script.roborock_popup
        data:
          browser_id: THIS
 works for me even when launching a separate script (as pasted above for xiaomi-vacuum-card and with mini-media-player
 
does the same config work with fixed data, e.g.:
service: browser_mod.popup
data:
  title: The title
? If so please check if the code for the custom card entered does not have spacing issues.

**Comment by rfromano** [comment]
> ```
> tap_action:
>   action: fire-dom-event
>   browser_mod:
>     service: script.roborock_popup
>     data:
>       browser_id: THIS
> ```
> 
> works for me even when launching a separate script (as pasted above for xiaomi-vacuum-card and with mini-media-player
> 
> does the same config work with fixed data, e.g.: service: browser_mod.popup data: title: The title ? If so please check if the code for the custom card entered does not have spacing issues.

This code in a custom card it doesn't even run the script:
```
tap_action:
   action: fire-dom-event
   browser_mod:
     service: script.popup_boilertemperatura
     date:
       browser_id: THIS
```
If I put this same code on a home assistant card, it runs the script and it works perfectly.


```
tap_action:
   action: call service
   service: browser_mod.popup
   service_date:
     browser_id: bro_tabletsala
     content:
       type: custom:thermostat-card
       entity: climate.boiler
       title: Boiler
       step: 1
```
If I use this code above in a personalized card it works, but it doesn't accept using:
```
browser_id: THIS
```
THIS is very useful, to use in many devices.
Thanks.
