### ISSUE TITLE
Popup style from themes doesn't work when reopening a popup on iOS

### ISSUE THREAD

**Issue by matt8707** [thomasloven/hass-browser_mod#444]
My Home Assistant version: 2022.9.5

**What I am doing:**
Styling browser_mod popup header from themes

**What I expected to happen:**
The style to apply

**What happened instead:**
on iOS the style works when I open the popup the first time. If I close and reopen the popup the style is gone. 

**Minimal** steps to reproduce:

```yaml
#popup
type: button
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Popup
      content:
        type: entities
        entities:
          - entity: sun.sun
```

```yaml
#theme
themes:
  test:
    card-mod-theme: test
    card-mod-more-info-yaml: |
      ha-header-bar$: |
        header {
          background: red !important;
        }
```

**However adding card_mod (anything) in the service call everything works as expected.**

```yaml
#temporary solution
service: browser_mod.popup
data:
  title: Popup
  card_mod:
    style:
      .: any
```

**Error messages from the browser console:**

*None*

```
BROWSER_MOD 2.1.3 IS INSTALLED
CARD-MOD 3.1.5 IS INSTALLED
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
