### ISSUE TITLE
Browser Mod: Service parameter not specified in service call

### ISSUE THREAD

**Issue by johntdyer** [thomasloven/hass-browser_mod#449]
My Home Assistant version: 2222.09.05

**What I am doing:**

```
trying to get a pop up working
```

**What I expected to happen:**

a pop up
**What happened instead:**
```
Browser Mod: Service parameter not specified in service call. 2 browser_mod.js:66:17877
    _service_action browser_mod.js:66
    <anonymous> browser_mod.js:66
    At mushroom.js:73
    Oe mushroom.js:78
    _handleAction mushroom.js:2175
    handleEvent mushroom.js:31
    i typography.js:181
    end ha-formfield.ts:8
    (Async: EventListener.handleEvent)
    bind ha-formfield.ts:8
    Ie mushroom.js:78
    update mushroom.js:78
    _$AS mushroom.js:78
    X mushroom.js:31
    _$AI mushroom.js:31
    m mushroom.js:31
    T mushroom.js:31
    _$AI mushroom.js:31
    Dt mushroom.js:37
    update mushroom.js:37
    performUpdate mushroom.js:25
    scheduleUpdate mushroom.js:25
    _$E_ mushroom.js:25
    requestUpdate mushroom.js:25
    o mushroom.js:25
    b mushroom.js:25
    ot mushroom.js:37
    Wa mushroom.js:1270
    qa mushroom.js:1281
    sl mushroom.js:2175
    E typography.js:181
    t typography.js:181
    a hui-error-badge.ts:22
    h hui-error-badge.ts:22
    h hui-error-badge.ts:22
    d hui-error-badge.ts:22
    v hui-error-badge.ts:22
    value hui-stack-card.ts:16
    _cards hui-light-card.ts:35
    value hui-light-card.ts:35
    h hui-error-badge.ts:22
    (Async: promise callback)
    h hui-error-badge.ts:22
    h hui-error-badge.ts:22
    d hui-error-badge.ts:22
    v hui-error-badge.ts:22
    value hui-masonry-view.ts:44
    _cards hui-masonry-view.ts:44
    value hui-masonry-view.ts:44
    value hui-masonry-view.ts:44
    value hui-masonry-view.ts:44
    performUpdate app.3e7f30b5.js:1249
```

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error
title: Main
path: home
icon: "mdi:home-assistant"
cards:
  # Kitchen
  - type: vertical-stack
    cards:
      - type: custom:mushroom-entity-card
        name: Daniels 💡
        entity: light.zwave_basement_ceiling
        tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            deviceID:
              - this
# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [ ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [ ] Have made sure I am using the latest version of the plugin.

- [ ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by abigdeel** [comment]
Syntax is wrong bruh Could've googled it...
```
 tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              browser_id: THIS
              dismissable: true
              title: Bruh
              content:
                type: custom:bruh
                entity: light.bruh
                icon: mdi:bruh
```
