### ISSUE TITLE
Trying to popup a frigate card using a script

### ISSUE THREAD

**Issue by tinimark** [thomasloven/hass-browser_mod#454]
Hi,

I know this is probably user error but I'm trying to make a script to pop-up a frigate card.
This works perfectly in dev tools call service.

service: browser_mod.popup
data:
  title: Test cam
  size: fullscreen
  content:
    type: custom:frigate-card
    cameras:
      - camera_entity: camera.topdrivecamera
        live_provider: ha
target:
  device_id: xx

But when I try to make it in to a script so I can call on it from Node Red it doesn't seem to work.
I'm sure it's just some syntax, any pointers greatly received.

test_popup:
  sequence:
    - service: browser_mod.popup
      data_template:
        deviceID: "xx"
        title: Testing script
        card:
          type: custom:frigate-card
          camera_entity:
            - camera.topdrivecamera

**Comment by gonzalezcalleja** [comment]
hi, this is my script for frigate-card in a popup:


```
  - service: browser_mod.popup
    data:
      browser_id: 
        - ipad
      title: Movimiento en la calle
      content:
        type: vertical-stack
        cards:
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.calle
                title: Calle
                dependencies:
                  all_cameras: false
            timeline:
              show_recordings: true
            view:
              default: live
          - type: horizontal-stack
            cards:
              - type: picture-entity
                show_state: false
                show_name: false
                camera_view: auto
                entity: camera.calle_person
              - type: picture-entity
                show_state: false
                show_name: false
                camera_view: auto
                entity: camera.calle_car
              - type: picture-entity
                show_state: false
                show_name: false
                camera_view: auto
                entity: camera.calle_dog
              - type: picture-entity
                show_state: false
                show_name: false
                camera_view: auto
                entity: camera.calle_bicycle
              - type: picture-entity
                show_state: false
                show_name: false
                camera_view: auto
                entity: camera.calle_motorcycle
      timeout: 60000
      size: wide
```
