### ISSUE TITLE
Sequence not working correctly on browser mod 2

### ISSUE THREAD

**Issue by Daniel-dev22** [thomasloven/hass-browser_mod#457]
Running the latest version of home assistant.

On browser mod 1 this worked, it navigated and closed the pop-up seamlessly.

```yaml
- type: custom:mushroom-template-card
  primary: Media
  icon: mdi:cog
  picture: local/icons/custom_icons/sonos.png
  tap_action:
    action: fire-dom-event
    browser_mod:
    command: commands
    commands:
       - command: navigate
          navigation_path: /lovelace/sonos
        - command: close_popup
```

On browser mod 2 this only navigates but doesn't close the pop-up 
```yaml
- type: custom:mushroom-template-card
   primary: Media
   icon: mdi:cog
   picture: local/icons/custom_icons/sonos.png
   tap_action:
     action: fire-dom-event
      browser_mod:
      service: browser_mod.sequence
      data:
        sequence:
          - service: browser_mod.navigate
            data:
               path: /lovelace/sonos
          -  service: browser_mod.close_popup
```
I also tried this per [documentation](https://github.com/thomasloven/hass-browser_mod/blob/master/documentation/services.md#browser_modsequence) 

```yaml
- type: custom:mushroom-template-card
  primary: Switches
  icon: mdi:cog
  picture: local/icons/custom_icons/scene-switch1.png
  tap_action:
  action: call-service
  service: browser_mod.sequence
  data:
    sequence:
       - service: browser_mod.navigate
         data:
            path: /lovelace/switches
       - service: browser_mod.close_popup
```

I was recommended to reverse the order and use a delay which worked for the user on desktop but not on mobile.

```yaml
type: custom:mushroom-template-card
primary: Media
icon: mdi:cog
picture: local/icons/custom_icons/sonos.png
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.sequence
    data:
      sequence:
        - service: browser_mod.close_popup
          data:
            browser_id: THIS
        - service: browser_mod.delay
          data:
            time: 1
        - service: browser_mod.navigate
          data:
            path: /lovelace/sonos
```

On mobile the above didn't work both with and without `browser_id: THIS`

[Link to forum post of it working on desktop](https://community.home-assistant.io/t/browser-mod-turn-your-browser-into-a-controllable-device-and-a-media-player/123806/1822?u=danny2100)
