### ISSUE TITLE
Browser mod 2.0: Please tell my why this isn't working

### ISSUE THREAD

**Issue by dnestico** [thomasloven/hass-browser_mod#460]
My Home Assistant version: 2022.9.2

I updated my code to the new browser mode 2.0 pop up code and it still isn't working
<img width="491" alt="Screen Shot 2022-10-01 at 8 58 07 PM" src="https://user-images.githubusercontent.com/3034555/193433534-1f4c6617-fa51-45d6-8dea-479d6c164fb4.png">

**What I expected to happen:**
My popups should be working again.

**What happened instead:**
They don't do anything now.

**Minimal** steps to reproduce:
Update code, nothing happens.

```yaml
type: custom:stack-in-card
cards:
  - type: custom:layout-card
    layout_type: masonry
    layout: {}
    cards:
      - type: custom:mushroom-chips-card
        chips:
          - type: menu
          - type: template
            entity: lock.front_door
            icon: >-
              {{ 'mdi:lock' if is_state('lock.front_door', 'locked') else
              'mdi:lock-open' }}
            icon_color: '{{ ''green'' if is_state(''lock.front_door'', ''locked'') else ''red'' }}'
            content: null
            tap_action:
              action: more-info
          - type: template
            entity: binary_sensor.contact_sensor
            icon: >-
              {{ 'mdi:garage-open' if is_state('binary_sensor.contact_sensor',
              'open') else 'mdi:garage' }}
            icon_color: >-
              {{ 'green' if is_state('binary_sensor.contact_sensor', 'off') else
              'red' }}
            content: null
            tap_action:
              action: call-service
              service: switch.toggle
              data: {}
              target:
                entity_id: switch.garage_bot
          - type: conditional
            conditions:
              - entity: group.all_light_entities
                state: 'on'
            chip:
              type: template
              icon: mdi:lightbulb
              tap_action:
                action: more-info
          - type: conditional
            conditions:
              - entity: sensor.driveway_car
                state: '1'
            chip:
              type: entity
              entity: sensor.driveway_car
          - type: conditional
            conditions:
              - entity: sensor.driveway_person
                state: '1'
            chip:
              type: entity
              entity: sensor.driveway_person
          - type: conditional
            conditions:
              - entity: sensor.porch_person
                state: '1'
            chip:
              type: entity
              entity: sensor.porch_person
          - type: conditional
            conditions:
              - entity: sensor.porch_dog
                state: '1'
            chip:
              type: entity
              entity: sensor.porch_dog
      - type: grid
        square: false
        columns: 2
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mushroom-chips-card
                chips:
                  - type: conditional
                    conditions:
                      - entity: person.david_nestico
                        state: home
                    chip:
                      type: entity
                      entity: person.david_nestico
                      content_info: nam
                      use_entity_picture: true
                      card_mod:
                        style: |
                          ha-card {
                              --chip-background: rgba(var(--rgb-state-person-home), 0.4);
                              margin-top: 5px;
                              margin-bottom: 10px;
                              animation: ping 2s ease-out infinite ;
                          }
                          @keyframes ping {
                            0% {
                              box-shadow: 0 0 5px 1px rgba(var(--rgb-green), 1);
                            }
                            100% {
                              box-shadow: 0 0 5px 10px rgba(var(--rgb-green), 0);
                            }
                          }
                  - type: conditional
                    conditions:
                      - entity: person.dad
                        state: home
                    chip:
                      type: entity
                      entity: person.dad
                      content_info: none
                      use_entity_picture: true
                      card_mod:
                        style: |
                          ha-card {
                              --chip-background: rgba(var(--rgb-state-person-home), 0.4);
                              margin-top: 5px;
                              margin-bottom: 10px;
                              animation: ping 2s ease-out infinite ;
                          }
                          @keyframes ping {
                            0% {
                              box-shadow: 0 0 5px 1px rgba(var(--rgb-green), 1);
                            }
                            100% {
                              box-shadow: 0 0 5px 10px rgba(var(--rgb-green), 0);
                            }
                          }
                          }
                card_mod:
                  style: |
                    ha-card { 
                      margin-left: 8px;
                    }
          - type: horizontal-stack
            cards:
              - type: custom:mushroom-chips-card
                chips:
                  - type: conditional
                    conditions:
                      - entity: person.david_nestico
                        state_not: home
                    chip:
                      type: entity
                      entity: person.david_nestico
                      content_info: none
                      use_entity_picture: true
                      card_mod:
                        style: |
                          ha-card {
                            {% if is_state('person.david_nestico', 'not_home') %}
                              --chip-background: rgba(var(--rgb-state-person-not-home), 0.4);
                            {% elif is_state('person.david_nestico', 'unknown') %}
                              --chip-background: rgba(var(--rgb-state-person-unknown), 0.4);
                            {% else %}
                              --chip-background: rgba(var(--rgb-state-person-zone), 0.4);
                            {% endif %} 
                              margin-top: 5px;
                              margin-bottom: 10px;
                          } 
                  - type: conditional
                    conditions:
                      - entity: person.dad
                        state_not: home
                    chip:
                      type: entity
                      entity: person.dad
                      content_info: none
                      use_entity_picture: true
                      card_mod:
                        style: |
                          ha-card {
                            {% if is_state('person.dad', 'not_home') %}
                              --chip-background: rgba(var(--rgb-state-person-not-home), 0.4);
                            {% elif is_state('person.dad', 'unknown') %}
                              --chip-background: rgba(var(--rgb-state-person-unknown), 0.4);
                            {% else %}
                              --chip-background: rgba(var(--rgb-state-person-zone), 0.4);
                            {% endif %} 
                              margin-top: 5px;
                              margin-bottom: 10px;
                          } 
                alignment: end
                card_mod:
                  style: |
                    ha-card { 
                      margin-right: 8px;
                    }
        subtitle: ''
      - type: custom:stack-in-card
        cards:
          - type: custom:layout-card
            layout_type: custom:grid-layout
            layout:
              grid-template-columns: 66px auto 36px
              margin: '-4px -4px -12px -4px;'
            cards:
              - type: custom:mushroom-entity-card
                entity: weather.vaughan_hourly
                icon_color: blue
                card_mod:
                  style: |
                    ha-card {
                      background: none;
                      --ha-card-box-shadow: 0px;
                    }
              - type: custom:hourly-weather
                entity: weather.vaughan_hourly
                icons: false
                label_spacing: '2'
                num_segments: '12'
                name: ' '
                card_mod:
                  style:
                    weather-bar$: |
                      .main {
                        --mush-rgb-red: 244, 67, 54;
                        --mush-rgb-pink: 233, 30, 99;
                        --mush-rgb-purple: 156, 39, 176;
                        --mush-rgb-deep-purple: 103, 58, 183;
                        --mush-rgb-indigo: 63, 81, 181;
                        --mush-rgb-blue: 33, 150, 243;
                        --mush-rgb-light-blue: 3, 169, 244;
                        --mush-rgb-cyan: 0, 188, 212;
                        --mush-rgb-teal: 0, 150, 136;
                        --mush-rgb-green: 76, 175, 80;
                        --mush-rgb-light-green: 139, 195, 74;
                        --mush-rgb-lime: 205, 220, 57;
                        --mush-rgb-yellow: 255, 235, 59;
                        --mush-rgb-amber: 255, 193, 7;
                        --mush-rgb-orange: 255, 152, 0;
                        --mush-rgb-deep-orange: 255, 87, 34;
                        --mush-rgb-brown: 121, 85, 72;
                        --mush-rgb-grey: 158, 158, 158;
                        --mush-rgb-blue-grey: 96, 125, 139;
                        --mush-rgb-black: 0, 0, 0;
                        --mush-rgb-white: 255, 255, 255; 

                        --color-clear-night: rgba(var(--mush-rgb-black), 0.2) !important;
                        --color-cloudy: rgba(var(--mush-rgb-grey), 0.2) !important;
                        --color-fog: var(--color-cloudy);
                        --color-hail: rgba(var(--mush-rgb-indigo), 0.2) !important;
                        --color-lightning: var(--color-rainy);
                        --color-lightning-rainy: var(--color-rainy);
                        --color-partlycloudy: rgba(var(--mush-rgb-blue), 0.2) !important;
                        --color-pouring: var(--color-rainy);
                        --color-rainy: rgba(var(--mush-rgb-indigo), 0.2) !important;
                        --color-snowy: rgba(var(--mush-rgb-white), 0.2) !important;
                        --color-snowy-rainy: var(--color-partlycloudy);
                        --color-sunny: rgba(var(--mush-rgb-yellow), 0.2) !important;
                        --color-windy: var(--color-sunny);
                        --color-windy-variant: var(--color-sunny);
                        --color-exceptional: rgba(var(--mush-rgb-amber), 0.2) !important;
                      }
                      .bar > div {
                        height: 42px !important;
                      }            
                      .bar > div:first-child {
                        border-top-left-radius: 12px !important;
                        border-bottom-left-radius: 12px !important;
                      }             
                      .bar > div:last-child {
                        border-top-right-radius: 12px !important;
                        border-bottom-right-radius: 12px !important;
                      }            
                      .bar > div > span {
                        text-shadow: none !important;
                        color: rgb(var(--primary-text-color));
                        font-size: 14px;
                        font-weight: bold;
                      } 
                      .axes > div > .bar-block-bottom > .hour {
                        font-size: 12px;
                        font-weight: bolder;
                      }
                      .axes > div > .bar-block-bottom > .temperature {
                        font-size: 12px;
                        font-weight: bolder;
                      }
                      .axes {
                        margin-top: 10px !important;
                      }
                    .: |
                      ha-card {
                        background: none;
                        --ha-card-box-shadow: 0px;
                        margin: -8px -4px -4px -16px;
                      }
              - type: custom:mushroom-template-card
                entity: input_boolean.weather_bar_dropdown
                icon: mdi:chevron-down
                icon_color: disabled
                hold_action:
                  action: none
                card_mod:
                  style:
                    mushroom-shape-icon:
                      $: |
                        .shape ha-icon {
                          transition: transform 0.14s !important;
                          {{ 'transform: rotate(-180deg);' if is_state(config.entity, 'on') }}
                        }
                      .: |
                        ha-card {
                          align-items: flex-end;
                          box-shadow: none;
                        }
                        mushroom-shape-icon {
                          --shape-color: none !important;
                        }
        card_mod:
          style: |
            ha-card {
              {{ 'height: 66px;' if is_state('input_boolean.weather_bar_dropdown', 'off') }}
            } 
      - type: custom:button-card
        styles:
          card:
            - background-color: rgba(0,0,0,0)
            - font-size: 20px
            - font-weight: 400
            - padding: 12px
            - box-shadow: none
          name:
            - justify-self: stretch
        name: |
          [[[ return `<div style='display: flex';>
              <div>${states['sensor.time'].state} | </div>
              <span style='width:100%;'>
              <marquee>${states['sensor.vaughan_summary'].state}</marquee></span>`; ]]]
      - type: horizontal-stack
        cards:
          - type: custom:mushroom-template-card
            primary: ''
            secondary: Temp
            layout: vertical
            icon_color: blue
            icon: mdi:thermometer
            badge_icon: |-
              {% set mode = states('climate.3family_room') %}
              {% if mode == 'off' %}
              mdi:power
              {% elif mode == 'cool' %}
              mdi:snowflake
              {% elif mode == 'heat' %}
              mdi:fire 
              {% elif mode == 'heat_cool' %}
              mdi:autorenew
              {% else %}
              mdi:home-thermometer
              {% endif %}
            badge_color: >-
              {% set status = state_attr('climate.3family_room','hvac_action')
              %}

              {% if status == 'off' %}

              grey

              {% elif status == 'cooling' %}

              blue

              {% elif status == 'heating' %}

              red

              {% else %}

              grey

              {% endif %}
            tap_action:
            action: fire-dom-event
            browser_mod:
              service: browser_mod.popup
              data:
                title: Thermostat
                content:
                  type: custom:mod-card
                  card:
                    type: vertical-stack
                    cards:
                      - type: custom:mushroom-climate-card
                        entity: climate.3family_room
                        fill_container: false
                        show_temperature_control: true
                        collapsible_controls: false
                        hvac_modes:
                          - heat
                          - cool
                          - fan_only
                        layout: horizontal
                      - type: custom:thermostat-dark-card
                        entity: climate.3family_room
                        hvac:
                          states:
                            idle: idle
                            cooling: cooling
                            heating: heating
                        step: '0.5'
                        chevron_size: '100'
                        pending: '3'
                        idle_zone: '2'
                        highlight_tap: true
            card_mod:
              style: |
                ha-card { 
                  background: var(--card-background-color);
                  width: 66px;
                  border-radius: 30px;
                  margin-left: auto;
                  margin-right: auto;
                  margin-bottom: 2px;
                }
          - type: custom:mushroom-template-card
            primary: ''
            secondary: Lights
            icon: hue:bulb-classic
            icon_color: amber
            badge_color: orange
            badge_icon: |
              {% if states('sensor.current_lights_on')|int > 0 %} 
                {{ 'mdi:numeric-' + states('sensor.current_lights_on') + '-circle' }}
              {% endif %}
            layout: vertical
            tap_action:
              action: call-service
              service: browser_mod.popup
              service_data:
                title: All Lights
                card:
                  type: custom:mod-card
                  card:
                    type: vertical-stack
                    cards:
                      - type: grid
                        square: false
                        columns: 3
                        cards:
                          - type: custom:mushroom-light-card
                            entity: light.zone_1
                          - type: custom:mushroom-light-card
                            entity: light.zone_2
                          - type: custom:mushroom-light-card
                            entity: light.zone_3
                      - type: grid
                        square: false
                        columns: 2
                        cards:
                          - type: custom:mushroom-light-card
                            entity: light.hue_go
                            use_light_color: true
                            show_brightness_control: true
                            show_color_temp_control: false
                            show_color_control: true
                          - type: custom:mushroom-light-card
                            entity: light.david_s_lightstrip
                            show_brightness_control: true
                            show_color_temp_control: false
                            show_color_control: true
                            icon: ''
                      - type: grid
                        square: false
                        columns: 2
                        cards:
                          - type: custom:mushroom-light-card
                            entity: light.lamp_2
                            show_brightness_control: true
                            show_color_temp_control: false
                            show_color_control: true
                          - type: custom:mushroom-light-card
                            entity: light.lightstrip
                            name: V/E Light
                            show_brightness_control: true
                            show_color_temp_control: false
                            show_color_control: true
                      - type: grid
                        square: false
                        columns: 2
                        cards:
                          - type: custom:mushroom-light-card
                            entity: light.tv_lightstrip
                            show_brightness_control: true
                            show_color_temp_control: false
                            show_color_control: true
                            name: TV
                          - type: custom:mushroom-light-card
                            entity: light.lamp
                            show_brightness_control: true
                            show_color_temp_control: false
                            show_color_control: true
            card_mod:
              style: |
                ha-card { 
                  background: var(--card-background-color);
                  width: 66px;
                  border-radius: 30px;
                  margin-left: auto;
                  margin-right: auto;
                  margin-bottom: 2px;
                }
          - type: custom:mushroom-template-card
            primary: ''
            secondary: Media
            icon: mdi:speaker
            layout: vertical
            icon_color: red
            tap_action:
              action: call-service
              service: browser_mod.popup
              service_data:
                title: Media
                card:
                  type: custom:mod-card
                  card:
                    type: vertical-stack
                    cards:
                      - type: grid
                        square: false
                        columns: 1
                        cards:
                          - type: custom:spotify-card
                            limit: 6
                            display_style: grid
                            hide_connect_devices: true
                            playlist_type: featured
                            default_device: Kitchen display
                            filter_devices:
                              - Nestico Whole Home
                              - David tv group
                              - Nestico Home group
                          - type: vertical-stack
                            cards:
                              - type: grid
                                square: false
                                columns: 2
                                cards:
                                  - type: custom:stack-in-card
                                    mode: vertical
                                    card_mod: null
                                    style: >
                                      ha-card {

                                      background-color:
                                      rgba(var(--rgb-primary-text-color), 0.01);

                                      }
                                    cards:
                                      - type: custom:mushroom-media-player-card
                                        entity: media_player.kitchen_display
                                        name: Kitchen display
                                        icon: mdi:cast
                                        use_media_artwork: true
                                        fill_container: false
                                        use_media_info: true
                                        show_volume_level: true
                                        media_controls:
                                          - on_off
                                        collapsible_controls: true
                                        tap_action:
                                          action: toggle
                                      - type: conditional
                                        conditions:
                                          - entity: media_player.kitchen_display
                                            state_not: 'off'
                                          - entity: media_player.kitchen_display
                                            state_not: idle
                                        card:
                                          entity: media_player.kitchen_display
                                          hide:
                                            icon: true
                                            name: true
                                            runtime: true
                                            source: true
                                            power: true
                                            state_label: true
                                            volume: false
                                            info: true
                                            progress: false
                                            controls: false
                                          more_info: false
                                          type: custom:mini-media-player
                                          toggle_power: true
                                          group: true
                                          card_mod:
                                            style:
                                              mmp-progress$: |
                                                paper-progress {
                                                  {{ '--paper-progress-container-color: rgba(63, 81, 181, 0.2) !important;' if is_state(config.entity, 'playing') }}
                                                }
                                              .: |
                                                ha-card {
                                                  margin: 30px 12px 12px;
                                                  --mmp-progress-height: 10px !important;
                                                  height: var(--mmp-progress-height);
                                                  --mmp-accent-color: rgb(255, 170, 0);
                                                  --ha-card-border-radius: 2px;
                                                }
                                  - type: custom:stack-in-card
                                    mode: vertical
                                    card_mod: null
                                    style: >
                                      ha-card {

                                      background-color:
                                      rgba(var(--rgb-primary-text-color), 0.01);

                                      }
                                    cards:
                                      - type: custom:mushroom-media-player-card
                                        entity: media_player.david_s_display
                                        name: Davids display
                                        icon: mdi:cast
                                        use_media_artwork: true
                                        fill_container: false
                                        use_media_info: true
                                        show_volume_level: true
                                        media_controls:
                                          - on_off
                                        collapsible_controls: true
                                        tap_action:
                                          action: toggle
                                      - type: conditional
                                        conditions:
                                          - entity: media_player.david_s_display
                                            state_not: 'off'
                                          - entity: media_player.david_s_display
                                            state_not: idle
                                        card:
                                          entity: media_player.david_s_display
                                          hide:
                                            icon: true
                                            name: true
                                            runtime: true
                                            source: true
                                            power: true
                                            state_label: true
                                            volume: false
                                            info: true
                                            progress: false
                                            controls: false
                                          more_info: false
                                          type: custom:mini-media-player
                                          toggle_power: true
                                          group: true
                                          card_mod:
                                            style:
                                              mmp-progress$: |
                                                paper-progress {
                                                  {{ '--paper-progress-container-color: rgba(63, 81, 181, 0.2) !important;' if is_state(config.entity, 'playing') }}
                                                }
                                              .: |
                                                ha-card {
                                                  margin: 30px 12px 12px;
                                                  --mmp-progress-height: 10px !important;
                                                  height: var(--mmp-progress-height);
                                                  --mmp-accent-color: rgb(255, 170, 0);
                                                  --ha-card-border-radius: 2px;
                                                }
                              - type: grid
                                square: false
                                columns: 2
                                cards:
                                  - type: custom:stack-in-card
                                    mode: vertical
                                    card_mod: null
                                    style: >
                                      ha-card {

                                      background-color:
                                      rgba(var(--rgb-primary-text-color), 0.01);

                                      }
                                    cards:
                                      - type: custom:mushroom-media-player-card
                                        entity: media_player.garage_tv
                                        name: Garage TV
                                        icon: mdi:cast
                                        use_media_artwork: true
                                        fill_container: false
                                        use_media_info: true
                                        show_volume_level: true
                                        media_controls:
                                          - on_off
                                        collapsible_controls: true
                                        tap_action:
                                          action: toggle
                                      - type: conditional
                                        conditions:
                                          - entity: media_player.garage_tv
                                            state_not: 'off'
                                          - entity: media_player.garage_tv
                                            state_not: idle
                                        card:
                                          entity: media_player.garage_tv
                                          hide:
                                            icon: true
                                            name: true
                                            runtime: true
                                            source: true
                                            power: true
                                            state_label: true
                                            volume: false
                                            info: true
                                            progress: false
                                            controls: false
                                          more_info: false
                                          type: custom:mini-media-player
                                          toggle_power: true
                                          group: true
                                          card_mod:
                                            style:
                                              mmp-progress$: |
                                                paper-progress {
                                                  {{ '--paper-progress-container-color: rgba(63, 81, 181, 0.2) !important;' if is_state(config.entity, 'playing') }}
                                                }
                                              .: |
                                                ha-card {
                                                  margin: 30px 12px 12px;
                                                  --mmp-progress-height: 10px !important;
                                                  height: var(--mmp-progress-height);
                                                  --mmp-accent-color: rgb(255, 170, 0);
                                                  --ha-card-border-radius: 2px;
                                                }
                                  - type: custom:stack-in-card
                                    mode: vertical
                                    card_mod: null
                                    style: >
                                      ha-card {

                                      background-color:
                                      rgba(var(--rgb-primary-text-color), 0.01);

                                      }
                                    cards:
                                      - type: custom:mushroom-media-player-card
                                        entity: media_player.android_tv_192_168_2_123
                                        name: Basement G-TV
                                        icon: mdi:cast
                                        use_media_artwork: true
                                        fill_container: false
                                        use_media_info: true
                                        show_volume_level: true
                                        media_controls:
                                          - on_off
                                        collapsible_controls: true
                                        tap_action:
                                          action: toggle
                                      - type: conditional
                                        conditions:
                                          - entity: media_player.android_tv_192_168_2_123
                                            state_not: 'off'
                                          - entity: media_player.android_tv_192_168_2_123
                                            state_not: idle
                                        card:
                                          entity: media_player.android_tv_192_168_2_123
                                          hide:
                                            icon: true
                                            name: true
                                            runtime: true
                                            source: true
                                            power: true
                                            state_label: true
                                            volume: false
                                            info: true
                                            progress: false
                                            controls: false
                                          more_info: false
                                          type: custom:mini-media-player
                                          toggle_power: true
                                          group: true
                                          card_mod:
                                            style:
                                              mmp-progress$: |
                                                paper-progress {
                                                  {{ '--paper-progress-container-color: rgba(63, 81, 181, 0.2) !important;' if is_state(config.entity, 'playing') }}
                                                }
                                              .: |
                                                ha-card {
                                                  margin: 30px 12px 12px;
                                                  --mmp-progress-height: 10px !important;
                                                  height: var(--mmp-progress-height);
                                                  --mmp-accent-color: rgb(255, 170, 0);
                                                  --ha-card-border-radius: 2px;
                                                }
                              - type: grid
                                square: false
                                columns: 2
                                cards:
                                  - type: custom:stack-in-card
                                    mode: vertical
                                    card_mod: null
                                    style: >
                                      ha-card {

                                      background-color:
                                      rgba(var(--rgb-primary-text-color), 0.01);

                                      }
                                    cards:
                                      - type: custom:mushroom-media-player-card
                                        entity: media_player.samsung_6_series_50
                                        name: Samsung TV
                                        icon: mdi:television
                                        use_media_artwork: true
                                        fill_container: false
                                        use_media_info: true
                                        show_volume_level: true
                                        media_controls:
                                          - on_off
                                        collapsible_controls: true
                                        tap_action:
                                          action: toggle
                                      - type: conditional
                                        conditions:
                                          - entity: media_player.samsung_6_series_50
                                            state_not: 'off'
                                          - entity: media_player.samsung_6_series_50
                                            state_not: idle
                                        card:
                                          entity: media_player.samsung_6_series_50
                                          hide:
                                            icon: true
                                            name: true
                                            runtime: true
                                            source: true
                                            power: true
                                            state_label: true
                                            volume: false
                                            info: true
                                            progress: false
                                            controls: false
                                          more_info: false
                                          type: custom:mini-media-player
                                          toggle_power: true
                                          group: true
                                          card_mod:
                                            style:
                                              mmp-progress$: |
                                                paper-progress {
                                                  {{ '--paper-progress-container-color: rgba(63, 81, 181, 0.2) !important;' if is_state(config.entity, 'playing') }}
                                                }
                                              .: |
                                                ha-card {
                                                  margin: 30px 12px 12px;
                                                  --mmp-progress-height: 10px !important;
                                                  height: var(--mmp-progress-height);
                                                  --mmp-accent-color: rgb(255, 170, 0);
                                                  --ha-card-border-radius: 2px;
                                                }
                                  - type: custom:stack-in-card
                                    mode: vertical
                                    card_mod: null
                                    style: >
                                      ha-card {

                                      background-color:
                                      rgba(var(--rgb-primary-text-color), 0.01);

                                      }
                                    cards:
                                      - type: custom:mushroom-media-player-card
                                        entity: media_player.spotify_david_nestico
                                        name: Spotify
                                        icon: mdi:spotify
                                        use_media_artwork: true
                                        fill_container: false
                                        use_media_info: true
                                        show_volume_level: true
                                        media_controls:
                                          - on_off
                                        collapsible_controls: true
                                        tap_action:
                                          action: toggle
                                      - type: conditional
                                        conditions:
                                          - entity: media_player.spotify_david_nestico
                                            state_not: 'off'
                                          - entity: media_player.spotify_david_nestico
                                            state_not: idle
                                        card:
                                          entity: media_player.spotify_david_nestico
                                          hide:
                                            icon: true
                                            name: true
                                            runtime: true
                                            source: true
                                            power: true
                                            state_label: true
                                            volume: false
                                            info: true
                                            progress: false
                                            controls: false
                                          more_info: false
                                          type: custom:mini-media-player
                                          toggle_power: true
                                          group: true
                                          card_mod:
                                            style:
                                              mmp-progress$: |
                                                paper-progress {
                                                  {{ '--paper-progress-container-color: rgba(63, 81, 181, 0.2) !important;' if is_state(config.entity, 'playing') }}
                                                }
                                              .: |
                                                ha-card {
                                                  margin: 30px 12px 12px;
                                                  --mmp-progress-height: 10px !important;
                                                  height: var(--mmp-progress-height);
                                                  --mmp-accent-color: rgb(255, 170, 0);
                                                  --ha-card-border-radius: 2px;
                                                }
            card_mod:
              style: |
                ha-card { 
                  background: var(--card-background-color);
                  width: 66px;
                  border-radius: 30px;
                  margin-left: auto;
                  margin-right: auto;
                  margin-bottom: 2px;
                }
          - type: custom:mushroom-template-card
            primary: ''
            secondary: Cams
            icon: mdi:cctv
            badge_icon: >-
              {{ 'mdi:bell-badge' if is_state('switch.wyze_notifications', 'on')
              else 'mdi:bell-minus' }}
            badge_color: >-
              {{ 'blue' if is_state('switch.wyze_notifications', 'on') else
              'grey' }}
            layout: vertical
            icon_color: cyan
            tap_action:
              action: navigate
              navigation_path: /homekit-infused/main_room
            card_mod:
              style: |
                ha-card { 
                  background: var(--card-background-color);
                  width: 66px;
                  border-radius: 30px;
                  margin-left: auto;
                  margin-right: auto;
                  margin-bottom: 2px;
                }
          - type: custom:mushroom-template-card
            primary: ''
            secondary: Voice
            icon: mdi:microphone-message
            layout: vertical
            icon_color: blue
            tap_action:
              action: call-service
              service: browser_mod.popup
              service_data:
                title: Google Home announcement
                card:
                  type: custom:notify-card
                  target: tts.google_translate_say
                  label: Say something on the Kitchen Display
                  card_title: Kitchen Display announcement
                  entity: media_player.kitchen_display
                  notification_title:
                    input: null
            card_mod:
              style: |
                ha-card { 
                  background: var(--card-background-color);
                  width: 66px;
                  border-radius: 30px;
                  margin-left: auto;
                  margin-right: auto;
                  margin-bottom: 2px;
                }
card_mod:
  style: |
    ha-card {
      padding: 2px;
      background: rgba(var(--rgb-primary-text-color), 0.01);
    }
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Have made sure I am using the latest version of the plugin.

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
