### ISSUE TITLE
empty popups

### ISSUE THREAD

**Issue by kdw2060** [thomasloven/hass-browser_mod#461]
My Home Assistant version: 2022.9.7
Browser: Firefox

**What I am doing:**
Trying to create a pop-up dialog

**What I expected to happen:**
An entities card to show up inside a pop-up

**What happened instead:**
Upon clicking an empty pop-up appears.

The yaml I'm using:

Variant 1:
```yaml
service: browser_mod.popup
data:
  title: testing
  browser_id: THIS
  content:
    type: entities
    entities:
      - sensor.euro95_esso_a12
      - sensor.euro95_esso_wommelgem
      - sensor.euro95_carrefour_borsbeek
      - sensor.euro95_carrefour_berchem
      - sensor.euro95_total_express_wezenbeek_oppem
      - sensor.euro95_q8_easy_kraainem
```

Variant 2:
```yaml
  tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.popup
        data:
          title: Goedkoopste in de buurt
          browser_id: THIS
          content:
            type: entities
            entities:
              - sensor.euro95_esso_a12
              - sensor.euro95_esso_wommelgem
              - sensor.euro95_carrefour_borsbeek
              - sensor.euro95_carrefour_berchem
              - sensor.euro95_total_express_wezenbeek_oppem
              - sensor.euro95_q8_easy_kraainem
```

I tested the service-call in the developer tools and the same code works there. I also tried several variations for browser-targeting. All give the same result.

**Error messages from the browser console:**
none

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
