### ISSUE TITLE
Notification - Allow "Dismiss" without action

### ISSUE THREAD

**Issue by jazzyisj** [thomasloven/hass-browser_mod#468]
I have some browser notifications that are displayed longer than usual because they can be lengthy (all my tts announcements are also displayed with browser_mod.notification).  Sometimes those notifications gets in the way of stuff in the UI and I'd like to just dismiss it without performing any other action.

Of course putting an action_text parameter without an action as no effect and I'm not aware of any action or service call to use as an action .  I'd like to propose a dismiss or close action that will close the browser notification.

I can currently accomplish this with a bit of a hack but it works great.

```
    - service: browser_mod.notification
      data:
        duration: 30000
        action_text: "DISMISS"
        action: navigate
        navigation_path: /
        message: "Scheduled climate fan timers have been adjusted."
```
