### ISSUE TITLE
Why this doesn't work?

### ISSUE THREAD

**Issue by prbtt** [thomasloven/hass-browser_mod#475]
```
  - type: button
    name: call-service
    tap_action:
      action: call-service
      service: browser_mod.popup
      data:
        title: call-service
        content:
          type: markdown
          content: "{{states('light.bed_light')}}"
```
I'm trying to display a pop-up on any browser that clicks on this button. I also noticed that I can't get this to work using scripts...

**Comment by prbtt** [comment]
I know that this works if called from my dashboard:
```
type: button
name: fire-dom-event
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: fire-dom-event
      content:
        type: markdown
        content: '{{states(''light.a1_lp2'')}}'
```
but this doesn't work on a script.
