### ISSUE TITLE
After closing popup with camera stream - sound does not stop - audio stream running in background

### ISSUE THREAD

**Issue by Majordomo2652** [thomasloven/hass-browser_mod#476]
My Home Assistant version:
Home Assistant 2022.10.5
Supervisor 2022.10.0
Frontend 20221010.0

**What I am doing:**
Opening and closing popup with rtsp camera stream.

**What I expected to happen:**
When I click on button - Popup opens + Video stream appears + Audio stream plays
When I close popup - popup disappears + Video disappears + Audio stops playing

**What happened instead:**
On first popup action everything works as intended.

On second and every consequent popup action:
When I click on button - Popup opens + Video stream appears + Audio stream plays
When I close popup - popup disappears + Video disappears + Audio **DOES NOT** stop

After multiple popup openings and closing I can hear loud sound from all streams running in background.
This happens on windows and android devices. 
When refreshing browser everything goes back to beginning. First popup works as intended, and from second onward sound doesnt stop.

```yaml
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              content:
                type: custom:webrtc-camera
                url: <camera_address>
                muted: false
              size: fullscreen
```

```

```

---

**By replacing the space in the checkboxes ([x]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
