### ISSUE TITLE
Nested Popup takes 2 actions to execute

### ISSUE THREAD

**Issue by muddro1** [thomasloven/hass-browser_mod#482]
My Home Assistant version: 2022.10.5

**What I am doing:**
I have a dashboard with a card for my bedroom lights. I have a hold_action utilizing fire-dom-event to popup a card with most of the individual lights in the room plus a light group (level 1 popup). I created a similar hold_action on the light group entity to popup a second card with the individual lights within that group (level 2 popup).

**What I expected to happen:**
For hold actions to work and popup the respective cards described above.

**What happened instead:**
The level 1 popup works as expected. However, on mobile, it always takes 2 attempts for the hold action to work on the level 2 popup. The first attempt will always try to select the words of the entity. Holding again executes the popup.

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error
          - type: horizontal-stack
            cards:
              - type: horizontal-stack
                cards:
                  - type: custom:mushroom-light-card
                    entity: light.bedroom_lights
                    layout: vertical
                    show_brightness_control: true
                    use_light_color: false
                    hide_state: false
                    icon: bha:ceiling-downlight
                    name: Main Bedroom
                    hold_action:
                      action: fire-dom-event
                      browser_mod:
                        service: browser_mod.popup
                        data:
                          title: Bedroom Lights
                          content:
                            type: vertical-stack
                            cards:
                              - type: custom:mushroom-light-card
                                entity: light.bedroom_lights
                                show_brightness_control: true
                                layout: horizontal
                                fill_container: false
                              - type: custom:mushroom-light-card
                                entity: light.lamps
                                show_brightness_control: true
                                layout: horizontal
                                hold_action:
                                  action: fire-dom-event
                                  browser_mod:
                                    service: browser_mod.popup
                                    data:
                                      title: Lamps
                                      content:
                                        type: vertical-stack
                                        cards:
                                          - type: custom:mushroom-light-card
                                            entity: light.person1
                                            show_brightness_control: true
                                            layout: horizontal
                                            fill_container: false
                                          - type: custom:mushroom-light-card
                                            entity: light.person2
                                            show_brightness_control: true
                                            layout: horizontal
                              - type: custom:mushroom-light-card
                                entity: light.bedroom_fan
                                show_brightness_control: true
                                layout: horizontal
                    collapsible_controls: false
# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
