### ISSUE TITLE
Popup Card Mod styles sticking

### ISSUE THREAD

**Issue by Sian-Lee-SA** [thomasloven/hass-browser_mod#488]
My Home Assistant version: 2022.11.2

**What I am doing:**
Opening a dialog with card mod styles will stick and apply the same styles to any dialog that opens after

**What I expected to happen:**
All card mod styles should reset

**What happened instead:**
Dialogs showing styles from a different dialog

**Minimal** steps to reproduce:
create two or more seperate popups, add card_mod styles to each with completely different values. Even a popup with no card)mod style will still inherit the old card_mod styles.

```yaml
# The least amount of code or steps possible to reproduce my error
# lovelace_gen

service: browser_mod.popup
data:
  card_mod:
    style: 
      '.': >-
            :host {
              --popup-border-width: 0;
              --popup-border-color: none;
              --popup-border-radius: 0;
              --mdc-theme-surface: #f7f8f9;
              --ha-card-background: #f7f8f9;
              --popup-min-width: 600px;
              --popup-max-width: 600px;
            }
            ha-dialog app-toolbar {
              background: #e9e9e9;
            }

            .content {
              width: auto !important;
            }
      ha-dialog$: >-
            .mdc-dialog {
              justify-content: flex-start !important;
            }

            /* custom scrollbar */
            ::-webkit-scrollbar {
              width: 20px;
            }

            ::-webkit-scrollbar-track {
              background-color: transparent;
            }

            ::-webkit-scrollbar-thumb {
              background-color: #d6dee1;
              border-radius: 20px;
              border: 6px solid transparent;
              background-clip: content-box;
            }

            ::-webkit-scrollbar-thumb:hover {
              background-color: #a8bbbf;
            }

            .mdc-dialog .mdc-dialog__surface {
              height: 100%;
            }
  content:
    type: 'custom:vertical-timeline'
    entities:
      {% for entity in entities %}
      - {{ entity }}
      {% endfor %}


# lovelace_gen

type: custom:popup-card
entity: {{ entity }}
style: !include ['../styles/dialog_white.yaml', {width: '1020px', padding: '12px'}]
card_mod:
  style: 
    ha-dialog$: '.mdc-dialog__surface, .mdc-dialog__content{overflow: visible !important; min-height: 590px}'
card:
  type: custom:statistics-datepicker-card
  card_mod:
    style: 
      '.': 'ha-card{--primary-text-color:#525252; }'
  entity_selector: {{ selector | default(false) }}   
  entities:
  {% if not entities %}
  {% set entities = [entity] %}
  {% endif %}
  {% for entity in entities %}
    - {{ entity }}
  {% endfor %}
  days_to_show: {{ days_to_show|default(28) }}
  stat_types: {{ stat_types|default(['min','max','mean']) }}
# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
