### ISSUE TITLE
Popup_cards not working for me

### ISSUE THREAD

**Issue by l3keboy** [thomasloven/hass-browser_mod#490]
My Home Assistant version: 2022.11.2

**What I am doing:**
First of all, I don't really think this is a bug with hass-browser_mod, but I don't just seem to get this to work, so I was wondering if someone could get me going in the right direction! Thanks in advance!
I am trying to overwrite the more-info dialog of a dummy sensor, the following code is used:

**What I expected to happen:**
The more-info dialog to be overwritten.

**What happened instead:**
I just get to see the normal more info dialog

**Minimal** steps to reproduce:
popup_cards config:
```yaml
    popup_cards:
      sensor.dummy_sensor_guest_wifi:
        title: Title
        card:
          type: picture-entity
          image: /path/to/file.jpg
          entity: sensor.dummy_sensor_guest_wifi
          show_state: false
          show_name: false
```

Card config:
```yaml
    type: custom:mushroom-chips-card
    chips:
      - type: template
        icon: mdi:wifi
        content: Title
        tap_action:
          action: more-info
        double_tap_action:
          action: more-info
        hold_action:
          action: more-info
        entity: sensor.dummy_sensor_guest_wifi
    alignment: center
```

**Error messages from the browser console:**
No error message that I know off

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- X Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- X Have made sure I am using the latest version of the plugin.

- X Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- X Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by MeowRay** [comment]
+1, hass-browser_mod 2.x version does not seem to support

**Comment by MeowRay** [comment]
I noticed. 2.x card action is no longer more-info, but fire-dom-event

```
type: custom:button-card
size: 18%
name: 车库门 (离线)
icon: mdi:garage-alert-variant
color: rgb(238, 82, 83)
state:
  - value: 'on'
    color: rgb(238, 82, 83)
    styles:
      card:
        - animation: blink 1s ease
    icon: mdi:garage-open-variant
    name: 车库门 (已开启)
  - value: 'off'
    color: rgb(84, 160, 255)
    icon: mdi:garage-variant
    name: 车库门 (已关闭)
hold_action:
  action: more-info
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: My title
      content: 
        type: vertical-stack
        cards:
          - type: custom:button-card
            size: 18%
            name: 车库门 (离线)
            icon: mdi:garage-alert-variant
            entity: binary_sensor.che_ku_men_chuan_gan_qi_b_contact
            color: rgb(238, 82, 83)
            state:
              - value: 'on'
                color: rgb(238, 82, 83)
                icon: mdi:garage-open-variant
                name: 车库门 (已开启)
              - value: 'off'
                color: rgb(84, 160, 255)
                icon: mdi:garage-variant
                name: 车库门 (已关闭)
          - show_name: true
            show_icon: true
            type: custom:button-card
            styles:
              card:
                - height: 100px
            name: >
              [[[

              var name =
              states['binary_sensor.che_ku_men_chuan_gan_qi_b_contact'].state;
               if (name == 'on'){
                  return '车库门半开 (目前已开启)';
               } else {
                  return '车库门半开';
               }

              ]]]
            tap_action:
              action: call-service
              service: script.chekumenbankai
              service_data: {}
              target: {}
            entity: switch.che_ku_men_yu_dun_l_l6
            icon: mdi:arrow-expand-up
            icon_height: 20px
          - type: grid
            square: false
            columns: 3
            cards:
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: script.chekumenkai
                  service_data: {}
                  target: {}
                entity: switch.che_ku_men_yu_dun_l_l6
                icon: mdi:arrow-expand-up
                icon_height: 60px
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: script.chekumenting
                  service_data: {}
                  target: {}
                entity: switch.che_ku_men_yu_dun_l_l5
                icon: mdi:stop
                icon_height: 60px
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: script.chekumengguang
                  service_data: {}
                  target: {}
                entity: switch.che_ku_men_yu_dun_l_l7
                icon: mdi:arrow-expand-down
                icon_height: 60px
          - type: history-graph
            entities:
              - entity: binary_sensor.che_ku_men_chuan_gan_qi_b_contact
                name: 历史
          - type: history-graph
            entities:
              - entity: binary_sensor.che_ku_men_chuan_gan_qi_b_contact
                name: 历史
entity: binary_sensor.che_ku_men_chuan_gan_qi_b_contact

```

**Comment by GeorgeSG** [comment]
It seems that a top level `popup_cards:` is not supported anymore.
You have to include your cards as a standard card in each view:

```yaml
- type: custom:popup-card
  entity: script.brita_pour_water
    title: Brita
    card:
      ...
```

At least that works for me.

**Comment by franlmc** [comment]
> It seems that a top level `popup_cards:` is not supported anymore. You have to include your cards as a standard card in each view:
> 
> ```yaml
> - type: custom:popup-card
>   entity: script.brita_pour_water
>     title: Brita
>     card:
>       ...
> ```
> 
> At least that works for me.

Sorry

Please can you explain that?

i understand that my camera cards in home assistant (done as picture-entity card) must be convert to custom:popup-card?

**Comment by GeorgeSG** [comment]
> Please can you explain that?
> 
> i understand that my camera cards in home assistant (done as picture-entity card) must be convert to custom:popup-card?

No.

What I mean is that if you previously did this in your `ui-lovelace.yaml`:

 ```yaml
popup_cards:
  sensor.dummy_sensor_guest_wifi:
    # popup card
    
title: Dashboard
views:
  - title: View1
    cards:
      - type: <whatever>
        entities: sensor.dummy_sensor_guest_wifi
```

you now have to do this:

```yaml
title: Dashboard
views:
  - title: View1
    cards:
      - type: custom:popup-card
        entity: sensor.dummy_sensor_guest_wifi
        title: popup title
        card:
           # popup card
      - type: <whatever>
        entities: sensor.dummy_sensor_guest_wifi
```

At least this works for me :)
