### ISSUE TITLE
Closing opened more-info's in popup closes popup in 2.x

### ISSUE THREAD

**Issue by emufan** [thomasloven/hass-browser_mod#502]
Follow up from https://github.com/thomasloven/hass-browser_mod/issues/392

My Home Assistant version: 2022.12.7

**What I am doing:**

Having a popup in browser_mod 2.1 with e.g. a simple entities card

Open a standard more-info of one of those entity in this popup

Close the standard more-info of this entity

=> The browser-mod popup is closed as well

**What I expected to happen:**

As in browser_mod < 2.0

=> only the more-info is closed, but the browser_mod popup is still open and I can click another entity's more-info in the card, ...

90% of my popups are detailed pages with entities for a e.g. device. And I would like to still be able to click through the more-info of the popup-content, without having to open the popup every time again.

If it is not a bug, I don't see the doc how to achieve it as wanted. Perhaps with the browser_mod.more-info service, but this would be a huge overhead in every popup code. Perhaps a global setting per popup to work as before?

```
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Wecker
      content:
        type: entities
        show_header_toggle: false
        state_color: true
        entities:
          - entity: input_boolean.wecker_schlafzimmer
```

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
