### ISSUE TITLE
browser_mod.popup custom CSS not applying on Fully Kiosk Browser

### ISSUE THREAD

**Issue by michaeldvinci** [thomasloven/hass-browser_mod#504]
My Home Assistant version: 0.XX.X

**What I am doing:**

screenshots:
- [Chrome on MacBook](https://i.imgur.com/iZzHIRM.png)

 - This has the custom css styling in the dev > services pane

- [Fully Kiosk Browser](https://i.imgur.com/s7okJwo.jpg)

**What I expected to happen:**
Both popups should have font-size of 60px

**What happened instead:**
As you can see with the first screenshot, the custom CSS is set, and the content shows up with a font-size 60px. However, in screenshot two, you can see that this does not work in fully kiosks browser. I've cleared the app cache, as well as logout/in with no luck so far.

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error

service: browser_mod.popup
data:
  style: |
    ha-dialog {
      --mdc-dialog-min-width: 750px !important;
      --mdc-dialog-max-width: 1080px !important;
    }
    .content {
      width: auto !important;
    }
    .mdc-dialog__content {
      font-size: 60px;
    }
  title: browser_mod.popup
  content: supposed to be 60px
  timeout: 30000


# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
