### ISSUE TITLE
Fire-dom-event not working

### ISSUE THREAD

**Issue by aw-jansen** [thomasloven/hass-browser_mod#506]
My Home Assistant version: 2022.12.8

Trying to use the pop-up via the fire-dom-event action but nothing happens.

Used the following config as action on one of the new tile cards:

```yaml
type: tile
  entity: light.upstairs
  tap_action:
    action: fire-dom-event
    browser_mod:
      service: browser_mod.more_info
      data:
        entity: light.bed_light
```

also tried the following but that fires on all registered devices (as expected):

```yaml
type: tile
  entity: light.upstairs
  tap_action:
    action: call-service
    browser_mod:
      service: browser_mod.popup
      data:
        entity: light.bed_light
```

running the action does not give any warnings or errors

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
The second should not run at all, because it doesn't have  a `service` parameter.

Do you actually *have*  an entity named `light.bed_light`?

**Comment by aw-jansen** [comment]
> The second should not run at all, because it doesn't have a `service` parameter.
> 
> Do you actually _have_ an entity named `light.bed_light`?

sorry, I copy pasted a wrong piece of my configuration. The second example should have been this:

`
type: tile
  entity: light.upstairs
  tap_action:
    action: call-service
    browser_mod:
      service: browser_mod.popup
      data:
        content:
          type: vertical-stack
          cards:
            - type: tile
              entity: light.upstairs
              name: Upstairs
              icon: mdi:lightbulb-group-outline
              features:
                - type: light-brightness
        target: {}
`

This works as expected (shows a pop-up on all registered devices). But I would like to trigger a pop-up on the device where the tap_action was being run from. As suggested in your wiki I tried the fire-dom-event but that doesn't seem to do anything at all.

**Comment by aw-jansen** [comment]
I got it working, having to copy paste my config here made me see it just slightly mismatched that of the format it should have been. 

Thanks for your reply and great addon! 

For anyone trying something similar, below my working code.

```yaml
type: tile
  entity: light.upstairs
  tap_action:
    action: fire-dom-event
    browser_mod:
      service: browser_mod.popup
      data:
        content:
          type: vertical-stack
          cards:
            - type: tile
              entity: light.upstairs_1
              name: Upstairs 1
              icon: mdi:lightbulb-group-outline
              features:
                - type: light-brightness
            - type: tile
              entity: light.upstairs_2
              name: Upstairs 2
              icon: mdi:lightbulb-group-outline
              features:
                - type: light-brightness
    ```
