### ISSUE TITLE
Support undefined title in service_data

### ISSUE THREAD

**Issue by dooz127** [thomasloven/hass-browser_mod#51]
For example, this yaml should still work even when you don't specify the `title` for the card:

```yaml
type: entities
entities:
  - entity: light.kitchen_light
    tap_action:
      action: call-service
      service: browser_mod.popup
      service_data:
        card:
          type: entities
          entities:
            - light.kitchen_light
        deviceID:
          - this
```
You can display a blank string or fetch `friendly_name` or `entity_id` of the first specified entity in the card.

I'm not a developer and would love to help with little things like so I'm trying to set up a dev environment, learn github, home assistant development, etc. but it's taking me a while.
