### ISSUE TITLE
after 2.2.0 update all popups are at the top of the screen

### ISSUE THREAD

**Issue by maverik80** [thomasloven/hass-browser_mod#512]
My Home Assistant version: 2023.01

**What I am doing:**hello everyone, after updating to the latest version I'm experiencing all the pop ups appear moved to the top of the screen, while before they were all in the center, I've read the documentation but I can't find any string that can help me. I am attaching an image, any help and welcome, thanks guys

![popup](https://user-images.githubusercontent.com/62015384/210750047-1dcd6082-c11d-4bd5-94a3-4a5437c71805.png)

```yaml
tap_action:
action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    style: |
      --popup-min-width: 400px;
    title: Setting luce Disimpegno
    dismissable: false
    timeout: 60000
    right_button: Indietro
    content:
      type: custom:mushroom-light-card
      entity: light.disimpegno
      show_color_temp_control: true
      collapsible_controls: true

**Comment by sagaland93** [comment]
Same for me. I'd also like popups to be centered like before.

**Comment by maverik80** [comment]
I couldn't figure out if it was my problem, but now thanks to you I understand that it's not, I searched far and wide but no option found, I hope for an update or for someone to explain to me How to do it, I at least explain to me

**Comment by antonio1475** [comment]
Same here. Not good for some small light control popups on mobile... 

I saw popups in the latest changelog, so I immediately thought of this...

**Comment by pickonedev** [comment]
Same here... everywhere, on computer, tablet, phone, all device will show the popup on top, not centered

**Comment by antonio1475** [comment]
Not only it's at the top now, but on desktop the card is now within another one.

Before (card only, center):
![image](https://user-images.githubusercontent.com/63130724/211149103-2ca35830-8043-4dfa-bf36-eaa41d1a3351.png)

After (card within card, top):
![image](https://user-images.githubusercontent.com/63130724/211149106-18a06499-5c30-4856-b92f-1816c2cf884f.png)

**Comment by sagaland93** [comment]
Matt solved it. Tested the changes he made to his [themes.yaml](https://github.com/matt8707/hass-config/commit/63aacb8f50ae907862e5456c02f8e2d874a39f9d) and it works for me.

**Comment by antonio1475** [comment]
> Matt solved it. Tested the changes he made to his [themes.yaml](https://github.com/matt8707/hass-config/commit/63aacb8f50ae907862e5456c02f8e2d874a39f9d) and it works for me.

I guess I don't know how to use that, because adding that file to my themes folder not only didn't fix it (using a Minimalist theme), but it generated Supervisor errors on restart.

### I might have found the root cause:
Line 141 of browser_mod.js has a typo:
`--vertial-align-dialog: flex-start;`
_vertial_

So I changed it to:
`--vertical-align-dialog: center;`
_Note that I also had to change it to center_

As per the "background" card, in 2.2.0 a bunch of paddings and margins where added for whatever reason...
Instead of fighting that, I went with a simple edit of line 153 to make it transparent. From:
```
        --mdc-theme-surface: var(
          --popup-background-color,
          var(--ha-card-background, var(--card-background-color, white))
        );
```
to
`        --mdc-theme-surface: transparent;`
**I don't know the impact of this on other places! I'm only using popups for these light control popups, so it works for me. I consider this a temporary workaround**

![image](https://user-images.githubusercontent.com/63130724/211154605-685fd167-62b2-46d3-9a7d-7bf357c45530.png)

**Comment by pickonedev** [comment]
I have solve this by adding this to my themes.yaml

```
my-theme:
  card-mod-theme: my-theme
  card-mod-more-info: |
    .: |
      ha-dialog {
        --vertical-align-dialog: center !important;
      }    
```

**Comment by silvannn** [comment]
`
card-mod-more-info-yaml: |
    .: |
      ha-dialog {
        --vertical-align-dialog: center !important;
      }
`
I added this to theme what I am using and it doesn't work.

**Comment by Simonh98** [comment]
Does anyone have a solution for this?

**Comment by pickonedev** [comment]
```
my-theme:
  card-mod-theme: my-theme
  card-mod-more-info-yaml: |
    .: |
      ha-dialog {
        --vertical-align-dialog: center !important;
      } 
```

**Comment by aLAN-LDZ** [comment]
ame here... te popup is on the top :( how to fix it ?

**Comment by antonio1475** [comment]
For me the current solution (especially targeted for mobile) is to add / replace this on your theme yaml file:

```
  card-mod-view-yaml: |
    "*:first-child$": |
      #columns .column > * {
        padding-left: 5px;
        padding-right: 5px;
        padding-bottom: 5px;
      }
  card-mod-more-info-yaml: |
    .: |
      @media (max-width: 450px) {
        ha-dialog {
            --mdc-dialog-min-width: calc(95vw)!important;
            --mdc-dialog-min-height: 0!important;
            # --mdc-dialog-max-height: 90%!important;
            # --dialog-surface-margin-top: 20px!important;
            --ha-dialog-border-radius: 20px!important;
            --vertical-align-dialog: center !important;
        }
      }
    ha-more-info-info:
      $: |
        @media (max-width: 450px) {
          .container {
            min-height: auto!important;
          }
        }
```
![image](https://user-images.githubusercontent.com/63130724/233089275-3743ad40-5b99-4b62-b0a3-2ee8083be158.png)

**Comment by pickonedev** [comment]
For me... it is not consistent :-( 
The consistency is like  2 of 10

**Comment by pickonedev** [comment]
I think that the consistency is all about the browser... I use an application which have a "browser" to  put a dashboard into the computer's desktop and everything is ok, everything it is working perfectly (Instead of having a desktop wallpaper on my computer, I have this dashboard and it's all good), this app it is using a "WebView2" type browser. And with Firefox and Fully Kiosk Browser, it doesn't have any consistency... on any device

**Comment by shlomki** [comment]
Running into the same problem, however for me none of the solutions above helped. 
It's interesting how this isn't happening for everyone, perhaps there is a conflict with another card?

**Comment by antonio1475** [comment]
> Running into the same problem, however for me none of the solutions above helped.
> It's interesting how this isn't happening for everyone, perhaps there is a conflict with another card?

Things keep changing in HA too. However, my solution continues to work in 2023.6.2
![IMG_5077](https://github.com/thomasloven/hass-browser_mod/assets/63130724/835f91fb-ddc3-46c3-9c04-f0778c308a67)
![IMG_5078](https://github.com/thomasloven/hass-browser_mod/assets/63130724/98d2b1a0-b36d-4c05-a763-654adfb63506)
![IMG_5079](https://github.com/thomasloven/hass-browser_mod/assets/63130724/1a5c5f77-daca-45f4-b365-54a96a782275)

@jabronimus  you add it to the theme that you use (or all). Here's my Minimalist UI (modified for popups) theme as reference:
<details>
  <summary>Click to expand</summary>

  ```

---
minimalist-desktop-popup:
  # Journal
  state-icon-color: "rgb(var(--color-theme))"
  border-radius: "20px"
  ha-card-border-radius: "var(--border-radius)"
  error-color: "var(--google-red)"
  warning-color: "var(--google-yellow)"
  success-color: "var(--google-green)"
  info-color: "var(--google-blue)"
  divider-color: "rgba(var(--color-theme),.12)"
  accent-color: "var(--google-yellow)"
  ha-dialog-border-radius: "10px"
  # fix added border-lines in 2022.11
  ha-card-border-width: "0px"
  card-mod-theme: "minimalist-desktop-popup"
  card-mod-view-yaml: |
    "*:first-child$": |
      #columns .column > * {
        padding-left: 5px;
        padding-right: 5px;
        padding-bottom: 5px;
      }
  card-mod-more-info-yaml: |
    .: |
      @media (max-width: 450px) {
        ha-dialog {
            --mdc-dialog-min-width: calc(95vw)!important;
            --mdc-dialog-min-height: 0!important;
            # --mdc-dialog-max-height: 90%!important;
            --vertical-align-dialog: center !important;
            --dialog-surface-margin-top: 20px!important;
            --ha-dialog-border-radius: 20px!important;
        }
      }
    ha-more-info-info:
      $: |
        @media (max-width: 450px) {
          .container {
            min-height: auto!important;
          }
        }

  modes:
    light:
      # text
      primary-text-color: "#212121"
      # main interface colors
      primary-color: "#434343"
      google-red: "#F54436"
      google-green: "#01C852"
      google-yellow: "#FF9101"
      google-blue: "#3D5AFE"
      google-violet: "#661FFF"
      google-grey: "#BBBBBB"
      color-red: "245, 68, 54"
      color-green: "1, 200, 82"
      color-yellow: "255, 145, 1"
      color-blue: "61, 90, 254"
      color-purple: "102, 31, 255"
      color-grey: "187, 187, 187"
      color-pink: "233, 30, 99"
      color-theme: "51,51,51"
      color-background-yellow: "250, 250, 250"
      color-background-blue: "250, 250, 250"
      color-background-green: "250, 250, 250"
      color-background-red: "250, 250, 250"
      color-background-pink: "250, 250, 250"
      color-background-purple: "250, 250, 250"
      color-yellow-text: "var(--primary-text-color)"
      color-blue-text: "var(--primary-text-color)"
      color-green-text: "var(--primary-text-color)"
      color-red-text: "var(--primary-text-color)"
      color-pink-text: "var(--primary-text-color)"
      color-purple-text: "var(--primary-text-color)"
      opacity-bg: "1"
      # background and sidebar
      card-background-color: "#FAFAFA"
      primary-background-color: "#EFEFEF"
      secondary-background-color: "#EFEFEF"
      # header
      app-header-text-color: "var(--primary-text-color)"
      app-header-background-color: "var(--primary-background-color)"
      # paper-tabs-selection-bar-color: "var(--primary-text-color)"
      # slider
      slider-color: "rgb(var(--color-blue))"
      slider-bar-color: "rgba(var(--color-blue),0.38)"
      # cards
      box-shadow: "0px 2px 4px 0px rgba(0,0,0,0.16)"
      ha-card-box-shadow: "var(--box-shadow)"
      # sidebar
      sidebar-selected-text-color: "var(--google-red)"
      sidebar-selected-icon-color: "var(--google-red)"
      sidebar-text-color: "#80868b"
      # switch
      switch-checked-color: "var(--google-blue)"
      # media player
      mini-media-player-accent-color: "var(--google-blue)"
    dark:
      # text
      primary-text-color: "#DDDDDD"
      # main interface colors
      primary-color: "#89B3F8"
      google-red: "#F18B82"
      google-green: "#80C994"
      google-yellow: "#FCD663"
      google-blue: "#89B3F8"
      google-violet: "#BB86FC"
      google-grey: "#BBBBBB"
      color-red: "241, 139, 130"
      color-green: "128, 201, 148"
      color-yellow: "252, 214, 99"
      color-blue: "137, 179, 248"
      color-theme: "221,221,221"
      color-purple: "102, 31, 255"
      color-grey: "187, 187, 187"
      color-pink: "233, 30, 99"
      color-background-yellow: "var(--color-yellow)"
      color-background-blue: "var(--color-blue)"
      color-background-green: "var(--color-green)"
      color-background-red: "var(--color-red)"
      color-background-pink: "var(--color-pink)"
      color-background-purple: "var(--color-purple)"
      color-yellow-text: "var(--color-yellow)"
      color-blue-text: "var(--color-blue)"
      color-green-text: "var(--color-green)"
      color-red-text: "var(--color-red)"
      color-pink-text: "var(--color-pink)"
      color-purple-text: "var(--color-purple)"
      opacity-bg: "0.1"
      # floating button text color
      mdc-theme-on-secondary: "var(--card-background-color)"
      # background and sidebar
      card-background-color: "#1D1D1D"
      primary-background-color: "#121212"
      secondary-background-color: "#121212"
      # header
      app-header-text-color: "var(--primary-text-color)"
      app-header-background-color: "var(--primary-background-color)"
      paper-tabs-selection-bar-color: "var(--primary-text-color)"
      # Sidebar
      sidebar-selected-text-color: "rgb(var(--color-blue))"
      sidebar-selected-icon-color: "rgb(var(--color-blue))"
      # Slider
      slider-color: "rgb(var(--color-blue))"
      slider-bar-color: "rgba(var(--color-blue),0.38)"
      # card
      box-shadow: "none"
      # media player
      mini-media-player-accent-color: "var(--google-blue)"
      # Journal
      state-icon-color: "rgb(var(--color-theme))"

  ```
</details>

**Comment by dsellers1** [comment]
I've been able to center the pop-up within card_mod (and not having to rely on the theme method). This works for browser_mod.popup and fire-dom-event. (Background color and blur added because I think it looks cool.)
```yaml
card_mod:
  style:
    ha-dialog$: |
      div.mdc-dialog div.mdc-dialog__scrim {
        background: rgba(0, 100, 100, 0.4);
      }
      div.mdc-dialog__container {
        --vertical-align-dialog: center !important;
      }
    .: |
      ha-dialog {
        --dialog-backdrop-filter: blur(0.8em); 
      }
```
![fully-screenshot](https://github.com/thomasloven/hass-browser_mod/assets/67642332/b881b129-5b1d-4721-8d55-99ff31e323ef)

<details><summary>call-service in Dev Tools example</summary>
(This example targets a registered browser. Change it to one of your devices or remove the target section.)

```yaml

service: browser_mod.popup
data:
  content:
    aspect_ratio: 100%
    type: iframe
    url: >-
      https://www.rainviewer.com/map.html?loc=40.1957,-83.9575,6&oFa=1&oC=1&oU=0&oCS=0&oF=0&oAP=1&c=3&o=83&lm=0&layer=sat-rad&sm=1&sn=1&hu=false
  card_mod:
    style:
      ha-dialog$: |
        div.mdc-dialog div.mdc-dialog__scrim {
          background: rgba(0, 100, 100, 0.4);
        }
        div.mdc-dialog__container {
          --vertical-align-dialog: center !important;
        }
      .: |
        ha-dialog {
          --dialog-backdrop-filter: blur(0.8em); 
        }
  dismissable: true
  autoclose: false
  timeout: 15000
  size: normal
target:
  device_id: 8721b7679af078d2eab177cbe434f900

```
</details>

<details><summary>fire-dom-event in a button card example</summary>

```yaml

type: button
name: Pop-up
show_name: true
show_icon: true
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      dismissable: true
      autoclose: true
      timeout: 7500
      content:
        aspect_ratio: 84.5%
        type: iframe
        url: >-
          https://www.rainviewer.com/map.html?loc=40.1957,-83.9575,6&oFa=1&oC=1&oU=0&oCS=0&oF=0&oAP=1&c=3&o=83&lm=0&layer=sat-rad&sm=1&sn=1&hu=false
      card_mod:
        style:
          ha-dialog$: |
            div.mdc-dialog div.mdc-dialog__scrim {
              background: rgba(0, 100, 100, 0.4);
            }
            div.mdc-dialog__container {
              --vertical-align-dialog: center !important;
            }
          .: |
            ha-dialog {
              --dialog-backdrop-filter: blur(0.8em); 
            }

```
</details>
