### ISSUE TITLE
Feature Request: target existing card

### ISSUE THREAD

**Issue by dooz127** [thomasloven/hass-browser_mod#52]
Closely related to #12 but it would be cool if we could target an existing lovelace card for a more-info or pop-up, e.g.:

```
type: entities
entities:
  - entity: climate.hallway
    tap_action:
      action: call-service
      service: browser_mod.popup
      service_data:
        defined_card: lovelace/2/my_hallway_thermostat_card
```
The use case here would be for dashboard or floorplan views to use minimal representations for entities (e.g., badges, icons, etc.) but be able to display more detailed cards in the tabs/loveplace view without having to duplicate configuration for existing cards. This may require work in the backend to generate unique id's for cards or to enforce unique titles for cards in a view. This may deviate from the goal of decentralized app routing (which I don't quite get why that's important).
