### ISSUE TITLE
Issues/unexpected behaviour when triggering popup within popup

### ISSUE THREAD

**Issue by adabelleleiram** [thomasloven/hass-browser_mod#520]
My Home Assistant version: 2023.1.0

**What I am doing:**
I would like to be able to open a popup from within another popup. In my case, I have a light group that I want to be able to expand. For the hold action of the light group, I trigger a popup that shows a list of all the entities in that group. Holding on each entity brings up another popup. If that entity is a group, it would expand that one too, otherwise show more-info for that light.

**What I expected to happen:**
To be able to open each popup with a hold action. When I close each popup, I expect to return to the previous popup.

**What happened instead:**
On mobile (both companion app and Chrome), I have to do the hold action twice within the first popup to open the second popup: 
https://user-images.githubusercontent.com/28298971/213862640-7cf5c40c-ff9f-4d5a-b139-38b6d72af636.mp4

This doesn't happen on my computer in Chrome (not even with mobile layout in dev tools).

When I close popup 2, I'm sent back to the main view. This happens on mobile and on my computer.

**Minimal** steps to reproduce:
* Use the yaml below.
* Hold button card to open popup 1
* Hold button card
** On computer browser: opens popup 2
** On mobile (companion or browser): hold again to open popup 2
* Close popup

```yaml
# The least amount of code or steps possible to reproduce my error
type: button
entity: light.dining_room_light
hold_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Popup 1
      content:
        type: horizontal-stack
        cards:
          - type: button
            entity: light.dining_room_pendant_up
            hold_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.popup
                data:
                  title: Popup 2
                  content:
                    type: custom:more-info-card
                    title: "Popup 2"
                    entity: light.dining_room_pendant_up

# Put your code/steps here
```

**Error messages from the browser console:**
Nothing on computer. Can't check on mobile...?
```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
