### ISSUE TITLE
browser_mod.popup in sequence with browser_id is not working

### ISSUE THREAD

**Issue by Code-TT** [thomasloven/hass-browser_mod#529]
My used browser_mod: 2.2.0. 
I used this script / sequence in the past to show a popup of my cam in the actual browser. 

```
sequence:
  - service: browser_mod.popup
    data:
      browser_id: "{{ browser_id }}"
      content:
        title: "Live: Hauseingang"
        camera_view: live
        type: picture-glance
        entities: []
        camera_image: camera.hauseingang
        hold_action:
          action: none
        tap_action:
          action: none
      size: wide
      right_button: Schließen
      right_button_action:
        service: browser_mod.close_popup
        data: null
      style: |
        --popup-background-color: #222;
        --ha-card-background: #111
alias: Kamera Haustür Popup
mode: restart
icon: mdi:webcam
```

It works well before. Now it's not working anymore. Nothing happens if I run the sequence. 
If I delete `browser_id: "{{ browser_id }}"` the popup is showing up on all machines. I don't want that. 
In the Wiki under Cookbook is written, that `deviceID: "{{ deviceID }}"` should make it. This example doesn't work either. If replace the line with browser_id to deviceID, the popup is plopping up everywhere again. 
Can you please help me to fix that problem?
