### ISSUE TITLE
Popup appears multiple times (once on each browser tab)

### ISSUE THREAD

**Issue by ribbal** [thomasloven/hass-browser_mod#531]
My Home Assistant version: 2023.1.7

**What I am doing:**
Clicked a button to trigger a browser mod popup. I have multiple HA browser tabs open. 

**What I expected to happen:**
Popup to appear **only** on the current 'active' browser tab.

**What happened instead:**
Popup appears on **all** open HA browser tabs.

**Minimal** steps to reproduce:
Open multiple HA browser tabs (and refresh all tabs), trigger a browser mod popup (popup appears on all open tabs)

```yaml
type: button
name: Living Room
icon: mdi:sofa-outline
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      browser_id: THIS
      dismissable: true
      content:
        type: custom:mushroom-light-card
        entity: light.lounge_lamp
        icon: mdi:floor-lamp
```

**Error messages from the browser console:**
No messages appear in browser console, when clicking the button to trigger the popup.
```

```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
