### ISSUE TITLE
Remotely invoke the new Voice Assist capability

### ISSUE THREAD

**Issue by int-rnd** [thomasloven/hass-browser_mod#534]
Now that HA has the voice assist feature, it would be awesome to be able to trigger that uI/listening via a service so that it opens and starts listening for a command using the microphone of the browser registered in browser mod. 

My use case will be a button in the room that then triggers browser mod to open the assist and start listening so I can give it voice commands.

**Comment by dcapslock** [comment]
@int-rnd do you still need a solution for this?

**Comment by int-rnd** [comment]
Yes please! I have a small machine running Rasbian and Chrome that I would love to be able to trigger remotely.
________________________________

**Comment by dcapslock** [comment]
OK. WIll leave open and investigate.

**Comment by dcapslock** [comment]
Reviewing this again. There is no easy way for Browser Mod to reliably or neatly call up Assist. There are two ways that may work depending on your environment.

1. If shortcuts are enabled, use javascript to simulate '(A)' keypress.
2. If you don't mind a browser reload, use the HA supported `?conversation=1` search string.

e.g.

#### 1 - Shortcut
__Note__: Needs shortcuts enabled
```yaml
action: browser_mod.javascript
data:
  code: |
    window.dispatchEvent(new KeyboardEvent('keydown', {'key': 'a'}));window.dispatchEvent(new KeyboardEvent('keyup', {'key': 'a'}));
```

#### 2 - Browser search string
__NOTE__: Browser will reload. Does not work with browser_mod.navigate. Adjust path to suit.
```yaml
action: browser_mod.javascript
data:
  code: |
    window.location = '/?conversation=1'
```
