### ISSUE TITLE
Navigation triggered multiple times for popup and is not popped after dismiss

### ISSUE THREAD

**Issue by MauriceNino** [thomasloven/hass-browser_mod#539]
My Home Assistant version: 2023.2.3

**What I am doing:**
Creating a popup for an entity in a subview.

**What I expected to happen:**
When I navigate into a subview, then trigger a popup, I want to navigate back with a single click.

**What happened instead:**
I need to click multiple times.

**Minimal** steps to reproduce:

1. I navigate into a subview
2. I open the popup
3. I dismiss the popup
4. I need to click the back button 3x to go out of the subview

```yaml
type: vertical-stack
cards:
  - type: custom:mushroom-light-card
    entity: light.some_light
    hold_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.popup
        data:
          dismissable: true
          content:
            type: custom:mushroom-light-card
            entity: light.some_light
```

**Error messages from the browser console:**

```
BROWSER_MOD 2.2.0 IS INSTALLED

// ... (just mod install messages, no errors, no warnings, ..)
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
