### ISSUE TITLE
Navigate pages in a popup

### ISSUE THREAD

**Issue by Veuchez** [thomasloven/hass-browser_mod#540]
Can I open and navigate a page in a popup?
I would like to open the "/config" page in a popup.
Thank you!

**Comment by Jbautista13** [comment]
You could try using the popup service call with an iframe card, the iOS companion app may or may not have trouble with the card though, it's a bug that's been around for a while and never fixed.

**Comment by Veuchez** [comment]
Already tried, I was asking for this feature precisely because "iframe" doesn't work on the android and iOS app...

**Comment by dcapslock** [comment]
This would only work in an iFrame, and even then you get the Header and Sidebars, so unless you are hiding them it's not a good outcome.

Having Browser Mod manage a config screen in a popup is out of scope so that won't be an option either.

Below is an interesting idea to provide for a way to go to any page, but have a Toast with a Return button. This uses custom:button-card to be able to get the current location from javascript. 

The only caveat with this is if what you are doing generates a new Toast message.

```yaml
show_name: true
show_icon: true
type: custom:button-card
name: Config Page
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.sequence
    data:
      browser_id: THIS
      sequence:
        - service: browser_mod.navigate
          data:
            path: /config/dashboard
        - service: browser_mod.notification
          data:
            duration: -1
            message: Viewing Config Page
            dismissable: true
            action_text: Return
            action:
              - service: browser_mod.navigate
                data:
                  browser_id: THIS
                  path: |
                    [[[
                       return(window.location.pathname);
                    ]]]

```
