### ISSUE TITLE
Tap action with confirmation don't work in browser_mod popup

### ISSUE THREAD

**Issue by timn** [thomasloven/hass-browser_mod#545]
My Home Assistant version: 2023.2.5

**What I am doing:**
In browser_mod popup click on button with confirmation set.

**What I expected to happen:**
Confirmation should popup and allow me to confirm.

**What happened instead:**
Button has no function, no dialog, button action not triggered.

**Minimal** steps to reproduce:
Add browser_mod popup with button with confirmation.

```yaml
# The least amount of code or steps possible to reproduce my error
  - type: state-icon
    entity: <some entity>
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.popup
        data:
          title: Dialog
          content:
            type: button
            entity: switch.X
            tap_action:
              action: call-service
              service: script.turn_on
              data:
                entity_id: script.my_script
              confirmation:
                text: Really?
```

**Error messages from the browser console:**
None

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
