### ISSUE TITLE
History Back after popup

### ISSUE THREAD

**Issue by maxalbani** [thomasloven/hass-browser_mod#546]
Hi,

In my dashboard every page has a button to navigate back using javascript code: history.back().

Unfortunately after opening a popup with browser_mod the current page is duplicated in the history, and two taps are needed to return to the previous page.

Tips to fix?
Thank you!

**Comment by redlefloh** [comment]
@maxalbani sorry to hijack your thread, but could you share your code for the back button? I am trying a browser back button as well, but for some reason the code below actually does not take me back? Thanks!

```
name: Browser Back
type: custom:button-card
color_type: card
tap_action:
  action: call-service
  service: browser_mod.javascript
  service_data:
    code: history.back();
    browser_id: THIS
color: rgba(26, 40, 55, 0.5)
icon: mdi:arrow-left-bold-box
styles:
  card:
    - height: 100px
    - width: 100px
  name:
    - font-size: 14px
    - font-weight: bold
```

**Comment by modo1302** [comment]
> Hi,
> 
> In my dashboard every page has a button to navigate back using javascript code: history.back().
> 
> Unfortunately after opening a popup with browser_mod the current page is duplicated in the history, and two taps are needed to return to the previous page.
> 
> Tips to fix? Thank you!

Same here! Bump!

**Comment by henriklund** [comment]
This problem also exists if you navigate to a subview in HA.
- include  a popup in a subview
- navigate to the subview page
- trigger a popup
- clicking the subview 'back' button (top left corner) will not work the first time.

I have noticed that triggering a popup once results in three clicks on back being necessary, 2x popup -> 5 clicks, 3x popup -> 7 clicks and so forth.

**Comment by henriklund** [comment]
I have found that adding a _dismiss_action_ seems to be working in my case:

```
        tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              title: 'TEST'
              dismiss_action:
                service: browser_mod.javascript
                data:
                  code: window.history.back()
              content:
                type: {some type}
```
