### ISSUE TITLE
browser_mod.more_info under browser_mod.popup

### ISSUE THREAD

**Issue by Veuchez** [thomasloven/hass-browser_mod#548]
My Home Assistant version: 2023.3.1

**What I am doing:**
In a popup window I have a button that opens browser_mod.more_info for me.
I would like Browser_mod.more_info to open in front of the popup and instead it opens behind the below

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error
type: custom:button-card
size: 60%
icon: |
  [[[
    if (states['cover.tapparella_porta_cucina'].state == 'open') return 'mdi:window-shutter-open'
    else return 'mdi:window-shutter'
  ]]]
styles:
  icon:
    - color: |
        [[[
          if (states['cover.tapparella_porta_cucina'].state == 'open') return 'rgb(70, 130, 180)'
          else return 'grey'
        ]]]
show_name: false
show_state: false
tap_action:
  action: fire-dom-event
  browser_mod:
    blocking: true
    service: browser_mod.popup
    data:
      card_mod:
        style:
          ha-dialog$: |
            .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
              #width:100%;
              box-shadow:none;
              border-radius: 0px;
              border: 0px !important;
              background: none;
            }
      content:
        type: custom:vertical-stack-in-card
        style: |
          ha-card {
            border-radius: 20px 20px 20px 20px!important;
            box-shadow: none !important;
            background: white !important;
            #margin: 10px 10px 10px 10px;
            transition: none;
            border: 1px solid grey;
            width: 100% !important;
          }
        cards:
          - type: custom:vertical-stack-in-card
            style: |
              ha-card {
                background: none !important;
                transition: none;
                border: 0px;
                #height: 470px !important;
                margin: 0px 8px 0px 9px !important;
              }
            cards:
              - type: conditional
                conditions:
                  - entity: automation.alza_tapparelle_programma_1
                    state: 'on'
                card:
                  type: custom:layout-card
                  layout_type: grid
                  layout_options:
                    grid-template-columns: 15% 16% 25% 24% 20%
                    grid-template-rows: 42px
                    margin: 0px
                  cards:
                    - type: markdown
                      content: 'ALZA:'
                      style: |
                        ha-card {
                          height: 26px !important;
                          min-width: 80px !important;
                          #margin-top: -5px;
                          box-shadow: 0px 0px;
                          background: none !important;
                          border: 0px;
                        }
                        ha-markdown {
                          padding: 5px !important;
                          font-size: 14px
                        }
                    - type: custom:button-card
                      style: |
                        ha-card {
                          height: 25px !important;
                          width: 50px !important;
                          margin-top: 2.5px !important;
                          transition: none;
                          box-shadow: 2px 2px 9px 0px Gray !important;
                          border-radius: 5px 5px 5px 5px!important;
                          background: none !important;
                        }
                      size: 30%
                      styles:
                        card:
                          - font-size: 14px
                        icon:
                          - color: grey
                      entity: input_datetime.alza_tapparelle_programma_1
                      tap_action:
                        action: fire-dom-event
                        browser_mod:
                          blocking: true
                          service: browser_mod.more_info
                          data:
                            entity: input_datetime.alza_tapparelle_programma_1


# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [ ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [ ] Have made sure I am using the latest version of the plugin.

- [ ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
