### ISSUE TITLE
browser_mod.more_info not working

### ISSUE THREAD

**Issue by superpower10** [thomasloven/hass-browser_mod#550]
### Wanted to try browser_mod.more_info under Developer->Services but button for running script is gray and can't be pressed:

![2023-03-09_07h39_03](https://user-images.githubusercontent.com/20533966/223941217-8d54f11a-191b-43ac-b61e-8e010d2ce0a4.jpg)

### Here is the YAML (after pressing change to YAML-Mode). But the same thing:

![2023-03-09_07h39_16](https://user-images.githubusercontent.com/20533966/223941231-43868b50-8b28-44b0-8acf-738f461b8717.jpg)

### I also tried it in Lovelace on a card but nothing happens there either:
```
tap_action: call-service
service: browser_mod.more_info
service_data:
  entity_id: light.nachttisch
```

### And I tried it like this:
```
tap_action: call-service
service: browser_mod.more_info
service_data:
  entity_id: light.nachttisch
  deviceID:
     - this
```

### My System:
```
Home Assistant 2023.3.2
Supervisor 2023.03.1 
Operating System 9.5
Frontend 20230306.0 - latest 
```

**Comment by antonio1475** [comment]
You're using it wrong, I was too. The correct way is within a fire-dom-event, as explained [here](https://github.com/thomasloven/hass-browser_mod/blob/master/documentation/services.md#:~:text=To%20call%20a%20service%20from%20a%20dashboard%20use%20the%20call%2Dservice%20action%20or%20the%20special%20action%20fire%2Ddom%2Devent%3A)

Example:
```
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.more_info
    data:
      entity: sensor.terraza_humidity
```
