### ISSUE TITLE
Please allow changing more theme styles, don't hardcode to primary-color (timeout progress bar)

### ISSUE THREAD

**Issue by ASNNetworks** [thomasloven/hass-browser_mod#553]
I use a white (#F7F7F7) color as primary-color, since this gives me a menubar and background that looks clean. The mobile app uses this color as the color for the menubar which I want to be the same as my background, so it gives a cleaner look. Also browsers like Edge use this color for the menubar of the browser.

The issue is that some projects hardcode stuff to 'primary-color'. The issue is that this makes them invisible in my setup, since I also use a white background. 

In this case the browser_mod popup has a timeout option, with a progress bar. It's nearly invisible in my setup, since it's white, like my backround of the popup. A very easy solution is that I can color the progress bar of the timeout myself to any color.

![image](https://user-images.githubusercontent.com/54230480/226110807-bc251d9e-aa36-44f9-89ce-cbe5facf73fb.png)

Like in here, I would like to just decide myself what color I want the progress bar to be. In my case it's invisible, since it uses the primary-color, which is the same color as my popup header.

**Comment by ASNNetworks** [comment]
Easily fixable with:

```
action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: Purifier
    timeout: 300000
    style: |
      --primary-color: ENTER COLOR
```
