### ISSUE TITLE
Popups with Buttons in Grids are empty

### ISSUE THREAD

**Issue by henessy31** [thomasloven/hass-browser_mod#568]
My Home Assistant version: 2023.4.1

**What I am doing:**
I updated to HA 2023.4(.1)

**What I expected to happen:**
Pop Ups should be displayed.

**What happened instead:**
Pop Ups containing a Grid with Buttons is showing nothing

**Minimal** steps to reproduce:
I just updated.

```yaml
square: true
columns: 4
type: grid
cards:
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.gruppe_heimkino_switch
    name: Heimkino
    icon: mdi:power-plug
    theme: minimalist-mobile
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by Anilm3** [comment]
Same here, I couldn't see any related logs either.

**Comment by pico1881** [comment]
Same problem for me after 2023.4 update

**Comment by Anilm3** [comment]
Digging a bit deeper, I can see some exceptions in chrome when I open the popup, the exceptions don't show up in a different dashboard I have with the same buttons but without browser-mod:

```
hui-button-card.ts:87 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'switch.tv_remote')
    at i.transformer (hui-button-card.ts:87:37)
    at i.set [as _stateObj] (transform.ts:43:52)
    at transform.ts:79:20
    at Set.forEach (<anonymous>)
    at r.willUpdate (transform.ts:77:18)
    at i.performUpdate (reactive-element.ts:1329:14)
    at i.scheduleUpdate (reactive-element.ts:1263:17)
    at i._$Ej (reactive-element.ts:1235:25)

**Comment by 60bobo60** [comment]
I noticed that only the popups related to the "type: light" are displayed but not the "type: button"

**Comment by danielyc** [comment]
Having the same issue with the button cards. The problem only occurs if there is an entity specified in the button.

Just specify a tap action with a service call and don't specify an entity within the button as a workaround!

**Comment by Sebaem80** [comment]
the same phenomenon has been happening to me since the update to 2023.4... almost all popups no longer work or nothing happens with the tap action.

In the upper part of my dashboard are several chips with auto-entities in the popups. these continue to work.

```
     action: fire-dom-event
      browser_mod:
        service: browser_mod.popup
        data:
          title: Welche Lichter sind aktuell an ?
          content:
            type: custom:auto-entities
            filter:
              include:
                - domain: light
                  state: 'on'
              exclude:
                - domain: light
                  attributes:
                    type: browser_mod
                - entity_id: light.alle_lichter
            card:
              type: entities
              show_header_toggle: false
```

The other popups on my dashboard unfortunately no longer…
The following is an example that worked until the update...

```show_name: true
show_icon: true
type: button
icon: phu:nuki
tap_action:
  action: call-service
  service: browser_mod.popup
  data:
    title: Was möchtest Du ?
    left_button: Haustür Öffnen ?
    right_button: Haustür abschließen ?
    right_button_action:
      service: lock.lock
      data:
        entity_id: lock.nuki_emde_home_lock
    left_button_action:
      service: lock.open
      data:
        entity_id: lock.nuki_emde_home_lock
theme: ios-dark-mode-blue-red

```

**Comment by 60bobo60** [comment]
> Having the same issue with the button cards. The problem only occurs if there is an entity specified in the button.
> 
> Just specify a tap action with a service call and don't specify an entity within the button as a workaround!

I try thanks

**Comment by kksligh** [comment]
I have a similar issue - reported it here - https://github.com/home-assistant/core/issues/91124

**Comment by kksligh** [comment]
I'm using tile cards instead of button cards in my grid pop outs as a workaround if anyone is needing something. The problem is definitely when an entity is assigned to the button. If you want I show states with your buttons, tile or mushroom cards can be used as alternatives

**Comment by JoostAB** [comment]
Same here...
The shadow-root of button cards just stays empty in popup:
![image](https://user-images.githubusercontent.com/16137715/231083642-07992fcd-c17b-4166-ba35-766d3bb25617.png)

**Comment by Phoenix-DH** [comment]
Same issue here, buttons are not shown anymore.
Will try the workarrounds as a test.

**Comment by theone11** [comment]
I also have the button card missing problem in popups - still missing in 2023.4.3

Using the Tile Card workarround for now - would prefer the Button Card.

**Comment by 60bobo60** [comment]
I restored to Core 2023.3.6 and now everything still works, I will wait to update when the problem is solved

**Comment by joeyjojo747** [comment]
Big issue for me with lots of pop-up cards with buttons missing in grids.
As a work around I'm using https://github.com/custom-cards/button-card.
Changing from type: button_to_type: custom:button-card_is a quick workaround.

**Comment by artipixel** [comment]
Same error. Temp workaround worked with custom button card.
If you are calling a service on click or sending data to a service, you will need to change service entity_id to be configured under service_data like this:
```
type: custom:button-card
  name: 'Button'
  show_name: true
  tap_action:
      action: call-service
      service: YOUR_SERVICE
      service_data:
        timer_minutes: 10 # Example data parameter
        entity_id: YOUR_ENTITY # i.e. switch.boiler
```

**Comment by slothking87** [comment]
I have the same problem. I use bootstrap grids on my pop ups and any button that is not a custom buttoncard doesnt display for some reason. 
Ever since updating to 2023.04 I have had the problem. Downgrading fixes it

**Comment by scstraus** [comment]
Same error with button cards:

```
  - type: custom:popup-card
    entity: sensor.trash_display
    title: "Trash Needs Taking Out"
    card:
      type: button
      name: I took it out!
      tap_action:
        action: call-service
        service: input_boolean.turn_off
        service_data:
          entity_id: input_boolean.trash_needs_taking_out
      entity: sensor.trash_display
```
