### ISSUE TITLE
Date selector does not work in a popup

### ISSUE THREAD

**Issue by kangaroomadman** [thomasloven/hass-browser_mod#569]
My Home Assistant version: 2023.4.1

**What I am doing:**
Trying to use a date selector in a pop up. 

**What I expected to happen:**
When clicking the date selector inside the popup, I expect the calendar input to be shown so that a date can be selected. 

**What happened instead:**
No calendar input is shown and therefore a date cannot be input. 

**Minimal** steps to reproduce:
Use the following YAML in Developer Tools / Services:

```yaml
service: browser_mod.popup
data:
  title: Date Selector
  content:
    - name: date
      label: Date
      selector:
        date:
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
