### ISSUE TITLE
Thermostat gets broken in popup

### ISSUE THREAD

**Issue by HeimdallMidgard** [thomasloven/hass-browser_mod#57]
Hello,

unfort. inside the popup the thermostat card gets broken. I don't know if this is a problem of the thermostat card or the popup card. If I keep the popup open for a while it starts working and is loading up the data correctly and it works normal. If I can help anyhow with providing more information let me know.

Thank your very much

![popup](https://user-images.githubusercontent.com/50184150/74469903-cdee4d00-4e9d-11ea-9d40-df21b3781619.PNG)

```
      - type: service-button
        title: Heizung
        style:
          top:  31%
          left: 6%
        service: browser_mod.popup
        service_data:
          title: Heizung Schlafzimmer
          card:
                  type: thermostat
                  entity: climate.schlafzimmer
```

**Comment by jazzyisj** [comment]
Maybe a related issue.   Thermostat actually functions state and target temperature are missing in the popup.  No css used in either.

```
popup_cards:
  sensor.upstairs_thermostat_temperature:
    title: Upstairs Thermostat
    card:
      type: thermostat
      entity: climate.upstairs_thermostat
```


Card on page
![image](https://user-images.githubusercontent.com/44064559/75602138-6dabfd80-5a90-11ea-8fcc-91dde9acf8cb.png)

Thermostat Card in popup.
![image](https://user-images.githubusercontent.com/44064559/75602150-82889100-5a90-11ea-9c80-6a8884036d27.png)
