### ISSUE TITLE
Scroll bars after update 2023.4

### ISSUE THREAD

**Issue by braticks** [thomasloven/hass-browser_mod#574]
After update 2023.4 I have scroll bars on the side and bottom.

**Comment by guilhermecespedes** [comment]
I am facing the same problem, did you find any solution?

**Comment by braticks** [comment]
No. Staying on 2023.3 version

**Comment by jack5mikemotown** [comment]
Temporary fix for this would likely be `height: auto` somewhere in the css. Possibly `width: auto` too. Haven't tried fixing this issue with browser my specifically but it has been a temporary fix with other custom cards so I'd imagine it would work here too.

Starting point for anyone who wants to mess around and try to fix it themselves

**Comment by twister36** [comment]
I am too see this issue since the last upgrade:
![image](https://github.com/thomasloven/hass-browser_mod/assets/114322877/c4bfa3b3-1a60-4e46-98e9-e7fa7763d6fb)

**Comment by ASNNetworks** [comment]
Don't have this issue on 2023.4.x, but it is present on 2023.5.2. Reverted back to 2023.4.6 for now, sadly too many frontend changes I need to address.

**Comment by KGS501** [comment]
In my case I was able to fix the problem temporarily by adding the following code to my popup

```yaml
card_mod:
   style:
     ha-dialog$: |
         div.mdc-dialog div.mdc-dialog__surface {
            padding: 20px;
         }
```
