### ISSUE TITLE
more-info service not working with alias

### ISSUE THREAD

**Issue by tommyjlong** [thomasloven/hass-browser_mod#58]
config.yaml:
```
browser_mod:
  devices:
    abdd022c_012f3ca9:
      name: Lenovo_Chrome
```
automation that does NOT work:
```
    - service: browser_mod.more_info
        data:
          entity_id: camera.front_yard_vivotek
          deviceID:
            - lenovo_chrome
```
automation that does work
```
      - service: browser_mod.more_info
        data:
          entity_id: camera.front_yard_vivotek
          deviceID:
           #- lenovo_chrome
            - abdd022c-012f3ca9

```
Testing the alias:
Goto Developers Tool->States, click on the following to get a popup
`light.lenovo_chrome`
Turn switch off =>black screen behind popup
Turn switch on => restores screen.

I also changed the alias configuration, replacing the device ID with "_" underbar to "-" dash, but no difference.
