### ISSUE TITLE
browser_mod.javascript: add callback support

### ISSUE THREAD

**Issue by jdtechsol** [thomasloven/hass-browser_mod#581]
process data resulting from browser_mod.javascript's execution (not at all going to be surprised if I get a "no")

**Comment by thomasloven** [comment]
Why can't you do that in the javascript function yourself?

**Comment by jdtechsol** [comment]
Sorry for the late response but I only get to tinker with HASS every so often. 

The point is to be able to get real-time information which is not possible (unless I am missing something).

I mean, I could do this in lovelace:

```
  tap_action:
    action: fire-dom-event
    browser_mod:
      service: browser_mod.sequence
      data:
        sequence:
          - service: var.set
            data:
              entity_id: var.username
              value: ""
          - service: browser_mod.javascript
            data:
              code: hass.callService('var', 'set', {entity_id:"var.username",value:hass.user.name});
          - service: script.get_username
```
and have get_username wait for the value of var.username to populate.

Setting aside that, while unlikely, overlapping requests could happen, wouldn't it be easier if the value of hass.user.name was returned from browser_mod.javascript which could then be used as data in the next service call or maybe even
```
          - service: browser_mod.javascript
            data:
              code: hass.callService('var', 'set', {entity_id:"var.username",value:hass.user.name});
              handler: script.do_stuff_with_username
```
where the handler is sent the result as data?

if this comes off a bit incoherent, I apologize, I just wokr up :)

**Comment by dcapslock** [comment]
@jdtechsol @smartqasa Taking some time to review some older requests.

Looking into the request to return data from javascript, the question arises as to what would be returned and when to return it? Javascript could be many lines long and could indeed listen for DOM events and wish to send back multiple results.

So I recommend the best javascript 'handler' is to fire a custom hass event which can be done using `hass.callApi`

e.g. ```browser_mod.hass.callApi('POST','events/my_username_event',{username:window.browser_mod.hass.user.name})```

Then you can listen in an automation trigger

```yaml
alias: My Username Automation
description: ""
triggers:
  - trigger: event
    event_type: my_username_event
    variables:
      username: "{{ trigger.event.data.username }}"
conditions: []
actions: []
mode: single

```

Then looking at _Changed Variables_ in Automation Trace you will get

```yaml
this:
  entity_id: automation.my_username_automation
  state: 'on'
  attributes:
    id: '1748821780012'
    last_triggered: '2025-06-02T01:08:27.488133+00:00'
    mode: single
    current: 0
    friendly_name: My Username Automation
  last_changed: '2025-06-02T01:09:43.862471+00:00'
  last_reported: '2025-06-02T01:09:43.862471+00:00'
  last_updated: '2025-06-02T01:09:43.862471+00:00'
  context:
    id: 01JWQ2ZWSP3RDCT71WYG2M3P77
    parent_id: null
    user_id: null
trigger:
  id: '0'
  idx: '0'
  alias: null
  platform: event
  event:
    event_type: my_username_event
    data:
      username: dev_name
    origin: REMOTE
    time_fired: '2025-06-02T01:09:46.184016+00:00'
    context:
      id: 01JWQ2ZZ27DTDXC5PHB9MFJT3H
      parent_id: null
      user_id: 1283f038bd70410f98eb21132060fbac
  description: event 'my_username_event'
username: dev_name
```
