### ISSUE TITLE
Can I get the browser_id of the current browser in a template?

### ISSUE THREAD

**Issue by JelkeH** [thomasloven/hass-browser_mod#582]
I would like to be able to control the brightness of the current browser by a slider using the `light.<<browser_id>>_screen` entity.
Something like:

```
type: entities
entities:
  - type: custom:slider-entity-row
    entity: light.{{browser_id}}_screen
```

Would something like this be possible? I hope the get this working, but currently I'm stuck at being able to retrieve the current `browser_id`

**Comment by jdtechsol** [comment]
+1 this

**Comment by ViRuSTriNiTy** [comment]
https://github.com/thomasloven/hass-browser_mod/issues/631#issuecomment-1791956956 might be a solution

**Comment by dcapslock** [comment]
@JelkeH what you would be able to do is use buttons that user fire-dom-event to browser_mod, with `browser_id: THIS` which then calls a script to set the value of the light. If you are still after a solution I can put together a small example. You won't be able to get a native slider, so would need to set the increments to something suitable, say +/- 10% per button press.

**Comment by dcapslock** [comment]
@jdtechsol @JelkeH I have spent some tome looking at options. The best option I have found is using auto-entities and an experimental options feature `eval_js` that allows to adjust options passed to the card us javascript, including overwriting the `entity` passed to the card. So you can use auto-entities with any entity, and then overwrite to pick the relevant entity from `window.browser_mod.browserEntities`. I have tested using auto entities 1.16.1.

#### Example

```yaml
type: custom:auto-entities
filter:
  include:
    - entity_id: light.bed_light
      options:
        eval_js: true
        entity: ${window.browser_mod.browserEntities.screen}
        type: custom:slider-entity-row
  exclude: []
```

#### Result

Same Dashboard showing on different browsers.

<img width="1036" alt="Image" src="https://github.com/user-attachments/assets/153d9e58-06df-48a5-8677-138ceaea2504" />

A Browser Mod way of doing this is not possible as entities exist in the core and frontend, so while some magic could be done at the front end as the browser is known, it would get complicated when it comes to managing in the core.
