### ISSUE TITLE
Improvement on pop up behavior on "small-ish" displays

### ISSUE THREAD

**Issue by acateon** [thomasloven/hass-browser_mod#59]
Im using a official raspberry pi display with 800 x 480px resolution and the popup behavior is a bit annoying. I don't know if this behavior is due to browser_mod or the Lovelace framework itself but anyhow:

When the height is sub 500px the popup is rendered in full width (not what I want), but as soon as height is increased to 501 its rendered as a centered frame.

Is it posible via card_mod to force center rendering regardless of resolution?
Is it also possible to disable the title bar all together and only rely on clicking outside of the box to close the popup?

Se exempels below:

![popup2](https://user-images.githubusercontent.com/14361705/74920939-3f158f00-53cd-11ea-8e7e-f10f03cd1dea.png)
![popup1](https://user-images.githubusercontent.com/14361705/74920945-4341ac80-53cd-11ea-9399-dc1cea37dcdc.png)

**Comment by jazzyisj** [comment]
> Is it also possible to disable the title bar all together and only rely on clicking outside of the box to close the popup?

As per browser_mod docs.

> The optional parameter auto_close: true will make the popup close automatically when the mouse is moved or a key is pressed on the keyboard. This also removes the header bar.

**Comment by acateon** [comment]
> > Is it also possible to disable the title bar all together and only rely on clicking outside of the box to close the popup?
> 
> As per browser_mod docs.
> 
> > The optional parameter auto_close: true will make the popup close automatically when the mouse is moved or a key is pressed on the keyboard. This also removes the header bar.

Thanks but I'm aware of the function but that doesn't play nice with a touch-panel if the first input wakes the screen. Then the popup is gone at the same time as the touch screen registers input...

**Comment by gamer06** [comment]
Hi my friend @acateon do you solve the problem?
I have the same but with popup image of my camera... the popup is in fullscreen.

**Comment by acateon** [comment]
> Hi my friend @acateon do you solve the problem?
> I have the same but with popup image of my camera... the popup is in fullscreen.

Under view modify the general poup as follow, change to fit the camera card you're using instead of more info.

```
    popup_cards:
      alarm_control_panel.larm:
        title: " "
        card:
          type: alarm-panel
          entity: alarm_control_panel.larm
        style:
          position: fixed
          z-index: 999
          top: 0
          left: 0
          height: 10%
          width: 10%
          max-width: 370px
          display: block
          align-items: center
          justify-content: center
          background: rgba(0, 0, 0, 0.16)
          flex-direction: column
          margin-left: 27%
```
And the card is in my case called by:

```
                        tap_action:
                          action: more-info
                          entity: alarm_control_panel.larm
```
Its a work in progress since not all css attributes are respected..

**Comment by gamer06** [comment]
Could you share the card when you put the tap_action? I'm not getting there...

**Comment by acateon** [comment]
```
                      - entity: alarm_control_panel.larm
                        icon: mdi:shield-home
                        cardOptions:
                          states:
                            - armed_home
                        offStates:
                          - "disarmed"
                          - "pending"
                        tap_action:
                          action: more-info
                          entity: alarm_control_panel.larm
```
