### ISSUE TITLE
Date, nor datetime selector not working within popups.

### ISSUE THREAD

**Issue by CptBananaPeel** [thomasloven/hass-browser_mod#593]
My Home Assistant version: 2023.6.3

**What I am doing:**
Trying to make a popup that add a calendar event, for which i need, 2 text inputs and a date input.

**What I expected to happen:**
when using the date selector within the popup, i expect to click on the selector and a 3rd popup appears, to input the date.

**What happened instead:**
When clikcing nothing additional appears

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error
service: browser_mod.popup      
data:
  title: new calendar event
  right_button: Create
  right_button_action: 
  content:
    - name: start_date
      selector:
        date: 
```

**Error messages from the browser console:**
Nothing that i can see.

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

Thanks a lot for this incredible addon for HA! 
Customizing the more-info is a game changer!
