### ISSUE TITLE
Slider missing from Mushroom Fan Card when using Browser Mod PopUp window

### ISSUE THREAD

**Issue by z06Drew** [thomasloven/hass-browser_mod#602]
My Home Assistant version: 2023-07-01

**What I am doing:**
Displaying a Mushroom Fan Card on a Browser Mod PopUp window

**What I expected to happen:**
Slider control to be visible and useable

**What happened instead:**
Slider control is not visible and does nothing when clicking where it normally would display.  The same card looks and works as expected when not placed on a browser mod popup window

**Minimal** steps to reproduce:
Use browser mod to create a popup that has a mushroom fan control card.

```yaml
# The least amount of code or steps possible to reproduce my error
type: button
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      content:
        type: custom:mushroom-fan-card
        entity: fan.family_room_fan

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
