### ISSUE TITLE
Popups "style:" in 2.3.0 doesnt works

### ISSUE THREAD

**Issue by chertvl** [thomasloven/hass-browser_mod#607]
My Home Assistant version: 2023.7.2

**What I am doing:**
Updated from 2.2.2 to 2.3.0 and "styles:" is broken
Same like this guy:
https://community.home-assistant.io/t/browser-mod-turn-your-browser-into-a-controllable-device-and-a-media-player/123806/2139?u=chertvl 

**What I expected to happen:**
I want back transparent popups background ;)

**What happened instead:**
Popups shows --surface color instead of --popup-background-color

**Minimal** steps to reproduce:
Look at yaml

```yaml
# The least amount of code or steps possible to reproduce my error

      tap_action:
        action: fire-dom-event
        browser_mod:
          service: browser_mod.popup
          data:
            style: |
              --popup-background-color: transparent;
            content:
              type: custom:myrandomperfectcards
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
