### ISSUE TITLE
No longer full screen pop-ups in 2.3.0

### ISSUE THREAD

**Issue by Daniel-dev22** [thomasloven/hass-browser_mod#608]
In 2.3.0 browser mod pop-ups are no longer full screen.

Here's my configuration below that I use for all of my cameras. Previously the pop-up was a full screen video now it's a small portion.

```yaml
show_state: false
show_name: false
camera_view: auto
type: picture-entity
entity: camera.outdoor_1
camera_image: camera.outdoor_1
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      size: fullscreen
      style: |
        --popup-background-color: black
      content:
        type: custom:webrtc-camera
        mode: mse
        url: outdoor_1
        intersection: 0.75
double_tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      size: fullscreen
      style: |
        --popup-background-color: black
      content:
        type: custom:frigate-card
        cameras:
          - camera_entity: camera.outdoor_1
        view:
          default: clips
        dimensions:
          aspect_ratio_mode: unconstrained
        media_viewer:
          auto_unmute: all
          controls:
            next_previous:
              style: none
        overrides:
          - conditions:
              mediaLoaded: true
            overrides:
              menu:
                style: hidden
        menu:
          style: overlay
          button_size: 50
          buttons:
            image:
              enabled: true
            live:
              enabled: false
            clips:
              enabled: true
            recordings:
              enabled: true
card_mod:
  style: |
    camera {
      width: 100px;
      height: 50px;
      object-fit: fill;
    }
```

Browser mod 2.3.0
![Screenshot_20230715_181202_Home Assistant](https://github.com/thomasloven/hass-browser_mod/assets/47092714/71856d11-3541-46f9-9c69-0e6c3485962f)

Browser Mod 2.2.2 is full screen.
![Screenshot_20230715_181301_Home Assistant](https://github.com/thomasloven/hass-browser_mod/assets/47092714/ca1a1972-af13-44ce-aaa2-3e28d194b992)
