### ISSUE TITLE
Issues with 0.106

### ISSUE THREAD

**Issue by VDRainer** [thomasloven/hass-browser_mod#61]
Not sure where to report this, but errors are shown from browser_mod.

I'm using browser_mod to show different popups at a picture-entity
```
          - type: picture-entity
            entity: camera.warnungen
            show_name: false
            show_state: false
            tap_action:
              action: call-service
              service: browser_mod.popup
              service_data:
                title: "DWD Wetterwarnung \U000026A0"
                style:
                  border-radius: 15px
                  width: 600px
                card: 
                  type: markdown
                  content: |
                    TEST
                deviceID:
                  - this
            hold_action:
              action: call-service
              service: browser_mod.command
              service_data:
                command: more-info
                entity_id: camera.warnungen
                #large: true
                deviceID:
                  - this
            double_tap_action:
              action: call-service
              service: browser_mod.command
              service_data:
                command: more-info
                entity_id: sensor.dwd_weather_warnings_current_warning_level
                #large: true
                deviceID:
                  - this
```
Since 0.106.0b any of the tap actions doesn't work
![Auswahl_281](https://user-images.githubusercontent.com/26381449/75090002-b0387c00-555e-11ea-95b1-a1b7c6b2284e.png)
For testing i tried an entity-button instead of the picture-entity, same behavior.
```
          - type: entity-button
            entity: sensor.dwd_warn_count
          # - type: picture-entity
          #   entity: camera.warnungen
          #   show_name: false
          #   show_state: false
```
After replacing the entity-button with a custom:button card,
```
          - type: custom:button-card
            entity: sensor.dwd_warn_count
          # - type: picture-entity
```
the browser_mod errors are gone, but the popup shows an error about the markdown card.
![Auswahl_282](https://user-images.githubusercontent.com/26381449/75090082-ad8a5680-555f-11ea-9067-025295123273.png)
hold_action and double_tap_action show the expected more-infos from the camera and the sensor.

After leaving the console, changing to another tab and go back, the popup shows the the expected markdown.
![Auswahl_285](https://user-images.githubusercontent.com/26381449/75090159-62bd0e80-5560-11ea-9bb6-9c718f9e506d.png)

Browser_mod reinstalled multiple times, card-tools and card mod installed manually.
```
  - url: /local/card-tools.js?v=2.1.1
    type: module
#  - url: /community_plugin/lovelace-card-tools/card-tools.js
#    type: module
  - url: /local/card-mod.js?v=13
    type: module
  # - url: /community_plugin/lovelace-card-mod/card-mod.js
  #   type: module
```
