### ISSUE TITLE
[Bug]: Impossible action button on browser_mod with mushroom

### ISSUE THREAD

**Issue by S1M8N** [thomasloven/hass-browser_mod#611]
My Home Assistant version: 2023.07.1

**Minimal** steps to reproduce:
1. Create browser_mod popup in lovelace
2. Add Mushroom card
3. Clic for action -> nothing happens

**What I expected to happen:**
nothing...

Example code :
```yaml
type: custom:mushroom-template-card
primary: Record
secondary: ''
icon: mdi:file-video
badge_icon: ''
icon_color: blue
layout: horizontal
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      size: normal
      content:
        type: vertical-stack
        cards:
          - type: custom:mushroom-select-card
            entity: input_select.select_media_cameras
            name: Select cameras
```
- Browser: Opera LVL5 (core: 100.0.4815.44)
- HA Version: 2023.07.1
- Mushroom: 3.0.3
- Browser_mod: 2.3.0

---

- [ x ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [ x ] Have made sure I am using the latest version of the plugin.

- [ x ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ x ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
