### ISSUE TITLE
Question: Perform action only on current browser

### ISSUE THREAD

**Issue by Phoenix-DH** [thomasloven/hass-browser_mod#613]
Hey,

I created a script which will get loaded when I click a button in the dashboard.
Now I figured out that the navpath will be changed on all devices/browsers.
Is there a possibility to change it only on the current one, without knowing the id?
Or how would that work?

Thank you!

```
  - service: browser_mod.navigate
    data:
      path: /lovelance-floorplan/vacuum_erdgeschoss
```

**Comment by xZetsubou** [comment]
why not use `fire-dom-event` rather then script?
```yaml
tap_action:
  action: 'fire-dom-event'
  browser_mod:
    service: browser_mod.navigate
    data:
      path: /lovelance-floorplan/vacuum_erdgeschoss
```

**Comment by Phoenix-DH** [comment]
Ah ok, thanks for the hint, will try.

**Comment by xZetsubou** [comment]
in case you want to trigger a script and use navigate service as well on the current browser, you can use `sequence` service to call multi services
an example button will call  a script and also will call navigate service:
```yaml
type: button
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.sequence
    data:
      sequence:
      - service: script.my_script
      - service: browser_mod.navigate
        data:
          path: /config

```
