### ISSUE TITLE
Can not click out of popup on iOS app

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/hass-browser_mod#617]
My Home Assistant version: 0.XX.X

**What I am doing:**
opening a markdown popup 

**What I expected to happen:**
have some way of clicking out of the popup

**What happened instead:**

cant click out, not even swipe in another view, can only completely swipe the app out of Phone, and reload

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error
hold_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
#      style: |
 #       --popup-border-radius: 0px;
 #       --popup-padding-x: 0px;
 #       --popup-padding-y: 0px;
 #       --dialog-backdrop-filter: blur(0.8em) brightness(1.2);
 #       --dialog-content-padding: 20px;
      content:
        type: markdown
# Put your code/steps here
```

**Error messages from the browser console:**

no errors
```
// Select everything from the browser console and copy it

// Paste it here
```

![image](https://github.com/thomasloven/hass-browser_mod/assets/33354141/29002245-51c2-4526-a183-31c1ff551531)
---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X ] Have made sure I am using the latest version of the plugin.

- [X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
