### ISSUE TITLE
Cant read properties of the state

### ISSUE THREAD

**Issue by arifroni** [thomasloven/hass-browser_mod#620]
Home Assistant 2023.7.3
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

**What I am doing:**
Using a popup to show some buttons.

**What I expected to happen:**
button lock/name changes with entity state.

**What happened instead:**
popup doesn't show up

**Minimal** steps to reproduce:

```
type: custom:button-card
name: main button
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: title
      content:
        type: custom:button-card
        entity: light.office_group_1
        name: popup button
        tap_action:
          action: more-info
        lock:
          enabled: |
            [[[ 
              return entity.state !== 'on'
            ]]]
          exemptions: []
```

**Error messages from the browser console:**

```
Uncaught ButtonCardJSTemplateError: TypeError: Cannot read properties of undefined (reading 'state') in 'return entity.state !== 'on''
    at ti.eval (eval at _evalTemplate (button-card.js:425:9303), <anonymous>:4:17)
    at ti._evalTemplate (button-card.js:425:9389)
    at ti._getTemplateOrValue (button-card.js:425:9976)
    at button-card.js:547:3887
    at Array.forEach (<anonymous>)
    at n (button-card.js:547:3829)
    at button-card.js:547:3869
    at Array.forEach (<anonymous>)
    at n (button-card.js:547:3829)
    at button-card.js:547:3869
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x ] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
