### ISSUE TITLE
[Help] Popup selector dynamic

### ISSUE THREAD

**Issue by LaBoss** [thomasloven/hass-browser_mod#624]
Hello

I’m trying to create an automatic popup for my buttons that are inputs_selects,

I can get the lists of options like this

```
state_attr('input_select.optioninput', 'options')
```

But I would like to use it in a poupup dynamically, I tried the following way but I don’t see any option.
```

tap_action:
      action: call-service
      service: browser_mod.popup
      service_data:
        title: Escolha uma opção
        card_mod:
          style:
            ha-dialog$: |
              div.mdc-dialog div.mdc-dialog__scrim {
                backdrop-filter: blur(10px);
              }
        right_button: Definir
        right_button_action:
          action: call-service
          service: input_select.select_option
          service_data:
            option: "???"
            entity_id: "[[[ return entity.entity_id; ]]]"
        content:
          - name: params
            label: Options
            selector:
              select:
                multiple: false
                options: >
                  {{ state_attr(entity.entity_id, 'options') }}

```

Any idea how to get this to work?

Thanks

**Comment by xZetsubou** [comment]
You can't use jinja2 templates with `button-card` use JS 
```yaml
[[[ return states[entity.entity_id].attributes.options ]]]
```

**Comment by LaBoss** [comment]
> You can't use jinja2 templates with `button-card` use JS
> 
> ```yaml
> [[[ return entity.attributes.options ]]]
> ```

Thanks its works nicely

![opts](https://github.com/thomasloven/hass-browser_mod/assets/5363187/c4e65d62-a9e6-4d83-a2d4-bfc20bd346d3)

The full code is

 ```
   tap_action:
      action: call-service
      service: browser_mod.popup
      service_data:
        title: Escolha uma opção
        card_mod:
          style:
            ha-dialog$: |
              div.mdc-dialog div.mdc-dialog__scrim {
                backdrop-filter: blur(10px);
              }
        right_button: Definir
        right_button_action:
          action: call-service
          service: input_select.select_option
          data:
            entity_id: "[[[ return entity.entity_id; ]]]"           
        content:
          - name: option
            label: Rooms to clean
            selector:
              select:
                mode: list
                multiple: false
                options: '[[[ return entity.attributes.options ]]]'
```

**Comment by cbass27** [comment]
I know this is closed but hoping you may have a solution to when the 'Definir' button is pressed with no options selected, I get an error "failed to call service input_number/set_value required key not provided @ data['value']" which makes sense as there isn't a value being returned to the service call. Ideally, I would like to select one of the options as a default or even better, return the value from an entity state. Thanks in advance.

**Comment by camels84** [comment]
i'm in the same situation,
i have the button:

```
type: button
name: Select Media Players
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Select Media Players
      right_button: Confirm
      right_button_action:
        service: script.process_selection
        data:
          selected_players: "{{ params }}"
      content:
        - name: params
          label: Select Media Players
          selector:
            select:
              multiple: true
              options: "[[[ return input_select.available_media_players.attributes.options ]]]"
```


can you help me?
