### ISSUE TITLE
 Popup title incorrect font

### ISSUE THREAD

**Issue by MeowRay** [thomasloven/hass-browser_mod#626]
My Home Assistant version: 2023.08

```yaml
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: aaaa
      content:
        type: vertical-stack
        cards:
          - type: custom:button-card
            name: 剩余时间
            template: homekit_timer_states
            entity: timer.p1_kong_diao_ding_shi_qi
            variables:
              unit: 分钟
            show_icon: false
            styles:
              card:
                - width: 564px
                - height: 120px
```

Fonts display incorrectly after updating Homeassistant and browser_mod to latest version
![image](https://github.com/thomasloven/hass-browser_mod/assets/29674595/fd919521-1d10-44ac-9231-e020e071a9ec)

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

---
