### ISSUE TITLE
Option to prevent action button from closing popup

### ISSUE THREAD

**Issue by BackedUpBooty** [thomasloven/hass-browser_mod#627]
I've currently got a basic popup for turning a TV on or off:

```
  - type: state-icon
    entity: script.office_tv_turn_on
    hold_action:
      action: call-service
      service: script.office_tv_on
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.popup
        data:
          style: |
            --dialog-backdrop-filter: blur(0.8em) brightness(1.2);
          size: normal
          title: TV Power Options
          content: Would you like to...
          timeout: 60000
          right_button: Turn TV Off
          right_button_action:
            action: call-service
            service: media_player.turn_off
            data:
              entity_id: media_player.office_tv
          left_button: Turn TV On
          left_button_action:
            action: call-service
            service: script.office_tv_on
```

I have a firestick and the firemote card, which I would like to display in the popup. I'd like to be able to turn the TV on with the popup button but then be able to use the firemote card once the TV is on and the firestick is responding without having to reopen the popup.

I tried adding 
```
          left_button: Turn TV On
          left_button_action:
            action: call-service
            service: script.office_tv_on
            data:
              dismissable: false
```
as a long shot but no joy (unsurprising). 

If I've missed this in the documentation then apologies, but is this possible without removing the popup buttons themselves and adding others as part of a card?
