### ISSUE TITLE
Remove hardcoded padding

### ISSUE THREAD

**Issue by miramo** [thomasloven/hass-browser_mod#628]
My Home Assistant version: **2023.8.2**

**What I am doing:**
I'm trying to get a popup without the hardcoded padding.

**What I expected to happen:**
A popup without padding.

**What happened instead:**
A popup with hardcoded padding.

<img width="2050" alt="image" src="https://github.com/thomasloven/hass-browser_mod/assets/4146892/017588f1-9f8e-4231-98be-1a2ee8cddcf5">

**Minimal** steps to reproduce:

```yaml
action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    size: normal
    style: |
      --popup-min-width: 400px;
      --popup-padding-x: 0px;
      --popup-padding-y: 0px;
      .container {
        padding: 0px !important;
      }
    content:
      type: custom:mini-graph-card
      entities:
        - sensor.average_temperature
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by xZetsubou** [comment]
You can use card_mod to remove it
```yaml
action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    size: normal
    style: |
      --popup-min-width: 400px;
      --popup-padding-x: 0px;
      --popup-padding-y: 0px;
    card_mod:
      style: >
        .container {
            padding: 0px !important;
        }
    content:
      type: custom:mini-graph-card
      entities:
        - sensor.average_temperature
```
Or you can modify your theme with `card_mod` to change padding globally.
```yaml
  card-mod-theme: umu_v1 # my theme name
  card-mod-more-info-yaml: |
    .: |
      ha-dialog > div > div {
        padding: 0% !important;
      }
```
