### ISSUE TITLE
Pop up Media-Browser works on Browser but not on Android and iOS apps

### ISSUE THREAD

**Issue by Christophe-01** [thomasloven/hass-browser_mod#629]
My Home Assistant version: 2023.8.3

**What I am doing:**
Open a popup media-browser

I have test with a simple core picture-card navigate to  url: /media-browser/media_player.tv_salon on iOs, Android Apps and with Chrome, Safari and Edge and all works fine. So is not a HA Core Bug.

**What I expected to happen:**
Open a popup media-browser

**What happened instead:**
Works on all browser (Safari, Edge, Chrome)
Infinity charging on Apps (Android, iOs)

![Browser mod link Bug](https://github.com/thomasloven/hass-browser_mod/assets/111463172/40229dcd-9229-4d29-aca0-655567c4b4f2)

**Minimal** steps to reproduce:
Just test the code above

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
tap_action:
  haptic: heavy
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Vidéothèque
      dismissable: true
      autoclose: false
      hide_header: false
      large: false
      content:
        type: iframe
        url: /media-browser/media_player.tv_salon
        aspect_ratio: 200%
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X ] Have made sure I am using the latest version of the plugin.

- [X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
