### ISSUE TITLE
Popups no longer work in 0.106

### ISSUE THREAD

**Issue by vandalon** [thomasloven/hass-browser_mod#63]
After updating to HA core 0.106, popups no longer work and i'm getting this error in the logs:

```
browser_mod.js:56:274 Uncaught TypeError: Cannot assign to read only property '0' of object '[object Array]'
```

**Comment by ThePicklenat0r** [comment]
I'm having the same issue, and am getting a similar error:

```
Logger: frontend.js.latest.202002204
First occured: February 26, 2020, 9:34:08 PM (20 occurences)
Last logged: 8:16:24 AM

https://[redacted]/browser_mod.js:56:314 Uncaught TypeError: Cannot assign to read only property 'deviceID' of object '#<Object>'
```

**Comment by ercsey** [comment]
Same for me.

```http://ha-address/browser_mod.js:56:274 Uncaught TypeError: Cannot assign to read only property '0' of object '[object Array]'```

**Comment by vandalon** [comment]
In 0.106.1 the error changed to:

`

2020-02-28 10:20:57 ERROR (MainThread) [frontend.js.latest.202002204] https://hass.net.wiebel.nl:8123/browser_mod.js:60:12066 TypeError: Attempted to assign to readonly property.

`

**Comment by jazzyisj** [comment]
Same issue here but would like to note that global popups defined with popup_cards: in ui-lovelace.yaml are still working without error.

**Comment by deluxestyle** [comment]
I'm having the same issue after update to 0.106.2
 If I call the browser_mod.popup with the button entity row it works. If call browser_mod.popup with the normal tap_action I get the error

**Comment by Dielee** [comment]
Hello guys, I have the same error but there is a workaround for me. 
Configure your popup_cards:

```
views:
  - title: Home
    id: Home
    icon: mdi:home
    popup_cards:
      input_boolean.wecker: &wecker
        title: Wecker
        card:
          type: entities
          entities:
            - input_boolean.wecker
            - entity: input_datetime.wecker
              name: Weckzeit
            - entity: input_boolean.wecker_wochenende
              name: Wochenende
            - entity: input_boolean.schlafzimmer_rollo
              icon: mdi:window-open

```

and then leave the tap_action, like this:

```
        - type: glance
          title: Status
          columns: 5
          entities:
              - entity: sensor.waschmaschine_state
                name: Wäsche
              - entity: input_boolean.putzen
                tap_action:
                  action: toggle
              - entity: input_boolean.urlaub
                tap_action:
                  action: toggle
              - entity: input_boolean.wecker

```

Works for me, hope this helps..

**Comment by deluxestyle** [comment]
I‘m using the same workaround with popular cards. Maybe it is not even a workaround. It works very well

**Comment by jazzyisj** [comment]
With some fooling around I have discovered that disabling the deviceID tag allows all popups to work.  Obviously they will open on all devices but all is better than none!

**Comment by esbenlydiksen** [comment]
I have the same problem. Removing the deviceID does not seem to make a difference. Keeping my fingers crossed for a fix.

**Comment by VDRainer** [comment]
Thanks so much!
Can confirm, this works for me too and fixes https://github.com/thomasloven/hass-browser_mod/issues/61.

**Comment by pejotigrek** [comment]
I have the same problem. from 0.106 to 0.106.5 still getting:

`2020-03-05 00:53:57 ERROR (MainThread) [frontend.js.latest.202002205] https://skyn3t.duckdns.org:27/browser_mod.js:60:314 Uncaught TypeError: Cannot assign to read only property 'deviceID' of object '#<Object>'`

tried this fix: https://github.com/thomasloven/hass-browser_mod/issues/63#issuecomment-594790445, unfortunately it doesn't work in my scenario.

popups started to work fine after removing all `deviceID` references from yaml.

I guess some proper fix is needed in the original code?

**Comment by jsiemek** [comment]
I also can confirm that @CAB426  fix works for me.

**Comment by CAB426** [comment]
@pejotigrek Can you post your card and popup config?  I'll take a look at it.

**Comment by pejotigrek** [comment]
@CAB426 I've got plenty of them, but I guess that doesn't matter - so here's one of them: popup with informations about person's whereabouts opened after tapping on a person [words all in caps are redacted]:

```
  - entity: person.SOME_PERSON
    tap_action:
      action: call-service
      entity: person.SOME_PERSON
      service: browser_mod.popup
      service_data:
        deviceID: this
        title: "PERSON"
        card:
          type: vertical-stack
          cards:
          - type: markdown
            content: |
              ## PERSON is **{% if (states('person.SOME_PERSON') == 'home') %}w domu{% elif (states('person.SOME_PERSON') == 'not_home') %}poza domem{% else %}{{ states('person.SOME_PERSON') }}{% endif %}.**
              **Adres w pobliżu:**
              {{ state_attr('device_tracker.GOOGLE_MAPS', 'address') }}
              (z dokładnością do {{ state_attr('device_tracker.GOOGLE_MAPS', 'gps_accuracy') }}m)
              
              **Stan baterii:** {% if (state_attr('device_tracker.GOOGLE_MAPS', 'battery_charging') == false) %}{{ state_attr('device_tracker.GOOGLE_MAPS', 'battery_level') }}%{% else %}ładowanie{% endif %}
          - type: map
            entities:
            - person.SOME_PERSON
            default_zoom: 14
            dark_mode: false
```

that started to work after I commented out the `deviceID` line.
