### ISSUE TITLE
What is the browserID of my current device?

### ISSUE THREAD

**Issue by woobenjamin** [thomasloven/hass-browser_mod#631]
Hi all and thanks in advance for any advice:

I want to grab the browserID of my current computer. The idea is to use this as an input for figuring out what adjustments I need to make for a picture-elements panel card. I know there are probably other ways to deal with the picture-elements card, but I thought this might be the simplest.

Thanks.

ben

**Comment by jelmerwouters** [comment]
Following code works for me

```yaml
- service: media_player.play_media
  data:
    entity_id: |
      [[[
        return 'media_player.' + (window.browser_mod.browserID).replaceAll('-','_');
      ]]]
    media_content_id: https://stream.qmusic.nl/qmusic/aachigh
    media_content_type: url
```
