### ISSUE TITLE
After displaying and dismissing a timed popup, the `progress` CSS style continues to increase

### ISSUE THREAD

**Issue by Vitani** [thomasloven/hass-browser_mod#640]
My Home Assistant version: 2023.9.2

**What I am doing:**

Showing a popup with the `timeout` set to 60 seconds

**What I expected to happen:**

The pop up shows, the progress bar counts down, then the popup disappears

**What happened instead:**

The pop up shows, the progress bar counts down, then the popup disappears BUT the CSS for `browser-mod-popup` continues to be updated

![image](https://github.com/thomasloven/hass-browser_mod/assets/5907401/d7bd475a-fb5f-43a5-a3ce-3209049848f8)

**Minimal** steps to reproduce:

```yaml
service: browser_mod.popup
target:
  device_id:
    - xxxx
data:
  title: Person Detected
  size: wide
  timeout: 60000
  content:
    type: horizontal-stack
    cards:
      - show_state: false
        show_name: false
        camera_view: live
        type: picture-entity
        entity: camera.aaa
        tap_action:
          action: none
        hold_action:
          action: none
      - show_state: false
        show_name: false
        camera_view: live
        type: picture-entity
        entity: camera.bbb
        tap_action:
          action: none
        hold_action:
          action: none
  dismissable: true
  autoclose: false
```

**Error messages from the browser console:**

N/A

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
