### ISSUE TITLE
Browser ID on poup

### ISSUE THREAD

**Issue by EvertJob** [thomasloven/hass-browser_mod#644]
My Home Assistant version: Home Assistant 2023.10.0b2

**What I am doing:**
I would like to use a script to open a pop-up **only** on the device (browser ID) that call's the script.

**What I expected to happen:**
Open a pop-up on the same browser as the script calls

**What happened instead:**
It opens on all browser.

**Minimal** steps to reproduce:
Just press the button

```yaml
# The least amount of code or steps possible to reproduce my error
# my script:
alias: "Pop-up: Scenes"
sequence:
  - service: browser_mod.popup
    data:
      dismissable: true
      autoclose: false
      title: Scenes
      content:
        type: entities
        entities:
          - entity: scene.ik_ben_thuis
          - entity: scene.weltrusten
          - entity: scene.donker
            icon: mdi:stairs
            name: Trap
          - type: divider
          - entity: scene.inschakelen_buiten_verlichting
          - entity: scene.uitschakelen_buiten_verlichting
        browser_id:
          - {{ browser_id }}
      right_button: Sluiten
      timeout: 30000

mode: single
icon: phu:scene-dynamic

# Put your code/steps here
# my button script:
show_name: true
show_icon: true
type: button
tap_action:
  action: fire-dom-event
  browser_mod:
    service: script.pop_up_scenes
    data:
      browser_id: THIS
entity: light.carport
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by engelchrisi** [comment]
I face the same issue. Could you please verify the value of your {{ browser_id }} variable. With me it was empty.

service: system_log.write
data:
  message: browser_id=<{{ browser_id }}>
  logger: error

  Output:
  2023-12-12 08:26:47.337 ERROR (MainThread) [error] browser_id=**<>**

The default behavior then applys when the value is empty:
"A server call will perform the service on ALL REGISTERED BROWSERS."

Btw. the usage of the variable browser_id is from the example on this page:
https://github.com/thomasloven/hass-browser_mod/blob/master/documentation/services.md

      - service: system_log.write
        data:
          message: "Button was clicked in **{{browser_id}}"**

**Comment by pelaxa** [comment]
Having the same issue.  Was a solution found but not posted?

**Comment by EvertJob** [comment]
@thomasloven any suggestions?

**Comment by dcapslock** [comment]
@EvertJob I have tested the following which is working. I did find that when I did not quote the ```{{ browser_id }}``` in the script that it converted to `[]` on save when editing in the UI. So if you are editing script directly in YAML you wight try quoting like I did.

### Script
```
action: browser_mod.popup
metadata: {}
data:
  dismissable: true
  title: Test From Script
  content: Testing 1 2 3
  browser_id: 
    - "{{ browser_id }}"
```

### Button
```
show_name: true
show_icon: true
type: button
tap_action:
  action: fire-dom-event
  browser_mod:
    service: script.test_browser_mod
    data:
      browser_id: THIS
entity: light.bed_light
```
