### ISSUE TITLE
BrowserMod Won't Play Sound After Certain Period of TIme

### ISSUE THREAD

**Issue by ecchodun** [thomasloven/hass-browser_mod#646]
My Home Assistant version: 2023.10.3

**What I am doing:**

Installed BrowserMod on Lenovo M8 Tablet.  Running an Alarm Clock app with Fully Kiosk running in the background.  

**What I expected to happen:**

Play a sound when a door is open.  Works for about 10 minutes even when in the Alarm Clock app, then no longer.  Perhaps Fully Kiosk losing focus, but everything is on?

**What happened instead:**

No sound, nothing.

**Minimal** steps to reproduce:

n/a

```yaml
# The least amount of code or steps possible to reproduce my error

service: media_player.play_media
data:
  media_content_type: audio/x-wav
  media_content_id: http://192.168.0.209:8123/local/door_closing.wav
target:
  entity_id: media_player.lenovo_m8_tablet_bedroom

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X ] Have made sure I am using the latest version of the plugin.

- [X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by jelmerwouters** [comment]
I think I have a very similar, if not the same behaviour, although I am trying to keep a radio stream open on my device. This stops playing after a certain amount of time as well, although I have the browser open and disabled 'Automatically close connection'. Using the following code:

```yaml
- type: custom:button-card
  template: picture_button
  entity_picture: /local/radio/local.png?v=40
  tap_action:
    action: fire-dom-event
    browser_mod:
      service: browser_mod.sequence
      data:
        sequence:
          - service: browser_mod.close_popup
          - service: media_player.play_media
            data:
              entity_id: |
                [[[
                  return 'media_player.' + (window.browser_mod.browserID).replaceAll('-','_');
                ]]]
              media_content_id: https://stream.qmusic.nl/qmusic/aachigh
              media_content_type: url
```
