### ISSUE TITLE
mushroom-chips-card inside vertical-stack-in-card does not work with popups

### ISSUE THREAD

**Issue by codemunkie15** [thomasloven/hass-browser_mod#647]
Home Assistant 2023.10.2
Supervisor 2023.10.0
Operating System 10.5
Frontend 20231005.0 - latest

**What I am doing:**
If you create a popup with a vertical-stack-in-card that contains a mushroom-chips-card, the mushroom-chips-card does not show (or it is hidden behind the other card)

**What I expected to happen:**
Cards display as though they weren't in a popup.

**What happened instead:**
mushroom-chips-card is not visible.

**Minimal** steps to reproduce:

```yaml
- type: custom:mushroom-template-card
  primary: Back garden
  tap_action:
    action: fire-dom-event
    browser_mod:
      service: browser_mod.popup
      data:
        title: "Back garden"
        dismissable: true
        content:
          type: vertical-stack
          cards:
            - type: custom:vertical-stack-in-card
              cards:
                - type: custom:mushroom-light-card
                  entity: light.hot_tub_lights
                - type: custom:mushroom-chips-card
                  chips:
                    - type: entity
                      entity: switch.hot_tub_jets
                      icon_color: blue
                      tap_action:
                        action: toggle
```

**Error messages from the browser console:**

None

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by codemunkie15** [comment]
Still an issue.

**Comment by dcapslock** [comment]
@codemunkie15 problem will be that vertical-stack-in-card and browser_mod have a conflict in how that load. Before looking further, what is the reason to use vertical-stack-in-card?

**Comment by codemunkie15** [comment]
It's generally used to merge 2 cards into 1. The content was already on my dashboard and I tried to move it to a popup instead and noticed it wasn't working as expected.

Looking forward to your fork by the way!

**Comment by dcapslock** [comment]
You can try using the standard vertical and horiztonal stacks. They seem to work well with browser_mod.

**Comment by dcapslock** [comment]
@codemunkie15 Looking into this more, when I take out the redundant vertical-stack from your code (vertical-stack-in-card is based on vertical-stack, all works well. Otherwise I find that it will not work on first try, and then starts to work. Looking at vertical-stack-in-card code, since it is based on HTMLElement and not LitElement, I am not sure if it handling updates from enclosed cards well.

### Seems to be working OK (remove redundant vertical-stack)

```yaml
type: custom:mushroom-template-card
primary: Back garden
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Back garden
      dismissable: true
      content:
        type: custom:vertical-stack-in-card
        cards:
          - type: custom:mushroom-light-card
            entity: light.bed_light
          - type: custom:mushroom-chips-card
            chips:
              - type: entity
                entity: light.kitchen_lights
                icon_color: blue
                tap_action:
                  action: toggle
```

<img width="552" alt="Image" src="https://github.com/user-attachments/assets/2a3d92f0-7f86-4b4b-b822-64e44fd3645f" />

### Alternative with native vertical-stack and some card-mod styling to get same borders and gap as vertical-stack-in-card

```yaml
type: custom:mushroom-template-card
primary: Back garden
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Back garden
      dismissable: true
      card_mod:
        style:
          hui-vertical-stack-card $:
            .: |
              div {
                border: 1px solid lightgray;
                border-radius: 12px;
                gap: 0px !important;
              }
          hui-vertical-stack-card $ mushroom-light-card $:
            .: |
              ha-card {
                border: none;
              }          
      content:
        type: vertical-stack
        cards:
          - type: custom:mushroom-light-card
            entity: light.bed_light
          - type: custom:mushroom-chips-card
            chips:
              - type: entity
                entity: light.kitchen_lights
                icon_color: blue
                tap_action:
                  action: toggle
```

<img width="552" alt="Image" src="https://github.com/user-attachments/assets/9fdb1b01-9161-4bcd-96f1-5d55f25d7319" />
