### ISSUE TITLE
Audio distortion on Lenovo Tab M10 HD running Fully

### ISSUE THREAD

**Issue by IceBotYT** [thomasloven/hass-browser_mod#648]
My Home Assistant version: 2023.10.4

**What I am doing:**
I'm playing a sound on my tablet during exit delay, entry delay, and triggered on my alarmo. The sound sounds fine when I play the sound thru fully, but it's slow and unreliabls

**What I expected to happen:**
Sound to play with no distortions

**What happened instead:**
Sound distorts

**Minimal** steps to reproduce:
1. Play a sound with media_player.play_media

```yaml
alias: Beep Siren until Armed for Exit Delay
sequence:
  - service: browser_mod.javascript
    data:
      code: fully.setAudioVolume(75, 3)
    target:
      device_id: ba032eb8f67eebdd4d716ce7e178c5ab
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: media_player.play_media
    data:
      media_content_id: https://******.duckdns.org/local/tablet_sounds/arming_exit_now.mp3
      media_content_type: url
    target:
      device_id: ba032eb8f67eebdd4d716ce7e178c5ab
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: browser_mod.javascript
    data:
      code: fully.setAudioVolume(40, 3)
    target:
      device_id: ba032eb8f67eebdd4d716ce7e178c5ab
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - repeat:
      while:
        - condition: state
          entity_id: alarm_control_panel.alarmo
          state: arming
      sequence:
        - service: media_player.play_media
          data:
            media_content_id: https://******.duckdns.org/local/tablet_sounds/arming.mp3
            media_content_type: url
          target:
            device_id: ba032eb8f67eebdd4d716ce7e178c5ab
        - delay:
            hours: 0
            minutes: 0
            seconds: 3
            milliseconds: 0
mode: single
icon: mdi:exit-run
```

**Error messages from the browser console:**

```
no errors in console
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
