### ISSUE TITLE
Control display brightness/temp

### ISSUE THREAD

**Issue by stonegray** [thomasloven/hass-browser_mod#649]
A lot of us are using this for mounted tablets. Specifically on iOS, there isn't a great way of controlling display brightness and colour temperature. I'd like browser mod to expose this. 

On the tablet side, we can inject a empty DIV into the DOM at the bottom of `<body>`:

```javascript
document.body.insertAdjacentHTML("beforeEnd", `<div id="colortemp"></div>`);
```

The CSS would fill the screen, make it semitransparent to tint/shade the contents under it, and ensure we can click through it:

```css
#colortemp {
    z-index: 300; 
    position: absolute; 
    height: 100vh;  width: 100vw; 
    top: 0; left: 0; bottom: 0; right: 0; 

    /* ensure we can click through it: */
    pointer-events: none; 

    /* exadurated color for testing; Filter grayscale/sepia might work better */
    background-color: rgba(80,0,0,0.2); 
}
```

The end result is a dimmer, warmer coloured display, perfect for keeping a tablet display on at night. 

This could be exposed in HA as a Light with colour temperature control, allowing tint and brightness to be easily synced with nearby lights.

I've written something similar on my computer to [sync up external displays over DDC and builtin displays](https://gist.github.com/stonegray/154df0c4cd0a2c344524f52774b9200c), the effect looks amazing.
