### ISSUE TITLE
Pop-up close button (X) missing when there's no `title` and `size: fullscreen` is used

### ISSUE THREAD

**Issue by moostmartijn** [thomasloven/hass-browser_mod#653]
My Home Assistant version: 0.XX.X

**What I am doing:**

I would like to use `dismissable: true` without adding a `title:`
The close button, the X, does not appear in this situation. When adding a title, it will. 

**What I expected to happen:**
That there will be a close button also when there's not title (bar)

**What happened instead:**
The card is full screen, but there is no closing button. 

**Minimal** steps to reproduce:
Add a card with `dismissable: true` and `size: fullscreen`, the close button is missing. 

```yaml
# The least amount of code or steps possible to reproduce my error
service: browser_mod.popup
data:
  dismissable: true
  autoclose: false
  content: test
  size: fullscreen
target:
  device_id: xxx

# Put your code/steps here
service: browser_mod.popup
data:
  dismissable: true <- 
  autoclose: false
  content:
    type: custom:mini-media-player
    entity: media_player.woonkamer
    artwork: full-cover
    source: icon
    icon: mdi:speaker
    max_volume: 40
    hide:
      volume: false
      source: false
      power: true
      power_state: true
      info: false
      runtime: false
      icon_state: false
      prev: true
      next: false
      jump: true
      progress: false
      name: false
    speaker_group:
      platform: sonos
      show_group_count: true
      sync_volume: true
      entities:
        - entity_id: media_player.woonkamer
          name: Woonkamer
        - entity_id: media_player.sonos_one_keuken
          name: Keuken
  size: fullscreen
target:
  device_id: 0c8ae80a31d43a1972c22bb252d590a3
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
