### ISSUE TITLE
browser_mod.sequence using old data?

### ISSUE THREAD

**Issue by jdtechsol** [thomasloven/hass-browser_mod#654]
My Home Assistant version: 2023.11.0

**What I am doing:**
Trying to increment value of an input_number and then immediately use its new value. In this example, the starting value of input_number.test is 0.0

For the record, i tried using level: info or level: debug in the system_log.write data but then the message wouldn't show up at all, so ERROR it is. 

Is this the expected behavior? I've even added in a delay of up to 60 seconds and it stil logs the previous value for input_number,test. 

**What I expected to happen:**
2023-11-10 05:38:09.595 ERROR (MainThread) [homeassistant.components.system_log.external] input_number.test before inc: 0.0
2023-11-10 05:38:09.610 ERROR (MainThread) [homeassistant.components.system_log.external] input_number.test after inc: 1.0

**What happened instead:**
2023-11-10 05:38:09.595 ERROR (MainThread) [homeassistant.components.system_log.external] input_number.test before inc: 0.0
2023-11-10 05:38:09.610 ERROR (MainThread) [homeassistant.components.system_log.external] input_number.test after inc: 0.0

**Minimal** steps to reproduce:
create the following input_number:
```yaml
test:
    name: test
    min: 0
    max: 30
    step: 1
    mode: slider
```

create a button card, use the following tap_action

```yaml
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.sequence
        data:
          sequence:
            - service: system_log.write
              data:
                message: >-
                  [[[ return 'input_number.test before inc: '+states['input_number.test'].state ]]]
            - service: input_number.increment
              data:
                entity_id: input_number.test
            - service: system_log.write
              data:
                message: >-
                  [[[ return 'input_number.test after inc: '+states['input_number.test'].state ]]]
```

**Error messages from the browser console:**

none

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
