### ISSUE TITLE
Open Subview dashboard as a Popup

### ISSUE THREAD

**Issue by dortamur** [thomasloven/hass-browser_mod#655]
It would be really useful to be able to open a Subview as content for a Popup. This would allow complex dashboard popups without having to define a Popup's content as YAML.

This could be called as:

```yaml
service: browser_mod.popup
data:
  title: Living Room
  content: 
    navigation_path: /lovelace/living_room
```

or perhaps:

```yaml
service: browser_mod.popup
data:
  title: Living Room
  content: 
    subview: living_room
```
