### ISSUE TITLE
Datetime selector not working in popup

### ISSUE THREAD

**Issue by cooperised** [thomasloven/hass-browser_mod#660]
My Home Assistant version: 2023.11.2

A popup containing a datetime selector is not usable.

Expected result: a second popup on clicking the date selector, allowing a date to be chosen.

Actual result: no popup, rendering the datetime selector inoperative.

To reproduce:

```yaml
    service: browser_mod.popup
    data:
      title: Test
      content:
        - name: date
          label: 'Date:'
          selector:
            datetime: null
```

---
Other selectors are fine, this problem affects only date and datetime.  This is a duplicate of #593 but that issue was closed as stale, and the problem persists.

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by edeckert** [comment]
same here. I added a datetime helper. And when I try to change the value of the date, the datepicker is not opening. See this video:

[Example-Video](https://github.com/thomasloven/hass-browser_mod/assets/91415525/093d668b-aee1-49a6-aa9e-5a2cd2b4c3d5)

**Comment by Dawidooox** [comment]
I can confirm that this issue still exists in Home Assistant 2024.12.2

**Comment by Alien8ions** [comment]
I ran into this (undocumented) bug as well, was trying to improve WAF by adding a scheduler that triggers a popup on a simple button press.
The only crude workaround I found was to embed a glance card, not really user friendly 
This is my best effort for now...
`type: custom:mushroom-template-card
primary: >-
  {{ state_attr('input_datetime.shower_ready', 'timestamp')|
  timestamp_custom('%H:%M', true) }}
secondary: Time when shower ready
icon: mdi:shower-head
fill_container: false
entity: input_datetime.shower_ready
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: When would you like to shower ?
      right_button: Set !
      right_button_action:
        service: script.add_shower_time
      content:
        type: glance
        entities:
          - entity: input_datetime.shower_ready
            name: Set time > 1h in the future 🚿
double_tap_action:
  action: none
`
I hope this might get some attention 
Diego

**Comment by dcapslock** [comment]
See PR #812 which fixes this issue. You will need to adjust styling of the popup to make sure the selector dialog is on top. See note in amended [Popups](https://github.com/dcapslock/hass-browser_mod/blob/popup-hass-dialogs/documentation/popups.md#form-content) documentation.

**Comment by dcapslock** [comment]
> `Permission denied to access property "id"`
> 
> Any fix for this or a cleaner workaround?

@KevSex usually permission issues are from iframe to main frame. Can you describe a bit more of your setup?

**Comment by dcapslock** [comment]
@KevSex I can't reproduce any console log errors to do with permission. However I do note that the HA code for input_datetime does not give id nor name to the form control, which Chrome recommends to fix. So its plausible another custom component is trying to access the control by id and failing as it does not have an id.

Anyhow, I am pretty sure you will get the correct input_datetime dialog with PR #812 from testing with similar code you have posted. I was not sure the sequence of another popup would work but it seems to work fine for my tests.

**Comment by dcapslock** [comment]
> [@dcapslock](https://github.com/dcapslock) It looks like it has fixed it for us, albeit I'm struggling to fix the styling with `card_mod` as the date/time selector is not showing on top of my form. I've tried various options of changing the z-index but not having any luck. Based on my example above, do you have suggestions on where/how to apply the additional styling?

You don't need card_mod for styling popups. Styling can be done directly. For testing your case, what worked for me is below:

```
...
  tap_action:
    action: fire-dom-event
    browser_mod:
      service: browser_mod.sequence
      data:
        sequence:
          - service: script.reset_event_times
          - service: browser_mod.popup
            data:
              dismissable: true
              autoclose: false
              title: Create event
              style: |-                      # <- added
                z-index: 5;               # <-
                position: absolute;  # <-
              content:
...
```
