### ISSUE TITLE
To do list cannot delete items when using custom popup

### ISSUE THREAD

**Issue by kei81131** [thomasloven/hass-browser_mod#661]
My Home Assistant version: 2023.12.0

**What I am doing:**
Use custom popup card to show todo list card in dashboard

**What I expected to happen:**
When I tap the button of todo list card, which is for clear the completed items
I can only do it in original todo list card

**What happened instead:**
When I use custom popup card, and tap that button it will do nothing

**Minimal** steps to reproduce:

```yaml
type: custom:popup-card
entity: input_boolean.test_onoff
title: Custom popup
dismissable: true
card:
  type: shopping-list
  title: to do list test in popup
  entity: todo.ttt
left_button: ttt

```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

![image](https://github.com/thomasloven/hass-browser_mod/assets/111072203/a776cfde-f35e-4e07-bfe5-d678cced79c3)
![image](https://github.com/thomasloven/hass-browser_mod/assets/111072203/0ee5a9f5-b0bf-4c82-b71e-76c1a554537b)
---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
