### ISSUE TITLE
Default dashboard based on device type

### ISSUE THREAD

**Issue by Selim042** [thomasloven/hass-browser_mod#664]
I'd love to see the ability to have a default dashboard set depending on the type of device, such as phone, tablet, or desktop.  I thought of this after messing around with the new conditional card options.
![image](https://github.com/thomasloven/hass-browser_mod/assets/8419844/9f47a6f6-0ece-4667-bc1a-60f91898691d)

**Comment by dcapslock** [comment]
Version 2.4.0 allows for a Default action which you can see to set different view depending on which device. The easiest way will be to set statically via known devices. However, you could use a script passing `broswer_id: THIS` to then decide what path to provide `broswer_mod.navigate`.

The key point in the script is to get the sensor which you wish to check. You can do this by looking up the device entities for the device id that matches the Browser ID. 

`device_entities(device_id(browser_id))` will give something like

```yaml
[
  "sensor.dcd_browser_browser_path",
  "sensor.dcd_browser_browser_visibility",
  "sensor.dcd_browser_browser_useragent",
  "sensor.dcd_browser_browser_user",
  "binary_sensor.dcd_browser_browser_fullykiosk",
  "sensor.dcd_browser_browser_width",
  "sensor.dcd_browser_browser_height",
  "binary_sensor.dcd_browser_browser_dark_mode",
  "binary_sensor.dcd_browser",
  "light.dcd_browser_screen",
  "media_player.dcd_browser",
  "sensor.dcd_browser_browser_battery",
  "binary_sensor.dcd_browser_browser_charging"
]
```

then you can select which entity matches 

```yaml
device_entities(device_id(browser_id)) | select("contains", "_browser_width") | list | first
```

will give something like

`sensor.dcd_browser_browser_width`

Putting it altogether....

#### Example Script

```yaml
sequence:
  - variables:
      device_width: >
        {% set sensor = device_entities(device_id(browser_id)) |
        select("contains", "_browser_width") | list | first %} {% set width =
        states(sensor) | float(1280) %}  {% set breakpoints = 
          [
            { 'width': 768, 'size': 'mobile' },
            { 'width': 1024, 'size': 'tablet' },
            { 'width': 1280, 'size': 'desktop' },
            { 'width': 999999, 'size': 'wide' },
          ]
        %} {{ (breakpoints | selectattr('width', 'gt', width) | list | first
        ).size }}
  - variables:
      navigation_path: |
        {% set paths =
          { 
            'mobile': '/dashboard-test/0',
            'tablet': '/dashboard-test/0',
            'desktop': '/dashboard-test/test-view-2',
            'wide': '/dashboard-test/test-view-2',
          } 
        %}  {{ paths[device_width] }}
  - action: browser_mod.navigate
    data:
      browser_id: |
        {{ browser_id }}
      path: |
        {{ navigation_path }}
fields:
  browser_id:
    selector:
      text: {}
    name: Browser ID
alias: Navigate per Device Width
description: ""
```

#### Default action

```yaml
action: script.navigate_per_device_width
data:
  browser_id: THIS
```
