### ISSUE TITLE
Tap_action within popup stopped working

### ISSUE THREAD

**Issue by Scoff123** [thomasloven/hass-browser_mod#665]
My Home Assistant version: 2023.12.4

**What I am doing:**
Performing a single tap on a custom button card, to launch a browser_mod popup, which displays my system information. Then within the popup, clicking on my 'restart' button entity, to restart my Home Assistant.

**What I expected to happen:**
A confirmation text should appear that says 'Are you sure?' and asking if I want to restart my home assistant or cancel the request. This has been working correctly until the latest update of either HA core, or Browser_mod. Both were updated at the same time.

**What happened instead:**
Absolutely nothing happens now when i click the 'restart' button entity, no confirmation text, no error message, no message about failing to call a service. 

If I use the same button entity code elsewhere on my dashboard, NOT inside a popup, then the code works correctly.

**Minimal** steps to reproduce:
Launch a popup using browser_mod, click on a button entity inside the popup, which should call a service via tap_action. Nothing happens.

```yaml
# The least amount of code or steps possible to reproduce my error

type: entities
    entities:
      - type: button
        name: Restart Home Assistant VM
        tap_action:
          action: call-service
          service: homeassistant.restart
          confirmation:
            text: Restart Home Assistant?
        action_name: Restart
        icon: mdi:home-assistant

```

**Error messages from the browser console:**
No error messages are displayed in the browser console
---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
