### ISSUE TITLE
deviceID doesn't work under hold_action

### ISSUE THREAD

**Issue by rotcop4u2** [thomasloven/hass-browser_mod#67]
I have noticed that on my setup when I issue a popup and use
```
deviceID:
  - this
```
under hold_action: it breaks my popup. but works perfectly on tap_action:

**Comment by rotcop4u2** [comment]
further description in my use..
```
            hold_action:
              action: call-service
              service: browser_mod.popup
              service_data:
                style:
                  top: 15%
                  width: 500px
                  text-shadow: 1px 1px silver
              # height: 400px
                  border-radius: 10px
                  --ha-card-border-radius: 10px
                  --ha-card-background: gainsboro
                title: Freezer Stats
                card:
                  type: entities
                  entities:  
                    - sensor.freezer_on
                deviceID:
                  - this
```
