### ISSUE TITLE
popup stopped working in IOS app

### ISSUE THREAD

**Issue by bkbartk** [thomasloven/hass-browser_mod#674]
My Home Assistant version: 2024.1.3

I have several popups in lovelace like
```
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.popup
        data:
          title: Afwasmachine
          content:
            type: entities
            entities:
              - switch.011090518272000349_bsh_common_setting_powerstate
              - select.011090518272000349_programs
              - >-
                switch.011090518272000349_dishcare_dishwasher_option_silenceondemand
              - button.011090518272000349_start_pause
              - button.011090518272000349_stop
              - >-
                switch.011090518272000349_dishcare_dishwasher_option_variospeedplus
```

but when I tab in IOS nothing happens, on browser a popup opens.
this worked before, but now not any more
this issue is on entities and also on picture-element card, other cards I did not check.

a popup should open

create an entities card,
with entity and add the tap_actionaction.
now open the ios app and click the entity

```yaml
type: picture-elements
elements:
  - type: state-icon
    entity: switch.lamp_bijkeuken
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.popup
        data:
          title: Lamp Trapkast
          content:
            type: entities
            entities:
              - switch.lamp_bijkeuken_timer
              - switch.lamp_bijkeuken
```

**Error messages from the browser console:**
none

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
(however "Make sure to configure your [frontend](https://www.home-assistant.io/components/frontend/) with javascript_version: latest" is no longer valid for HA)
see: https://community.home-assistant.io/t/please-remove-javascript-version-from-your-frontend-config/573633/3?u=bkbartk

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
