### ISSUE TITLE
cant call fire-dom-event

### ISSUE THREAD

**Issue by Winzy54** [thomasloven/hass-browser_mod#677]
I use an entity person card. (i think this is how it called) and i would like to open a pop up with a map. 
when i use call service - browser_mod: popup with the below code its working fine, but i want the pop up to open only on the current device i press the button and not all the devices. i read that i need to use fire-dom-event or browser_mod.popup _action but i dont have them as actions. 

can any one help me with this or maybe change my code that it will work only on the current device. 

```
type: custom:mushroom-person-card
entity: person.daniel
layout: horizontal
icon_type: entity-picture
hold_action:
  action: none
double_tap_action:
  action: none
tap_action:
  action: call-service
  service: browser_mod.popup
  target: {}
  data:
    dismissable: true
    autoclose: false
    title: History 24 hours - Noaam
    content:
      type: map
      entities:
        - entity: person.daniel
      hours_to_show: 24
      dark_mode: false
      default_zoom: 14
    size: normal
```
