### ISSUE TITLE
Markdown card not working in a Popup card

### ISSUE THREAD

**Issue by LDprg** [thomasloven/hass-browser_mod#681]
My Home Assistant version: 2024.2.1

**What I am doing:**
Adding a Markdown card to a popup card causes it to be empty. Static text and Templates wont work.

**What I expected to happen:**
The markdown card to work as expected like everywhere else.

**What happened instead:**
Well no visible markdown card/content.

**Minimal** steps to reproduce:
1. create a popup card
2. add a markdown card with some content 
3. open the popup card

**Error messages from the browser console:**

Nothing special here.

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by MEKadan** [comment]
This is a mod of a pop-up card I have. Includes some sample sensors and also markdown.

For me it works

```
show_name: true
show_icon: true
type: button
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Tank heater contactor control
      content:
        type: vertical-stack
        cards:
          - type: entities
            title: Title 1
            show_header_toggle: false
            theme: my_theme
            entities:
              - entity: sensor.sensor_1
                name: Name for sensor 1
                secondary_info: last-updated
              - entity: sensor.sensor_2
                name: Name for sensor 2
                secondary_info: last-updated
          - type: markdown
            title: My markdown name
            content: >-
              Your markdown text goes here
              Your markdown text goes here
              Your markdown text goes here                           
       
name: Name for the card
show_state: true
icon: mdi:something
icon_height: 40px

```
