### ISSUE TITLE
close_popup closes the view, but stream continues in background

### ISSUE THREAD

**Issue by barisahmet** [thomasloven/hass-browser_mod#694]
My Home Assistant version: 2024.3.3

**What I am doing:**
I have a Fully Kiosk Home Assistant dashboard. When motion detected on doorbell, I show the camera popup with AgentDVR url using browser_mod.popup, it works well. When AgentDVR shows popup, my server CPU usage jumps from 5% to 50%, it's normal. However, when I call close_popup it stays 50% and using network in background. Which I think that means it just hides the popup. It doesn't dispose it. When I refresh the web page, it goes down to 5% again.

**What I expected to happen:**
When I call close_popup, it should stop streaming the web content.

**What happened instead:**
It hides the popup, but still using resources in background.

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error

service: browser_mod.popup
data:
  browser_id: tablet
  size: fullscreen
  content: >
    <img style="display: block;-webkit-user-select: none;margin:
    auto;background-color: hsl(0, 0%, 25%);"
    src="http://192.168.1.21:8025/video.mjpg?oid=3&size=1024x768" width="1480"
    height="924">
```

after card shown, just hide it with;

```yaml
service: browser_mod.close_popup
data:
  browser_id: tablet
```

**Error messages from the browser console:**

```
It runs in tablet, I dont know how to get the log from it.
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
