### ISSUE TITLE
Entities not loading in popup 0.107b3

### ISSUE THREAD

**Issue by matt8707** [thomasloven/hass-browser_mod#70]
I noticed that in 0.107 `input_number`, `group`, `input_select` (maybe more) doesn't load the first time browser_mod opens a popup. If I close the popup and open it again they load properly. 

It may be related to the new lazy-loading https://github.com/home-assistant/frontend/issues/4984#issuecomment-591034824

Is this a bug in hass, or is there a way to preload contents of a popup?
My solution for now is to hide these entities on my dashboard so they populate directly in a popup.

Steps to reproduce, new blank dashboard
```
views:
  - path: default_view
    cards:
      - type: entities
        entities:
          - entity: light.xx
            tap_action:
              action: call-service
              service: browser_mod.popup
              service_data:
                title: Test
                card:
                  type: entities
                  entities:
                    - input_number.xx
                    - group.xx
                    - input_select.xx
                deviceID:
                  - this
```
