### ISSUE TITLE
Cannot Close Popup in mobile browser

### ISSUE THREAD

**Issue by 400HPMustang** [thomasloven/hass-browser_mod#708]
My Home Assistant version: 2024.5.3

**What I am doing:**

Trigger a popup using browser_mod.popup on Safari on iOS

**What I expected to happen:**

To be able to click an area outside the popup so that it will close

**What happened instead:**
The popup opens full screen and there is no space outside the popup to click so that it will close

**Minimal** steps to reproduce:
Create custom button card with the popup below that has enough entites so that you have to scroll on a mobile browser
Trigger popup on mobile browser
Popup opens full screen and cannot be closed

```yaml
# The least amount of code or steps possible to reproduce my error
service: browser_mod.popup
target: {}
data:
  dismissable: true
  content:
    type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Lights on
      show_header_toggle: false
    filter:
      include:
        - domain: light
        - domain: switch
      exclude:
        - state: "off"
        - state: unavailable
        - hidden_by: user
        - integration: adaptive_lighting
        - integration: bhyve
        - integration: unifi
        - integration: sonos
        - name: Fountain
        - name: /[Pp]ower/
        - name: /[Pp]ump/
        - name: /[Ww]ax/
        - name: /[Mm]ode/
        - name: /[Bb]ridge/

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```
![IMG_2409](https://github.com/thomasloven/hass-browser_mod/assets/45641587/0f3f7418-8729-4bce-93e1-424e22a5f649)
---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
