### ISSUE TITLE
Service browser_mod.navigate path template

### ISSUE THREAD

**Issue by Stephan1908** [thomasloven/hass-browser_mod#713]
Hi,
I have a tablet with fullykiosk and a smartmirror with browsermod. Now I would like to use the sensor.l201_eea_aktuelle_seite (current page fullykiosk) to synchronize the path on the smartmirror (with browser_mod.navigate).
So, if I call up a different page on the tablet, it should also be displayed on the smartmirror.

Is it possible to specify the path using a template?
Something like this:

![grafik](https://github.com/thomasloven/hass-browser_mod/assets/60405276/2fc37650-c8c7-4923-8fe3-4ac87fcd00b1)

Thank you, 
Greetings Stephan

**Comment by dcapslock** [comment]
When using in a script or automation you can use templates directly. `value_template` etc. are related to template sensors. Below is an automation that does what you wish, having one browser mirror another as to path.

```yaml
alias: Test Mirror Path
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.ios_virtual_browser_path
    to: null
conditions: []
actions:
  - action: browser_mod.navigate
    metadata: {}
    data:
      browser_id:
        - 8889a92512aca038906bbc7dc02de66b
      path: "{{ trigger.to_state.state }}"
mode: single
```
