### ISSUE TITLE
Popup Card is no longer working

### ISSUE THREAD

**Issue by shwarnock** [thomasloven/hass-browser_mod#719]
My Home Assistant version: 0.XX.X

**What I am doing:**
I am using popup cards within browser_mod to open up remotes for my tvs when the entity for the remote is pressed. This was working fine for several months until today.

**What I expected to happen:**
Clicking my remote entity opens the popup with my built remote control

**What happened instead:**
The more info dialog for the entity is opened

**Minimal** steps to reproduce:
1. Create a popup card
2. Populate the popup card with a custom lovelace card
3. Link this to any entity
4. Click the entity

```yaml
type: custom:popup-card
entity: remote.millennium_falcon
dismissable: true
card:
  type: custom:android-tv-card
  remote_id: remote.millennium_falcon
  slider_id: media_player.millennium_falcon
  media_player_id: media_player.millennium_falcon
  keyboard_id: media_player.android_tv_192_168_86_54
  rows:
    - - power
      - search
      - home
    - - emby
      - youtube
      - keyboard
    - - back
      - volume_down
      - volume_up
    - - touchpad
title: Millennium Falcon Remote
```
---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X ] Have made sure I am using the latest version of the plugin.

- [ X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
