### ISSUE TITLE
javascript command to open a new window stop working on ipad and iphone companion app

### ISSUE THREAD

**Issue by Emilef22** [thomasloven/hass-browser_mod#741]
My Home Assistant version: 2024.8.0b5

**What I am doing:**
Trying to open a new browser window in google chrome with the javascript action command on a Ipad air M2 13'' and on Iphone 15 pro.

**What I expected to happen:**
A new window browser of chrome should open with the right url

**What happened instead:**
Nothing on Iphone and Ipad but the command work on macbook pro

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error
 Here is my code:

data:
  browser_id:
    - 7be19d2c001f9076f1e245cf3d4ec513
  code: >-
    window.open('https://www.google.com/search?q={{
    state_attr('media_player.salon', 'media_artist') }} - {{
    state_attr('media_player.salon', 'media_title') }} chords',
    '&ie=UTF-8&oe=UTF-8')
enabled: true
action: browser_mod.javascript



# Put your code/steps here
```
data:
  code: >-
    window.open('https://www.google.com/search?q={{
    state_attr('media_player.salon', 'media_artist') }} - {{
    state_attr('media_player.salon', 'media_title') }} chords',
    '_blank&rlz=1C5CHFA_enCA1003CA1003&oq=chords&aqs=chrome.0.69i59j0i512l3j69i60l4.790j0j9&sourceid=chrome&ie=UTF-8')
  browser_id: []
enabled: true
action: browser_mod.javascript

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [ x] Have made sure I am using the latest version of the plugin.

- [x ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
