### ISSUE TITLE
Default volume setting

### ISSUE THREAD

**Issue by Ramotny** [thomasloven/hass-browser_mod#742]
Is there a way to set default volume of browser player? If HA-UI is restarted (browser load/refresh) volume is always (re)set to max.

**Comment by dcapslock** [comment]
[v2.4.0 Released](https://github.com/thomasloven/hass-browser_mod/releases/tag/v2.4.0) which has a Default action through which you can use javascript to adjust volume.

e.g.
```yaml
action: browser_mod.javascript
data:
  code: window.browser_mod.player.volume = 0.5
```
