### ISSUE TITLE
[Discussion] Disable Automatic Creation of Sensors/Entities in browser_mod

### ISSUE THREAD

**Issue by manunited10** [thomasloven/hass-browser_mod#743]
Hi everyone,

I've been using `browser_mod` for quite some time and am really pleased with its functionality. My primary use case is for creating pop-up cards. For instance, when I press a garage button-card, another card pops up with controls for the garage cover, lights, live camera, etc.

However, I've noticed an issue with the way `browser_mod` registers browsers. It creates entities like `media_player`, `light.screen`, and so on, each with a name that appears to be a pseudo-random number and is temporary. While it could be useful for some use cases, this leads to a cluttered list of sensors/entities in Home Assistant. For example, when I open the `media/radio browser` at the bottom right and select a target device, I see at least 20 media players listed, many of which are unavailable (greyed out) and have names like `81075fdd-9802a24e`. These entities are also listed under `Settings/Devices & Services/Entities`.

Is there a way to configure `browser_mod` to avoid creating these sensors and only use it as a `pop-up tool`? Any guidance would be greatly appreciated!

Thanks in advance!

**Comment by dcapslock** [comment]
@manunited10 you can turn off Auto register of Browsers in Browser Mod config pabel.

![Image](https://github.com/user-attachments/assets/b5cb5b8c-4acc-43c3-9a3f-b752d999ccf7)

**Comment by manunited10** [comment]
@dcapslock if I do that then the popups wouldn't work, would they?

**Comment by dcapslock** [comment]
@manunited10 not if you only wish to have local popups and not remotel popups.

**Comment by manunited10** [comment]
That's the point. On my wall dashboards around the house, yes I enabled deviceID / name etc. But I also use HA on other browsers/computer, e.g. at work. So yeah I get your help, but I think it's not applicable for my use case.

Having said that, even locally, when opening on different browsers or even on incognito, it recognises a new device. How would you open a popup without registering a new device? What am I missing?

**Comment by dcapslock** [comment]
browser_mod.popup used with fire-dom-event with no browser_id will show popup on local browser.

**Comment by manunited10** [comment]
I tested and unfortunately without `Auto-register` the popup does not work on a new browser (when calling service `fire-dom-event` + `browser_mod.popup`).
dashboard:
```yaml
- type: custom:button-card
  template: garage_card_with_popup
  view_layout:
    grid-area: header4
```
button-card
```yaml
garage_card_with_popup:
  template: garage_card
  tap_action:
    action: fire-dom-event
    browser_mod:
      service: script.garage_popup
      data:
        browser_id: THIS
```
script:
```yaml
- garage_popup:
    mode: single
    icon: hass:garage
    sequence:
    - service: browser_mod.popup
      data:
        browser_id: '{{ browser_id }}'
        title: Garage
        content:
          type: vertical-stack
          cards:
             ...
```
