### ISSUE TITLE
Media player doesn't show extra.title when playing an audio stream

### ISSUE THREAD

**Issue by XqeH57r** [thomasloven/hass-browser_mod#748]
My Home Assistant version: 2024.9.1

**What I am doing:**

I'm using browser_mod to play an icecast audio stream on my dashboard on a button click. It's working well, but the media player doesn't show the `extra.title` property of the media_player.play_media action.

The audio plays great! But there is no title rendered on the media-control card.

**What I expected to happen:**
The media-control card to show the extra-title property.

**What happened instead:**
No title is rendered (also showing mini-media-player card).

![image](https://github.com/user-attachments/assets/4914a58b-b4fa-44e7-bc57-570433df9993)

**Minimal** steps to reproduce:

This is how I am playing the audio:

```yaml
# The least amount of code or steps possible to reproduce my error

    tap_action:
      action: perform-action
      perform_action: media_player.play_media
      data:
        media_content_id: http://IP:PORT/STREAM
        media_content_type: audio/mpegURL
        extra:
          title: Police and Fire Scanner
      target:
        entity_id: media_player.desktop_browser
```

**Error messages from the browser console:**

No errors

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
