### ISSUE TITLE
Show “More_Info” camera in full screen

### ISSUE THREAD

**Issue by DerT94** [thomasloven/hass-browser_mod#751]
Hey,

Is it possible to display a camera directly as a full screen?
I currently use the following command
```
action: browser_mod.more_info
data:
  large: true
  ignore_popup_card: true
  browser_id:
    - ID
  entity: ...........

```

But this does not open the camera in full screen
