### ISSUE TITLE
[Help] Popup selector dynamic

### ISSUE THREAD

**Issue by camels84** [thomasloven/hass-browser_mod#759]
i'm trying to follow this issue 
https://github.com/thomasloven/hass-browser_mod/issues/624

but in my case, it won't work!

i have this function:

```

type: button
name: Select Media Players
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Select Media Players
      right_button: Confirm
      right_button_action:
        service: script.process_selection
        data:
          selected_players: "{{ params }}"
      content:
        - name: params
          label: Select Media Players
          selector:
            select:
              multiple: true
              options: "[[[ return input_select.available_media_players.attributes.options ]]]"
```

and the result is not populating the list, if i put the string result (from Jinja2) it works! 
I think also that should be refenced in tuturial page!

tanks!
