### ISSUE TITLE
Browser_mod lowers the volume of media until i cast something else.

### ISSUE THREAD

**Issue by sheitmaster** [thomasloven/hass-browser_mod#768]
Here's my issue, i have set up an automation to play sounds when motion is detected and other things.
This works fine in homeassistant as is until Browser_mod opens up a popup with my camera feed if the camera detects motion.
Then the audio of all sounds are atleast halved.

The volume remains this low until i stop and restart the casting.
The audio-files are really loud, i made them myself and they are at the limit before starting to distort.

This is an issue caused by either HASS or Browser_mod, and i suspect the latter.
I've tried the usual steps, my google nest volume is at 100%
Media volume in HSS is at 100%
I even have the code in the yaml to set volume at max before playing the audio, but browser_mod simply turns down other sounds like it has priority speaker or something...

Anyone got any good idéas on how to fix this?

**Comment by willat8** [comment]
I don't have much to add other than I see the same behaviour with an identical setup as yours. Using CAST browser_mod device. I have to re-cast the dashboard to get the volume back to normal, and it immediately gets much quieter whenever using the popup service.

**Comment by willat8** [comment]
Maybe https://github.com/thomasloven/hass-browser_mod/issues/742#issuecomment-2964395721 is worth a try?

**Comment by dcapslock** [comment]
It's likely a sound format difference. You could test setting to manual to see if it is a difference. https://support.google.com/chromecast/answer/10110321

I also note that there is a [longstanding issue with Spotify](https://community.spotify.com/t5/Other-Podcasts-Partners-etc/Low-Volume-on-Chromecast/td-p/4801530) that is similar. So unlikely to be a Browser Mod only issue. In teh end Browser Mod is just using html5 <audio> and <video>, nothing fancy.

**Comment by willat8** [comment]
The strange part is that the volume seems to get dramatically lower only after using browser_mod popup service. Volume level when playing media to CAST device via browser_mod is normal prior.

This is how I reproduce:
1. Cast dashboard to CAST device, use browser_mod media player entity to play an MP3 file on CAST device, works fine and volume normal

2. Use this action which displays live camera feed as popup window on CAST dashboard (there's no sound audible for the video feed, but I think that's expected unless the popup window is interacted with?)
```yaml
  - action: browser_mod.popup
    metadata: {}
    data:
      dismissable: true
      content:
        type: picture-entity
        entity: camera.front_door_live_view
        camera_view: live
        show_state: false
      browser_id:
        - [snip]
      timeout: 20000
      timeout_hide_progress: true
```

3. Repeat step 1, volume level is now maybe 10% of what it was originally, even though device volume is turned right up and media player entity volume is maxed out. I also tried setting volume to max using JavaScript action mentioned [here](https://github.com/thomasloven/hass-browser_mod/issues/742#issuecomment-2964395721) and still the volume is very low.
