### ISSUE TITLE
Pop-Up Button "Actions" vs "Services"

### ISSUE THREAD

**Issue by patienttruth** [thomasloven/hass-browser_mod#774]
My Home Assistant version:

Core
2024.12.5
Supervisor
2024.12.0
Operating System
14.1
Frontend
20241127.8

**What I am doing:**
Creating a dynamic popup

**What I expected to happen:**
paste an action in under `right_button_action:`

```
right_button_action:
  action: "{{right_button_action}}"
  metadata: {}
  data:
    entity_id: "{{right_button_entity_id}}"
```
This is the field `right_button_action`
```
fields:
  right_button_action:
    selector:
      select:
        options:
          - script.turn_on
          - automation.trigger
  right_button_entity_id:
    selector:
      text: null

```
**What happened instead:**
It didn't work. After troubleshooting for a while I tried replacing `action` with `service` and it worked.

Please consider adding `action` as a functional alternate to `service`.

NOTE, while I'm asking for something, originally I tried to use the "actions" field in the popup script. 

```
right_button_action:
  {{right_button_action}}
```
This is how I tried to configure the field in that case

```
fields:
  right_button_action:
    selector:
      action: {}
    name: Right Button Action

```
It formats the output like this, however it seems this also doesn't work for the Browser Mod Pop-up. 
```
right_button_action:
  - action: script.ht_clear_pop_up_from_tablet
    metadata: {}
    data:
      entity_id: script.ht_clear_pop_up_from_tablet
```

My case is solved, but I wanted to write in mostly since the `action` call doesn't work which might be considered a bug, the rest is definitely a FR. Thank you for the awesome integration Thomas!
