### ISSUE TITLE
card css apply on more info popups

### ISSUE THREAD

**Issue by deepakkoirala** [thomasloven/hass-browser_mod#799]
My Home Assistant version: 2025.1.4

**What I am doing:**

I am creating a theme to apply the css to hide the last-change time but there is a bug in popups.

**What I expected to happen:**

I want the last change time to hide when I open the more info popup.

**What happened instead:**

It should hide immediately but after the modal box is opened, it is hiding after few milliseconds and I could see the timestamp.

**Minimal** steps to reproduce:

I am using in Fully Kiosk in samsung android tablet A7 Mini. This happens at one time for switch or light but second time i open different switch or light, it does not happen. The css is getting applied for the first time open and later it is getting applied.

```yaml
wallpanel-theme:
  # Define your theme colors
  # Card-Mod settings to customize specific cards
  card-mod-theme: wallpanel-theme
  
  ha-dialog:
    animation:none !important;
  ha-dialog::backdrop:
    animation:none !important;
  ha-card:
    animation:none !important;
  
  modes:
    dark:
      primary-color: "#0288D1"
      background-color: "#121212"
      text-color: "#FFFFFF"

  card-mod-more-info-yaml: |
    ha-more-info-info$:
      more-info-content$:
        more-info-light$:
          ha-more-info-state-header$: |
            .last-changed {
              visibility: hidden !important;
            }
        more-info-switch$:
          ha-more-info-state-header$: |
            .last-changed {
              visibility: hidden !important;
            }
        more-info-lock$:
          ha-more-info-state-header$: |
            .last-changed {
              visibility: hidden !important;
            }
        more-info-cover$:
          ha-more-info-state-header$: |
            .last-changed {
              visibility: hidden !important;
            }
        more-info-alarm_control_panel$:
          ha-more-info-state-header$: |
            .last-changed {
              visibility: hidden !important;
            }
      state-card-content$:
        state-card-display$:
          state-info$: |
            .time-ago {
              visibility: hidden !important;
             }
# Put your code/steps here
```
Added via theme yaml file.

**Error messages from the browser console:**
No error in console.

```
// Select everything from the browser console and copy it

// Paste it here
```
No Error in console.

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [ X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [ X ] Have made sure I am using the latest version of the plugin.

- [ X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
