### ISSUE TITLE
Feature request | Screen saver

### ISSUE THREAD

**Issue by AalianKhan** [thomasloven/hass-browser_mod#8]
I love this custom component. I love the blackout mode but I would love to make it show something else other than a black screen. like the time, notifications (of hass), calendar, etc. If this is possible with the popup feature then can you please guide me. Thanks

**Comment by Dino-Tech** [comment]
@
```yaml
sleep_tablet: ## CLOCK SCREENSAVER
  sequence:
    - service: browser_mod.command
      data:
        command: popup
        deviceID:
          - OfficePC
          - OfficeTab LAN
          - Kiosk
        title: " "
        auto_close: true
        style:
          background: black
          font-family: "Digital-7 Mono"
          "--primary-text-color": rgba(255,255,255,0.2)
          "--paper-card-background-color": black
          "--iron-icon-stroke-color": black
          font-weight: bold
          height: 100%
          width: 100%
          margin: 0
        card:
          type: custom:bignumber-card
          entity: sensor.time_12_hour
          scale: 290px
```
