### ISSUE TITLE
Pop-ups not full size, have horizontal scroll bar

### ISSUE THREAD

**Issue by alanthewild** [thomasloven/hass-browser_mod#80]
This was working happily until a couple of days ago when I updated both the browser-mod and Home Assistant.
Now when opening a pop-up, the card doesn't seem to be maximised and has a horizontal scroll-bar.

Same issue happens on all of pop-ups (I only have 3 though).

Scroll bars on Chrome and Safari on macOS. 
On iPhone the right hand edge of the pop-up is cut-off. 

This popup normally shows -40dB, not -40 with dB off the screen.
![image](https://user-images.githubusercontent.com/28683403/78233439-3bc80400-7532-11ea-9b91-9f1667bdda07.png)

Here is the config for the screenshot above:
```
popup_cards:
  sensor.avr_volume_display:
    card:
      entities:
        - entity: input_number.avr_volume
          icon: 'mdi:volume-high'
          show_name: false
          type: 'custom:slider-entity-row'
      show_header_toggle: false
      type: entities
    large: false
    title: Lounge Volume
```

Running Home-assistant 107.7
Browser-mod version 25

Can try downgrading something for trouble shooting if needed.
