### ISSUE TITLE
History Graph Cards are not rendered in Popup

### ISSUE THREAD

**Issue by DNC74** [thomasloven/hass-browser_mod#802]
My Home Assistant version: 2025.2.1

**What I am doing:**
After updating HAOS from 2025.1.4 to 2025.2.1 I have the following issue: Opening a popup via fire-dom-event does not show embedded history-graph cards any more. Other cards like e.g. Entity are shown as they should.

**What I expected to happen:**
I expect history-graph-cards working again in a popup.
Here is an example of what it looked like when it was still working (before the upgrade to 2025.2.1)

![Image](https://github.com/user-attachments/assets/364fcca9-e392-4865-8645-55aec9312222)

**What happened instead:**
The place where the history-graph should be shown, is left empty.

![Image](https://github.com/user-attachments/assets/e738c276-c8dc-45e5-884f-f0886e54b962)

**Minimal** steps to reproduce:
Add history-graph card to the code for the popup. Both boolean and value based history-graph cards are not rendered

```yaml
# The least amount of code or steps possible to reproduce my error
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.popup
        data:
          title: Lüften
          size: normal
          dismissable: true
          content:
            type: vertical-stack
            cards:
              - type: history-graph
                entities:
                  - entity: binary_sensor.ventilation_living
                    name: Lüften
                  - entity: binary_sensor.living_csw_01_contact
                    name: Tür
                  - entity: binary_sensor.living_csw_02_contact
                    name: Fenster
                  - entity: sensor.humidity_living_outdoor_difference
                    name: Differenz
                  - entity: >-
                      input_number.ventilation_living_absolute_humidity_threshold
                    name: Toleranz
                hours_to_show: 24
                card_mod:
                  style:
                    .: |
                      ha-card { border: none; }
              - type: entities
                show_header_toggle: false
                state_color: true
                entities:
                  - entity: binary_sensor.ventilation_living
                    secondary_info: last-changed
                    name: Lüften?
                  - entity: binary_sensor.living_csw_01_contact
                    secondary_info: last-changed
                    name: Terrassentür
                  - entity: binary_sensor.living_csw_02_contact
                    secondary_info: last-changed
                    name: Fenster
                  - entity: automation.ventilation_living
                    name: Automation
                    secondary_info: last-changed
                card_mod:
                  style:
                    .: |
                      ha-card { border: none; }
              - type: conditional
                conditions:
                  - condition: state
                    entity: automation.ventilation_living
                    state: "on"
                card:
                  type: entities
                  state_color: true
                  show_header_toggle: false
                  entities:
                    - entity: sensor.living_air_01_humidity
                      name: Innen relativ
                    - entity: >-
                        input_number.ventilation_living_relative_humidity_minimum_threshold
                      name: Innen min.
                    - entity: sensor.wohnzimmer_comfort_absolute_luftfeuchtigkeit
                      name: Innen
                      secondary_info: last-changed
                    - entity: sensor.humidity_outdoor_average
                      name: Außen
                      icon: mdi:water-outline
                      secondary_info: last-changed
                    - entity: sensor.humidity_living_outdoor_difference
                      name: Differenz
                      icon: mdi:water-minus-outline
                    - entity: >-
                        input_number.ventilation_living_absolute_humidity_threshold
                      name: Toleranz
                    - entity: >-
                        input_number.ventilation_living_absolute_humidity_threshold_hysterese
                      name: Hysterese
                    - entity: input_boolean.ventilation_living
                  card_mod:
                    style:
                      .: |
                        ha-card { border: none; }
# Put your code/steps here
```

**Error messages from the browser console:**

```
CARD-MOD 3.4.4 IS INSTALLED
browser_mod.js?2.3.3:385 BROWSER_MOD 2.3.3 IS INSTALLED    BrowserID: xxx
...
card-mod.js?hacstag=190927524344:1 Card-mod warning

ha-chart-base.ts:297  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'darkMode')
    at i.value (ha-chart-base.ts:297:30)
    at i.value (ha-chart-base.ts:223:38)
value @ ha-chart-base.ts:297
value @ ha-chart-base.ts:223
await in value
value @ ha-chart-base.ts:123
_$AE @ reactive-element.ts:1395
performUpdate @ reactive-element.ts:1345
scheduleUpdate @ reactive-element.ts:1262
_$Ej @ reactive-element.ts:1237
await in _$Ej
requestUpdate @ reactive-element.ts:1215
_$Eu @ reactive-element.ts:950
w @ reactive-element.ts:932
S @ lit-element.ts:115
i @ ha-chart-base.ts:31
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
V @ lit-html.ts:2183
update @ lit-element.ts:166
performUpdate @ reactive-element.ts:1333
scheduleUpdate @ reactive-element.ts:1262
_$Ej @ reactive-element.ts:1237
await in _$Ej
requestUpdate @ reactive-element.ts:1215
_$Eu @ reactive-element.ts:950
w @ reactive-element.ts:932
S @ lit-element.ts:115
F @ state-history-chart-timeline.ts:26
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
T @ lit-html.ts:1618
_$AI @ lit-html.ts:1403
v @ lit-html.ts:1192
g @ lit-html.ts:1553
_$AI @ lit-html.ts:1384
V @ lit-html.ts:2183
update @ lit-element.ts:166
performUpdate @ reactive-element.ts:1333
scheduleUpdate @ reactive-element.ts:1262
_$Ej @ reactive-element.ts:1237
await in _$Ej
requestUpdate @ reactive-element.ts:1215
set @ reactive-element.ts:731
j @ lit-html.ts:1883
_$AI @ lit-html.ts:1825
v @ lit-html.ts:1192
g @ lit-html.ts:1540
_$AI @ lit-html.ts:1384
v @ lit-html.ts:1192
g @ lit-html.ts:1540
_$AI @ lit-html.ts:1384
V @ lit-html.ts:2183
update @ lit-element.ts:166
performUpdate @ reactive-element.ts:1333
scheduleUpdate @ reactive-element.ts:1262
_$Ej @ reactive-element.ts:1237
await in _$Ej
requestUpdate @ reactive-element.ts:1215
set @ reactive-element.ts:731
(anonym) @ hui-history-graph-card.ts:135
(anonym) @ history.ts:258
(anonym) @ connection.js:23
_handleMessage @ connection.js:15

ha-chart-base.ts:297  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'darkMode')
    at i.value (ha-chart-base.ts:297:30)
    at i.value (ha-chart-base.ts:223:38)
value @ ha-chart-base.ts:297
value @ ha-chart-base.ts:223
await in value
value @ ha-chart-base.ts:123
_$AE @ reactive-element.ts:1395
performUpdate @ reactive-element.ts:1345
scheduleUpdate @ reactive-element.ts:1262
_$Ej @ reactive-element.ts:1237
await in _$Ej
requestUpdate @ reactive-element.ts:1215
_$Eu @ reactive-element.ts:950
w @ reactive-element.ts:932
S @ lit-element.ts:115
i @ ha-chart-base.ts:31
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
V @ lit-html.ts:2183
update @ lit-element.ts:166
performUpdate @ reactive-element.ts:1333
scheduleUpdate @ reactive-element.ts:1262
_$Ej @ reactive-element.ts:1237
await in _$Ej
requestUpdate @ reactive-element.ts:1215
_$Eu @ reactive-element.ts:950
w @ reactive-element.ts:932
S @ lit-element.ts:115
F @ state-history-chart-line.ts:30
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
T @ lit-html.ts:1618
_$AI @ lit-html.ts:1403
v @ lit-html.ts:1192
g @ lit-html.ts:1553
_$AI @ lit-html.ts:1384
V @ lit-html.ts:2183
update @ lit-element.ts:166
performUpdate @ reactive-element.ts:1333
scheduleUpdate @ reactive-element.ts:1262
_$Ej @ reactive-element.ts:1237
await in _$Ej
requestUpdate @ reactive-element.ts:1215
set @ reactive-element.ts:731
j @ lit-html.ts:1883
_$AI @ lit-html.ts:1825
v @ lit-html.ts:1192
g @ lit-html.ts:1540
_$AI @ lit-html.ts:1384
v @ lit-html.ts:1192
g @ lit-html.ts:1540
_$AI @ lit-html.ts:1384
V @ lit-html.ts:2183
update @ lit-element.ts:166
performUpdate @ reactive-element.ts:1333
scheduleUpdate @ reactive-element.ts:1262
_$Ej @ reactive-element.ts:1237
await in _$Ej
requestUpdate @ reactive-element.ts:1215
set @ reactive-element.ts:731
(anonym) @ hui-history-graph-card.ts:135
(anonym) @ history.ts:258
(anonym) @ connection.js:23
_handleMessage @ connection.js:15
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
