### ISSUE TITLE
Feature Request: Interaction-Based Timeout for Pop-Up Auto-Close

### ISSUE THREAD

**Issue by OCT0PUSCRIME** [thomasloven/hass-browser_mod#804]
Description:
I’m using a browser mod pop-up to display a remote control for my TV. Currently, the pop-up auto-closes after a set timeout, which works fine, but I have to set the timeout relatively long to account for varying lengths of use.

Proposed Feature:
It would be helpful if the timeout timer started after the first user interaction and reset with each subsequent interaction. This would allow for a shorter timeout period without accidentally closing the pop-up during active use.

Use Case:
This feature would improve usability in scenarios where  widely varying length of interaction is expected, such as controlling a TV or other devices, without requiring excessively long timeout settings.

Acknowledgement:
I understand this is a niche use case and may involve additional complexity, but I wanted to share in case it's useful to others or aligns with future development goals.

**Comment by dcapslock** [comment]
Hi, the area of timeouts and what to do, reset, pause, etc. would mean a myriad of options to allow for config and coding. In that light I don't believe a base feature is easy to include. However, I have included below an option for you to consider which is straightforward to implement.

The solution is around making your own event listener that interacts with the key element that the current timeout is calculated from. In effect, resetting the coutdown timer. While this parameter is internal to Browser Mod and subject to change, I don't believe it will change any time soon.

First, update your Browser Mod popup code to use a sequence so you can create a javascript handler function, then add as an event listener. 

#### Example Setup Code

In this example I have included a delay, then two javascript calls, one to setup the handler if not so already from a pervious call, and one to setup event listener for "click". You may also need a correspondencing ones for "touchend", "pointerdown", "keydown" depending on your use case. You can include in one browser_mod.javascript call or separate them, no real difference just preference in how you wish to code/maintain.

Note: Yaml styling below for `code:` secitons as per Home Assistant Yaml editor on save.

```yaml
show_name: true
show_icon: true
type: button
name: Fake Entity Test
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.sequence
    data:
      sequence:
        - service: browser_mod.more_info
          data:
            entity: light.test
        - service: browser_mod.delay
          data:
            time: 100
        - service: browser_mod.javascript
          data:
            code: |
              if (!window.myHandler) window.myHandler = function() {
                window.browser_mod._popupEl._timeoutStart = new Date().getTime() }
        - service: browser_mod.javascript
          data:
            code: >
              if (window.myHandler) {
              window.browser_mod._popupEl.addEventListener("click",
              window.myHandler) }
```

#### Example Dismiss Code

Next, in your popup, include the following code to stop the event listeners. If you added other event listeners above, inclde removal of those listeners here.

```yaml
    dismiss_action:
      action: browser_mod.javascript
      data:
        code: >-
          if (window.myHandler) {
          window.browser_mod._popupEl.removeEventListener("click",
          window.myHandler) }
```

**Comment by OCT0PUSCRIME** [comment]
@dcapslock This was working phenomenally. Unfortunately I think 2.5.0 removed a bunch of functionality this workaround relied on.

**Comment by dcapslock** [comment]
@OCT0PUSCRIME. 2.5.0 refactored where popups are in the DOM, but also added some events that make this easier. Updated code below. Note the rearrangement as the javascript code needs to be run before the popup is shown as it listens for the new events "browser-mod-popup-opened" and "browser-mod-popup-closed". Tested to work with different popup tags which now allow multiple popups.

IMPORTANT: You popup no loner needs the dismiss action so it needs to be removed from your popup.

```yaml
show_name: true
show_icon: true
type: button
name: Fake Entity Test
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.sequence
    data:
      sequence:
        - service: browser_mod.javascript
          data:
            code: |
              if (!window.myHandler) window.myHandler = function(ev) {
                ev.target._timeoutStart = new Date().getTime();
              }              
              if (!window.myPopupListenersAdded) {
                window.myPopupListenersAdded = true;
                window.browser_mod.addEventListener("browser-mod-popup-opened", (ev) => {
                  ev.detail.popup.addEventListener("click", window.myHandler)
                });
                window.browser_mod.addEventListener("browser-mod-popup-closed", (ev) => {
                  ev.detail.popup.removeEventListener("click", window.myHandler);
                });
              }
        - service: browser_mod.delay
          data:
            time: 100
        - service: browser_mod.popup
          data:
            popup_card_id: timer1
```
