### ISSUE TITLE
Popup only shows full screen

### ISSUE THREAD

**Issue by TrevskiUK** [thomasloven/hass-browser_mod#805]
My Home Assistant version: 2024.2.2
Companion app on Android 15, Pixel 8.

I am running an action browser_mod.popup in an Automation.

**What I expected to happen:**
A popup window is displayed containing my message.

**What happened instead:**
A full screen is displayed with my message. This happens no matter what the setting of "Size" is.

**Minimal** steps to reproduce:
Run the action (see below)

```yaml
# The least amount of code or steps possible to reproduce my error

alias: Bed Heat away toggle popup
description: ""
triggers:
  - trigger: state
    entity_id:
      - input_boolean.bed_heat_away_toggle
conditions: []
actions:
  - action: browser_mod.popup
    metadata: {}
    data:
      dismissable: true
      autoclose: true
      browser_id:
        - ccf5712711c219d3b2565912f02e20e3
      content: >-
        Home/Away mode is now  {% set t =
        states('input_boolean.bed_heat_away_toggle') %} {% if t == 'on' %}
        Active.  {% else %} Deactivated. {% endif %} 
mode: single

```

**Error messages from the browser console:**
None 
```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [ x] Have made sure I am using the latest version of the plugin.

- [ x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x

![Image](https://github.com/user-attachments/assets/89d66cc4-7a13-46a8-929d-23234b5b2e98)

 ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
