### ISSUE TITLE
Media player entity unavailable on any Android device.

### ISSUE THREAD

**Issue by crixle** [thomasloven/hass-browser_mod#808]
My Home Assistant version: 2025.1.2
My Browser Mod version: 2.3.3

**What I am doing:**
Enrolling Android devices using WallPanel, Chrome, and Firefox

**What I expected to happen:**
A working media player entity for any of the registered clients.

**What happened instead:**
All media players registered to an Android browser mod client are constantly unavailable on multiple OS versions.

**Minimal** steps to reproduce:
* Register Android device through WallPanel, Chrome, or Firefox on Android 6, 10, and 13.

```yaml
# The least amount of code or steps possible to reproduce my error
Not applicable.
# Put your code/steps here
```
1. Open Browser Mod panel
2. Name the device
3. Click on the Register toggle
4. Reload page, reboot device, etc
5. Open new Browser Mod client device.

* Have tried updating WebView to latest build and the dev build.

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it
Cannot view console on Android device (also cannot be rooted)
// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X ] Have made sure I am using the latest version of the plugin.

- [ X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by lpt2007** [comment]
I have same problem. In my case media player is unavailible all the time(but working anyway after refresh ), other entities become unavailible after couple of hours.
I made automation to refresh ha when unavailible entity apears.

```
alias: At startup or in unknown or unavailable state, ha reactivates speech via browser_mod media player on alarm-panel
description: ""
triggers:
  - event: start
    trigger: homeassistant
conditions:
  - condition: or
    conditions:
      - condition: state
        entity_id: light.alarm_panel_screen
        state: unavailable
      - condition: state
        entity_id: light.alarm_panel_screen
        state: unknown
    enabled: false
actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
  - action: mqtt.publish
    data:
      evaluate_payload: false
      qos: 0
      retain: false
      topic: home/alarm/command
      payload: "{\"wake\": true, \"wakeTime\": 180}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
  - action: mqtt.publish
    data:
      evaluate_payload: false
      qos: 0
      retain: false
      topic: home/alarm/command
      payload: "{\"reload\": true}"
mode: single
```
