### ISSUE TITLE
Statistics not shown in popups

### ISSUE THREAD

**Issue by Phoenix-DH** [thomasloven/hass-browser_mod#814]
My Home Assistant version: 2025.2.4

**What I am doing:**
I have a browser_mod popup with some statistics and other stuff. This is not showing anymore. Only blank fields.
When I use the same code UI to test, everything is working and showing. This should show that there might be no issue with the combination of types, but with the popup itself.

**What I expected to happen:**
Show the whole content.

**What happened instead:**
For the stats, only blank fields are there. The entities only are shown.

**Minimal** steps to reproduce:
This is the code from the popup:

```yaml
action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: Regen Statistik
    size: wide
    #autoclose: true
    timeout: 180000
    hide_header: false
    content:
        type: custom:layout-card
        layout_type: custom:grid-layout
        layout:
          grid-template-columns: 50% 50%
          grid-template-areas: |
            "left right"
        cards:
          - type: vertical-stack
            cards:
              - chart_type: line
                period: hour
                type: statistics-graph
                entities:
                  - entity: sensor.esszimmer_esszimmer_esszimmer_regenmesser_rain_last_hour
                    name: Niederschlag letzte Stunde
                stat_types:
                  - state
                days_to_show: 1
              - chart_type: line
                period: day
                type: statistics-graph
                entities:
                  - entity: sensor.niederschlag_letzte_7_tage_in_mm
                    name: Niederschlag letzte 7 Tage
                stat_types:
                  - mean
                logarithmic_scale: false
                days_to_show: 7
            view_layout:
              grid-area: left
          - type: vertical-stack
            cards:
              - type: entity
                entity: sensor.esszimmer_esszimmer_esszimmer_regenmesser_rain_today
                name: Heute
              - type: entity
                entity: input_number.niederschlag_gestern_in_mm
                name: Gestern
              - type: entity
                entity: input_number.niederschlag_vorgestern_in_mm
                name: Vorgestern
              - chart_type: line
                period: week
                type: statistics-graph
                entities:
                  - entity: sensor.esszimmer_esszimmer_esszimmer_regenmesser_rain_today
                    name: Niederschlag letzte 365 Tage
                name: Test
                stat_types:
                  - change
                days_to_show: 365
            view_layout:
              grid-area: right
```

**Error messages from the browser console:**

No errors visible.

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
