### ISSUE TITLE
Selection by deviceID is broken

### ISSUE THREAD

**Issue by Eckart0** [thomasloven/hass-browser_mod#829]
My Home Assistant version: 2025.4

Because I don't know whether the error is due to BrowserMod or state-switch, I am also reporting an error here:

I want to use lovelace-state-switch to hide maps on some tablets using the deviceID.
This does not work as soon as I have renamed the deviceID in the browser mod settings.

An example: deviceID, issued with commandl "localStorage["lovelace-player-device-id"] into your browsers console"
In Browser-Mod deviceID renamed to "k68w14-chrome"

The results are:

```
type: custom:state-switch
entity: deviceID
default: default
states:
  1b22b00b-fe70767a:
    type: markdown
    content: |
      Desktop ID_unrenamed
  k68w14-chrome:
    type: markdown
    content: |
      Desktop ID_renamed
  default:
    type: markdown
    content: |
      Default      

```
ejects: Desktop ID_unrenamed

```
type: custom:state-switch
entity: deviceID
default: default
states:
  k68w14-chrome:
    type: markdown
    content: |
      Desktop
  default:
    type: markdown
    content: |
      Default      

```
ejects: Default

Regards, Eckart

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [ x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [ x] Have made sure I am using the latest version of the plugin.

- [ x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
