### ISSUE TITLE
browser_mod.popup button action does nothing

### ISSUE THREAD

**Issue by safrimus** [thomasloven/hass-browser_mod#837]
My Home Assistant version: 2025.4.4

**What I am doing:**
I have an automation that opens a browser_mod.popup when someone rings my doorbell. This works well to show a live feed of the camera. I also want to add a button to the popup that when clicked, will close the popup and open a dashboard that has all a live view of all my cameras.

My hardware is a Fire HD tablet running full kiosk.

**What I expected to happen:**
When the "View All" button is clicked, the popup closes and /dashboard-tablet/camerakiosk opens.

**What happened instead:**
The popup just closes when button is clicked.

**Minimal** steps to reproduce:
Created an automation that runs the browser_mod.popup action on doorbell press trigger. This is the yaml for the browser_mod.popup action I'm using:

```yaml
action: browser_mod.popup
data:
  dismissable: false
  size: fullscreen
  timeout: 120000
  browser_id:
    - tablet_browser
  content:
    type: custom:webrtc-camera
    url: rtsp://...
    mode: webrtc
  right_button: View All
  right_button_action:
    action: browser_mod.navigate
    data:
      browser_id: tablet_browser
      path: /dashboard-tablet/camerakiosk
```

If I run just the browser_mod.navigate action using developer tools, that works. But nothing happens when the button is clicked in the popup other than the popup closing. 

**Error messages from the browser console:**
No related error messages in the fully kiosk logs.

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
