### ISSUE TITLE
Missing Popup Card Cards Option

### ISSUE THREAD

**Issue by KyleStilkey** [thomasloven/hass-browser_mod#840]
I like to use this popup card for multiple camera views, with the latest version of Home Assistant it seems that the button to select cards is missing. I can edit these entries in the yaml/code but there use to be a way where I could click a cards button and I could easily edit all my entries, now I can no longer do this.

Here is an example code of what I use to show multiple cameras, but I can no longer edit each entry through the UI, I now how to rely on using the code editor.

```
type: vertical-stack
cards:
  - show_name: true
    show_icon: true
    type: button
    entity: input_button.cameras_button
    show_state: false
    icon_height: 50px
    name: Cameras
  - type: custom:popup-card
    entity: input_button.cameras_button
    dismissable: true
    card:
      type: vertical-stack
      cards:
        - type: horizontal-stack
          cards:
            - camera_view: live
              type: picture-glance
              entities:
                - entity: switch.side_doorbell_power
                - entity: siren.side_doorbell_siren
              title: Side Door Doorbell
              camera_image: camera.side_door_doorbell
            - camera_view: live
              type: picture-glance
              title: Side Door Left
              entities:
                - entity: switch.outside_side_door_camera_left_power
                - entity: siren.outside_side_door_camera_left_siren
                - entity: light.outside_side_door_camera_left_floodlight
              camera_image: camera.outside_side_door_camera_left
        - camera_view: live
          type: picture-glance
          title: Front Doorbell
          entities: []
          camera_image: camera.03cabcc9_ring_mqtt_3
        - type: horizontal-stack
          cards:
            - camera_view: live
              type: picture-glance
              entities: []
              camera_image: camera.outside_front_door_camera_left_profile_0
              title: Front Door Left
            - camera_view: live
              type: picture-glance
              entities: []
              camera_image: camera.outside_front_door_camera_right_profile_0
              title: Front Door Right
        - type: horizontal-stack
          cards:
            - camera_view: live
              type: picture-glance
              title: Basement Doorbell
              image: https://demo.home-assistant.io/stub_config/kitchen.png
              entities:
                - entity: switch.basement_doorbell_camera_feed_live_stream
              camera_image: camera.basement_bathroom
            - camera_view: live
              type: picture-glance
              title: Outside Deck Floodlight
              entities:
                - entity: switch.dining_room_kitchen_light_switch_top
              camera_image: camera.outside_deck_floodlight_camera_profile_0
    size: normal
```
