### ISSUE TITLE
[Bug]: More-info popup not open

### ISSUE THREAD

**Issue by IgorSimic** [thomasloven/hass-browser_mod#852]
### My Home Assistant Version

Core: 2025.5.2
Frontend: 20250516.0

### What I am doing

Updated to v2.3.8 and all my more-info popus with custom:popup-card gone, just original more-info for entity is displayed.

Version 2.3.3 workking as expected, so I revert back to it.

My test code, popup card:
```
type: custom:popup-card
entity: sensor.sun_next_dawn
title: Sun.sun popup
dismissable: true
size: normal
card:
  type: markdown
  content: Test popup content for more-info sensor.sun_next_dawn entity.
```

Initiator card (click on entity should open popup):
```
type: entities
entities:
  - entity: sensor.sun_next_dawn
```

**Comment by dcapslock** [comment]
Checking you have done a frontend refresh. Although the code is there for cache busting of JS file, I have noted some users need to refresh. Check if you can see your Browser Mod panel and what version shows there.

**Comment by IgorSimic** [comment]
I cleared cache and refresh page.
When I install 2.3.8, nothing happens until I clear cache. When I do more-info popups starts behave as I described.
Same with returning to 2.3.3.

**Comment by dcapslock** [comment]
So I understand you well, 2.3.78 works after clearing cache. If you want that looked into please share browser details and console log while Browser Mod is not working. As much as possible Browser Mod attemps to process frontend JS file correctly on upgrade.

**Comment by IgorSimic** [comment]
No  2.3.8 not working after clearing cache.

**Comment by dcapslock** [comment]
Thanks for clarifying. Can you share browser Console log showing what version is loading?

**Comment by IgorSimic** [comment]
I doble checked...
It looks like, more-info popup work with 2.3.8 too, but not inside custom:bootstrap-grid-card panel.
I need to investigate this and I'll be back with simple example.

**Comment by dcapslock** [comment]
I note there is a change from 2.3.4 which changes the way a popup card is found. In 2024 there was a workaround to an edit view issue that suggested to nest a card one level deep. So 2.3.8 allows for this as well. If you have custom:popup-card nested any further, that is not expected but may have worked previoulsy but led to edit view issues etc.

**Comment by dcapslock** [comment]
I have looked at custom:bootstrap-grid-card panel and have found that the card depth is important. If you have the custom:popup-card in a bootstrap row then that is too deep for 2.3.8. If you have as a card in its own at a level one deep then it will work, and semantically makes more sense with config. 

The test config is extended from custom:bootstrap-grid-card example.

### Working

This works and looks as you would expect as for layout, as you don't need to work out how to account for the hidden card in a row.

```yaml
type: custom:bootstrap-grid-card
cards:
  - type: row
    cards:
      - type: button
        class: col-xs-12 col-md-6 col-xxl-3
        name: Button 1
      - type: button
        class: col-xs-12 col-md-6 col-xxl-3
        name: Button 2
      - type: button
        class: col-xs-12 col-md-6 col-xxl-3
        name: Button 3
      - type: button
        class: col-xs-12 col-md-6 col-xxl-3
        name: Button 4
  - type: row
    class: justify-content-center
    cards:
      - type: entity
        class: col-xs-12 col-md-3 col-xxl-4
        entity: sun.sun
      - type: entity
        class: col-xs-12 col-md-8 col-xxl-10
        entity: sensor.sun_next_dawn
  - type: custom:popup-card
    entity: sun.sun
    title: Sun.sun popup
    dismissable: true
    size: normal
    card:
      type: markdown
      content: Test popup content for more-info sun.sun entity.
```

### Won't work with Browser Mod

This does not work and having the custom:popup-card in a row affects the layout. Perhaps you can wrap in another card but that will also not be found by Browser Mod.

```yaml
type: custom:bootstrap-grid-card
cards:
  - type: row
    cards:
      - type: button
        class: col-xs-12 col-md-6 col-xxl-3
        name: Button 1
      - type: button
        class: col-xs-12 col-md-6 col-xxl-3
        name: Button 2
      - type: button
        class: col-xs-12 col-md-6 col-xxl-3
        name: Button 3
      - type: button
        class: col-xs-12 col-md-6 col-xxl-3
        name: Button 4
  - type: row
    class: justify-content-center
    cards:
      - type: entity
        class: col-xs-12 col-md-3 col-xxl-4
        entity: sun.sun
      - type: entity
        class: col-xs-12 col-md-8 col-xxl-10
        entity: sensor.sun_next_dawn
      - type: custom:popup-card
        entity: sun.sun
        title: Sun.sun popup
        dismissable: true
        size: normal
        card:
          type: markdown
          content: Test popup content for more-info sun.sun entity.
```
