### ISSUE TITLE
[Bug]: Unable to open custom popup with fire-dom-event more_info

### ISSUE THREAD

**Issue by gdozzi** [thomasloven/hass-browser_mod#859]
### My Home Assistant Version

Core: 2025.5.3
Frontend: 20250516.0
browser_mod: 2.3.8

### What I am doing

I'm tring to open a custom:popup-card (with a fake entity id) with an fire-dom-event 

### What I expect to happen

I expect to see the custom popup (as it happens correctly with version 2.3.3) 

### What happened instead

I see the default more-info popup of home assistant

### Minimal steps to reproduce

1. Define a custom:popup-card with a fake id (eg an id not associated with any entity)
2. Define an action fire-dom-event with the same fake id 
3. Try

### Include any yaml code here

```YAML
YAML for event generation:

- type: template
        tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.more_info
            data:
              entity: light.test
        ...

YAML of custom:popup-card
type: custom:popup-card
    dismissable: true
    title: Test
    entity: light.test
    card:
      type: vertical-stack
      cards:
        ...
```

### Error messages from the browser console

```console

```

### By checking each box below I indicate that I ...

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
- [x] If this issue is to do with an Android device losing connection, sensors becoming unavailable etc., please confirm you have read, understood and tried methods described in Wiki Article [Andoird Devices 'Always On'](https://github.com/thomasloven/hass-browser_mod/wiki/Andoird-Devices-'Always-On')

**Comment by dcapslock** [comment]
@gdozzi I have tested your config and it works. I am thinking that you may have your custom:popup-card more than one level deep in your dashboard config. This is not epxetced and 2.3.8 will not find deep custom popup cards. 

#### OK

```yaml
type: vertical-stack
cards:
  - type: custom:popup-card
    title: Fake Entity Popup - light.test
    dismissable: true
    card:
      type: markdown
      content: This replaces the more-info dialog
    entity: light.test
```

#### Not OK - Card will not be found.
```yaml
type: vertical-stack
cards:
  - type: vertical-stack
    cards:
      - type: custom:popup-card
        title: Fake Entity Popup - light.test
        dismissable: true
        card:
          type: markdown
          content: This replaces the more-info dialog
        entity: light.test
```

**Comment by gdozzi** [comment]
Hi @dcapslock! thank you so much for your help, it was a great solution! The custom-popups were at level 2 compared to the dashboard. I moved them to level 1 and everything works fine! I think it would be useful to add this info to the doc, so that it is tracked correctly! Thanks for the help and for your work!

**Comment by lambros414** [comment]
I am having the same issue.  I have my pop-up a couple of levels deep - in many circumstances.  It is needed for the design of my dashboard.  Just so I can understand.... did pop-ups previously work when several level's deep and then stop in 2.3.8?  The comment above said:

" I am thinking that you may have your custom:popup-card more than one level deep in your dashboard config. This is not epxetced and 2.3.8 will not find deep custom popup cards."

Is this a change in design, a feature that has gone away because of other code, or a bug?

Someone above was able to solve the problem my moving their cards up to level one.  Because of the nature of my dashboards and card_mods used... I have been relying on being able to go a few levels deep.  Will this not be working moving forward or is there a change in the works?

I'm just trying to understand better.

**Comment by PeterPalenik** [comment]
@dcapslock I need to load popup cards dynamically based on some entities selected by a template. For it I have a custom popup card in an auto-entities card (in a vertical stack), so for me it stopped working since the change from 2.3.3 to 2.3.8. Is there a way how to do it without the 2 levels/would it be possible to add one more level to the lookup?

Here is an example that works on the older version:

```
  - type: custom:auto-entities
    filter:
      include:
        - options:
            type: custom:popup-card
            title: Custom popup
            dismissable: true
            entity: this.entity_id
            card:
              type: markdown
              content: This replaces the more-info dialog
          entity_id: weather.home
      exclude: []
    card:
      type: vertical-stack
    show_empty: false
    card_param: cards
  - type: entities
    entities:
      - entity: weather.home

```

**Comment by dcapslock** [comment]
@PeterPalenik Browser Mod now looks for popup cards in the config, not in what any custom cards have processed from the config. So this is more about Browser Mod not supporting popup cards generated by auto-entities and other like cards (config-template-card, decluttering-card etc). It would be very inefficient for Browser Mod to load each card just in case the card generates a popup card for it to find. The changes in 2.3.8 brought a controller approach to popup cards, in that the main code finds a popup card, rather that the popup card acting on its own listening for `more-info` events. This now allows for popup cards to be in a different view, as all views are available for it Browser Mod to search for a popup card.

Without knowing more about your actual config, your example leads me to wonder if what you are trying to achieve is using auto-entities to ease generating the same popup card for multiple entities. If so then take a look at the proposed feature request (#908) where it is proposed to use target selector for popup card rather than a single entity. This would support multiple entities, areas, labels, devices. So in this way you can share a popup card very broadly - e.g. all entities with a label is quite configurable and you could have a label just for popup card matching. If this feature request would provide an alternative way to gain your outcome, please leave a comment on the feature request (code is actually ready to go and a 2.5.0 alpha would not be far away).

**Comment by PeterPalenik** [comment]
Thanks for the reply. I see. I somehow missed this breaking change in the release notes/did not connect the dots. Yeah the new feature looks good. That's what I'm trying to do - to create a popup card for multiple entities. This new approach will be much more efficient in my use case because this on the fly generation of popup cards was really slow and was hitting the limits of HA max template output. Not sure if it will solve my use-case yet, because I generate the entities dynamically using pyscript, so will have to look if it would be possible to generate some common area/device/label for these entities so that I can properly match them.

**Comment by dcapslock** [comment]
Not included in the FR, but in my code, is the adding of `target:` to `browser_mod.more_info`. So you would be able to add to other cards an action like that below to target a label that is only on the popup card in another view. That way a label could be exclusively used for matching more_info to popup card. The one caveat of this is that the target selector does not show labels not connect to anything, but will work fine in yaml.

```yaml
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.more_info
    target:
      label_id: 
        - my_label
```

```yaml
type: custom:popup-card
target:
  label:
    - my_label
...
```

**Comment by PeterPalenik** [comment]
Today I had some time to get back to this on the newest browser_mod version. I was able to use the target to select all my entities I need and it nicely opened when I clicked some of them. The problem is that I need to show some entity specific info in the popup card, like history graph etc and run some action based on the selected entity. But I'm unable to do it because I have no information which entity was clicked. Would it be somehow possible to access eg. an entity_id variable in templates? Or is there some other way I'm missing?

**Comment by dcapslock** [comment]
@PeterPalenik There is no entity_id natively available. As to use entity_id needs a javascript template approach I see it as an advanced feature and to include it in some way would probably lead to more support queries from those who may not understand templating, especially with what AI can spit out as incorrect solutions.

Given your advanced use, you can look at my example below to use a button-card to add an event listener to `hass-more-info` and store the entityId for later use. I assume you would be using javascript templates in your approach.

Full section yaml below. For testing I am setting two entities directly on popup - adjust to suit. Note: if you adjust the code in button-card that sets up the listener, which only does it once, you will need to refresh your page.

```yaml
type: grid
cards:
  - type: heading
    heading_style: title
    heading: More-Info Entity
  - type: custom:button-card
    name: more-info watcher
    variables:
      moreInfoWatcher: |
        [[[
          if (!window.customMoreInfoWatcher) {
            window.customMoreInfoWatcher = true
            window.addEventListener("hass-more-info", (ev) => {
              if (ev.detail?.entityId !== "") {
                window.customMoreInfoEntityID = ev.detail?.entityId;
                console.log(`hass-more-info: ${ev.detail?.entityId}`);
              }
            });
          }
        ]]]
    styles:
      card:
        - display: |
            [[[
              return this.preview ? "block" : "none"
            ]]]
  - type: custom:popup-card
    title: Custom more-info entity
    dismissable: true
    popup_card_id: custom-more-info
    target:
      entity_id:
        - sensor.sun_next_midnight
        - sensor.sun_next_noon
    card:
      type: custom:button-card
      entity: |
        [[[
          return window.customMoreInfoEntityID ?? ""
        ]]]
      section_mode: true
      grid_options:
        rows: 2
        columns: 6
  - type: entities
    entities:
      - entity: sensor.sun_next_midnight
      - entity: sensor.sun_next_noon
```

**Comment by dcapslock** [comment]
popup card with custom-more-info card to show how to use entity for any card.

```yaml
type: custom:popup-card
title: Custom more-info entity
dismissable: true
popup_card_id: custom-more-info
target:
  entity_id:
    - sensor.sun_next_midnight
    - sensor.sun_next_noon
card:
  type: custom:button-card
  show_name: false
  show_icon: false
  styles:
    card:
      - border: 0
      - padding: 0
    grid:
      - grid-template-areas: "\"more-info\""
  custom_fields:
    more-info:
      card:
        type: custom:more-info-card
        entity: |
          [[[
            return window.customMoreInfoEntityID ?? ""
          ]]]
  entity: |
    [[[
      return window.customMoreInfoEntityID ?? ""
    ]]]
  section_mode: true
  grid_options:
    rows: 2
    columns: 6

```
