### ISSUE TITLE
Login attempt or request with invalid authentication

### ISSUE THREAD

**Issue by antoinevandenhurk** [thomasloven/hass-browser_mod#86]
Ever since I installed "browser_mod" via HACS, I receive an error of login attempt or request with invalid authentication of 192.168.1.36. The IP address belongs to a tablet which functions as a dashboard.

> Logboekdetails ( WARNING )
Logger: homeassistant.components.http.ban
Source: components/http/ban.py:74
Integration: http ([documentation](https://www.home-assistant.io/integrations/http), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+http%22))
First occurred: 19:09:20 (5763 occurrences)
Last logged: 20:07:01

> Login attempt or request with invalid authentication from 192.168.1.36
> Login attempt or request with invalid authentication from 172.30.33.7

I have created a separate user for the tablet, with admin rights.

/config/configuration.yaml:
```
browser_mod:
  prefix: "browser_"
  devices:
    8b5a7724-10b7d17c:
      name: antoine_z400
    df51e7b2-da7fd613:
      name: fam_z400
    6f0ad3e2-df119023:
      name: fam_V10Pro
    212673e9_3caffe7c:
      name: dashboard
#
http:
  base_url: !secret base
```
The notifications appear every second, making HASS unstable every now and then.
