### ISSUE TITLE
Version 2.3.8 - Check for custom:popup-card not working

### ISSUE THREAD

**Issue by dcapslock** [thomasloven/hass-browser_mod#863]
There have been issues with 2.3.8 (2.3.4 to 2.3.7 in _Phoenix_ fork) where custiom popup cards (custom:popup-card) would stop working. The root of those issues has been to do with a change in 2.3.8 (2.3.4 in _Phoenix_ fork) in how custom popup cards are found in the Dashboard. Version 2.3.4 only found cards at the first level of a Dashboard. Version 2.3.8 was adjusted to find cards one level deep. The choice of level is one of efficiency and simplicity.

### Reasons why custom popup cards may be one level deep

1. The Dashboard is a Panel with one card.
2. User applied a suggested 2024 workaround to workaround an edit view issue at the time.
3. Desire to structure the Dashboard to keep custom popup cards near where they are used.

#### OK

```yaml
type: vertical-stack
cards:
  - type: custom:popup-card
    title: Custom Popup
    dismissable: true
    card:
      type: markdown
      content: This replaces the more-info dialog
    entity: sun.sun
```

#### Not OK - Card will not be found.

```yaml
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: custom:popup-card
        title: Custom Popup
        dismissable: true
        card:
          type: markdown
          content: This replaces the more-info dialog
        entity: sun.sun
```
