### ISSUE TITLE
[Bug]: custom:popup-card no working on bage sinbce last version

### ISSUE THREAD

**Issue by llaumgui** [thomasloven/hass-browser_mod#868]
### My Home Assistant Version

Core : 2025.5.3

### What I am doing

Since the last version, my "custom:popup-card" not working on badges (top of the page). The other place widget continue to work.

### What I expect to happen

Keep working.

### What happened instead

The clic even is not override by the popup.

### Minimal steps to reproduce

1.
2.
3.
...

### Include any yaml code here

```YAML
badges:
      - type: custom:mushroom-template-badge
        content: |-
          {% if (states(entity) == 'unknown') %}
            Absent
          {%- else -%}
            {{ state_translated(entity) }}
          {%- endif %}
        icon: ''
        color: ''
        entity: person.llaumgui
        picture: |
          {% if (states(entity) == 'home') %}
            /local/presence/guillaume_on.jpg
          {%- else -%}
            /local/presence/guillaume_off.jpg
          {%- endif %}
        label: ''
        tap_action:
          action: more-info
      - type: custom:mushroom-template-badge
        content: |-
          {% if (states(entity) == 'unknown') %}
            Absent
          {%- else -%}
            {{ state_translated(entity) }}
          {%- endif %}
        icon: ''
        color: ''
        picture: |
          {% if (states(entity) == 'home') %}
            /local/presence/emma_on.jpg
          {%- else -%}
            /local/presence/emma_off.jpg
          {%- endif %}
        label: ''
        entity: person.emma
        tap_action:
          action: more-info
      - type: custom:mushroom-template-badge
        content: |-
          {% if (states(entity) == 'unknown') %}
            Absent
          {%- else -%}
            {{ state_translated(entity) }}
          {%- endif %}
        icon: ''
        color: ''
        picture: |
          {% if (states(entity) == 'home') %}
            /local/presence/lilian_on.jpg
          {%- else -%}
            /local/presence/lilian_off.jpg
          {%- endif %}
        label: ''
        entity: person.lilian_kulakowski
        tap_action:
          action: more-info
      - type: custom:mushroom-template-badge
        content: Courrier
        icon: mdi:email-newsletter
        color: blue
        label: ''
        visibility:
          - condition: state
            entity: input_boolean.boite_aux_lettres
            state: 'on'
        tap_action:
          action: toggle
        entity: input_boolean.boite_aux_lettres
        hold_action:
          action: more-info
      - type: custom:mushroom-template-badge
        content: Grise
        icon: phu:garbage-residual
        color: brown
        entity: schedule.poubelle_grise
        label: Poubelle
        visibility:
          - condition: state
            entity: schedule.poubelle_grise
            state: 'on'
        tap_action:
          action: none
        hold_action:
          action: none
        double_tap_action:
          action: none
      - type: custom:mushroom-template-badge
        content: Jaune
        icon: mdi:recycle
        color: green
        entity: schedule.poubelle_jaune
        label: Poubelle
        visibility:
          - condition: state
            entity: schedule.poubelle_jaune
            state: 'on'
        double_tap_action:
          action: none
        hold_action:
          action: none
        tap_action:
          action: none
      - type: custom:mushroom-template-badge
        content: '{{ states(entity) }}%'
        icon: mdi:battery-20
        color: orange
        entity: sensor.dacia_gd814qs_batterie
        label: Dacia Spring
        visibility:
          - condition: numeric_state
            entity: sensor.dacia_gd814qs_batterie
            below: 20
        tap_action:
          action: more-info
      - type: custom:mushroom-template-badge
        content: '{{ states(entity) }}°C'
        icon: mdi:fridge-alert
        color: '#EF5350'
        label: Frigo {{ area_name(entity) | lower }}
        visibility:
          - condition: numeric_state
            entity: automation.alert_temperature_frigo_congelateur
            above: 8.9
        entity: sensor.thermo_hygro_cuisine_frigo_temperature
      - type: custom:mushroom-template-badge
        content: '{{ states(entity) }}°C'
        icon: mdi:fridge-industrial-alert
        color: '#EF5350'
        label: Congélateur {{ area_name(entity) | lower }}
        visibility:
          - condition: numeric_state
            entity: sensor.thermo_hygro_garage_congelateur_temperature
            above: -15
        entity: sensor.thermo_hygro_garage_congelateur_temperature
        tap_action:
          action: more-info
      - type: custom:mushroom-template-badge
        content: Fumée
        icon: mdi:smoke
        color: '#EF5350'
        label: '{{ floor_name(entity) }}'
        visibility:
          - condition: state
            entity: binary_sensor.fumee_smoke
            state: 'on'
        entity: binary_sensor.smoke_detector_rdc_smoke
        tap_action:
          action: more-info
      - type: custom:mushroom-template-badge
        content: Fumée
        icon: mdi:smoke
        color: '#EF5350'
        label: '{{ floor_name(entity) }}'
        visibility:
          - condition: state
            entity: binary_sensor.smoke_detector_1er_smoke
            state: 'on'
        entity: binary_sensor.smoke_detector_1er_smoke
        tap_action:
          action: more-info
      - type: custom:mushroom-template-badge
        content: '{{ state_translated(entity) }}'
        icon: mdi:water-alert
        color: '#42A5F5'
        label: '{{ area_name(entity) }}'
        visibility:
          - condition: state
            entity: >-
              binary_sensor.water_leak_detector_buanderie_machine_a_laver_water_leak
            state: 'on'
        entity: binary_sensor.water_leak_detector_buanderie_machine_a_laver_water_leak
        tap_action:
          action: more-info
      - type: custom:mushroom-template-badge
        content: '{{ state_translated(entity) }}'
        icon: mdi:water-alert
        color: '#42A5F5'
        label: '{{ area_name(entity) }}'
        visibility:
          - condition: state
            entity: >-
              binary_sensor.water_leak_detector_cuisine_lave_vaisselle_water_leak
            state: 'on'
        entity: binary_sensor.water_leak_detector_cuisine_lave_vaisselle_water_leak
        tap_action:
          action: more-info
      - type: custom:mushroom-template-badge
        content: >-
          {{ expand(entity) | selectattr('state', 'eq', 'open') | list | count
          }} / {{ expand(entity) | list |count }}
        icon: mdi:window-shutter-open
        color: >-
          {% if expand(entity) | selectattr('state', 'eq', 'open') | list |
          count > 0 %}
            #42A5F5
          {% else %}
            grey
          {% endif %}
        entity: cover.shutter_group_maison
        tap_action:
          action: more-info
        hold_action:
          action: toggle
      - type: custom:mushroom-template-badge
        content: >-
          {{ expand(entity) | selectattr('state', 'eq', 'on') | list | count }}
          / {{ expand(entity) | list |count }}
        icon: phu:aqara-motion
        color: >-
          {% if expand(entity) | selectattr('state', 'eq', 'open') | list |
          count > 0 %}
            orange
          {% else %}
            grey
          {% endif %}
        entity: binary_sensor.motion_sensor_groupe_maison
        hold_action:
          action: none
        tap_action:
          action: more-info
      - type: custom:mushroom-template-badge
        content: >-
          {{ expand(entity) | selectattr('state', 'eq', 'on') | list | count }}
          / {{ expand(entity) | list |count }}
        icon: >-
          {% if expand(entity) | selectattr('state', 'eq', 'on') | list | count
          > 0 %}
            phu:double-window-open
          {% else %}
            phu:double-window-closed
          {% endif %}
        color: >-
          {% if expand(entity) | selectattr('state', 'eq', 'on') | list | count
          > 0 %}
            orange
          {% else %}
            grey
          {% endif %}
        entity: binary_sensor.open_sensor_group_fenetre
        tap_action:
          action: more-info
        hold_action:
          action: toggle
      - type: custom:mushroom-template-badge
        content: >-
          {{ expand(entity) | selectattr('state', 'eq', 'on') | list | count }}
          / {{ expand(entity) | list |count }}
        icon: >-
          {% if expand(entity) | selectattr('state', 'eq', 'on') | list | count
          > 0 %}
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}
        color: >-
          {% if expand(entity) | selectattr('state', 'eq', 'on') | list | count
          > 0 %}
            orange
          {% else %}
            grey
          {% endif %}
        entity: binary_sensor.open_sensor_group_door
        tap_action:
          action: more-info
        hold_action:
          action: toggle
      - type: custom:popup-card
        entity: cover.shutter_group_maison
        title: Volets maison
        content:
          state_color: true
          type: entities
          entities:
            - entity: cover.shutter_group_maison
            - type: divider
            - entity: cover.shutter_group_1er_etage
            - entity: cover.shutter_chambre_parentale
              name: Chambre parentale
            - entity: cover.shutter_chambre_lilian
              name: Chambre Lilian
            - entity: cover.shutter_chambre_robin
              name: Chambre Robin
            - entity: cover.shutter_degagement
              name: Dégagement
            - type: divider
            - entity: cover.shutter_group_rez_de_chaussee
            - entity: cover.shutter_salon
              name: Salon
            - entity: cover.shutter_salle_a_manger
              name: Salle à manger
            - entity: cover.shutter_cuisine
              name: Cuisine
          show_header_toggle: true
          card_mod:
            style: |
              ha-card {
                background: none !important;
              }
        size: normal
      - type: custom:popup-card
        entity: binary_sensor.motion_sensor_groupe_maison
        title: Fenetres maison
        content:
          state_color: true
          type: entities
          entities:
            - entity: binary_sensor.motion_sensor_chambre_parentale_occupancy
              name: Chambre parentale
              secondary_info: last-changed
            - entity: binary_sensor.motion_sensor_chambre_lilian_occupancy
              name: Chambre Lilian
              secondary_info: last-changed
            - entity: binary_sensor.motion_sensor_chambre_robin_occupancy
              name: Chambre Robin
              secondary_info: last-changed
            - entity: binary_sensor.motion_sensor_degagement_occupancy
              name: Dégagement
              secondary_info: last-changed
            - type: divider
            - entity: binary_sensor.motion_sensor_salon_entree_occupancy
              name: Entrée
              secondary_info: last-changed
            - entity: binary_sensor.motion_sensor_salon_occupancy
              name: Salon
              secondary_info: last-changed
            - entity: binary_sensor.motion_sensor_salle_a_manger_occupancy
              name: Salle à manger
              secondary_info: last-changed
            - entity: binary_sensor.motion_sensor_garage_occupancy
              name: Garage
              secondary_info: last-changed
          card_mod:
            style: |
              ha-card {
                background: none !important;
              }
        size: normal
      - type: custom:popup-card
        entity: binary_sensor.open_sensor_group_fenetre
        title: Fenetres maison
        content:
          state_color: true
          type: entities
          entities:
            - entity: binary_sensor.open_sensor_window_chambre_parentale_contact
              name: Chambre parentale
              secondary_info: last-changed
            - entity: binary_sensor.open_sensor_window_chambre_lilian_contact
              name: Chambre Lilian
              secondary_info: last-changed
            - entity: binary_sensor.open_sensor_window_chambre_robin_contact
              name: Chambre Robin
              secondary_info: last-changed
            - entity: binary_sensor.open_sensor_window_salle_de_bain_contact
              name: Salle de bain
              secondary_info: last-changed
            - entity: binary_sensor.open_sensor_window_toilettes_haut_contact
              name: Toilette du haut
              secondary_info: last-changed
            - type: divider
            - entity: binary_sensor.open_sensor_window_salon_contact
              name: Salon
              secondary_info: last-changed
            - entity: binary_sensor.open_sensor_window_salle_a_manger_contact
              name: Salle à manger
              secondary_info: last-changed
            - entity: binary_sensor.open_sensor_window_cuisine_contact
              name: Cuisine
              secondary_info: last-changed
            - entity: binary_sensor.open_sensor_window_toilettes_bas_contact
              name: Toilette du bas
              secondary_info: last-changed
          card_mod:
            style: |
              ha-card {
                background: none !important;
              }
        size: normal
      - type: custom:popup-card
        entity: binary_sensor.open_sensor_group_door
        title: Portes maison
        content:
          state_color: true
          type: entities
          entities:
            - entity: binary_sensor.open_sensor_door_maison_contact
              name: Porte d'entrée
              secondary_info: last-changed
            - entity: binary_sensor.open_sensor_door_garage_contact
              name: Porte garage
              secondary_info: last-changed
            - entity: binary_sensor.open_sensor_door_garage_basculante_contact
              name: Porte basculante
              secondary_info: last-changed
          card_mod:
            style: |
              ha-card {
                background: none !important;
              }
        size: normal
```

### Error messages from the browser console

```console
No error
```

### By checking each box below I indicate that I ...

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
- [x] If this issue is to do with an Android device losing connection, sensors becoming unavailable etc., please confirm you have read, understood and tried methods described in Wiki Article [Andoird Devices 'Always On'](https://github.com/thomasloven/hass-browser_mod/wiki/Andoird-Devices-'Always-On')

**Comment by dcapslock** [comment]
Thank you for the report. It’s likely that the issue is that the 2.3.4 and above does not look in the badges section for popup cards. A workaround will be to move them to a section of the dashboard.

**Comment by dcapslock** [comment]
I note that the UI will not allow a custom popup cards (or any other card that is not a badge) to be added to the badges section. So it is recommended to move them out to the main Dashboard section. Version 2.4.0 will also allow custom popup cards to be kept in another view and be global to a dashboard which will give you options for keeping custom popup cards together. A pre release version is available in HACS if you wish to test this new feature.

**Comment by llaumgui** [comment]
> Thank you for the report. It’s likely that the issue is that the 2.3.4 and above does not look in the badges section for popup cards. A workaround will be to move them to a section of the dashboard.

If I move custom:popup-card it's not working... It's need to move badge so.

**Comment by dcapslock** [comment]
Can you share your whole dashboard YAML? 

The custom popup card is designed to be a regular card which you will see when editing but not when running until it is used. It may be one deep in another card (e.g vertical-stack). If it is located elsewhere (badges) or deep in a stack it will not be found.

**Comment by llaumgui** [comment]
https://pastebin.com/HaJUkx5p (1 day pastbin)

**Comment by dcapslock** [comment]
Looking at your YAML you have custom:popup-card in the badges section. These need to be in the main section. The mushroom badges can remain as is. 

e.g. 

where you have yaml as below - the popup card will not be found. 

```yaml
badges:
...
      - type: custom:mushroom-template-badge
        content: >-
          {{ expand(entity) | selectattr('state', 'eq', 'open') | list | count
          }} / {{ expand(entity) | list |count }}
        icon: mdi:window-shutter-open
        color: >-
          {% if expand(entity) | selectattr('state', 'eq', 'open') | list |
          count > 0 %}
            #42A5F5
          {% else %}
            grey
          {% endif %}
        entity: cover.shutter_group_maison
        tap_action:
          action: more-info
        hold_action:
          action: toggle
...
      - type: custom:popup-card
        entity: cover.shutter_group_maison
        title: Volets maison
        content:
          state_color: true
          type: entities
          entities:
            - entity: cover.shutter_group_maison
            - type: divider
            - entity: cover.shutter_group_1er_etage
```

instead try something like below, where the popup card is in the main section, not the badges section.

```yaml
views:
  - title: Pièces
    path: pieces
    type: sections
    sections:
...
      - type: grid
        cards:
          - type: custom:popup-card
            entity: cover.shutter_group_maison
            title: Volets maison
            content:
              state_color: true
              type: entities
              entities:
                - entity: cover.shutter_group_maison
                - type: divider
                - entity: cover.shutter_group_1er_etage     
badges:
...
      - type: custom:mushroom-template-badge
        content: >-
          {{ expand(entity) | selectattr('state', 'eq', 'open') | list | count
          }} / {{ expand(entity) | list |count }}
        icon: mdi:window-shutter-open
        color: >-
          {% if expand(entity) | selectattr('state', 'eq', 'open') | list |
          count > 0 %}
            #42A5F5
          {% else %}
            grey
          {% endif %}
        entity: cover.shutter_group_maison
        tap_action:
          action: more-info
        hold_action:
          action: toggle
```
