### ISSUE TITLE
[Bug]: confirmation in a nested window is broken

### ISSUE THREAD

**Issue by WRoss7** [thomasloven/hass-browser_mod#869]
### My Home Assistant Version

Core: 2025.5.3
Frontend: 20250516.0

### What I am doing

Browser_mod version: 2.3.8
After the last update, confirmation of a nested window no longer works

### What I expect to happen

The action associated with the Yes button should be executed

### What happened instead

Clicking on the confirmation button does not happen

### Minimal steps to reproduce

1. I click the button
2. the pop-up opens
3. I click Yes
4. the pop-up disappears, but the associated action is not executed

### Include any yaml code here

```YAML
type: tile
entity: sensor.date
features_position: bottom
vertical: false
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Manutention
      content: Do you want to confirm?
      right_button: "Yes"
      right_button_action:
        action: call-service
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.roborock_s5_manutenzione
      left_button: "No"
```

### Error messages from the browser console

```console

```

### By checking each box below I indicate that I ...

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
- [x] If this issue is to do with an Android device losing connection, sensors becoming unavailable etc., please confirm you have read, understood and tried methods described in Wiki Article [Andoird Devices 'Always On'](https://github.com/thomasloven/hass-browser_mod/wiki/Andoird-Devices-'Always-On')
