### ISSUE TITLE
[Bug]: browser-mod pop_up no longer working (possibly as of 2.3.8

### ISSUE THREAD

**Issue by lambros414** [thomasloven/hass-browser_mod#876]
### My Home Assistant Version

Installation method: Home Assistant OS
Core: 2025.5.3
Supervisor: 2025.05.3
Operating System: 15.2
Frontend: 20250516.0

### What I am doing

I am using browser-mode pop-up in a bunch of instances for confirmation of an action to be performed.  I just noticed that all of my instances stopped working.  I noticed on a different thread that this could be if the pop-up was put in a couple of levels deep in a card.

To test my environment, I move the card up to  first level on my dashboard and it is still not working.

I can't figure out what to do.  

Here is the code that has been working perfectly until recently:

`name: Garage <br>Siren
type: custom:button-card
entity: switch.garage_siren
show_entity_picture: true
entity_picture: /local/Icons/siren-white-circle.png
size: 40%
icon: mdi:alarm
aspect_ratio: 1/1
show_name: true
show_icon: true
show_state: true
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Confirm Action
      content: |-
        [[[  
        if (entity.state == 'on')  
          return 'Are you sure you want to turn off the siren?'; 
        return 'Are you sure you want to turn on the siren?' 
        ]]]
      right_button: "Yes"
      left_button: "No"
      right_button_action:
        action: call-service
        service: script.toggle_entity
        data:
          entity_id: switch.garage_siren
      left_button_action:
        service: browser_mod.popup
        data:
          title: Operation cancelled.
          dismissable: false
          timeout: 500
      card_mod:
        style:
          ha-dialog$: |
            div.mdc-dialog div.mdc-dialog__scrim {
              backdrop-filter: blur(5px); 
            }
            div.mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
              background: rgba(28, 28, 28,.5) !important;
              border: none !important;
              border-style: solid !important;
              border-color: blue !important;
              border-radius: 8px !important;
              box-shadow: 0px 5px 5px 0 rgba(0, 0, 0, 0.3) !important;
              font-variant: small-caps !important;
            }
color_type: card
styles:
  card:
    - font-variant: small-caps
    - color: white
    - border-radius: 8px
    - box-shadow: 0px 5px 5px 0 rgba(0, 0, 0, 0.3)
  name:
    - color: white
    - font-weight: bold
    - font-size: 100%
  state:
    - font-size: 80%
state:
  - value: "off"
    color: black
    styles:
      card:
        - filter: opacity(65%)
  - value: "on"
    color: red
`

### Minimal steps to reproduce

1.
2.
3.
...

### Include any yaml code here

```YAML
name: Garage <br>Siren
type: custom:button-card
entity: switch.garage_siren
show_entity_picture: true
entity_picture: /local/Icons/siren-white-circle.png
size: 40%
icon: mdi:alarm
aspect_ratio: 1/1
show_name: true
show_icon: true
show_state: true
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Confirm Action
      content: |-
        [[[  
        if (entity.state == 'on')  
          return 'Are you sure you want to turn off the siren?'; 
        return 'Are you sure you want to turn on the siren?' 
        ]]]
      right_button: "Yes"
      left_button: "No"
      right_button_action:
        action: call-service
        service: script.toggle_entity
        data:
          entity_id: switch.garage_siren
      left_button_action:
        service: browser_mod.popup
        data:
          title: Operation cancelled.
          dismissable: false
          timeout: 500
      card_mod:
        style:
          ha-dialog$: |
            div.mdc-dialog div.mdc-dialog__scrim {
              backdrop-filter: blur(5px); 
            }
            div.mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
              background: rgba(28, 28, 28,.5) !important;
              border: none !important;
              border-style: solid !important;
              border-color: blue !important;
              border-radius: 8px !important;
              box-shadow: 0px 5px 5px 0 rgba(0, 0, 0, 0.3) !important;
              font-variant: small-caps !important;
            }
color_type: card
styles:
  card:
    - font-variant: small-caps
    - color: white
    - border-radius: 8px
    - box-shadow: 0px 5px 5px 0 rgba(0, 0, 0, 0.3)
  name:
    - color: white
    - font-weight: bold
    - font-size: 100%
  state:
    - font-size: 80%
state:
  - value: "off"
    color: black
    styles:
      card:
        - filter: opacity(65%)
  - value: "on"
    color: red
```

### Error messages from the browser console

```console
I don't get any messages, the action just doesn't work
```

### By checking each box below I indicate that I ...

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
- [x] If this issue is to do with an Android device losing connection, sensors becoming unavailable etc., please confirm you have read, understood and tried methods described in Wiki Article [Andoird Devices 'Always On'](https://github.com/thomasloven/hass-browser_mod/wiki/Andoird-Devices-'Always-On')

**Comment by dcapslock** [comment]
Hi, there is one issue with 2.3.8 where `action: call-service` does not work. It was broken in the updates in 2.3.6, to allow for any `action:` as a popup `_action:`. This will be fixed in the next release. To workaround you can use your service action directly `action: <service`, or just remove `action: call-service`.

So either.

```yaml
      right_button_action:
        action: script.toggle_entity
        data:
          entity_id: switch.garage_siren
```

or 

```yaml
      right_button_action:
        service: script.toggle_entity
        data:
          entity_id: switch.garage_siren
```

This is the only issue I can find with your example. Please confirm if this is the only issue, or if you don't get the first popup at all. Thank you.

NOTE: Level of deepness is regarding `custom:popup-card` only. Calls to `browser_mod.popup` can be anywhere.
