### ISSUE TITLE
Version 2.3.8 - Breaking issue with actions using `action:call-service`

### ISSUE THREAD

**Issue by dcapslock** [thomasloven/hass-browser_mod#877]
Version 2.3.8 has an issue where popup `_action`s will not work if they are using the old style `action: call-service` configuration. The simple workaround is to either call the action directly or remove `action: call-service` as Browser Mod actions will work with `service:` alone.

#### Broken in 2.3.8 ❌ 

```yaml
      right_button_action:
        action: call-service
        service: light.toggle
        data:
          entity_id: light.bed_light
```

#### Workarounds... ✅ 

```yaml
      right_button_action:
        action: light.toggle
        data:
          entity_id: light.bed_light
```

or

```yaml
      right_button_action:
        service: light.toggle
        data:
          entity_id: light.bed_light
```
