### ISSUE TITLE
Hide Overflow

### ISSUE THREAD

**Issue by madmicio** [thomasloven/hass-browser_mod#88]
Hi Thomas!
is there a way to hide Overflow in a popup?

**Comment by Dino-Tech** [comment]
maybe `overflow: hidden` works here

**Comment by KTibow** [comment]
You can use card-mod styling for popups. Example:
```yaml
service: browser_mod.popup
service_data:
  title: Popup example
  style: |
    * {
      overflow: hidden;
    }
  card:
    type: entities
    entities:
      - light.bed_light
      - light.kitchen_lights
      - light.ceiling_lights
  deviceID: this
```
Mind closing?
