### ISSUE TITLE
naming devices creates mediaplayer unavailable

### ISSUE THREAD

**Issue by thundergreen** [thomasloven/hass-browser_mod#9]
```
## Browser MOD ####
browser_mod:
  devices:
    0b64db44_0c827440:
      name: Thorsten
    e7b12fe1_3d99b6f9:
      name: Emilie
```

I added thos in my config. I will create for example media_player.phone_thorsten but shows unavailable and "old" entity with deviceID still in entites in dev-states

any hint here?

![image](https://user-images.githubusercontent.com/13320319/61536306-9f59e200-aa34-11e9-97e5-d332f67cbfd6.png)
