### ISSUE TITLE
[Bug]: Template doesn't re-render on popup created via action

### ISSUE THREAD

**Issue by codemunkie15** [thomasloven/hass-browser_mod#907]
### My Home Assistant Version

Installation method
Home Assistant OS
Core
2025.6.1
Supervisor
2025.06.2
Operating System
15.2
Frontend
20250531.3

### What I am doing

I am creating a popup via the `browser_mod.popup` action with a Mushroom template chip inside, but the template doesn't update on state change.

I tried the same thing with a popup created from a `tap_action` in a dashboard using `fire-dom-event` and the state updates properly there with the exact same card config.

### What I expect to happen

The template should re-render on state changes.

### Minimal steps to reproduce

Run this action with any entity from Developer tools and then modify the state. The template will not re-render.

```
action: browser_mod.popup
data:
  browser_id: <browser id>
  content:
    type: custom:mushroom-chips-card
    chips:
      - type: template
        content: "{{states('sensor.anything')}}"
```

Add this to a dashboard and then click the entity to open the popup. Modify the state from Developer tools. The template will re-render as expected.

```
type: tile
entity: <any entity>
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      content:
        type: custom:mushroom-chips-card
        chips:
          - type: template
            content: "{{states('sensor.anything')}}"
```

### Include any yaml code here

```YAML

```

### Error messages from the browser console

```console

```

### By checking each box below I indicate that I ...

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
- [x] If this issue is to do with an Android device losing connection, sensors becoming unavailable etc., please confirm you have read, understood and tried methods described in Wiki Article [Andoird Devices 'Always On'](https://github.com/thomasloven/hass-browser_mod/wiki/Andoird-Devices-'Always-On')

**Comment by dcapslock** [comment]
This will not work as expected in Developer tools (see further below for why). The following is working fine on a Dashboard.

```yaml
type: button
entity: light.bed_light
tap_action:
  action: perform-action
  perform_action: browser_mod.popup
  data:
    content:
      type: custom:mushroom-chips-card
      chips:
        - type: template
          content: "{{states('light.bed_light')}}"
    browser_id:
      - e37643b8cd031cfb006c04181ac31758
  target: {}
```

The difference when using Developer tools is that any action is executed as a script with a sequence of the action to be performed (card actions use direct callService). Templates are evaluated __before__ sending data to scripts, hence the popup will be just recieving `"on"` or `"off"` for the mushroom template chip content, and not the expected `{{ states('sensor.anything') }}`.

You can test what to expect by using a simple script and calling from both Developer tools and Dashboard card action.

### Script
```yaml
sequence:
  - variables:
      test_output: "{{ { 'test_input': test_input } }}"
  - stop: ""
    response_variable: test_output
alias: Test Script
description: ""
```

### Developer Tools
#### Action Yaml
```yaml
action: script.test_script
data:
  test_input: "{{ states('light.bed_light') }}"
```
#### Result
```yaml
test_input: "off"
```
#### Script Trace
```yaml
this:
  entity_id: script.test_script
  state: 'off'
  attributes:
    last_triggered: '2025-06-26T01:51:46.918407+00:00'
    mode: single
    current: 0
    friendly_name: Test Script
  last_changed: '2025-06-26T01:51:46.919985+00:00'
  last_reported: '2025-06-26T01:51:46.919985+00:00'
  last_updated: '2025-06-26T01:51:46.919985+00:00'
  context:
    id: 01JYMYY4PZQ67CRR4QRK42XA34
    parent_id: null
    user_id: 1283f038bd70410f98eb21132060fbac
test_input: 'off'
context:
  id: 01JYMZQ7B8E6V4FHDENBAWP59T
  parent_id: null
  user_id: 1283f038bd70410f98eb21132060fbac
test_output:
  test_input: 'off'
```
### Dashboard
#### Card with action
```yaml
type: button
entity: light.bed_light
tap_action:
  action: perform-action
  perform_action: script.test_script
  target: {}
  data:
    test_input: "{{ states('light.bed_light') }}"
```
#### Script Trace
```yaml
this:
  entity_id: script.test_script
  state: 'off'
  attributes:
    last_triggered: '2025-06-26T02:05:28.822819+00:00'
    mode: single
    current: 0
    friendly_name: Test Script
  last_changed: '2025-06-26T02:05:28.826310+00:00'
  last_reported: '2025-06-26T02:05:28.826310+00:00'
  last_updated: '2025-06-26T02:05:28.826310+00:00'
  context:
    id: 01JYMZQ7B8E6V4FHDENBAWP59T
    parent_id: null
    user_id: 1283f038bd70410f98eb21132060fbac
test_input: '{{ states(''light.bed_light'') }}'
context:
  id: 01JYMZWKVQ5TD8G3ZDRRYEJCHE
  parent_id: null
  user_id: 1283f038bd70410f98eb21132060fbac
test_output:
  test_input: '{{ states(''light.bed_light'') }}'
```

**Comment by dcapslock** [comment]
Additional follow up... this works in Developer Tools.  A bit cumbersome but does give you a way to test popup in Developer tools.

```yaml
action: browser_mod.popup
data:
  content:
    type: custom:mushroom-chips-card
    chips:
      - type: template
        content: |
          {{ "{{ states('light.bed_light') }}" }}
  browser_id:
    - e37643b8cd031cfb006c04181ac31758
target: {}
```

**Comment by codemunkie15** [comment]
Hi

Thanks for the quick reply. It's not for testing, I'm actually using the browser_mod.popup service in some scripts and automations (to show camera streams when someone rings the doorbell for example). I overlay mushroom chips over the camera card in the popup to show some states but noticed that the chips don't update when the state changes.

Your additional follow-up looks exactly like the code I posted above? Are you saying that code does re-render on state change on your instance?

EDIT: Ah you are escaping the template so the actual template is passed to the frontend instead of the template being evaluated in the script and the raw state value being passed to the popup content! Is it worth something in the docs around this? I know it's not browser mod specific but I'm sure plenty of people don't know this is how it works.

Thanks

**Comment by dcapslock** [comment]
Hi,

Best way to test is to make sure that the automation is passing what you expect is by first using a test script and looking at traces, and or carefully looking at your automation traces. When your automation is not giving you the output you expect, its likely that something is wrong with your template, either malformed, or being passed as evaluated. e.g. 'on' or 'off' rather that the unevaluated template. No custom card can re-render 'off' to 'on'.

Looks like automations work even a bit differently than Developer tools, which I have seen in the past when getting rest_commands working with parameters passed from automations. The order of quotes is important. `'` on teh outside, `"` on the inside.

Further tip, take what the script sees and double check in Template tool.

e.g. 

```yaml
action: script.test_script
data:
  test_input: |
    {{ '{{ states("light.bed_light") }}' }}
```

gives in script....

```yaml
test_output:
  test_input: '{{ states("light.bed_light") }}'
```

which works fine as a template.

but...

```yaml
action: script.test_script
data:
  test_input: |
    {{ "{{ states('light.bed_light') }}" }}
```

gives in script...

```yaml
test_output:
  test_input: '{{ states(''light.bed_light'') }}'
```

which when you take `{{ states(''light.bed_light'') }}` and test in Template tool, it does not like the double single quotes!

> EDIT: Ah you are escaping the template so the actual template is passed to the frontend instead of the template being evaluated in the script and the raw state value being passed to the popup content! Is it worth something in the docs around this? I know it's not browser mod specific but I'm sure plenty of people don't know this is how it works.

Yes, per caveats above. If you wish to submit a Wiki article on this to help others, that would be great. Submit a blank issue titled 'Wiki Submission'. 🙏
