### ISSUE TITLE
Allow custom:popup-card to work with custom:decluttering-card

### ISSUE THREAD

**Issue by klejejs** [thomasloven/hass-browser_mod#909]
## Problem

As I have multiple similar popup cards, I have created a template using `custom:decluttering-card` and put a popup card under there. Unfortunately, this way, the popup card does not successfully replace more info dialog. I guess it is related to the following issue: https://github.com/thomasloven/hass-browser_mod/issues/863.

## Example code
```yaml
decluttering_templates:
  person_more_info:
    default:
      - person: ''
      - person_name: ''
      - notify_mobile_app: ''
    card:
      type: custom:popup-card
      entity: '[[person]]'
      title: '[[person_name]]'
      dismissable: true
      size: normal
      popup_card_all_views: true
      card:
        type: vertical-stack
        cards: ...
  person_card:
    default:
      - name: ""
      - entity: input_button.dummy_button
    card:
      type: custom:mushroom-person-card
      entity: '[[entity]]'
      layout: vertical
      fill_container: false
      name: '[[name]]'
      secondary_info: none
      primary_info: none
      icon_type: entity-picture
...
views:
  - title: Home
    type: sections
    sections:
      - type: grid
        cards:
          - type: vertical-stack
            cards:
              - type: custom:decluttering-card
                template: person_more_info
                variables:
                  - person: person.arturs
                  - person_name: "Arturs"
                  - notify_mobile_app: notify.mobile_app_...
          - square: false
            type: grid
            cards:
              - type: custom:decluttering-card
                template: person_card
                variables:
                  - name: "Arturs"
                  - entity: person.arturs
```

The example used to work before `v2.3.8`

This works if I do not have the `custom:popup-card` within the decluttering card but bring it outside, directly as a section, however, it complicates the YAML as I need to replicate essentially the same card multiple times.

**Comment by dcapslock** [comment]
@klejejs with 2.3.8, improvements were made so that the Popup card is totally hidden (no HTML output) when not in use (or in edit mode). With 2.3.8+, the Home Assistant 'more-info' event is processed via the main Browser Mod popup element which then seraches the dashboard config, up to 1 level deep, for a card that matches the 'more-info' entity. If found, the card is loaded and shown in a popup and the Home Assistant 'more-info' closed. Previously, the popup card was rendered but hidden by CSS, and listened for 'more-info' directly and then acted. This gave rise to various issues including blank areas in newer section dashboard layouts. So now if you use a custom:popup-card in a custom:decluttering-card, it will not work as there is no card directly in the dashboard config for Browser Mod to find.

As for a solution, allowing for Browser Mod to know about and understand other custom cards and how they work would be a maintenance nightmare so that approach will not work. The alternate approach is to bring in improvements to custom:popup-card that makes it easier to manage popup cards in a more intuative and clean way. 2.4.0 allows for popup cards to be global to all views. Further improvements requested include matching popup cards by entity area, labels, device etc, and multiple entities (#908).

So, putting that all together, the recommendation for your use case is to put the custom:decluttering-template as the card for custom:popup-card, also putting those cards in a subview (though not required). Example dashboard based on your use case below works fine with Browser Mod 2.4.1.

```yaml
decluttering_templates:
  person_more_info:
    default:
      - person: ''
      - person_name: ''
      - notify_mobile_app: ''
    card:
      type: vertical-stack
      title: '[[person_name]]'
      cards:
        - type: tile
          entity: '[[person]]'
views:
  - type: sections
    max_columns: 4
    title: Home
    path: home
    sections:
      - type: grid
        cards:
          - type: button
            name: Dev User
            tap_action:
              action: more-info
              entity: person.dev
          - type: button
            name: Jane Doe
            tap_action:
              action: more-info
              entity: person.jane_doe
  - title: Popups
    type: sections
    max_columns: 4
    subview: true
    sections:
      - type: grid
        cards:
          - type: custom:popup-card
            target:
              entity_id: person.dev
            card:
              type: custom:decluttering-card
              template: person_more_info
              variables:
                - person: person.dev
                - person_name: Dev User
            popup_card_all_views: true
            entity: person.dev
          - type: custom:popup-card
            card:
              type: custom:decluttering-card
              template: person_more_info
              variables:
                - person: person.jane_doe
                - person_name: Jane Doe
            popup_card_all_views: true
            target:
              entity_id: person.jane_doe
            entity: person.jane_doe
```
