### ISSUE TITLE
Custom element doesn't exist

### ISSUE THREAD

**Issue by Alfiegerner** [thomasloven/hass-browser_mod#92]
I get this when using browser_mod.pop_up - but only in mobile view, desktop view works fine:

![image](https://user-images.githubusercontent.com/596188/81025907-7673e200-8ecc-11ea-9d73-6948634b84b8.png)

```
               data:
                  card:
                    entity: sensor.water_tank_percentage
                    hours_to_show: 12
                    type: gauge
                    unit: '%'
                    severity:
                      green: 50
                      red: 0
                      yellow: 30
                  deviceID: this
                  style:
                    '--more-info-header-background': 'rgba(255, 159, 9, 1)'
                  title: Water %
                service: browser_mod.popup
```

I have tried using Preloader as follows for problematic elements:

```
preloader:
  preload_cards:
    - map
    - hui-map
    - hui-map-card
    - gauge
    - hui-gauge
    - hui-gauge-card
  preload_rows:
    - lock-entity-row
    - hui-lock-entity-row
```
But no joy.  Anyone any suggestions?
