### ISSUE TITLE
Conflict between entity types

### ISSUE THREAD

**Issue by CarpeDiemRo** [thomasloven/hass-browser_mod#95]
Use case:
Use multiple addons in order to create a Tablet Dashboard.
Mix browser_mod.popup service for extra info and image card for floor plan.

Code:
ui-yaml file

a. 
```
          - type: icon
            icon: mdi:information-outline
            title: Information
            style:
              top: 87.41%
              left: 10.7%
              color: rgba(255, 255, 255, 0.10)
              padding: 0.8vw
              --iron-icon-height: 4vw
              --iron-icon-width: 4vw
            tap_action: !include popup/sidebar_information.yaml
```

b. 
```
          - entity: switch.kitchen_light
            hold_action:
              action: none
            state_image:
              'off': /local/floorplan/apartment/transparent_square.png
              'on': /local/floorplan/apartment/kitchen_1.png
            style:
              left: 50%
              top: 50%
              width: 100%
            tap_action:
              action: none
            type: image

          - entity: switch.kitchen_light
            image: /local/floorplan/apartment/transparent_square.png
            style:
              left: 53.5%
              top: 75%
            tap_action:
              action: toggle
            type: image

```

sidebar_information.yaml

```
              action: call-service
              service: browser_mod.popup
              service_data:
                title: Close
                deviceID: this
                style:
                  background: none
                  box-shadow: none
                  width: calc(400px + 400px + 400px)
                card:
                  type: custom:layout-card
                  column_num: 3
                  column_width: [400, 400, 400]
                  layout: vertical
                  cards:
                    - type: entities
                      title: Home Assistant
                      show_header_toggle: false
                      style: &entities-style |
                        ha-card {
                          box-shadow: none;
                          border-radius: 1em;
                          background: rgba(34, 38, 39, 0.9);
                          padding: 0.3em 1.25em 0.4em 0.5em;
                        }
                        .card-header {
                          margin-left: 0.4em;
                          margin-bottom: 0.1em;
                          font-family: sf text;
                          letter-spacing: 0.005em;
                        }
                      entities:
                        - entity: sensor.version_current
                        - entity: sensor.version_available
                        
                        - entity: sensor.processor_use
                          icon: 'mdi:chip'

                        - entity: sensor.load_1m
                          icon: 'mdi:chip'
                          

                        - entity: sensor.last_boot
                          icon: 'mdi:clock'
                          name: BigSister Uptime


                        - entities:
                            - entity: sensor.asuswrt_download_speed
                              name: Router Download Speed
                              icon: 'mdi:chip'
                              tap_action:
                                action: call-service
                                service: homeassistant.update_entity
                                service_data:
                                  entity_id: sensor.asuswrt_download_speed
                            - entity: sensor.asuswrt_upload_speed
                              name: Router Upload Speed
                              icon: 'mdi:memory'
                              tap_action:
                                action: call-service
                                service: homeassistant.update_entity
                                service_data:
                                  entity_id: sensor.asuswrt_upload_speed
                          positions: &bar_card_positions
                            icon: outside
                            indicator: 'off'
                            name: outside
                          severity: &bar_card_severity
                            - color: '#303435'
                              from: 0
                              to: 89
                            - color: '#6d2525'
                              from: 90
                              to: 100
                          decimal: 0
                          entity_row: true
                          style: &bar_card_style |
                            bar-card-iconbar {
                              padding-left: 0.23em;
                            }
                            bar-card-name {
                              padding-left: 0.25em;
                            }
                            bar-card-value {
                              margin-right: auto;
                              color: #e0e1e1;
                              text-shadow: none;
                              font-size: 1em;
                              font-weight: 400;
                              letter-spacing: 0.01em;
                            }
                            bar-card-background {
                              background: radial-gradient(circle, rgba(52, 57, 58, 0.1) 0%, rgba(17,18,18,0.2) 75%);
                              box-shadow: inset 0 0 25px #00000045;
                              border-radius: 0.3em;
                            }
                            bar-card-backgroundbar {
                              background: none;
                            }
                          unit_of_measurement: 'Mbps'
                          height: 2em
                          width: 55%
                          type: custom:bar-card

                        - type: custom:hui-horizontal-stack-card
                          style: &horizontal-style |
                            #root {
                              justify-content: space-evenly;
                              margin: 1.4em -0.7em 0.7em 0;
                            }
                          cards:

                          - type: custom:button-card
                            name: >
                              [[[ return 
                              '<ha-icon icon="mdi:reload">
                              </ha-icon> Home Assistant'; ]]]
                            tap_action:
                              action: call-service
                              service: script.turn_on
                              service_data:
                                entity_id: script.homeassistant_restart
                            template: name_action
```

The info button is grayed out. If I remove this part
```
          - entity: switch.kitchen_light
            hold_action:
              action: none
            state_image:
              'off': /local/floorplan/apartment/transparent_square.png
              'on': /local/floorplan/apartment/kitchen_1.png
            style:
              left: 50%
              top: 50%
              width: 100%
            tap_action:
              action: none
            type: image 
```
Info button works as design. 
See attached image
![Screenshot 2020-05-18 at 15 22 21](https://user-images.githubusercontent.com/38489167/82213673-3d505e80-991d-11ea-8cb3-c4208ff8fc27.png)

Do you have any workaround ideas?
