### ISSUE TITLE
Custom element doesn't exist: hui-entity-filter-card

### ISSUE THREAD

**Issue by jarrah31** [thomasloven/hass-browser_mod#96]
Since upgrading to 1.108.9 from 1.106, my popup cards have been giving the following error:

![image](https://user-images.githubusercontent.com/3072303/82445385-9d214380-9a9c-11ea-8669-8c007e19df73.png)

I thought this might be related to the new loading feature in 1.107, so I tried Lovelace Card Preloader but that hasn't helped either. 

Here is my code to reproduce the issue.

```
resources:
  - url: /hacsfiles/lovelace-card-preloader/lovelace-card-preloader.js
    type: js
 
preload_cards:
  - entity-filter

title: Home
views:
  - title: Test2
    panel: false
    path: test2
    popup_cards:
      input_boolean.window_is_open:
        title: Open Windows
        card:
          type: entity-filter
          state_filter:
            - "Open"
          entities:
            - sensor.win_lounge_top_left
            - sensor.win_lounge_top_right
    cards:
      - type: conditional
        conditions:
          - entity: input_boolean.kiosk_cond_btt1
            state: "on"
        card:
          type: button
          name: Turn Off Lights
          entity: input_boolean.window_is_open
          tap_action:
            action: more-info
```
Thanks.

**Comment by heymoe** [comment]
I have a similar issue after upgrading to 0.110.1 and upgrading to the latest version of this integration (from 25 to 27) yesterday.

My map popup_card fails with:
`Custom element doesn't exist: hui-map-card.`

Here is my code:
```
popup_cards:
      device_tracker.xxx_position:
        card:
          aspect_ratio: 16x9
          default_zoom: 14
          entities:
            - device_tracker.xxx_position
          hours_to_show: 12
          title: null
          type: map
        style:
          width: 60%
        title: xxx
```

This worked fine when running 0.109.6 and version 25 of this integration.
